### ISSUE TITLE
Options for transfer of large objects like video

### ISSUE THREAD

**Issue by aaaasssdd** [tinode/chat#101]
When to support  Options for transfer of large objects like video？ thanks.

Do you have a plan。

**Comment by or-else** [comment]
Working on it: https://github.com/tinode/chat/tree/large-files

**Comment by aaaasssdd** [comment]
Do you have a release plan ？ thanks.

**Comment by or-else** [comment]
Yes. The plan is to release as soon as possible.

**Comment by aaaasssdd** [comment]
thanks.
