### ISSUE TITLE
Group owner {leave} returns no error

### ISSUE THREAD

**Issue by jaylevin** [tinode/chat#102]
### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

### Your environment
- [ ] api.tinode.co
- [x] Your own setup:
  * OSX
  * 0.15
  * MySQL
  * Go 1.10.1

### Steps to reproduce

```
leave := &pbx.ClientLeave {
		Topic: topicID,
		Unsub: unsub,
}

leaveMsg         := &pbx.ClientMsg_Leave { Leave: leave }
clientMessage := &pbx.ClientMsg { Message: leaveMsg }

err := resp.Send(clientMessage)
if err != nil {
    log.Println(err)
}
       log.Println("Error:", err)
```

Am I missing something here? The serve console logs that there is an error, but doesn't return anything for the error.

### Expected behaviour
Error returned from `resp.Send(clientMessage)` should be the same as the one printed to the tinode server console

`replyLeaveUnsub: owner cannot unsubscribe`

### Actual behaviour
Error is `nil`

### Server-side log
`2018/06/07 17:14:37 leave:<topic:"grphIYtXahrzz8" unsub:true >
2018/06/07 17:14:37 failed to unsub replyLeaveUnsub: owner cannot unsubscribe`

### Client-side log
`2018/06/07 17:18:24 Error: <nil>`

Any help would be much appreciated. Thanks

**Comment by or-else** [comment]
If `unsub` is `true` in 
```
leave := &pbx.ClientLeave {
		Topic: topicID,
		Unsub: unsub,
}
```
Then it's not a bug but an expected behaviour. The owner cannot hard-unsubscribe from a group. Either set `unsub` to `false` or transfer group ownership to someone else first.

**Comment by jaylevin** [comment]
Ah, that makes some sense, I was setting `unsub=true`. Much appreciated!
