### ISSUE TITLE
Database being reset every restart/stop on docker

### ISSUE THREAD

**Issue by TaylorChristie** [tinode/chat#106]
### Subject of the issue
On every restart/stop of tinode, the database is being overwritten. I am using the pull request I used which modifies the MySQL DSN, but I don't see how that would change things.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

### Your environment
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc): docker linux
  * version of tinode server: 0.15.1
  * database backend: mysql
  * which client used (javascript, android, cli) and its version: custom

### Steps to reproduce
Create a service using tinode/tinode-mysql:0.15.1 and a custom MySQL DSN and `docker-compose up -d` it. run `docker-compose stop chat` then `docker-compose up chat` and all the database information will be reset. 

### Expected behaviour
To only reset the data on the ENV flag or a complete remove.

### Actual behaviour
The data is reset on every restart/stop.

### Server-side log
N/A

### Client-side log
N/A

**Comment by or-else** [comment]
Well, your PR where you introduced $RESET_DB contains the bug you are reporting. Basically,
```
RESET_DB=false
if [ $RESET_DB ] ; then
  echo "RESET_DB IS TRUE";
fi
```
will print "RESET_DB IS TRUE". 

`RESET_DB=false` assigns a string "false" to the RESET_DB and `if [ $RESET_DB ]` evaluates a  non-empty string to true.

Can you revise your PR please?

**Comment by TaylorChristie** [comment]
Wow I completely overlooked that, nice catch. Sorry about that; I assumed bash handled if statements differently. Created a PR.
