### ISSUE TITLE
Sub to 'usrKIkb4JUijJ0' from 'usrGJGWhP18Exs'

### ISSUE THREAD

**Issue by aaaasssdd** [tinode/chat#108]
When I test the 1:1 user selection, I can see the background log as follows. Can I finish the process at server? I need your help, thank you very much.

2018/06/19 16:54:32 Session.dispatch got '{"sub":{"id":"96588","topic":"usrKIkb4JUijJ0","get":{"what":"data sub desc"}}}' from '211.157.159.106:21267'
2018/06/19 16:54:32 Sub to 'usrKIkb4JUijJ0' from 'usrGJGWhP18Exs'
2018/06/19 16:54:32 hub: creating new p2p topic GJGWhP18Exs KIkb4JUijJ0
2018/06/19 16:54:32 hub: created second subscription
2018/06/19 16:54:32 hub: created first subscription
2018/06/19 16:54:32 hub: marking request as 'topic created'
2018/06/19 16:54:32 hub: topic created or loaded: p2pGJGWhP18ExsoiRvglSKMnQ
2018/06/19 16:54:32 Topic started: 'p2pGJGWhP18ExsoiRvglSKMnQ'
2018/06/19 16:54:32 Session.dispatch got '{"set":{"id":"96589","topic":"fnd","desc":{"public":"?}}}' from '211.157.159.106:21267'
2018/06/19 16:54:32 s.set: processing 'set'
2018/06/19 16:54:32 s.set: sending to topic
2018/06/19 16:54:33 Session.dispatch got '{"get":{"id":"96590","topic":"fnd","what":"sub"}}' from '211.157.159.106:21267'
2018/06/19 16:54:33 s.get: processing 'get.sub'

**Comment by or-else** [comment]
> 2018/06/19 16:54:32 Session.dispatch got '{"sub":{"id":"96588","topic":"usrKIkb4JUijJ0","get":{"what":"data sub desc"}}}' from '211.157.159.106:21267'

https://github.com/tinode/chat/blob/master/server/session.go#L169

> 2018/06/19 16:54:32 Sub to 'usrKIkb4JUijJ0' from 'usrGJGWhP18Exs'

https://github.com/tinode/chat/blob/master/server/session.go#L253

> 2018/06/19 16:54:32 hub: creating new p2p topic GJGWhP18Exs KIkb4JUijJ0

https://github.com/tinode/chat/blob/master/server/hub.go#L442

> 2018/06/19 16:54:32 hub: topic created or loaded: p2pGJGWhP18ExsoiRvglSKMnQ

https://github.com/tinode/chat/blob/master/server/hub.go#L768

If you need something else, please be more specific. 

You can use github's search to find strings of interest in the code. You can also use local code search, such as `grep`.
