### ISSUE TITLE
[Cluster Not Working]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#11]
Hello,

How does to run server on cluster mode? I tried to execute 2 process of **$GOPATH/bin/server** which in first process use **cluster-one.conf** (listen to localhost:6060) and the second one use **cluster-two.conf** (listen to localhost:6062). 

But after I accessing both of the web consoles (**localhost:6060/x/example-react-js/** & **localhost:6062/x/example-react-js/**) I cannot login. I received error 500 instead.

So is this bug or the functionality is not yet done or I misconfigured both of my servers? I tried with **devel** branch but I also face the same issue.

<img width="1680" alt="screenshot 2017-07-22 09 39 43" src="https://user-images.githubusercontent.com/5761331/28487400-e51eec0a-6ec1-11e7-9656-c7c6dd8d04a7.png">

<img width="1178" alt="screenshot 2017-07-22 09 24 09" src="https://user-images.githubusercontent.com/5761331/28487408-01a5130e-6ec2-11e7-9b2d-b668bff27c1b.png">

Thanks

**Comment by or-else** [comment]
Could you please share your config files with me?

**Comment by riandyrn** [comment]
Sure (y)

[cluster-one.conf.txt](https://github.com/tinode/chat/files/1167261/cluster-one.conf.txt)
[cluster-two.conf.txt](https://github.com/tinode/chat/files/1167262/cluster-two.conf.txt)

Actually these two configs files are default configs found on the repo :D (y)

**Comment by or-else** [comment]
It looks like it's unlikely to be related to cluster but rather something with your database. Try regenerating it. Meanwhile I'll add better error logging. I'll upload it to devel later today.

**Comment by or-else** [comment]
I just pushed a change to devel. It should now log the DB error that's causing the HTTP 500.
I also fixed a supposedly unrelated bug in cluster code. Please try and let me know. Thanks!

**Comment by riandyrn** [comment]
Hmm.., yes, it looks like the problem lies within with my database. Somehow I need to run the database execution from my $HOME directory. So it fixed now.

Thanks a lot, Gene! :D (y)
