### ISSUE TITLE
Return 200 on /

### ISSUE THREAD

**Issue by fstn** [tinode/chat#112]
### Subject of the issue
If you use Kubernetess Ingress GCE, your service must return 200 on /. Actually it returns 404.
So the Kubernetes backend is marked as unhealthy

### Is this a bug report of a feature request?
- [x] Feature request

**Comment by or-else** [comment]
It's a feature request :)

**Comment by fstn** [comment]
Yes sure ;) I checked Feature request ;)

**Comment by or-else** [comment]
build-all.sh is for cross-compiling binaries for multiple platforms using [gox](https://github.com/mitchellh/gox). You probably don't need it. What happens when you follow the [Build From Source](https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source) instructions?

**Comment by fstn** [comment]
Thank you, I found a way to solve my issue ;)
Do you agree if server return {"ctrl":{"code":404,"text":"not found","ts":"2018-06-26T07:38:14.65Z"}} on HTTP 200 ?

**Comment by or-else** [comment]
If HTTP status is 200, the server should return `{"ctrl":{"code":200,"text":"ok","ts":"2018-06-26T07:38:14.65Z"}}`. The HTTP status code should match the value of `ctrl.code`.

**Comment by or-else** [comment]
This should do it: https://github.com/tinode/chat/commit/5dcb69bbd828546ce7c9422a000c8a18350c7d84

This basically allows you to serve the app from `/` instead of `/x/`

**Comment by fstn** [comment]
Thank you

**Comment by or-else** [comment]
The feature has been released as a part of [v0.15.2](https://github.com/tinode/chat/releases/tag/v0.15.2). Closing this.
