### ISSUE TITLE
Build essential Docker Image to build the project

### ISSUE THREAD

**Issue by fstn** [tinode/chat#113]
### Subject of the issue
I would like to collaborate on project but my go build env doesn't work.
It could be create to have a docker image to build the project.
Idea:
- input volume
- output volume
- when running it takes source file inside the input and generate the output in the output folder

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

**Comment by or-else** [comment]
You are welcome to make such a docker image. Take a look at this old docker file:
https://github.com/tinode/chat/blob/v0.14.4/docker/tinode-server/Dockerfile

It built tinode from source.

**Comment by or-else** [comment]
Is this still relevant? Do you need help?

**Comment by or-else** [comment]
I never used CI, so for me it's not easier :)

I think the docker file I referenced above does what you want. If it's not then I just don't fully understand what you want to achieve and what's missing.
