### ISSUE TITLE
UnRead Message And ProcessUnRead Message

### ISSUE THREAD

**Issue by xingguangkuo** [tinode/chat#115]
1、How do I use tinodejs to get an unread message from topic?
      var t111 = Tinode.Tinode.getTopic(uid)
      var msgCount = 0;
      var isShowMsg = false;
       if(t111.seq){
             var msgCount = t111.seq-t111.read;
        }
 The above code segment is correct. Can you get unread messages?

2、When a contact in my contact list has unread messages, I click on this contact to get in, and first get the historical message record. And the unread message is read at the same time, but how can I notify the server that the message I have not read has been read?
             var t111 = Tinode.Tinode.getTopic(u.id);
                  t111.subscribe().then(function (ctrl) {
                     t111.getMessagesPage(page);
                  });
             t111.onData = function (msg) {
                 1）
                     t111.noteRecv(data.seq);
                     error log ：  note(): user not found
                 2）
                      Tinode.Tinode.getMeTopic().setMsgReadRecv(u.id, "msg", msg.seq)
                      Tinode.Tinode.getMeTopic().setMsgReadRecv(u.id, "read", msg.seq)
                      log：no   
             }
The above fragment code. I tried two kinds of API, the first hint did not have the user ID, the second API interface did not have log output, and the contact list refreshed after the last unread message.

How do these two questions be solved? Thank you

**Comment by or-else** [comment]
> 1、How do I use tinodejs to get an unread message from topic? ...
> var msgCount = t111.seq-t111.read;

Yes, this seem to be correct. Here is a sample:
https://github.com/tinode/example-react-js/blob/master/index.html#L1989

> 2、When a contact in my contact list has unread messages,...
> t111.noteRecv(data.seq);

Yes, that's how you do it. Here is sample code:
https://github.com/tinode/example-react-js/blob/master/index.html#L4107

**Comment by or-else** [comment]
> 1. 

BTW, in your code sample you are getting topic from cache. I assume it's subscribed or has been subscribed, so it got data from server.
