### ISSUE TITLE
How to use ‘acc’tn-cli

### ISSUE THREAD

**Issue by JasonHXiang** [tinode/chat#116]
Hi~
I’m going to use acc command in tn-cli, but it puzzled me because it failed with error ‘missing cred’
Need your help!

**Comment by or-else** [comment]
Please show the logs and actual error message.

**Comment by or-else** [comment]
Yes, that's indeed a problem. Credential handling was not implemented in tn-cli. Here you go:
https://github.com/tinode/chat/commit/cb4f4e717ffac5815eec129e62099190e4deb6ea

Basically, if your server is configured to require email addresses (default), then {acc} must include it in the credential field.

**Comment by JasonHXiang** [comment]
Wow, Awesome！Thank you very much @or-else 

I replaced the tn-cli.py in [cb4f4e7](https://github.com/tinode/chat/commit/cb4f4e717ffac5815eec129e62099190e4deb6ea), but some error comes with the traceback "Protocol message SetDesc has no "cred" field". Does it need me to modify Protocol message processing logic?

**[Traceback]**
tn> acc --user=new --scheme=basic --uname=beckham --password=beckham123 --fn=Beckham --cred=email:beckham@example.com
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "/virtualenv/env/lib/python2.7/site-packages/grpc/_channel.py", line 165, in consume_request_iterator
    request = next(request_iterator)
  File "tn-cli.py", line 359, in gen_message
    cmd = serialize_cmd(inp, id)
  File "tn-cli.py", line 315, in serialize_cmd
    cmd.do_login, cmd.fn, cmd.photo, cmd.private, cmd.auth, cmd.anon, cmd.tags, cmd.cred)
  File "tn-cli.py", line 90, in accMsg
    public=public, private=private, cred=parse_cred(cred))))
  File "/virtualenv/env/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 484, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/virtualenv/env/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 548, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message SetDesc has no "cred" field.
<_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception iterating requests!)>

**Comment by JasonHXiang** [comment]
By the way, how to configure tinode server not requiring the email addresses?

**Comment by or-else** [comment]
> "Protocol message SetDesc has no "cred" field"

Please pull https://github.com/tinode/chat/blob/large-files/pbx/model_pb2.py and https://github.com/tinode/chat/blob/large-files/pbx/model_pb2_grpc.py as well.

> By the way, how to configure tinode server not requiring the email addresses?

replace `["email"]` with `[]` or remove.
https://github.com/tinode/chat/blob/large-files/server/tinode.conf#L135
