### ISSUE TITLE
Is the back-end service log normal？

### ISSUE THREAD

**Issue by xingguangkuo** [tinode/chat#118]
I run the go run environment log. Is it right that websocket is often closed?

Session.dispatch got '{"hi":{"id":"79015","ver":"0.15","ua":"TinodeWeb/0.15 (Safari/601.1; Win32); tinodejs/0.15"}}' from '182.48.107.122:49638'
Session.dispatch got '{"login":{"id":"79016","scheme":"basic","secret":"Szh3WWpXWHA6N1dDZGg4R04="}}' from '182.48.107.122:49638'
Session.dispatch got '{"sub":{"id":"79017","topic":"me","get":{"what":"sub desc"}}}' from '182.48.107.122:49638'
case Sub to 'me' from 'usrd2R9ck8EXmo'
Sub to 'me' from 'usrd2R9ck8EXmo'
sess.writeLoop: ping/websocket: close sent
sess.writeLoop: ping/websocket: close sent
sess.readLoop: websocket: close 1005 (no status)
serveWebsocket - stop
Session.dispatch got '{"hi":{"id":"82735","ver":"0.15","ua":"TinodeWeb/0.15 (Safari/601.1; Win32); tinodejs/0.15"}}' from '182.48.107.122:50066'
Session.dispatch got '{"login":{"id":"82736","scheme":"basic","secret":"Ym9iOmJvYjEyMw=="}}' from '182.48.107.122:50066'
Session.dispatch got '{"sub":{"id":"82737","topic":"me","get":{"what":"sub desc"}}}' from '182.48.107.122:50066'
case Sub to 'me' from 'usrctNBS3OGhFE'
Sub to 'me' from 'usrctNBS3OGhFE'
sess.readLoop: websocket: close 1005 (no status)
serveWebsocket - stop
Session.dispatch got '{"hi":{"id":"69823","ver":"0.15","ua":"TinodeWeb/0.15 (Safari/601.1; Win32); tinodejs/0.15"}}' from '182.48.107.122:50454'
Session.dispatch got '{"login":{"id":"69824","scheme":"basic","secret":"Szh3WWpXWHA6N1dDZGg4R04="}}' from '182.48.107.122:50454'
Session.dispatch got '{"sub":{"id":"69825","topic":"me","get":{"what":"sub desc"}}}' from '182.48.107.122:50454'
case Sub to 'me' from 'usrd2R9ck8EXmo'
Sub to 'me' from 'usrd2R9ck8EXmo'
sess.writeLoop: ping/websocket: close sent

Thank you！

**Comment by or-else** [comment]
If you close or reload a browser tab with the client app, the websocket connection is closed by the server by timeout.

**Comment by xingguangkuo** [comment]
I know，Thanks！
