### ISSUE TITLE
How to keep a connection to get unread messages

### ISSUE THREAD

**Issue by xingguangkuo** [tinode/chat#119]
1：I first log in to the chat system and then set up a Topic. When I refresh regularly and judge the connection, I want to get the read messages and the number of SEQ in the topic again, but the number of messages in the topic, or the last data, has sent me the message. But I didn't get the latest news. When I refreshed the page and got it again, the unread message was displayed.

if (Tinode.Tinode.isConnected()) {
   if (c.id.indexOf("usr") == 0) {
        var t111 = Tinode.Tinode.getTopic(c.id)
        console.info(t111);
        //seq always get data from cache
}

How can this problem be solved? Thank you!

2：If I enter the contact list every time, I get the connection again. You can get the latest number of unread messages, but because I was refreshed regularly. At this time, I had a previous session connection, so I couldn't receive the message tree in real time. You can only refresh the list to see the unread message tree, while the current chat page has not received the message sent by the other party.

How can this problem be solved? Thank you!

**Comment by TaylorChristie** [comment]
If you login and subscribe to the `me` packet you will receive `pres` packets on new messages with the what as `msg`. It seems your using the JavaScript client but I'm not entirely sure. With the pres packets you get the seq number of the current message (without actually receiving the message) which you can use to get unread messages even if you are unsubscribed.

Your question is hard to understand and it doesn't make much sense to me but hopefully my answer helps you out. You should consult the api documentation.

**Comment by or-else** [comment]
1. Taylor Christie has answered this.

> When I refresh regularly

That's a highly inefficient and it's not how it's supposed to be used. Tinode is not a passive database. It will notify you automatically of all events.

2. 
> If I enter the contact list every time, I get the connection again

You are closing the connection. Don't close it.

Why don't you take a look at the JS example https://github.com/tinode/example-react-js and just do it the same way?
