### ISSUE TITLE
Is alternative license possible

### ISSUE THREAD

**Issue by richp10** [tinode/chat#125]
### Subject of the issue
I need a chat system to embed within a product which will be installed at client sites - GPL 3 is a deal breaker

### Is this a bug report of a feature request?
- [x ] Feature request

Is there any possibility of dual licensing - even on a commercial basis?

**Comment by or-else** [comment]
Certainly. Please contact me at gene@tinode.co (.co, not .com)
Thanks.

**Comment by edhemphill** [comment]
yeah - we were about to use it... but the copyleft is a deal killer.

**Comment by or-else** [comment]
The answer is still the same - contact us.
