### ISSUE TITLE
Golang Example

### ISSUE THREAD

**Issue by magicalbanana** [tinode/chat#126]
### Subject of the issue
Can we get more documentation on how to create an account? It's still a bit unclear although then new docs are getting there. For example, what's the end point we call to create an account?

Better yet, can we get an example purely as an API in `go`? And how do you add an API key to a running instance?

**Comment by or-else** [comment]
> Can we get more documentation on how to create an account

Please be specific. Ask specific questions, show what's missing.

> what's the end point we call to create an account?

It's always the same endpoint which creates a websocket:
https://github.com/tinode/chat/blob/master/docs/API.md#connecting-to-the-server.
Then all further communication with the server is conducted over the websocket (except large file uploading/downloading).

> can we get an example purely as an API in go

That's a lot of work.

**Comment by magicalbanana** [comment]
> Please be specific. Ask specific questions, show what's missing.
A full example would be nice. Like an actual request that hows the Headers, Body, etc. Although I figured this out, I am getting a method not allowed error which would be debugged faster if this documentation is available.
If I had more docs, I can help out building a full Golang API example.

**Comment by or-else** [comment]
OK, I think I understand now. 

You are trying to use Tinode as if it's a REST API. It is **NOT** a REST API. It's a streaming publish-subscribe API. The endpoint `/v0/channels` is only used to open a websocket. It is NOT for `http post`ing packets to it. It's used only to open a websocket. Once the websocket is created, the client uses websocket API to send packets. See here on websockets: https://en.wikipedia.org/wiki/WebSocket

Here is Go's stock implementation of websockets: https://golang.org/x/net/websocket
Here is another one that Tinode uses: https://github.com/gorilla/websocket

The API documentation is already quite clear on this point. Please do read the documentation with open mind.

**Comment by magicalbanana** [comment]
@or-else I see. So let's say that I have an application that already registers and authenticates users. Can I then just make a call to the Tinode server to create a user and authenticate them at the same time? I can right? But not using REST.

**Comment by or-else** [comment]
If I understand your question correctly, you have a client-server app which already has a mechanism for creating and authenticating users. You want to use Tinode as a second server. It should be possible. I don't see any big issues with such a use case.

**Comment by or-else** [comment]
BTW, it may be easier for you to create the users directly, like this app does:
https://github.com/tinode/chat/blob/master/tinode-db/gendb.go#L45

**Comment by magicalbanana** [comment]
@or-else yep. Basically, the user is created through the service we have and then the idea is, to call tinode to create a user on that service as well. When they authenticate, it also authenticates to tinode returning a token or whatever it is that tinode returns and from there. So my query really is, how do I make a call to tinode to create a user? I was wrong on my approach using REST. So I'll take a look at WebSocket calls. If you could perhaps or know of an example, I'd much appreciate it.

**Comment by or-else** [comment]
Just create the user directly: https://github.com/tinode/chat/blob/master/tinode-db/gendb.go#L45
