### ISSUE TITLE
Web Push API Encryption with VAPID support: webpush-go

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#128]
The feature request follows #120.

Looks like the webpush-go lib supports the browser dependent push services.
https://github.com/SherClockHolmes/webpush-go

Apple doesn't support it as shown here: https://caniuse.com/#feat=push-api 👎
Maybe you should change from (only) FCM to webpush-go to be prepared for apple push-api support in future releases? Low prio...

Client side JS (example https://webpushdemo.azurewebsites.net/, https://github.com/tinode/example-react-js/issues/12) would be easy to do.

**Comment by or-else** [comment]
FCM currently supports Android, iOS, desktop, and all major browsers except Safari (because Safari does not support push notifications): https://caniuse.com/#feat=push-api. And it's already implemented. Could you please explain why it needs to be changed? What's the use case that's not supported by FCM?

BTW, you are welcome to implement push notifications using any other library. Please send a pull request.

**Comment by pwFoo** [comment]
Hi @or-else,
You're right , all use cases supported, but instead of dependent on the used browser it's a FCM / Google dependency.

Browser dependent push service:
"notification server (e.g. Firebase Cloud Messaging (FCM), Mozilla Cloud Services (MCS), and Windows Push Notification Service (WNS) depending on which browser is being used"
Source: https://webpushdemo.azurewebsites.net/, "section STEP 1"

Would be nice to use the browser dependent push service instead of a fixed one.
I'm new with Go, but could take a look how it's implemented and if I could change.

**Comment by or-else** [comment]
FCM is a Google dependency indeed but it does not seem to be an issue outside of China.  Google owns ~80% of the smartphone market and 60% of the web browser market. If it decides to discontinue FCM or starts charging money, it's going to be a big problem for everyone. Given their problems with EU regulators it's highly unlikely that they will do anything like that.

I can see how FCM is a problem in China but I have no ability to test the alternatives anyway.

> Would be nice to use the browser dependent push service instead of a fixed one.

Why?

> I'm new with Go, but could take a look how it's implemented and if I could change.

If you could just add the notifications to the webapp that would be nice. The frontend still needs to be done regardless of the backend stack. The web app is all javascript, no need to learn Go.
