### ISSUE TITLE
Best way to invalidate keys

### ISSUE THREAD

**Issue by magicalbanana** [tinode/chat#129]
### Subject of the issue
What's the best way to invalidate issued keys?

**Comment by or-else** [comment]
You mean the API keys? 

* Change salt to reject all issued keys.
* There is a 16 bit sequential ID in the key. It's not being checked now, but it would be trivial to add `if id < X` or `if id != X`. Just increment the ID and reject all the keys with the wrong sequential ID.
* There is also a 32 bit AppId field. It's also currently unused. You can issue keys with different AppIds to different customers. Then implement some white list or black list policy. 

Just don't make database calls when checking the API key. Keep everything needed to check the key in memory.
