### ISSUE TITLE
RethinkDB password

### ISSUE THREAD

**Issue by magicalbanana** [tinode/chat#133]
### Subject of the issue
There seems to be no way to add rethinkdb password? Am I correct on this?

```
 Failed to init DB: gorethink: Wrong password
```

**Comment by or-else** [comment]
RethinkDB calls it `AuthKey`. It's quite trivial to add it. Just add `authkey` to `tinode.conf` in the `store_config.adapters.rethinkdb` section https://github.com/tinode/chat/blob/master/server/tinode.conf#L117.
Here all the options you can add to the RethinkDB configuration https://github.com/tinode/chat/blob/master/server/db/rethinkdb/adapter.go#L35.

**Comment by magicalbanana** [comment]
I think it's called `Password` now. https://github.com/GoRethink/gorethink/blob/master/session.go#L39

**Comment by or-else** [comment]
OK, thanks. I'll update the connection params with the new values tomorrow.

**Comment by magicalbanana** [comment]
@or-else can you also do a docker image release? Because I'm trying to test this out on Kubernetes.

**Comment by or-else** [comment]
Updated https://github.com/tinode/chat/commit/875939b311a9254eb14caade4c93ceae99621361
Docker images released https://hub.docker.com/r/tinode/tinode-rethinkdb/

**Comment by magicalbanana** [comment]
Legendary. Thanks @or-else!
