### ISSUE TITLE
Can the deleted chat receive messages from the peer?

### ISSUE THREAD

**Issue by JasonHXiang** [tinode/chat#134]
Hi, sorry to disturb you again.
[A Problem] 
Can the deleted chat receive messages from the peer?

In my case, user A and user B have a p2p chat topic. Now user A deletes B with {del} pkt. If user B sends some messages to A, user A's client doesn't receive any pkt.
I want to know whether it is possible that the deleted chat can receive messages from the peer, and then continue the chat before. @or-else

**Comment by or-else** [comment]
Please provide client-side and server-side logs.

**Comment by JasonHXiang** [comment]
In fact, my question is that 
after _user A_ unsubscribed _user B_，_user B_ sends a message to _user A_，
how does it make_user A_ receives the message and re-subscribes to _user B_ and continue the chat before.
By the way, I want _user A_ can be awaked up when the peer _user B_ comes to chat with her.

p.s. In the case of the official web demo (https://api.tinode.co/), alice chats with bob. Now alice leaves or delete bob on the contacts panel. Then, bob sends a message 'Hi' to alice, alice can't receive any message, and bob won't displayed on allice's contacts forever.

**Comment by or-else** [comment]
> p.s. In the case of the official web demo (https://api.tinode.co/), alice chats with bob. Now alice leaves or delete bob on the contacts panel. Then, bob sends a message 'Hi' to alice, alice can't receive any message, and bob won't displayed on allice's contacts forever.

That's not how it works now. A deletes the chat, B resubscribes and sends a message. The message is delivered. Unless users ban each other re-subscription works just fine.

You are doing something which is different from the way it's supposed to be done. That's why I'm asking for the logs.

**Comment by JasonHXiang** [comment]
OK, I'm using the web demo on https://api.tinode.co/. Here is the log.
[User Chat Addresses]
alice: **usrbzICiDFu8xw**
bob: **usrvzADGSWAX38**

[Client **alice** Log]
```
[07:02:33:826] in: {"info":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","what":"kp"}}
tinode.js:896 [07:02:35:262] in: {"data":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","ts":"2018-08-07T07:02:34.886Z","seq":21,"content":"1234"}}
tinode.js:896 [07:02:36:135] out: {"note":{"topic":"usrvzADGSWAX38","what":"recv","seq":21}}
tinode.js:896 [07:02:36:140] in: {"info":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","what":"recv","seq":21}}
tinode.js:896 [07:02:36:617] in: {"info":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","what":"read","seq":21}}
tinode.js:896 [07:02:39:739] out: {"note":{"topic":"usrvzADGSWAX38","what":"read","seq":21}}
tinode.js:896 [07:02:43:903] out: {"note":{"topic":"usrvzADGSWAX38","what":"kp"}}
tinode.js:896 [07:02:46:725] out: {"pub":{"id":"128426","topic":"usrvzADGSWAX38","content":"5678"}}
tinode.js:896 [07:02:47:110] in: {"ctrl":{"id":"128426","topic":"usrvzADGSWAX38","params":{"seq":22},"code":202,"text":"accepted","ts":"2018-08-07T07:02:46.814Z"}}
tinode.js:896 [07:02:47:112] in: {"data":{"topic":"usrvzADGSWAX38","from":"usrbzICiDFu8xw","ts":"2018-08-07T07:02:46.814Z","seq":22,"content":"5678"}}
tinode.js:896 [07:02:47:614] out: {"note":{"topic":"usrvzADGSWAX38","what":"recv","seq":22}}
tinode.js:896 [07:02:48:112] out: {"note":{"topic":"usrvzADGSWAX38","what":"read","seq":22}}
tinode.js:896 [07:02:48:191] in: {"info":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","what":"recv","seq":22}}
tinode.js:896 [07:02:50:723] in: {"info":{"topic":"usrvzADGSWAX38","from":"usrvzADGSWAX38","what":"read","seq":22}}
tinode.js:896 [07:02:57:640] out: {"del":{"id":"128427","topic":"usrvzADGSWAX38","what":"topic"}}
tinode.js:896 [07:02:58:098] in: {"ctrl":{"id":"128427","topic":"usrvzADGSWAX38","code":200,"text":"ok","ts":"2018-08-07T07:02:57.729Z"}}
```

[Client **bob** Log]
```
[07:02:33:384] out: {"note":{"topic":"usrbzICiDFu8xw","what":"kp"}}
tinode.js:896 [07:02:34:797] out: {"pub":{"id":"68060","topic":"usrbzICiDFu8xw","content":"1234"}}
tinode.js:896 [07:02:35:263] in: {"ctrl":{"id":"68060","topic":"usrbzICiDFu8xw","params":{"seq":21},"code":202,"text":"accepted","ts":"2018-08-07T07:02:34.886Z"}}
tinode.js:896 [07:02:35:264] in: {"data":{"topic":"usrbzICiDFu8xw","from":"usrvzADGSWAX38","ts":"2018-08-07T07:02:34.886Z","seq":21,"content":"1234"}}
tinode.js:896 [07:02:35:767] out: {"note":{"topic":"usrbzICiDFu8xw","what":"recv","seq":21}}
tinode.js:896 [07:02:36:266] out: {"note":{"topic":"usrbzICiDFu8xw","what":"read","seq":21}}
tinode.js:896 [07:02:36:592] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","what":"recv","seq":21}}
tinode.js:896 [07:02:40:176] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","what":"read","seq":21}}
tinode.js:896 [07:02:44:273] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","what":"kp"}}
tinode.js:896 [07:02:47:110] in: {"data":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","ts":"2018-08-07T07:02:46.814Z","seq":22,"content":"5678"}}
tinode.js:896 [07:02:48:060] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","what":"recv","seq":22}}
tinode.js:896 [07:02:48:190] out: {"note":{"topic":"usrbzICiDFu8xw","what":"recv","seq":22}}
tinode.js:896 [07:02:48:192] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrvzADGSWAX38","what":"recv","seq":22}}
tinode.js:896 [07:02:48:573] in: {"info":{"topic":"usrbzICiDFu8xw","from":"usrbzICiDFu8xw","what":"read","seq":22}}
tinode.js:896 [07:02:50:309] out: {"note":{"topic":"usrbzICiDFu8xw","what":"read","seq":22}}
tinode.js:896 [07:03:10:215] out: {"note":{"topic":"usrbzICiDFu8xw","what":"kp"}}
tinode.js:896 [07:03:11:892] out: {"pub":{"id":"68061","topic":"usrbzICiDFu8xw","content":"90"}}
tinode.js:896 [07:03:12:246] in: {"ctrl":{"id":"68061","topic":"usrbzICiDFu8xw","params":{"seq":23},"code":202,"text":"accepted","ts":"2018-08-07T07:03:11.980Z"}}
tinode.js:896 [07:03:12:248] in: {"data":{"topic":"usrbzICiDFu8xw","from":"usrvzADGSWAX38","ts":"2018-08-07T07:03:11.980Z","seq":23,"content":"90"}}
tinode.js:896 [07:03:12:756] out: {"note":{"topic":"usrbzICiDFu8xw","what":"recv","seq":23}}
tinode.js:896 [07:03:13:252] out: {"note":{"topic":"usrbzICiDFu8xw","what":"read","seq":23}}
```

**Comment by or-else** [comment]
OK, I see you point. This is not really a bug. When you delete the topic you actually sever the connection between the users. Deleting a topic means "I don't want to continue this conversation anymore". What you probably want is to delete all messages and archive the conversation. Or you want automatic restoration of a topic when the other p2p user sends a message.

**Comment by or-else** [comment]
Another option is to delete the topic for the other user too when one user deletes it.

**Comment by JasonHXiang** [comment]
> Or you want automatic restoration of a topic when the other p2p user sends a message.

Yes, this is what I want🙂.
I need alice can restore the chat with bob when bob sends messages to alice.

**Comment by or-else** [comment]
It follows from your description that the user A does not want to delete the topic. User A wants to archive the topic and maybe delete all the messages.

**Comment by JasonHXiang** [comment]
Thank you for answering my questions.🤝@or-else

em, I added a field named is_del to the table subscriptions, and solved my problem finally.
User A requests a API to make is_del=True, and it stands for deleting the chat, but the subscription does not be deleted actually, so User A can receive the messages from B, and then continue the chat before.

**Comment by JasonHXiang** [comment]
Honestly, I ran into another problem how to compare User Addresses with Python. I didn’t find a Pythonic method to solve this. As I see, a user address is typed as Uid, or uint64.

For Example:
[User Chat Addresses]
alice: usrbzICiDFu8xw
bob: usrvzADGSWAX38

**Comment by or-else** [comment]
> I added a field named is_del to the table subscriptions

Great that you solved your problem. On the other hand, it's going to be a problem if users are unable to delete their conversations at all.

> how to compare User Addresses with Python

UIDs on the client are just strings. Why not compare them as strings?
```
alice="usrbzICiDFu8xw"
bob="usrvzADGSWAX38"
print("equal" if alice == bob else "not equal")
```

**Comment by or-else** [comment]
Why do you need to generate the names of p2p topics? They are not generally exposed beyond the server.

**Comment by or-else** [comment]
This release fixes the problem you reported. Thanks!
https://github.com/tinode/chat/releases/tag/v0.15.5-beta1

There is some inconsistence in reporting online status for p2p topics with one subscription deleted, so this is not the final release.

**Comment by or-else** [comment]
Finished: https://github.com/tinode/chat/releases/tag/v0.15.5-rc2
