### ISSUE TITLE
Can you give a basic demo of how to use the GRPC api in go?

### ISSUE THREAD

**Issue by vjeson** [tinode/chat#136]
for example ,how to call ClientMsg_Acc ClientMsg_Login in grpc , 
I wrote a basic, but I don't know how to continue.
`	
const (
	address     = "localhost:6061"
	defaultName = "chat"
)

        conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatal("did not connect: %v", err)
	}
	defer conn.Close()
	nodeClient:=pb.NewNodeClient(conn)
       pluginClient := pb.NewPluginClient(conn)
	//pb.Session_AUTH
	unused,err:=pluginClient.Account(context.Background(), &accountEvent)
`

**Comment by vjeson** [comment]
Don't need a full demo , just part of the workflow , how to init and call , I think 5 minutues is enough to you , If you can tell me the general idea, I can implement a demo.

Anyway ,I will take a look at python version at first
Thanks

**Comment by or-else** [comment]
No, 5 min is not enough for me to write a basic client. Please do try to figure it out yourself. If you fail feel free to ping me again in a week or so.
You may find this tutorial useful: https://grpc.io/docs/tutorials/basic/go.html

Keep in mind that the Tinode gRPC client uses streaming API. So this part is most relevant:
https://grpc.io/docs/tutorials/basic/go.html#client-side-streaming-rpc

**Comment by vjeson** [comment]
I've created a basic demo, but I have some questions, can you explain for me? I marked the question with todo ,and my receive method is right?
`
package main

import (
	"log"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	pb "chat/pbx"
	"fmt"
	"strconv"
	"encoding/base64"
)

const (
	address     = "localhost:6061"
	defaultName = "chat"

)
var 	tid =100
func main() {
	conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatal("did not connect: %v", err)
	}
	defer conn.Close()
	nodeClient:=pb.NewNodeClient(conn)

	nodeMessageLoopClient,err:=nodeClient.MessageLoop(context.Background(),) //TODO:What parameters should I pass here？

	go receiveMsg(nodeMessageLoopClient)
	tid:=getNextId()
	helloMsg:=&pb.ClientMsg{Message:&pb.ClientMsg_Hi{Hi:&pb.ClientHi{Id:tid,UserAgent:"tindoe/0.1/go/0.1;gRPC-go",Ver:"0.15",Lang:"EN"}}}
	err=nodeMessageLoopClient.Send(helloMsg)
	if err!=nil{
		fmt.Printf("send hello error: %v", err)
	}
	var cred []*pb.Credential
	cred=append(cred,&pb.Credential{Method:"email",Value:"c2@gg.com"})
	secret:=base64.StdEncoding.EncodeToString([]byte("c2:1"))
	fmt.Printf(secret)
	accMsg:=&pb.ClientMsg{Message:&pb.ClientMsg_Acc{Acc:&pb.ClientAcc{Id:getNextId(),UserId:"new",Scheme:"basic",Secret:[]byte("c2:1"),Login:true,Desc:&pb.SetDesc{Public:[]byte("{\"fn\":\"c2\"}")},Cred:cred}}}
	nodeMessageLoopClient.Send(accMsg)

	select {

	}


	//loginMsg:=&pb.ClientMsg{Message:&pb.ClientMsg_Login{Login:&pb.ClientLogin{Id:getNextId(),Scheme:"basic",Secret:[]byte("YTE6MQ==")}}}
	//nodeMessageLoopClient.Send(loginMsg)
	//if err!=nil{
	//	fmt.Printf("send login error: %v", err)
	//}


	//accountEvent := pb.AccountEvent{Action: pb.Crud_CREATE,}
	//pluginClient := pb.NewPluginClient(conn)
	////pb.Session_AUTH
	//unused,err:=pluginClient.Account(context.Background(), &accountEvent)
	//if err != nil {
	//	log.Fatal("could not greet: %v", err)
	//}
	//fmt.Println(unused)

}

func receiveMsg(client pb.Node_MessageLoopClient)  {
	for {
		serverMsg,_:=client.Recv()
		switch v := serverMsg.Message.(type) {
		case *pb.ServerMsg_Ctrl:
			fmt.Printf("ServerMsg_Ctrl is: %v \n", v)
		case *pb.ServerMsg_Data:
			fmt.Printf("ServerMsg_Data is: %v \n", v)
		case *pb.ServerMsg_Pres:
			fmt.Printf("ServerMsg_Pres is: %v \n", v)
		case *pb.ServerMsg_Info:
			fmt.Printf("ServerMsg_Info is: %v \n", v)
		}


	}

}

func getNextId() string  {
	tid++
	return strconv.Itoa(tid)
}
`

**Comment by or-else** [comment]
> nodeMessageLoopClient, err := nodeClient.MessageLoop(context.Background(), ) //TODO:What parameters should I pass here?

Optional call parameters grpc.CallOption
https://github.com/tinode/chat/blob/master/pbx/model.pb.go#L3411

> //TODO: NewPluginClient  What are these methods used for ? when I should use these methods?

You don't need these if you only create a client. These are for communicating with plugins. The chatbot needs to use them because it needs to attach to new accounts.

BTW, you may find it easier to post your code to https://gist.github.com/
Alternatively create a repository on github, add your code as a pull request, invite me to review the PR.

**Comment by vjeson** [comment]
Thanks very much
The code format is very bad with github markdown editor. I think that's a bug 
Now I just need to call the api from server to sync account with other system, so call the grpc api is one way ,But I think it would be a better choice if we had a restful API

**Comment by or-else** [comment]
> But I think it would be a better choice if we had a restful API

If you need me help then please describe your use case in detail.

**Comment by yogesnsamy** [comment]
Here's the code I've got going, hope it helps someone just starting out: https://gist.github.com/yogesnsamy/536f75c46af31470bf03b0f8e6171b0b
