### ISSUE TITLE
Android App as channel or pager. Without chat

### ISSUE THREAD

**Issue by freenetwork** [tinode/chat#137]
### Tell me

Can I use this project to notify employees? Make it impossible to correspond? At the moment, alerts are generated by sms, but this has become expensive.

### Is this a feature request?
- [X ] Feature request

#### Server-side
  * platform Windows
  * version of tinode server, e.g. `v0.15.4`
  * MySQL
  
#### My Client-side
Android App

**Comment by or-else** [comment]
It should be possible out of the box for ~10000 people.

Do you communicate with them as a group, i.e. send the same message to all of them (or a group) or you want to send different messages to different individuals?

**Comment by freenetwork** [comment]
different messages to different individuals?

**Comment by or-else** [comment]
Then you want something like this:

* Create a user you want to use for sending messages.
* Set his default auth permissions to something like JRAS
* Create a user for every employee (or let them regisister).
* Use tn-cli to send messages to users: first subscribe to user, then send message, then leave.
