### ISSUE TITLE
Question: Implement sqlite driver for tinode?

### ISSUE THREAD

**Issue by doanguyen** [tinode/chat#138]
I'm new to both Golang and real-time applications, so my question might be very naive. Is this worth to implement SQLite driver for Tinode since it's really helpful for development time. SQLite is io write locking so it may be troublesome.

Thanks for a very well written open source btw.

**Comment by or-else** [comment]
Thanks!

SQLite is great for small, usually single-user systems. SQLite adapter may be useful if you are building something very small scale, where running a single binary is more important than scaling. If you expect to use Tinode in a classic server-client environment then something like PostgreSQL adapter would be a lot more useful.

**Comment by doanguyen** [comment]
Sure, I'm talking about the development environment only. I know you put a lot of effort into this project so my request might be unnecessary.

**Comment by or-else** [comment]
If the idea is to use the sqlite adapter as a development backend, for instance for running tests, then I can see a use case.

**Comment by or-else** [comment]
You are welcome to contribute one if you find it useful.

**Comment by dzcpy** [comment]
How about supporting PostgreSQL?

**Comment by or-else** [comment]
@dzcpy 

Someone is working on it albeit slowly:
https://github.com/tinode/chat/pull/300

**Comment by or-else** [comment]
Postgress tracking issue: https://github.com/tinode/chat/issues/232
