### ISSUE TITLE
Admin Panel for the chat appllication

### ISSUE THREAD

**Issue by vatsal78** [tinode/chat#139]
It is a Feature request.

Are you planning to make admin panel for the same too manage all the things of the application.

**Comment by or-else** [comment]
An admin panel or a CLI would certainly be useful. It's just a substantial amount of work. It may have to wait until the project gets more contributors.

**Comment by vatsal78** [comment]
What we want to achieve is:
1. Addition and Deletion of user as well as bot
2. See the user chat history (Personal as well as group)
3. See idle time and online/offline status of every user
4. Create group and add as many as user to that group
5. Chat handover from one user to another in admin panel

**Comment by or-else** [comment]
> 1. Addition and Deletion of user as well as bot

OK. As far as server is concerned, a bot is just a regular user.
Creating an account already exists.
Deleting an account is ambiguous. There is suspending, when an account is blocked - the owner cannot login, the account cannot accept new messages. And then there is deleting which requires deleting all content created by the account. Suspending is easy, deleting is harder.

> 2. See the user chat history (Personal as well as group)

OK. There is no such thing as personal. It's all messages within a topic.

> 3. See idle time and online/offline status of every user

A paginated list of users online?
See one user?

> 4. Create group and add as many as user to that group

What's the use case for it?

> 5. Chat handover from one user to another in admin panel

I'm not sure I understand. Please elaborate.

**Comment by or-else** [comment]
What are the use cases you have it mind? Support for a service like WhatsApp or Telegram? Customer support over chat? What else?

**Comment by TaylorChristie** [comment]
Depending on the stack you want to use for the admin panel, I can probably help out.

**Comment by pwFoo** [comment]
Admin panel should use api and could be deployed optional as additional docker container? So it could be stopped If not needed?

**Comment by or-else** [comment]
@TaylorChristie the stack is open for discussion. I think it should be either Node or Python but anything else should be considered as well.

@pwFoo Yes, I believe it should be a separate web app with it's own Docker container, started and stopped completely separately from the main app.
It can be similar to to Django's or RethinkDB's admin panel:
https://github.com/fabiocaccamo/django-admin-interface

**Comment by TaylorChristie** [comment]
@or-else I can do either; I'm well versed in both.  I'm currently using lots of node in my current projects.

**Comment by or-else** [comment]
I think Node is a bit more popular these days than Python. 

I think the best approach is to use gRPC interface to make calls from the admin client to the server. If something is missing in the current gRPC interface it would not be too difficult to add.

It would almost certainly require a `root` or `admin` authentication level which needs to be added to the server (in addition to `Auth` and `Anon`)

**Comment by TaylorChristie** [comment]
I'll be needing this admin/root user and the grcp commands in order to delete users from the system. Is this feature currently under development? My company now wants the ability to hard delete (and disable) users and messages.

**Comment by or-else** [comment]
The root user is already implemented. See https://github.com/tinode/chat/releases/tag/v0.15.7

 I'll add an option to disable users. The root will be able to sent something like `{set what="upd" user="userXYZ" status="disabled"}`. That will make user account un-accessible + will disable all topics where the user is the owner. 

I'll also add an option to terminate all user's sessions.

Then there is the question of actually deleting data from the database. That's potentially a very heavy operation. Particularly messages. Do you actually need to delete the messages of a deleted user?

**Comment by or-else** [comment]
This feature is technically available through `tn-cli`. It's non-GUI but offers pretty much all functionality of an admin interface. Is there anything missing in `tn-cli`?

**Comment by or-else** [comment]
Admin is available now:
https://tinode.co/tnadmin.html
