### ISSUE TITLE
Tinode.js break react native

### ISSUE THREAD

**Issue by fstn** [tinode/chat#141]
In react native, the user agent is not define so:  

`
  // First test for WebKit based browser.
  ua = ua.replace(' (KHTML, like Gecko)', '');
`

in tinode.js l63 break because ua is not define

**Comment by or-else** [comment]
Thanks for the fix.

It looks like `navigator` is defined under React Native? It's not defined in Node.
https://github.com/tinode/tinode-js/blob/master/src/tinode.js#L875

**Comment by fstn** [comment]
It's not define when using expo without remote debugger :(

**Comment by or-else** [comment]
OK, thanks!
