### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by ciaoamigoschat** [tinode/chat#142]
Do you know where I can find an example done in reactNative?

**Comment by fstn** [comment]
You can use the same code as the react app ;)

**Comment by fstn** [comment]
Can you close it? I opened a new one on the good project

**Comment by ciaoamigoschat** [comment]
Scenario:
1) With native react the server is started without -static_data?
2) Can a backend logic be created to customize client behavior? Example: points, gifts, etc.

**Comment by or-else** [comment]
> With native react the server is started without -static_data?

I'll leave this to @fstn to answer.

> Can a backend logic be created to customize client behavior? Example: points, gifts, etc.

You need to be more specific. In general, server knows nothing about what's being sent in the messages. All that logic should be in the client.

**Comment by ciaoamigoschat** [comment]
Leaving logic to clients is never a good choice for many reasons.
Our application, for now developed in Adobe Media Server, analyzes every behavior of the client.
Example:
- If I send more than 3 messages per second, it is blocked for 60 seconds.
- Points are awarded every 10 minutes of activity.
- Every 10 blocked private messages are denied the possibility to send others, etc. 
- etc..

**Comment by or-else** [comment]
The logic you listed can be implemented as a server-side [plugin](https://github.com/tinode/chat/blob/master/pbx/model.proto#L11).

**Comment by ciaoamigoschat** [comment]
This server is not aware of the content of the messages.
1) But must know, how many messages are sent by a client -> provide an antiflood
2) Must know if a customer performs activities, etc.

**Comment by or-else** [comment]
> This server is not aware of the content of the messages.

Correct. The server itself does not need to know. All to knows is how to route and store messages.

> But must know, how many messages are sent by a client -> provide an antiflood

Which is perfectly possible with the plugin. You can implement any kind of custom logic there.

> Must know if a customer performs activities, etc.

Ditto.

**Comment by or-else** [comment]
I assume you are either satisfied with the answer or it's no longer relevant. Closing. 
If you would like to discuss it further, please post to https://groups.google.com/d/forum/tinode

Thanks!
