### ISSUE TITLE
Message content parsed for "true" or "false" when using grpc

### ISSUE THREAD

**Issue by srkridev** [tinode/chat#145]
### Subject of the issue
When sending message to another member using gRPC, message content is parsing only for values "true" or "false" and not the actual content.
When "true" or "false" is sent no parsing error is displayed (in the server log, provided below).
Seems in code a boolean or some other comparison is performed, that verifying the actual content.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

### Your environment
v0.15.5
tinode-mysql.windows-amd64.zip
grpc client
Windows 10, MySQL on Linux

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows)
  * version of tinode server, v0.15.5
  * database backend (MySQL on Linux)
  
#### Client-side
gRPC client

### Steps to reproduce
Tell us how to reproduce this issue.
Issue observed when send a "pub" message fro a gRPC client.

### Expected behaviour
Message should be processed as is, and not compare for strings "true" or "false"

### Actual behaviour
Content is not processed as is, but compared for values "true" or "false"

### Server-side log
Please find the log messages displayed in the server log.
Note: No error reported when 'content:"true"' or 'content:"false"'

2018/09/10 15:55:29 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"test" >
2018/09/10 15:55:29 pbx: failed to parse bytes test invalid character 'e' in literal true (expecting 'r')
2018/09/10 15:55:36 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"t" >
2018/09/10 15:55:36 pbx: failed to parse bytes t invalid character ' ' in literal true (expecting 'r')
2018/09/10 15:55:45 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"tr" >
2018/09/10 15:55:45 pbx: failed to parse bytes tr invalid character ' ' in literal true (expecting 'u')
2018/09/10 15:55:52 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"tru" >
2018/09/10 15:55:52 pbx: failed to parse bytes tru invalid character ' ' in literal true (expecting 'e')
2018/09/10 15:55:58 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"true" >

2018/09/10 15:59:36 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"false" >
2018/09/10 15:59:46 grpc in: pub:<id:"12130" topic:"usrLzBm0ZLuio4" no_echo:true content:"falsex" >
2018/09/10 15:59:46 pbx: failed to parse bytes falsex invalid character 'x' after top-level value

### Client-side log
Message sent successfully to server, but no response received at client end.

**Comment by or-else** [comment]
I was able to reproduce it. Thanks for the report.

**Comment by or-else** [comment]
OK, it's more of a misunderstanding than a bug. The `content` cannot be a naked string. It must be a json string. For example, in C-like languages it must be `content = "\"t\""`, **not** `content = "t"`. In Python you need to  `json.dumps(content).encode('utf-8')`

I've updated `tn-cli` to correctly wrap `content`.
