### ISSUE TITLE
Connection error in react native

### ISSUE THREAD

**Issue by sramezani** [tinode/chat#147]
I am try to connect Tinode Websocket with react native app, but i get error: 

`WebSocketEvent {type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false…}`

#### like this image:

![screenshot from 2018-09-10 18-33-55](https://user-images.githubusercontent.com/33284430/45304563-96070b80-b52d-11e8-9b03-fd9e659f64b9.png)

I am test Tinode Websocket connection in web and not problem with this and easily connect and login.

even i am try connect directly with react native websocket to tinode like below images but again i get error.

![screenshot from 2018-09-10 18-41-42](https://user-images.githubusercontent.com/33284430/45305041-bc797680-b52e-11e8-937d-fccadf6a521f.png)
![screenshot from 2018-09-10 18-40-26](https://user-images.githubusercontent.com/33284430/45305053-c13e2a80-b52e-11e8-9d0b-d9a2f3cdc22b.png)

**Comment by or-else** [comment]
It seems like the problem is due to a network timeout. Does the webapp work when you connect to it with a web browser **from the same host**? In other words, if you are running the app in an emulator, can you connect to the internet from the emulator?

**Comment by or-else** [comment]
Any update on this?

**Comment by sramezani** [comment]
hi sorry for late answer.

we found the problem.
actually it was very silly.
we are living in iran and we think either tinode server or iran government have blocked our requests.

so, we have fixed this issue by vpn.

**Comment by or-else** [comment]
Great.

Tinode server does not block any IPs.
