### ISSUE TITLE
PIng/Pong Functionality 

### ISSUE THREAD

**Issue by TaylorChristie** [tinode/chat#148]
### Subject of the issue
Due to some limitations of proxy servers, it would be nice to have a ping/pong functionality to keep the connection alive. Instead of modifying proxy server configurations to allow long timeouts for requests. Some simple functionality that will send ping requests every ~30 seconds and receive pongs would solve this issue (Adonis Websockets uses this solution). It could also assist in connection and health information metrics. 

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Linux
  * 0.15
  * MySQL

**Comment by or-else** [comment]
It's there from the very beginning once ever 50 seconds or so: https://github.com/tinode/chat/blob/master/server/hdl_websock.go#L47

Do I understand correct you want it every 30 seconds?

**Comment by TaylorChristie** [comment]
Oh the actual time difference doesn't matter; I didn't see this functionality in the documentation! It's great to hear it's actually already implemented. How do I access it through the API?

**Comment by or-else** [comment]
You don't see it in documentation because it's a part of websocket specification. It's been in use from the very beginning. It's on all the time. The server sends pings, the clients send pongs. It works now everywhere.

**Comment by TaylorChristie** [comment]
Oh I see. The reason I wanted to have actual socket messages with ping/pong is that proxies like nginx don't actually see that as a "message" through the server, so it assumes that no messsages are being sent and will timeout if set to a low timeout; I could be wrong though. I know in the past though I had to raise the timeout threshold in order to keep socket connections alive for tinode through an nginx proxy.

**Comment by or-else** [comment]
The proxy needs to explicitly recognise a websocket connection. Websocket is initially opened as HTTP and then "upgraded" or "hijacked". After issuing an `Upgrade` request on the initial HTTP connection, the connection is [switched](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake) to a different mode which is more like a plain TCP connection than an HTTP. 

In case of outdated proxies use long polling.

**Comment by or-else** [comment]
BTW, nginx has support for websockets. It's just needs to be configured:
https://www.nginx.com/blog/websocket-nginx/

**Comment by TaylorChristie** [comment]
Here's a similar issue someone else is having: https://stackoverflow.com/questions/10550558/nginx-tcp-websockets-timeout-keepalive-config The issue is that tinode can not send or recieve websocket messages for a long time (ie: the user is away from the PC). I don't believe nginx listens to the websocket spec keepalive as in my tests behind nginx it would drop the connection unless i increased the keepalive time. If you think this is more of an issue with nginx instead then you can close this.

**Comment by or-else** [comment]
The issue you reference is an issue with nginx 1.0.12 which was released in Feb 2012. In May 2012 nginx 1.3 was released which had support for websockets. That was more than 6 years ago. I don't see what can be done when the client is behind such an outdated proxy other than to switch to an even older tech. In case of Tinode that's using long polling.
