### ISSUE TITLE
how to pub a message to any specified topic

### ISSUE THREAD

**Issue by vardef** [tinode/chat#149]
user bind to session when is logged in,that is to say, to send a message, you must subscribe the topic first. how to pub a message to any specified topic? eg: admin or other system trigger

**Comment by or-else** [comment]
Subscribing to topic is required for (a) loading topic to memory, (b) permissions checking. Why is it a problem to send {sub} first?

**Comment by rain10154** [comment]
it's a problem when red envelope

**Comment by or-else** [comment]
Is it petlrsolalized, with a different redemption code for different users, or the same code for everyone?

**Comment by vardef** [comment]
Subscribing to topic  first can solve the problem ，thanks @or-else
