### ISSUE TITLE
Audio and video call support

### ISSUE THREAD

**Issue by SantoshSah** [tinode/chat#150]
### Subject of the issue
Do you have any future plan for audio/video chat features?

### Is this a bug report of a feature request?
- [x] Feature request

**Comment by or-else** [comment]
It's a lot of work, probably as much as the original project. It's not going to happen until the project gains some traction.

**Comment by pcgpcgpcg** [comment]
Is it possible to join tinode project as a contributor?

**Comment by or-else** [comment]
Of course. You are welcome to join.

**Comment by pcgpcgpcg** [comment]
that's great! so just pull request,is it right?

**Comment by or-else** [comment]
> that's great! so just pull request,is it right?

If you are contributing something significant, I would like you to sign the CLA:
https://github.com/tinode/chat/blob/master/docs/CLA.md

Also, you may want to tell what you want to contribute just to be sure that we are on the same page. Thanks!

**Comment by novalis111** [comment]
Simple implementation (like Zulip, Riot/Matrix) would be to auto-generate a link to a room at https://meet.jit.si/ or https://talky.io/ - Zulip just uses some md5 hash to attach to these urls and inserts the link into the chat.

**Comment by pwFoo** [comment]
Audio & video calls would be great, but should be implemented the right way. Don't like the external link / service way.

Maybe implement it later, but native. I don't have experience with that parts, but maybe there is a lib to do it (webrtc, peerjs?)

**Comment by pwFoo** [comment]
I found [JsSIP](https://github.com/versatica/JsSIP). Maybe that could help with SIP calls?
But I think it needs a SIP server...

**Comment by pwFoo** [comment]
Audio / Video Calls (also screen sharing, file transfer) could be a peer to peer (tinode client) feature?
https://github.com/feross/simple-peer

**Comment by gedw99** [comment]
ion has a golang backend and flutter / js front end for video conf and screen sharing.


https://github.com/pion/ion-examples

can do multi party also using a SFU.

many many people are using it. it works.

**Comment by rkgarcia** [comment]
Probably we can use something like https://github.com/KalbiProject/Kalbi

I will use this tool for internal communications, I'm a begginer using golang but i want to learn and apply to this project.

Regards

**Comment by or-else** [comment]
> https://github.com/KalbiProject/Kalbi

This is a server-size component which allows two or more clients to start a VoIP session. Adding VoIP to Tinode would also require a lot of client-side work.

**Comment by or-else** [comment]
This is in progress in https://github.com/tinode/chat/tree/calls-dev

**Comment by or-else** [comment]
Released in https://github.com/tinode/chat/releases/tag/v0.20.0-beta2 for web and android, iOS is in progress.
