### ISSUE TITLE
How to build a chatbot with .Net?

### ISSUE THREAD

**Issue by BenDerPan** [tinode/chat#153]
### Subject of the issue
I wish to build a C# version chatbot,  could someone give some guides?

### Is this a bug report of a feature request?
- [ ] Bug report
- [* ] Feature request

#### Server-side
- [ ] api.tinode.co
- [* ] Your own setup:
  * platform (Windows)
  * version of tinode server, e.g. `0.15.1`
  * database Mysql
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ *] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

**Comment by or-else** [comment]
Here is a basic gRPC tutorial for C#: https://grpc.io/docs/quickstart/csharp.html
Specifically this part tells how to generate C# files from the .proto:
https://grpc.io/docs/quickstart/csharp.html#generate-grpc-code

Then use the python example as a template for your bot.

**Comment by BenDerPan** [comment]
@or-else  that's work, thx, I will make a PR when I finish it.

**Comment by or-else** [comment]
Great, thanks!

**Comment by BenDerPan** [comment]
@or-else  It's ok now, I made a PR, could you please review it.

**Comment by or-else** [comment]
Before I merge it, could you please sign the CLA?
https://github.com/tinode/chat/blob/master/docs/CLA.md

Thanks!

**Comment by BenDerPan** [comment]
@or-else  I signed it, :)

**Comment by BenDerPan** [comment]
@or-else  I made a new PR, fixed the problems:
1. Git-moving preserves the commit history. Just moving without git erases the commit history (One by One move can work on windows).
2. Use all lowercase paths at the top level.

**Comment by or-else** [comment]
> @or-else I signed it, :)

Thanks, but I need your real name there. It will not be disclosed anywhere.

**Comment by BenDerPan** [comment]
@or-else OK now ,I signed again.

**Comment by or-else** [comment]
Great, all done, PR merged. Thanks!
