### ISSUE TITLE
iOS client

### ISSUE THREAD

**Issue by maximbukanov** [tinode/chat#154]
### Subject of the issue
How long do you plan to make a client for iOS? Will this app be made with JS (e.g. React Native) or Swift?

### Is this a bug report of a feature request?
- [x] Feature request

**Comment by or-else** [comment]
I have no immediate plans for an iOS client. I don't know Swift or React Native, I don't own an iPhone.

**Comment by fstn** [comment]
I did a React Native App, you can use the Tinode js on branch devel

**Comment by or-else** [comment]
@aforge has started work on an iOS client. It would be the right time to join and help: https://github.com/tinode/ios

**Comment by ozobken** [comment]
Nice - I am talking to Tinode from IOS via Objective-C/GRPC, and what I have could be turned into a client as well, but something in Swift would be preferable for an "official" client.
The GRPC/Swift wrapper is still experimantal, but it might be up to scratch for real world use.

**Comment by aforge** [comment]
@ozobken One thing that would be super useful right now is a working UI in Swift. Would you happen to have it?

**Comment by ozobken** [comment]
@aforge - No - sorry - my whole project is in Obj-C - I'm using https://github.com/slackhq/SlackTextViewController for the message interface, which is also now deprecated.  Happy to help with the Swift app when I can, though

**Comment by ozobken** [comment]
Interesting wrinkle with this - Apple notifications that set a "badge" can only supply a number from the backend, not increment/decrement - does the Tinode backend know how many "unread" messages exist for a specific user (I guess, based on "sub"s) so we can pass that to the IOS notification?

I have notifications working via FCM just fine by uncommenting the section in push_fcm.go, but of course, this doesn't send any badge info, just the message notification

**Comment by or-else** [comment]
> does the Tinode backend know how many "unread" messages exist for a specific user

Yes it does. Are you saying you need this info in a push notification?

**Comment by or-else** [comment]
To be sure we are on the same page. The server knows unread count per-topic. It does not currently track the total unread count for all topics.

**Comment by ozobken** [comment]
Yes - IOS push notifications can set the "badge" on the app icon but it has to send an absolute "total" number in each notification - So the code in push_fcm.go needs to be able to compute the total and send it along with the message in the JSON payload as a "badge" value
See:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

**Comment by or-else** [comment]
The native iOS client is fully functional: https://github.com/tinode/ios. I think this issue can be closed now.
