### ISSUE TITLE
Ability to import data.json using Rest API

### ISSUE THREAD

**Issue by fstn** [tinode/chat#158]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

### Expected behaviour
I would like to be able to call a REST API to import data.json file in order to be able to synchronize Tinode users with my servers users.

The idea is to transform:
./init-db -data=data.json

Into POST data.json to rest API

The purpose is to synchronize users, group and topics every night...

**Comment by fstn** [comment]
> If you have an existing database of users it's possible to make Tinode login completely natural.

It might be better in this way...

Can you give me the step to follow to be able to get my users, my channels from an external Database?

I found this https://github.com/tinode/chat/tree/master/server/auth

**Comment by or-else** [comment]
If you need help, ask.

**Comment by fstn** [comment]
OK, I made a slack like application using React Native and Tinode. It's an enterprise application, and for support purpose,  we need to create user and connect them though a dynamic channel. 

**This is the use case 1:**

-  Franck has a issue with the salary calculator and ask for help
-  Our application connect Franck to support 1
-  Franck can now talk to support 1

**use case 2:**

- We had a new client (Logitech) in our system
- We had a new user Franck who works for Logitech
- We had a new user Marylin who works for Logitech
- We need a channel "Helps Logitech"
- Franck and Marylin must automatically subscribe to this channel
- Franck and Marylin  must automatically subscribe to each other

These 2 scenarios are really easy to do with data.json
Every night, our servers will generate a new data.json to import into Tinode.

It's an easy way to synchronize our server with Tinode. Just need a Rest API to import the data.json and a way to import incrementally.

Thanks

**Comment by or-else** [comment]
Let's call your business "Acme Corp".

**Use case 1**

* Is Frank an employee of Acme Corp? Meaning: he already has an LDAP record in the corporate ERP, he expect to use Tinode just like any other system at his place of work. He expects his conversation to be preserved. This is the case similar to using Slack at work.
* Frank is not an employee of Acme Corp. Frank just wants to contact Acme Support, resolve the issue and move on. He does not care that the conversation with Support is preserved.

**Use case 2**

* Neither Frank nor Marylin are employees of Acme Corp. When Acme Corp signs a contract with Logitec, Acme IT admin creates accounts for Frank and Marylin in Acme IT systems and Tinode, and creates a topic "Logitec Support Channel" in Tinode. Then Frank and Marylin must subscribe to this topic and to each other. 

Is this correct?

Use case 2:
> It's an easy way to synchronize our server with Tinode. Just need a Rest API to import the data.json and a way to import incrementally.

That does not seem to be too hard. I can help with that. Also, it would not be too hard to do the same with a plugin & a custom authenticator (authenticating users against a corporate LDAP or MSFT Directory).

**Comment by or-else** [comment]
> It's an easy way to synchronize our server with Tinode. Just need a Rest API to import the data.json and a way to import incrementally.

BTW, that will not update accounts which are currently active. If Frank is logged in, the changes won't take effect until Frank logs out and logs in again. Updating online will have to go through the gRPC API.  It's not hard. It just needs to be done. The `tn-cli` or something similar can be scripted.

**Comment by fstn** [comment]
Thank you, I replied bellow:

Let's call our application globale app "AcmeApp" and our slack like "SupportMe". Let's say that we have 2 clients Logitech and Stabilo.

> Let's call your business "Acme Corp".
> 
> **Use case 1**
> 
> * Is Frank an employee of Acme Corp? Meaning: he already has an LDAP record in the corporate ERP, he expect to use Tinode just like any other system at his place of work. He expects his conversation to be preserved. This is the case similar to using Slack at work.
> *** Frank is not an employee of Acme Corp. Frank just wants to contact Acme Support, resolve the issue and move on. He does not care that the conversation with Support is preserved.**
> 

The second one, Franck is not an employee of Acme Corp. And he does not care to preserve the conversation with Support. 

> **Use case 2**
> 
> * Neither Frank nor Marylin are employees of Acme Corp. When Acme Corp signs a contract with Logitec, Acme IT admin creates accounts for Frank and Marylin in Acme IT systems and Tinode, and creates a topic "Logitec Support Channel" in Tinode. Then Frank and Marylin must subscribe to this topic and to each other.
> 
> Is this correct?

Yes it's correct. We create contract on AcmeApp, every night we generate a data.json for SupportMe with links between clients and supports. The day after, Franck and Marylin can talk to each other, talk to the support but not to other clients like  Stabilo. That's why it's the server that subscribe the user to specific topics. (It's so easy to do with the data.json file).

> 
> Use case 2:
> 
> > It's an easy way to synchronize our server with Tinode. Just need a Rest API to import the data.json and a way to import incrementally.
> 
> That does not seem to be too hard. I can help with that. Also, it would not be too hard to do the same with a plugin & a custom authenticator (authenticating users against a corporate LDAP or MSFT Directory).

I think it's not hard to do too. But I'm not a Go developer, I'm just starting to learn it. I think it's possible to add a new endpoint and call the code used for initdb inside the endpoint...

**Comment by or-else** [comment]
**Use case 1**

Let's call Acme support agents Alice and Bob. Then the flow is the following:

* IT admin creates regular accounts for Alice and Bob, creates a designated topic "Incoming support requests", sets it's permissions to `anon: jw` (join and write).
* Frank uses `anon` authentication scheme to create an account. The `anon` scheme is created specifically for temporary users. 
* Frank subscribes write-only to the designated topic "Incoming support requests". There are two ways to do it: 
  * The client software knowns what topic to subscribe to.
  * A plugin subscribes `anon` users to the designated topic.
* Frank posts a message to the "Incoming support requests". 
* Both Alice and Bob are notified that a message is posted to "Incoming support requests". Let's assume Alice decides to respond to Frank's request. Alice posts a message to the "Incoming support requests" with a `head` field `reply: topic-name:frank's-message-seq-id` indicating to Bob that she is working on the request.
* Alice responds to Frank. There are two ways to do it:
  * Alice starts a p2p topic with Frank, like any other p2p conversation. This is very simple, but the drawback is that no one else sees what Alice write to Frank.
  * Alice starts a unique group topic where where converses with Frank. This is a touch more involved but the conversation is open to other support agents to join if needed.

**Comment by or-else** [comment]
**Use case 1**

What you need is a custom webapp for Frank. The existing webapp is too complex for Frank. The support app only needs to show a single conversation window.

**Comment by fstn** [comment]
> tn-cli

Do you have a easy example that show how to:

- Create a new user
- Subscribe the user to a specific topic 

Thanks

**Comment by or-else** [comment]
Checkout `root-user`, build the server and init-db, run init-db. Choose one of the user and make him the root user. Assuming you are running mysql and you want to make Alice the root, the command is 
```sql
UPDATE auth SET authlvl=30 WHERE uname='basic:alice'
```

Then issue the tn-cli commands:
```
$ python3 tn-cli.py 
Tinode command line client. Version 0.15/0.15.7rc4.
Logging in with cookie file
iterating
Server 'localhost:6061' 
False 
Connected to server: 
	ver: 0.15 
	build: mysql:undef 
201 created 
Authenticated as usrm0Y1GccsD_w 
200 ok  

tn-cli> acc --uname=joe --password=joe123 --cred=email:jdoe@example.com
201 created
tn-cli> .use --user=usr0EvalSo4LRA
tn-cli> sub me
```
`acc` creates a new account, `.use` sets "on behalf of" user, `sub me` subscribes "on behalf of" user `usr0EvalSo4LRA` to his 'me' topic.

**Comment by fstn** [comment]
Thanks, I finally did a small nodeJS service that import data.json using the initdb script ...

**Comment by or-else** [comment]
That's good. I still think the `tn-cli` or something like it is a better long-term solution though.

**Comment by or-else** [comment]
I believe this is either fixed or no longer relevant. Closing. Feel free to continue the conversation and I'll reopen.
