### ISSUE TITLE
gRpc query {sub topic me} does not return ```{meta}```

### ISSUE THREAD

**Issue by sad1y** [tinode/chat#159]
### Subject of the issue
Hello guys, can you explain me whats i doing wrong?
i trying to implement gRpc client for dotnet and i cant get ```{meta}``` response for ```{"sub":{"id":"xxxx","topic":"me","get":{"what":"sub desc"}}}``` request

the problem is that server does not return anything but
```{ "ctrl": { "id": "xxxx", "topic": "me", "code": 200, "text": "ok" } }```.

i expect that sever will send me ```{meta}``` data, like he do for builtin web client (webclient logs)
 ```
{"ctrl":{"id":"70033","topic":"me","params":{"acs":{"want":"JP","given":"JP","mode":"JP"}},"code":200,"text":"ok","ts":"2018-10-01T16:02:26.269Z"}}

{"meta":{"id":"70033","topic":"me","ts":"2018-10-01T16:02:26.269Z","desc":{"created":"2018-09-19T16:37:22.894Z","updated":"2018-09-19T16:37:22.894Z","defacs":{"auth":"xxx","type":"jpg"}},"private":{"comment":"some comment 123"}}}
```
 
### Is this a bug report of a feature request?
[x] Request for comments

#### Server-side
 * .NET Core SDK:
``` Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
  * version of tinode (docker ```tinode/tinode-mysql       e45b4d927f57        7 weeks ago```)
  * database backend  (mysql)
#### Client-side
```https://github.com/sad1y/Tinode.Client/tree/feature/create-topic```

### Steps to reproduce
```docker run --name mysql --network tinode-net --env MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.7```
```docker run -p 6060:18080 -p 6061:16061 -d --name tinode-srv --network tinode-net tinode/tinode-mysql:latest```

```dotnet run --project src```

### Client-side log
```
connected successfully!
ver: "0.15", build: "mysql:v0.15.5"
{ "hi": { "id": "2051948d", "userAgent": "dotnet-core-client", "ver": "0.15", "deviceId": "2051948d", "lang": "EN" } }
{ "ctrl": { "id": "2051948d", "code": 201, "text": "created", "params": { "ver": "IjAuMTUi", "build": "Im15c3FsOnYwLjE1LjUi" } } }
{ "login": { "id": "2051948e", "scheme": "basic", "secret": "YWxpY2U6YWxpY2UxMjM=" } }
{ "ctrl": { "id": "2051948e", "code": 200, "text": "ok", "params": { "user": "InVzcmI0S3FKcUhVZ1hFIg==", "authlvl": "ImF1dGgi", "token": "ImI0S3FKcUhVZ1hGbHg4UmJGQUFCQUFFQVFrTFV0bFJOUXVoUyt1cU4wbXBCNzNBdkQwMDE4ck1Fc01VQ3NxbFJmU289Ig==", "expires": "IjIwMTgtMTAtMTVUMTY6NTk6MTcuNDQ2WiI=" } } }
{ "sub": { "id": "2051948f", "topic": "me", "getQuery": { "what": "sub desc" } } }
{ "ctrl": { "id": "2051948f", "topic": "me", "code": 200, "text": "ok" } }
```

**Comment by or-else** [comment]
@BenDerPan , could you please take a look. Thanks!

**Comment by sad1y** [comment]
I failed with pushing my source, soon it will be updated, sorry for that

**Comment by sad1y** [comment]
!src update
https://github.com/sad1y/Tinode.Client/blob/feature/get-topics
thanks

**Comment by BenDerPan** [comment]
@or-else  @sad1y  Sorry for late , I am looking into it ,

**Comment by BenDerPan** [comment]
@sad1y  you can find my chatbot implement here :https://github.com/BenDerPan/chat/blob/master/chatbot/csharp/Tinode.ChatBot/ChatBot.cs

**Comment by sad1y** [comment]
thx @BenDerPan, i will check you implementation

**Comment by or-else** [comment]
It's been moved to a separate repository: https://github.com/tinode/csharpbot

**Comment by BenDerPan** [comment]
@sad1y  I checked your code, and I think your problem is that:
1. you should sub first before you get sub desc;
2. you should make a ClientGet request to get what you want ,as below:

```C#
            var message = new ClientMsg
            {
                Get = new ClientGet
                {
                    Id = GenerateMessageId(),
                    Topic = "me",
                    Query = new GetQuery
                    {
                        What = "sub desc",
                    }
                }
            };

            // {sub: {id: "70033", topic: "me", get: {what: "sub desc"}}}

            var response = await SendMessageAsync(message, message.Get.Id);
```
