### ISSUE TITLE
Group message notifications

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#161]
At the moment users get notifications for new group messages if the mentioned?

- no notifications for messages without mentioning user
- no push notification for group messages (mentioned or not)

**Comment by pwFoo** [comment]
Looks like it isn't dependent on mentioning user...
Now notifications and push notifications work fine. 

Also works fine since third user is registered. Don't know why or if it could be possible... 
So it works now for me.

**Comment by or-else** [comment]
If everything works, please close the issue.

I noticed that sometimes service worker installation gets stuck. Once it happens push no longer works.  So, check Developer Tools -> Application -> Service Workers if any service workers are in "waiting" state.

**Comment by pwFoo** [comment]
I close the issue for now. If I have problems again or information to debug I'll open it again... Thanks!
