### ISSUE TITLE
Searching users by name, tag or email address doesn't work for contacts

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#162]
With latest rc4 I can't find users by username, tags oder email address.
I don't know if it was fixed before and is new (again) in rc4. Because I haven't reset my test database before rc3 / rc4...

Add members to groups is improved and works fine with before added users (contacts).

I use the rc4 docker image / web client.

**Comment by pwFoo** [comment]
Strange...
Registered a third user and search works fine for all??

First test was with 2 users registered.

So maybe it has need some time / delay or it's dependent on registered users...?

**Comment by or-else** [comment]
Check the logs when it does not work.

**Comment by pwFoo** [comment]
I close the issue and until it happens again. Thanks!

Tinode gets better and better! Great!
