### ISSUE TITLE
Server supported by Tinode

### ISSUE THREAD

**Issue by SantoshSah** [tinode/chat#163]
### Subject of the issue
Which server Tinode is using? It is using Ejabberd like whatsapp?

### Is this a bug report of a feature request?
- [x] Question

**Comment by or-else** [comment]
This is the server. You are looking at its code here in this repo.

**Comment by or-else** [comment]
There was no followup, so I assume you are satisfied with the answer. Closing.

**Comment by SantoshSah** [comment]
Thank you for answer and sorry for my delayed response. I am satisfied with your answer. Before creating this issue, i had gone through [XMPP Server list](https://xmpp.org/about/technology-overview.html#muc) and did not find Tinode in XMPP server list. So i wanted to confirm by creating this issue. After your answer, i went through Tinode, run in my local and found that Tinode is also server like Ejabberd. :+1:
