### ISSUE TITLE
why need fcm?

### ISSUE THREAD

**Issue by rjliulei** [tinode/chat#170]
why tinode needs fcm since tinode is an IM server?

**Comment by or-else** [comment]
You still want to know that a message was sent to you while your client app was offline, like when your mobile phone was in your pocket.

**Comment by rjliulei** [comment]
you mean I can get messages when client app is exited or killed( do not run in the backgroud)?

**Comment by or-else** [comment]
Correct.

**Comment by rjliulei** [comment]
Thanks ! I can show a notification in app without fcm when app is running in the backgroud.
