### ISSUE TITLE
OTP email issue

### ISSUE THREAD

**Issue by vatsal78** [tinode/chat#173]
hi,
When i am registering the new user, the mail sending for otp gives error :- **smtp error unencrypted connection go.**
How to solve it.

**Comment by or-else** [comment]
What's your server version?

**Comment by or-else** [comment]
What's the version of your server?

**Comment by or-else** [comment]
What's your server version?

**Comment by vatsal78** [comment]
i am using  v0.15.7

**Comment by or-else** [comment]
Any update on this?

**Comment by or-else** [comment]
No update in 3 days. I assume it's either resolved or no longer relevant. Closing. Feel free to comment if something changes.
