### ISSUE TITLE
push Notifications configuration  Android / Linode.conf

### ISSUE THREAD

**Issue by VirgileDjimgou** [tinode/chat#175]
### FCM notifications configuration missing 
hello linode community ,  how to configure the notifications on server side  ?  , i have already genrate my own google service.json file on firebase , but i  don't know  exactlly where  i should  paste the  Cloud messaging api_key ....  
do you have a tutorial how to configure this with the tinode.conf?

### Is this a bug report of a feature request?
- [*] Bug report

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * linux Ubuntu 16.04
  * version of tinode server, : v0.15.8-rc1'
  * database backend : mysql 
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level ( 25 , 27).

**Comment by or-else** [comment]
1. Update 
* https://github.com/tinode/chat/blob/master/server/tinode.conf#L230
* https://github.com/tinode/chat/blob/master/server/tinode.conf#L236 or https://github.com/tinode/chat/blob/master/server/tinode.conf#L250

2. Webapp: update https://github.com/tinode/webapp/blob/master/firebase-init.js

3. Tindroid:  Follow instructions here https://developers.google.com/android/guides/google-services-plugin

**Comment by or-else** [comment]
I've updated the FAQ: https://github.com/tinode/chat/blob/devel/docs/faq.md

**Comment by or-else** [comment]
Any update on this?

**Comment by VirgileDjimgou** [comment]
Thank you so much for your quick Answer . As soon as I test it, I'll let you know  if the proposed config  ist ok in my case ...  :).

**Comment by or-else** [comment]
Any update on this? Did it work? Did it fail? 

If it's not longer relevant, please close the issue.
