### ISSUE TITLE
deactivation of Users Confirmation via Email . 

### ISSUE THREAD

**Issue by VirgileDjimgou** [tinode/chat#177]
### Subject of the issue
Hey tinode community  , i have one Question , it's could possible to  create new users on Chat Server  without  email confirmation ? , ..can we manage  that through linode.conf...i.e deactivate email confirmation in linode.conf ? , if yes why ?   (PS: i have already  implemented my own authentification logic with help of Firebase API  ... that is why i ask  that )

**Comment by or-else** [comment]
Yes. Remove this line:
https://github.com/tinode/chat/blob/master/server/tinode.conf#L156
or replace `["auth"]` with `[]`.

It might be easier to ask questions here https://groups.google.com/d/forum/tinode instead of opening issues.

**Comment by or-else** [comment]
Or remove the entire section https://github.com/tinode/chat/blob/master/server/tinode.conf#L151

**Comment by VirgileDjimgou** [comment]
Thanks man :)
