### ISSUE TITLE
gRPC connections from Objective-C seem to cause "UnMarshal" errors on the server

### ISSUE THREAD

**Issue by ozobken** [tinode/chat#178]
### Subject of the issue
I have had a good play with the cli gRPC client and am working on an IOS client for tinode.  I'm using the Objective-C gRPC/protobuf wrapper, and generating from the tinode proto

### Is this a bug report of a feature request?
- [*] Bug report

#### Server-side
- [*] Your own setup:
Tinode Server 0.15 running on CentOS - Works fine with the React-JS Web interface on 6060 and the tn-cli gRPC client on 6061
  
#### Client-side
MacOS/IOS Simulator, gRPC Obj-C 1.15.0

I'm generating a Hi and Login message using Objective-C and they appear to be be encoded ok - comparing WireShark from tn-cli and my app see reasonable messages on the network, but after sending my Hi and Login messages, I get:

Sending message <ClientHi 0x600002d38580>: {
    id: "122"
    user_agent: "MacTinodeTest/0.0.1 (Darwin/17.7.0)"
    ver: "0.15.7"
    lang: "EN"
}
Sending message <ClientLogin 0x600002824460>: {
    id: "123"
    scheme: "basic"
    secret: "a2VudGVzdDprZW50ZXN0"
}
RPC error: Error Domain=io.grpc Code=13 "{"created":"@1540878596.230028000","description":"Error received from peer","file":"/Users/ken/src/RGHack/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"grpc: failed to unmarshal the received message unexpected EOF","grpc_status":13}" UserInfo={io.grpc.HeadersKey={
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1540878596.230028000","description":"Error received from peer","file":"/Users/ken/src/RGHack/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"grpc: failed to unmarshal the received message unexpected EOF","grpc_status":13}, NSLocalizedDescription=grpc: failed to unmarshal the received message unexpected EOF}

I'm assuming these unmarshal errors are coming from the server.

Is there any way to enable additional debugging on the server to ensure it's receiving the gRPC messages ok?  All I get from the server is "2018/10/30 13:49:56 grpc exited 08PR3BPo2DU"

**Comment by or-else** [comment]
I guess the problem is with the `secret` field of the `ClientLogin` message. It should be `bytes` while you are probably send a `string`:
https://github.com/tinode/chat/blob/master/pbx/model.proto#L171

What do you see in the server logs?

The error comes from the gRPC guts. I don't see a way to instruct gRPC to produce more logging.

**Comment by ozobken** [comment]
The base64 String is just my debugging - the actual data is encoded as an NSData.  It fails even with just the Hi message, so it's not the Login message.

All the server says is "grpc exited" with a hex string following.

Hmm - it would be nice to see if the server received the API calls at all, or whether it's just failing at the gRPC level

**Comment by or-else** [comment]
Are you wrapping `ClientHi` and `ClienLogin` into a `ClientMsg`?

**Comment by ozobken** [comment]
Gah - Thankyou so much - I haven't used GRPC with a protocol of messages with "oneof" messages before and had assumed the Objective-C object model dealt with that.
