### ISSUE TITLE
Incorrect collation used in the connection to the MySQL database using the Docker setup

### ISSUE THREAD

**Issue by tiagoalves** [tinode/chat#181]
### Subject of the issue

Using the official Docker environment, when messages are retrieved from the MySQL server and pushed to the clients, emojis are represented as literal question marks.

I researched it and it's because the connection that the Go server establishes to the MySQL server is using the default collation `utf8_general_ci` (explained [here](https://github.com/go-sql-driver/mysql#unicode-support)).

However, emoji support needs characterset utf8mb4, I think.

I tried to change the MYSQL_DSN env var to include the correct collation config:

`MYSQL_DSN=root@tcp(mysql:3306)/tinode?collation=utf8mb4_unicode_ci`

However, the config file template includes a parameter already (?parseTime=true) which messes up the resulting connection string, here: https://github.com/tinode/chat/blob/master/docker/tinode/config.template#L57

Can you change the `config.template` file to not include `?parseTime=true` and we can include that in the `MYSQL_DSN` env var?

I can create a pull request with this but since this might be a backwards incompatible change, I don't know how you prefer to proceed.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform: Linux
  * version of tinode server: `0.15.9-rc1` (the official Docker image)
  * database backend: MySQL
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version: Chrome, latest
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Described above.

### Expected behaviour
Described above.

### Actual behaviour
Described above.

### Server-side log
This log shows that messages with emojis are correctly received in the Tinode server:

```
2018/11/08 18:13:30 in: '{"pub":{"id":"114008","topic":"usrzIrPzKohENs","content":"test 😄"}}' ip='172.18.0.6:52426' sid='3n9jofNfIn0' uid='aaZihoZOUnU'
```

### Client-side log
Message being sent:
```
[18:13:30:210] out: {"pub":{"id":"114008","topic":"usrzIrPzKohENs","content":"test 😄"}}
```

Message being correctly received before refresh:
```
[18:13:30:412] in: {"data":{"topic":"usrzIrPzKohENs","from":"usraaZihoZOUnU","ts":"2018-11-08T18:13:30.31Z","seq":178,"content":"test 😄"}}
```

Broken message being received after refresh:
```
[18:19:02:851] in: {"data":{"topic":"usrzIrPzKohENs","from":"usraaZihoZOUnU","ts":"2018-11-08T18:13:30.31Z","seq":178,"content":"test ?"}}
```

**Comment by or-else** [comment]
Interesting. Thanks!

There are two ways to solve it. One way to is to change the default utf8 encoding to utf8mb4. The other is to store `content` as raw bytes without parsing.

I guess I'll first switch to utf8mb4 as there is no downside to it. And the raw bytes can be considered later.

**Comment by tiagoalves** [comment]
Maybe we're saying the same thing, but note that, at least in my Docker setup, the database, tables and all text columns were already correctly using `utf8mb4`, if I remember correctly. I think the only problem was the **connection** from the Tinode server to MySQL that was using the driver's default `utf8_general_ci` collation.

**Comment by or-else** [comment]
Yes, I understood. I already changed it in devel:
https://github.com/tinode/chat/blob/devel/docker/tinode/config.template#L58

**Comment by or-else** [comment]
Release in v0.15.9-rc2 https://github.com/tinode/chat/commit/95a20a9d1f3eba8969aa9af33c8b2a903e273318
