### ISSUE TITLE
Implementing Channel feature (like Telegram)

### ISSUE THREAD

**Issue by mohgh** [tinode/chat#182]
### Subject of the issue
How difficult is to implement 'channels' like the ones we have in Telegram? I assume this is very much like groups except only the admin can post messages and all other users only have read permission. Any other user can join this group. So we just have to update the js and android sdks and implement ui. Am I correct? I appreciate your help.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Mac)
  * version of tinode server, e.g. `0.15.2-rc3`
  * rethinkdb
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [x] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

**Comment by or-else** [comment]
It's in the plans:

https://github.com/tinode/chat/blob/master/README.md#planned
> Group messaging with unlimited number (or hundreds of thousands) of members with bearer token access control.

**Comment by mohgh** [comment]
If you could point me in the right direction maybe I could help to implement it. Is this a work in progress? Are my assumptions about the way to implement this functionality correct?
I need this feature for my project so it will be very nice of you to help me figure it out.

**Comment by or-else** [comment]
I have not started working on it yet.

When a normal topic is loaded (someone attaches to a topic), the topic is loaded into memory together with all subscribers. The idea for Telegram-like channels is to keep in memory just those subscribers who are currently attached + admins + banned users. So, if a channel has 1M subscribers but only 100K are attached, keep just the 100K in memory.

**Comment by or-else** [comment]
Another consideration is the ability to serve a channel from multiple cluster hosts when running the server as a cluster. Currently one topic is attached to a single cluster node.

**Comment by pavankumar070** [comment]
Is there any updated about this feature ?

**Comment by or-else** [comment]
No work has been done on this feature.

**Comment by pavankumar070** [comment]
If possible could you please give me some directions? I'm going to hire a developer n get this work  be done

**Comment by or-else** [comment]
I described a high-level approach earlier in this conversation. The logic is to load only active users into memory for channels. If you are planning to hire someone it might be easier to just provide guidance for implementing the feature to that person directly.

**Comment by pavankumar070** [comment]
Sure, I am trying to find a good Dev. Hope I will open PR soon. Thank you

**Comment by incrypt0** [comment]
Sorry for cluttering the issue comment thread with a general question. I would like to work on this issue but can someone guide me into setting up the development environment or just point me to a resource for the same if exist. And where do all Tinode dev's hang out and chat like a discord server, slack or IRC or on Tinode itself?

**Comment by or-else** [comment]
> setting up the development environment

Other than
https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source
It's just regular go environment.

> Tinode itself?

You are welcome to join `grp0UNFkoIjPa0`

Regarding the task itself, it might be a bit too involved as a starter project. It might be a better idea to start with something simpler just to learn the code base.

**Comment by pwFoo** [comment]
I read latest beta has channel feature implemented? But what's the difference to groups?

Updated to latest beta, created a channel and added an user. Permissions and usage looks like a group chat with write permissions to both users (owner and member).

**Comment by or-else** [comment]
Yes, it is implemented. 

> But what's the difference to groups?

https://github.com/tinode/chat/blob/devel/docs/API.md#group-topics

> Permissions and usage looks like a group chat with write permissions to both users (owner and member).

The users you invite are invited as notmal subscribers. The readers must subscribe to your channel themselves. You cannot invite readers to channel and you cannot manage them individually. This is by design.

**Comment by or-else** [comment]
I've updated the FAQ with the explanation of the differences:
https://github.com/tinode/chat/blob/devel/docs/faq.md#q-what-is-the-difference-between-group-topic-and-channels

**Comment by or-else** [comment]
This is done and released.
