### ISSUE TITLE
wsarecv: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by zhonghaoling** [tinode/chat#183]
### Subject of the issue
wsarecv: An established connection was aborted by the software in your host machine.

### Is this a bug report of a feature request?
- [x] Bug report
![6600](https://user-images.githubusercontent.com/12765665/48324742-2fa58300-e66d-11e8-86b5-c7f6f4f22a68.jpg)

#### Server-side
- [x] localhost
- [x] Your own setup:
  * windows 10
  * version: 0.15.9-rc1

**Comment by or-else** [comment]
It seems like you don't have a connection to your database. The "invalid connection" means the call to database has failed because there is no connection.

**Comment by or-else** [comment]
Since websocket connections are failing too, it seems like you have a network problem. Maybe a misconfigured firewall?

**Comment by zhonghaoling** [comment]
> Since websocket connections are failing too, it seems like you have a network problem. Maybe a misconfigured firewall?



> It seems like you don't have a connection to your database. The "invalid connection" means the call to database has failed because there is no connection.

The firewall is turned off and this problem is still present, "Error:internal error(500)".So, I refresh the page, try a few more, it seems to be successful. However, this error message will still appear.

**Comment by zhonghaoling** [comment]
> Since websocket connections are failing too, it seems like you have a network problem. Maybe a misconfigured firewall?

There is no such problem under Linux system, such as CentOS 7.2

**Comment by or-else** [comment]
The problem seems to be due to network failure.

Check your Windows Defender settings. See here:
https://superuser.com/questions/1335258/windows-10-private-firewall-blocks-all-internet-traffic

**Comment by or-else** [comment]
It does not seem to be related to Tinode. It's that something is blocking network connections.

**Comment by or-else** [comment]
Have you been able to solve the problem?

**Comment by zhonghaoling** [comment]
> Have you been able to solve the problem?

Not at all. Try it according to your suggestion, the firewall is also closed, but it failed. So, I found the local environment test, windows10 system, mysql-5.7, tinode v0.15.9-rc1, and found no errors. But running on my cloud server, I got this error. This kind of mistake seems to be unreproducible

**Comment by or-else** [comment]
In your cloud setup, can you connect to the database from your compute instance? 

Like run mysql client in the same instance where you run Tinode server and try connecting to your mysql database using the same credentials as Tinode.

**Comment by or-else** [comment]
Make sure your cloud instance of mysql is configured with the same user and password which you use in tinode config.

**Comment by zhonghaoling** [comment]
> In your cloud setup, can you connect to the database from your compute instance?
> 
> Like run mysql client in the same instance where you run Tinode server and try connecting to your mysql database using the same credentials as Tinode.

Database account and password are no problem.It can be connected to the database  from my compute instance.

**Comment by or-else** [comment]
Is it possible that your mysql instance is preempted?

Given the limited information you shared, I can't really think of anything else. Sorry.

**Comment by or-else** [comment]
This is probably what's happening: https://github.com/go-sql-driver/mysql/issues/657

**Comment by zhonghaoling** [comment]
> This is probably what's happening: [go-sql-driver/mysql#657](https://github.com/go-sql-driver/mysql/issues/657)

After I modified the database configuration file, and set 'wait_timeout=30', the bug has not appeared.Thank you very much!

**Comment by or-else** [comment]
Great!
