### ISSUE TITLE
Support client-initiated ping/pong messages

### ISSUE THREAD

**Issue by tiagoalves** [tinode/chat#186]
### Subject of the issue

I'm aware that the server already supports WebSocket ping/pongs (heartbeats) where the server sends ping and the clients respond with pong.

I'm developing a mobile client (using the JS SDK with React Native) and the network connection is inherently unstable. Very often, and during long periods of time, I have no way to know that the connection to the Tinode server is down. The WebSocket's onDisconnect event only fires if theres a clean disconnect.

Can we add support for the Tinode client SDKs to be able to initiate ping/pong messages to the server so that we also know on the clients whether the connection is effectively down?

Could we also control the ping/pong frequency or enable/disable it at will? That would help to rapidly fire a ping request when the app comes to the foreground, for instance.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
> The WebSocket's onDisconnect event only fires if theres a clean disconnect.

Are you sure? onDisconnect should fire on a failed ping/pong. The ping/pong delay is ~1 min. 

> Can we add support for the Tinode client SDKs to be able to initiate ping/pong messages to the server so that we also know on the clients whether the connection is effectively down?

It's easy to modify on the server but the WebSocket implementation in browsers does not provide access to ping/pongs:
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
Unless you use a non-default implementation of WebSocket (e.g. https://www.npmjs.com/package/websocket) you won't be able to send a pong message from a React Native client.

I see the following options:
* Use long polling (wasteful, but you get a lot of control over connection).
* I can make server accept text of binary WebSocket messages with small payload to imitate pings and pongs. For instance, a message with a single byte 0 will be treated as pong, 1 as ping.

**Comment by or-else** [comment]
And btw, if you use a non-default ws library, the server won't need to be modified. It will respond to pongs normally.

**Comment by tiagoalves** [comment]
I'm referring to the client side only. I've tested it with the Android emulator and turned off my host machine's WiFi. I waited over 3 minutes without ever being notified that the Tinode connection was disconnected. This is also the experience I have with WebSockets from previous, unrelated projects.

Also, with ping/pong, I actually meant an application-level heartbeat protocol such as the client sending a text message "__ping__" and the server responding with "__pong__". This matches your second suggestion.

**Comment by or-else** [comment]
> I've tested it with the Android emulator and turned off my host machine's WiFi

Interesting. I read a bit more on WS. Apparently, it's up to the endpoint to send pings and browser clients likely just don't send them. It's the server that sends pings regularly while the client just respond to them with pongs. It explains why the client does not notice lost connection.

> This matches your second suggestion.

OK, I'll modify the server to respond to heartbeat messages the same way it responds to pongs and will add this option to the SDK.

**Comment by tiagoalves** [comment]
I see that you've implemented this feature already!

From your changes it seems that there's no way to know when a probe response was received other than subscribing to `onRawMessage` and checking if `message === '0'`, which is fine by me.

But if it makes sense to you, an explicit `onProbeResponse` or similar might make the API cleaner.

If you're wondering why I want to read the probe response, it's because I need to work with my own network timeouts.

**Comment by or-else** [comment]
I thought about it but then decided it won't be useful: if the connection is dead the send will fail.

**Comment by tiagoalves** [comment]
Makes sense.

But in this case, if the connection is dead/idle (network cable was disconnected or other non-clean disconnect), we will only be aware that the connection is actually dead whenever the WebSocket implementation triggers a send timeout error. I've just tested it with Chrome and it took over 30 seconds.

**Comment by or-else** [comment]
Let me test it.

**Comment by or-else** [comment]
Yep, I can see it. On the other hand, you can only use onNetworkProbe() to implement a timeout, i.e. send the probe then wait for onNetworkProbe for some seconds and if you don't get it, assume the connection is dead. Is that how you want do it?

**Comment by tiagoalves** [comment]
Yes, that's exactly it.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/releases/tag/v0.15.10-rc1
