### ISSUE TITLE
Is there any way to retreive the messsage 'createdat' or 'updatedat' via the gRPC API?

### ISSUE THREAD

**Issue by ozobken** [tinode/chat#187]
### Subject of the issue
I want to get the message timestamp

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
Server 0.15 on Centos with MySQL  

#### Client-side
My prototype IOS App.

I would like to be able to see the date a message was created/updated when it's sent via a "Sub" response via gRPC

**Comment by or-else** [comment]
The server is sending it in the `ts` field:
```
{"data":{"topic":"usrafcAFZG0gRk","from":"usrodX5QzfyCK4","ts":"2018-11-20T02:05:27.571Z","seq":24,"content":"vvvvvfdw"}}
```
Can you show your logs?

**Comment by or-else** [comment]
Opps. It's gRPC. It's a bug indeed.

**Comment by ozobken** [comment]
Yeah - the API has a documented 'ts' field - but it isn't exposed to the gRPC proto:

// {data} message
message ServerData {
	string topic = 1;
	// ID of the user who originated the message as {pub}, could be empty if sent by the system
	string from_user_id = 2;
	// Timestamp when the message was deleted or 0. Milliseconds since the epoch 01/01/1970
	int64 deleted_at = 3;
	int32 seq_id = 4;
	map<string, bytes> head = 5;
	bytes content = 6;
}

**Comment by or-else** [comment]
The fix will be in the next rc.

**Comment by ozobken** [comment]
Awesome - I've worked around it for now by adding an extra header with timestamp - but that's exposed another issue, but not one that bites every time - *sigh*

**Comment by or-else** [comment]
https://github.com/tinode/chat/commit/8d37418fbaef9fbfd3df48b01e84387f8723c80b

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/releases/tag/v0.15.10-rc1

**Comment by ozobken** [comment]
Looks good - thanks!
