### ISSUE TITLE
gRPC/Server Returns incorrect 'head' in a batch of messages

### ISSUE THREAD

**Issue by ozobken** [tinode/chat#188]
### Subject of the issue
When retrieving a set of messages via a {sub}, it returns the wrong 'head' for all but the first message

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
Server 0.15 on Centos with MySQL  

#### Client-side
My prototype IOS App.

I added a header for a timestamp (x-<piak>-ts), and the header wasn't correctly returned - the batch of messages all had the header from the first message even though the database has stored all the unique headers:

Sending Sub message <ClientMsg 0x600001780370>: {
    sub {
      id: "12348"
      topic: "usr_3K-sfX17UY"
      get_query {
        what: "data"
        data {
        }
      }
    }
}

Ctrl Message - <ServerCtrl 0x600000b90620>: {
    id: "12348"
    topic: "usr_3K-sfX17UY"
    code: 200
    text: "ok"
    params {
      key: "acs"
      value: "{\"want\":\"JRWPA\",\"given\":\"JRWPA\",\"mode\":\"JRWPA\"}"
    }
}

Data Message - <ServerData 0x600000e98380>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_tVxJkstDpc"
    seq_id: 1
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}
Data Message - <ServerData 0x600000e98380>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_tVxJkstDpc"
    seq_id: 2
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}
Data Message - <ServerData 0x600000e9c280>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_3K-sfX17UY"
    seq_id: 3
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}
Data Message - <ServerData 0x600000e98380>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_tVxJkstDpc"
    seq_id: 4
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}
Data Message - <ServerData 0x600000e98380>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_3K-sfX17UY"
    seq_id: 5
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}
Data Message - <ServerData 0x600000e9f780>: {
    topic: "usr_3K-sfX17UY"
    from_user_id: "usr_3K-sfX17UY"
    seq_id: 6
    head {
      key: "x-<piak>-ts"
      value: "20181120113454"
    }
    content: "redacted"
}

Ctrl Message - <ServerCtrl 0x600000b904d0>: {
    id: "12348"
    topic: "usr_3K-sfX17UY"
    code: 200
    text: "ok"
    params {
      key: "count"
      value: "6"
    }
    params {
      key: "what"
      value: "\"data\""
    }
}

**Comment by ozobken** [comment]
I did some more testing to check - and if I request the messages individually, the header is correct, it's only when it returns a batch.  Not sure if the bug is in the backend, or in the gRPC interface - the mysql adapter seems to retrieve and StructScan the rows ok, but the 'head' field is getting "cached" somewhere

**Comment by or-else** [comment]
I'm looking into it.

**Comment by or-else** [comment]
I cannot reproduce:
```
$ python3 tn-cli.py --login-basic bob:bob123
Tinode command line client. Version 1.0.0/0.15.9.
Logging in with login:password bob:bob123
Server 'localhost:6061' 
Connected to server: 
	ver: 0.15 
	build: mysql:undef 
201 created 
Authenticated as usrTVxhnBWttIw 
200 ok 
tn-cli> sub usrvfzLXF0MVqw
200 ok  
tn-cli> get --topic=usrvfzLXF0MVqw --data
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 1
content: "\"My reply is no\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 2
content: "\"Core Error - Bus Dumped\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 3
content: "\"Courage is something you can never totally own or totally lose.\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrvfzLXF0MVqw"
seq_id: 4
content: "\"Outlook good\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrvfzLXF0MVqw"
seq_id: 5
content: "\"Without a doubt\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrvfzLXF0MVqw"
seq_id: 6
content: "\"Cocaine is nature\'s way of saying you make too much money.\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 7
content: "\"ii\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 8
content: "\"66\""
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 9
head {
  key: "mime"
  value: "\"text/x-drafty\""
}
content: "{\"fmt\":[{\"len\":4,\"tp\":\"ST\"}],\"txt\":\"test\"}"
 
topic: "usrvfzLXF0MVqw"
from_user_id: "usrTVxhnBWttIw"
seq_id: 10
content: "\"aaa\""
 
200 ok 
tn-cli> 
```
Message 9 has a header, message 10 does not.

**Comment by ozobken** [comment]
I'll test from the python gPRC client on my data and see - maybe it's the Objective-C gRPC interface causing the issue

**Comment by or-else** [comment]
It's been a while. I assume it's either been resolved or no longer relevant.
