### ISSUE TITLE
Can't compile the server: unknown field 'Timestamp' in struct literal of type pbx.ServerData

### ISSUE THREAD

**Issue by tiagoalves** [tinode/chat#190]
### Subject of the issue

I'm able to compile the master branch but not most more recent commits. For instance, compiling tag `v0.15.10-rc1` gives the following error:

```
$ git checkout v0.15.10-rc1
HEAD is now at 575037f... add network probe handling
$ gox -osarch="linux/amd64" -ldflags "-s -w -X main.buildstamp=`git describe --tags`" -tags mysql -output $GOPATH/bin/tinode ./server > /dev/null

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # _/.../dev/tmp/tinode-chat/server
./pbconverter.go:34:12: unknown field 'Timestamp' in struct literal of type pbx.ServerData
./pbconverter.go:134:28: data.GetTimestamp undefined (type *pbx.ServerData has no field or method GetTimestamp)
```

If I try to compile the latest commit (`deluser` branch), I get even more errors but that is secondary to me since what I need is the network probe feature.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc): Mac
  * version of tinode server, e.g. `0.15.2-rc3`: `v0.15.10-rc1`
  * database backend: MySQL

**Comment by or-else** [comment]
run `go generate` first

**Comment by or-else** [comment]
The 0.15.10-rc1 has them defined: 
https://github.com/tinode/chat/blob/v0.15.10-rc1/pbx/model.pb.go#L2320
https://github.com/tinode/chat/blob/v0.15.10-rc1/pbx/model.pb.go#L2271

You somehow got an outdated generated file `model.pb.go`.

**Comment by tiagoalves** [comment]
You're right. I think it is picking up the Tinode code that's at `$GOPATH/src/github.com/tinode/chat/` even when I'm compiling from a local git clone. I'll have to dive into Go more seriously.

Thanks for the super fast response, as usual, and sorry for wasting your time.
