### ISSUE TITLE
Functional extension using external plugins/adapters

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#196]
### Subject of the issue
Chat service has various go lang interfaces (`auth`, `db`, `media` and so on). Is it possible to append new adapters which implement such interfaces as external plugins without requirements of creating pull-request into mainstream repository?
Use cases:
1) Ability to implement own custom chat with specific plugins (ex.: private auth service)
2) Ability to load user-created plugins from global directory in long run

### Is this a bug report of a feature request?
- [ ] Bug report
- [X] Feature request

#### Server-side
- [ ] api.tinode.co
- [X] Your own setup

**Comment by or-else** [comment]
Let's clarify. Your question is about adapters. Plugins are something else (gRPC interface for additional processing of messages, like creating chatbots or adding other automations).

Specifically the private authenticator can be done as an external service without recompiling the tinode server. Or to be precise it will be possible in a couple of days when `devel` is merged into `master` and 0.15.11 is released:
https://github.com/tinode/chat/tree/devel/server/auth/rest

DB adapter is probably impractical to implement as yet another RPC layer. If you build your own DB adapter you can contribute it back or you can keep it private. If you do the latter you will have to maintain your own fork of the server. On the other hand the fork is extremely trivial: the diff is just one line in the `import` section of the `main.go`:
```
_ "path/to/your/private/db/adapter"
```

Media adapter should be fine either as a REST or as JSON RPC or even as a plain HTTP redirect. Please show your use case and I'll make sure it's supported out of the box.

So, to your first question: yes, but with caveats.

To your second question: [dynamic loading of binaries in Go is uncommon](https://appliedgo.net/plugins/). This project follows the most common approach to adding adapters/drivers: includes them at compile time or call them as an RPC service. Also there is not that much variability in databases and file storage. Maybe 30 popular databases and 30 different variants of file storage systems.

A directory of user-created bots would be useful.

**Comment by afoninsky** [comment]
Thanks for your answer, everything is clear.
