### ISSUE TITLE
Feature Request - GRPC Service honours the TLS setting

### ISSUE THREAD

**Issue by ozobken** [tinode/chat#197]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [*] Feature request

Currently, the grpc server setup ignores the TLS settings - It would be nice if TLS is enabled, that the GRPC Server also honoured that setting and used the same certificates

**Comment by or-else** [comment]
Sure. Will add after finishing the android stuff.

**Comment by or-else** [comment]
v0.15.11 has been released. As far as I can tell everything works as expected, so I'm closing this issue. Feel free to comment if any problems with gRPC SSL remain.
