### ISSUE TITLE
Merge own settings into existing config

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#199]
### Subject of the issue
You've implemented `EXT_CONFIG` in latest dev release, and it's a good idea. It allows us to extend configuration without requirement of maintaining custom docker image.

Next step is to create logic which will merge external configuration instead of replacing it.
So we can create custom configs like this (no need to describe whole file):
```
{
 "auth_config": {
   "rest": {
    "server_url": "http://users:3000/users/tinode",
   }
 },
 "store_config": {
   "adapters": {
     "rethinkdb": {
       "addresses": "rethinkdb.default.svc.cluster.local"
     }
   }
 }
}
```

**Comment by or-else** [comment]
You are welcome to send a pull request :)

The merging of config generated in docker using ENV values and the partial config provided externally is going to be hard. Not hard to make it happen but hard to maintain and debug.

**Comment by afoninsky** [comment]
Have you thought about https://github.com/spf13/viper ?
It has envs and other stuff out of the box. Kinda:
```
func loadConfig() *viper.Viper {
	config := viper.New()
	config.AutomaticEnv()
	config.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	config.SetConfigName("tinode")

	config.AddConfigPath(".")
	if err := config.ReadInConfig(); err != nil {
		panic(fmt.Errorf("Fatal error config file: %s", err))
	}
	return config
}
```

**Comment by or-else** [comment]
No, I have not seen it before. One problem with viper that I immediately see is the lack of support for comments in JSON configs.

What is the problem that you are trying to solve?

**Comment by afoninsky** [comment]
I have no problem in general. But if I have ability to rewrite specific parts of configuration instead of cloning the whole file - it will slightly decrease complexity of deployment :)
Example: set rethinkdb host / user / password using ENV variables without touching any other configs.

**Comment by or-else** [comment]
BTW, if you just want more values to be read from the command line or the environment, please send a pull request.

**Comment by afoninsky** [comment]
> Can you describe the setup which requires this feature?

Example: I have rethinkdb with custom database and credentials, also I've implemented rest connector.
So, for now if I want to change something like this I have some options:

1) create pull-request with additional arguments or env variables
2) maintain own docker image with updated entrypoint.sh (or mount one during deployment)
3) use $EXT_CONFIG and keep _whole_ configuration file in separate directory

I'm too lazy for the first and the second options :) so I choose the third one. But in that case if something will change in the future releases - the whole configuration will be broken as I maintain fixed copy of it.

I strongly beleive that the more flexible the project the better for the community.
But again, it's OK for me and it's more about chatting. Possible way of improving if none features are left. Kinda :)

**Comment by or-else** [comment]
Well, what you are effectively saying you need an equivalent of `MYSQL_DSN` (https://github.com/tinode/chat/tree/master/docker) for `RethinkDB`. If that's the case then I can add just that.
