### ISSUE TITLE
Check that configured port is not already in use.

### ISSUE THREAD

**Issue by pkrs** [tinode/chat#2]
First time I launched the server it was configured to use :8080 port same as rethinkdb's admin interface, yet http.ListenAndServe did not produce any errors.

**Comment by or-else** [comment]
Thanks. Yes, that's the results of me moving port back and forth for Dockerfile. In the latest commit I've changed the default port to 6060

**Comment by or-else** [comment]
As for no errors, I get this:

```
...
2015/10/29 13:01:44 Server started with processes: 4
2015/10/29 13:01:44 Using config from: './config'
2015/10/29 13:01:44 Listening on [:8080]
2015/10/29 13:01:44 listen tcp :8080: bind: address already in use
Error: process exited with code 1.
```

**Comment by or-else** [comment]
Look here: https://github.com/tinode/chat/blob/master/server/config
`"listen": ":6060"` is the one

**Comment by pkrs** [comment]
Just re-tested it and issue is still there, this might be a bug of a particular go library version for mac that I have.
Anyway, not road-blocking but I'll keep the isssue open for now.

**Comment by or-else** [comment]
Yep, the config is a little outdated. I'll fix it on Monday.

**Comment by or-else** [comment]
Does not seem to be reproducible
