### ISSUE TITLE
[Question] Form example?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#201]
Forms implemented, but could you add example(s) how it works and how it could used?
Something like embedded poll (yes / no / maybe) or web service / form?

**Comment by or-else** [comment]
There are two sample forms in the demo. Is that not enough? What are you looking for specifically?

**Comment by pwFoo** [comment]
Haven't found examples? Where?

**Comment by or-else** [comment]
This is where it's defined: https://github.com/tinode/chat/blob/master/tinode-db/data.json#L319

The forms are inserted here: https://github.com/tinode/chat/blob/master/tinode-db/gendb.go#L376

Then see it live online: https://api.tinode.co/#/usrvwpax1eHfhU

**Comment by pwFoo** [comment]
Someone told me from embedded web apps in matrix chat. Just a way to add a web view (https url) at the top of a chat (room). Would be easy to add such a web app if there would be a field to add an url in chat room settings?

**Comment by or-else** [comment]
I don't understand. Please show an example.

**Comment by or-else** [comment]
It looks like this question is either resolved or no longer relevant. Closing.
