### ISSUE TITLE
[Question] {get} query

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#205]
### Subject of the issue
I want to get list of active users in the chat. Everything works fine (auth / channel creation /etc) except listing. According documentation (https://github.com/tinode/chat/blob/master/docs/API.md#get) minimum query should look like:
```
{ get: { topic: 'grpkaQoBI6_Js0', what: 'sub', id: 'nzkprp' } }
```
The answer I get:
```
{ ctrl:
   { id: 'nzkprp',
     topic: 'grpkaQoBI6_Js0',
     code: 400,
     text: 'malformed' } }
```
`2019/01/14 15:38:52 s.get: invalid Get message action`

Could you point me is it my mistype and query shouldn't look like this. Or problem is in my current grpc implementation?

Thank you.

### Your environment
- docker image tinode/tinode-rethinkdb:latest
- nodejs / https://www.npmjs.com/package/@grpc/grpc-js
- https://github.com/tinode/chat/blob/master/pbx/model.proto

**Comment by or-else** [comment]
What do you you see in the server log?

**Comment by or-else** [comment]
If I had to guess I would say `what: 'sub'` in gRPC is a enum while you are probably using a string. Here is tn-cli doing the same thing and working as expected:
```
genes-mbp:tn-cli gene$ python3 tn-cli.py --login-basic=bob:bob123 
Tinode command line client. Version 1.2.0/0.15.12rc1; gRPC/1.15.0.
Server at 'localhost:6061' 
Logging in with login:password bob:bob123
<= Connected to server: ver: 0.15; build: mysql:undef 
<= 201 created 
<= 400 malformed 
tn> login --uname=bob --password=bob123
<= Authenticated as usrDIw_BYYIWxU 
<= 200 ok 
tn> sub grpxA0k6HqvnrY
<= 200 ok (grpxA0k6HqvnrY) 
tn> get grpxA0k6HqvnrY --sub
<= meta sub grpxA0k6HqvnrY 
```

**Comment by or-else** [comment]
> If I had to guess I would say what: 'sub' in gRPC is a enum while you are probably using a string

Actually that's not correct. There is no "what" in the top-level in gRPC get:

```
message ClientGet {
	string id = 1;
	string topic = 2;
	GetQuery query = 3;
}
```

You have to assign "what" to GetQuery:
```
message GetQuery {
	string what = 1;

	// Parameters of "desc" request
	GetOpts desc = 2;
	// Parameters of "sub" request
	GetOpts sub = 3;
	// Parameters of "data" request
	GetOpts data = 4;
}
```

**Comment by afoninsky** [comment]
After researching a while I've found that valid query should look:
```
{ get: { topic: 'grpkaQoBI6_Js0', query: { what: 'sub' }, id: 'nzkprp' } }
```
Thank you 👍
