### ISSUE TITLE
How to remove a user's subscription by root user?

### ISSUE THREAD

**Issue by syklevin** [tinode/chat#207]
### Subject of the issue
I have logged as root user and try {leave} and {del} with what='sub', both return error `409 must attach first`.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * docker
  * latest 
  * mysql
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [x] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
```sh
python3 tn-cli.py --host 10.20.30.10:6061 --login-basic xena:xena123
tn-cli> .use --user usrR2NABIRxZDE
tn-cli> sub --topic new
tn-cli> leave --topic grps71MrsIwSEA --unsub
```
### Expected behaviour
return 200 ok

### Actual behaviour
return 403 permission denied (grps71MrsIwSEA) 

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
```sh
python3 tn-cli.py --host 10.20.30.10:6061 --login-basic xena:xena123
Tinode command line client. Version 1.1.2/0.15.11; gRPC/1.17.1.
Server at '10.20.30.10:6061' 
Logging in with login:password xena:xena123
Connected to server: 
	ver: 0.15 
	build: mysql:v0.15.10 
201 created 
Authenticated as usrUKCDs_aeEBw 
200 ok 

tn-cli> .use --user usrR2NABIRxZDE
Default user is 'usrR2NABIRxZDE' 

tn-cli> sub --topic new
200 ok (grps71MrsIwSEA) 

tn-cli> leave --topic grps71MrsIwSEA --unsub
403 permission denied (grps71MrsIwSEA) 

```

**Comment by or-else** [comment]
1. What software are you using to issue commands?
2. Please show complete commands you are issuing. 
3. Please show the server-side log.

In general, please use the github issue template. It greatly saves time.

**Comment by syklevin** [comment]
sorry for that; I updated the issue with template.

**Comment by or-else** [comment]
This is not a bug.  It's by design. 

Topic owner cannot unsubscribe from the topic. It says so in the server-side log. You must to pass topic ownership to another user first.

**Comment by admill1519** [comment]
I have created group and subscribe to it.

.use --user usr68q8L0YWgbE
sub --topic new

now I want to add 2 more user to this group. how to do it?

**Comment by or-else** [comment]
@admill1519 I'll add an example to https://github.com/tinode/chat/blob/devel/tn-cli/sample-script.txt

**Comment by or-else** [comment]
@admill1519 done

**Comment by admill1519** [comment]
> @admill1519 I'll add an example to https://github.com/tinode/chat/blob/devel/tn-cli/sample-script.txt

Thank you.
I went through the example file and I found it bit complicate, is there any alternate approach.

e.g. sub --$group topic --$topic name of user to subscribe to the group
unsub --$group topic --$topic name of user to subscribe to the group
 del --$group topic --hard

**Comment by or-else** [comment]
>  is there any alternate approach.

I'm not sure what you mean. This is all open source. You are welcome to simplify it as you see fit.

> I also observed that the commands used in the text file are not executable from the terminal
 
There is no distinction between executing from the file or command line. If you are having issues then it means you are doing something wrong. For example, all these commands that you provided as examples are invalid:
```
sub --$group topic --$topic name of user to subscribe to the group
unsub --$group topic --$topic name of user to subscribe to the group
del --$group topic --hard
```

**Comment by admill1519** [comment]
> > is there any alternate approach.
> 
> I'm not sure what you mean. This is all open source. You are welcome to simplify it as you see fit.
> 
> > I also observed that the commands used in the text file are not executable from the terminal
> 
> There is no distinction between executing from the file or command line. If you are having issues then it means you are doing something wrong. For example, all these commands that you provided as examples are invalid:
> 
> ```
> sub --$group topic --$topic name of user to subscribe to the group
> unsub --$group topic --$topic name of user to subscribe to the group
> del --$group topic --hard
> ```

Above commands is just example or you can say a way I want to execute my commands in command prompt.

**Comment by or-else** [comment]
The commands you provided as example are invalid commands. They don't work because they are incorrect.

**Comment by or-else** [comment]
There was no update on the issue in a while. I assume the issue is either resolved or no longer relevant. Please open a new issue  or use the [forum](https://groups.google.com/forum/#!forum/tinode) if problems persist.

**Comment by sanmiguel2019** [comment]
I have a similar problem with p2p subscriptions in GRPC.  As a root `A` user I can not unsubscribe user `B` from user `C`. It´s not supported and root user can not delete p2p subscriptions of other users?

```
2020/11/17 14:44:45 grpc in: hi:<id:"870614" user_agent:"php/grpc" ver:"1" lang:"es-ES" >  tDpLZsGHHwU
2020/11/17 14:44:45 grpc in: login:<id:"244075" scheme:"token" secret:"\211|\371\324\244K\255V\020\364\304_\036\000\001\000\001\000`\216\016nP\000_\r\252\262/\004O\030]\371u\241\226\327?\263\273A@\231^\316\346\3041\242" > auth_level:ROOT  tDpLZsGHHwU
2020/11/17 14:44:45 grpc in: del:<id:"233385" topic:"usriXz51KRLrVY" what:TOPIC user_id:"zi6rZuJ4YnE" hard:true >  tDpLZsGHHwU
2020/11/17 14:44:45 s.etn: invalid p2p self-subscription tDpLZsGHHwU

```

**Comment by or-else** [comment]
The feature works as expected:
```
$ python3 tn-cli.py --login-basic=xena:xena123
Tinode command line client. Version 1.5.2/0.16.8; gRPC/1.33.1; Python 3.7.2.
Server at 'localhost:16060' 
Logging in with login:password xena:xena123
<= Connected to server: maxTagLength: 96; maxTagCount: 16; ver: 0.16; maxMessageSize: 262144; minTagLength: 2; maxSubscriberCount: 32; build: rethinkdb:undef; maxFileUploadSize: 8388608                                     
<= 201 created 
<= Authenticated as usrSopyo8fthfg 
<= 200 ok 
tn> .use --user usrQtPwmvVssUw                                                                                                                                                                                                
<= Default user='usrQtPwmvVssUw'                                                                                                                                                                                              
tn> del --topic usrgNtTeLpyGkQ --hard topic                                                                                                                                                                                   
<= 200 ok (usrgNtTeLpyGkQ)                                                                                                                                                                                                    
tn> .exit                                                                                                                                                                                                                     
Shutting down...
```

The bug is in your code. If you believe there is a bug in Tinode, please open another issue. If you have a question write to the forum.
