### ISSUE TITLE
Support for UDP-based network transport

### ISSUE THREAD

**Issue by qwasdzxc** [tinode/chat#208]
server can works both udp and tcp protocolx like https://github.com/YuriyNasretdinov/instant-im

**Comment by or-else** [comment]
Is this a question? Or are you advertising some library for UDP communication?

**Comment by qwasdzxc** [comment]
This is feature request

**Comment by or-else** [comment]
Why is it important? Have you deployed Tinode and having issues in production?

**Comment by qwasdzxc** [comment]
This is important because sometimes packets of the messages will be lost when client have bad internet connection

**Comment by or-else** [comment]
I understand that. I'm not asking about this feature in general. I'm asking about your specific problem. Do you have a problem with Tinode connectivity in production?

**Comment by qwasdzxc** [comment]
I did not started it yet in production

**Comment by or-else** [comment]
Then this is not an immediate problem. Let's discuss it when and if it becomes one.

This is not a small feature. Google spent several years developing QUIC to solve this problem. I don't think it would be prudent to create a transport like this from scratch given that QUIC is going mainstream now.

**Comment by or-else** [comment]
No it is not. For example, do you see any encryption there?

**Comment by qwasdzxc** [comment]
I thought encryption it is already in tinode

**Comment by or-else** [comment]
Tinode uses [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security). 

All I see is a basic UDB server-side socket used for demo purposes. Maybe you can see anything more useful there, like reties and packet reordering? Frame sizing maybe? 

I would suggest to you to get some background on networking.

**Comment by qwasdzxc** [comment]
Code of QUIC transport https://chromium.googlesource.com/chromium/src/+/master/net/tools/quic/

**Comment by or-else** [comment]
Yes, I know that implementations of QUIC exist, including [one in Go](https://github.com/lucas-clemente/quic-go). Yes, I agree that something like QUIC is useful. 

My questions are about what to do and when.

Is there a real-life problem that you are trying to solve? If yes, please tell me more about your **real-life** problem. If not, then I do not see a point in spending time on this problem right now.

**Comment by qwasdzxc** [comment]
Ok
