### ISSUE TITLE
[Question or Discuss] network bandwidth costs too much at the server side

### ISSUE THREAD

**Issue by BenDerPan** [tinode/chat#209]
@or-else  Hi, I have a question about the bandwidth of tinode server, When logs in with basic user and password, all friends of the user account will receive Sub messages(update friends list, Broadcast?), including the user's basic information (nicknames, avatars, etc.), which consumes a lot of bandwidth. Especially in ChatBot (RPC), when the bandwidth is full at a certain time, it will lead to ChatBot disconnection and reconnection, which will increase the bandwidth and this will lead to more ChatBot disconnection, like an  amplified DDos. I don't know if this is a BUG or a policy mechanism for multi-terminal updates...

**Comment by or-else** [comment]
>  all friends of the user account will receive Sub messages

I'm not sure I understand what you mean. 

When a user subscribes to `me` topic all his contacts receive a presence notification `{"pres": {"what": "on", "topic": "..."}}`. That's a very small packet.

When a user requests contacts info `{"sub":{"topic":"me", "what":"sub"}}` all or partial contacts are sent. But you don't have to do it. If you don't need the contacts or topic description just don't ask for it:
`{"sub": {"topic": "me"}}` and that's it.
If you are caching contacts on the client, you can ask for just the updated contacts:
`{"sub":{"topic":"me","get":{"sub":{"ims":"2019-01-18T13:59:40.822Z"},"what":"sub"}}}. Take a look at the webapp and tindroid. They both cache data and request just the updates. 

> like an amplified DDos

Take a look at webapp and Tindroid. They both implements exponential backoff specifically to avoid DoS-ing the server.

**Comment by BenDerPan** [comment]
got it!!! you are right, when I sub "me", I use `{"sub":{"topic":"me", "what":"sub"}}`, so all the information are sent. now I just use `{"sub": {"topic": "me"}}` to avoid this. thank you. :)
