### ISSUE TITLE
SMTP error while using Email authentication 

### ISSUE THREAD

**Issue by hanqo** [tinode/chat#213]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [ ] Feature request

#### Server-side
linux 
0.15.9
rethinkdb
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * chrome

### Steps to reproduce
I setup the Email authentication by using gmail with
smtp.gmail.com and port with 587
I also tried 25 and it did not work either.

error from server log is 
SMTP error email@gmail.com dial tcp 64.233.167.108:587 connect: connection timed out

Thank you!

**Comment by or-else** [comment]
gmai.com or gmail.com?

Please show the original server-side log.

**Comment by hanqo** [comment]
sorry typo. I corrected it already. due to some restriction i cannot copy server log directly here, but this is the exact server log I got without prefix timestamp

**Comment by or-else** [comment]
`connect: connection timed out` means there is a problem with the network. Are behind a proxy or a firewall?

If you try from the same host
```
telnet 64.233.167.108:587
```
What do you see?

**Comment by hanqo** [comment]
you are right. the hosting provider I used disables SMTP by default.
Now everything works well!
Sorry for that.
