### ISSUE TITLE
create user with tags using cli

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#216]
### Subject of the issue
I am trying to create user using cli but not able to assign tags.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [x] tn-cli
  * Python version 2.7
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
acc --uname billiard --password 12341234 --fn 'nancy billiard' --tags nancy@business.com

run above command in cli

### Expected behaviour
create user and add tags to users table
### Actual behaviour
its not working giving below error
422 policy violation 
### Server-side log
2019/02/06 18:12:54 grpc in: acc:<id:"32477" user_id:"new" scheme:"basic" secret
:"billiard:12341234" tags:"nancy@business.com" desc:<default_acs:<> public:"{\"f
n\": \"nancy billiard\"}" > >  b0No47JGKRs
2019/02/06 18:12:54 s.acc: missing credentials; have: [] want: [email] b0No47JGK
Rs

### Client-side log
/usr/bin/python2.7 /home/amol/Downloads/chat-deluser/tn-cli/tn-cli1.py --login-basic=krishna:123
Tinode command line client. Version 1.1.1/0.15.11; gRPC/1.18.0.
Logging in with login:password krishna:123
Server '10.102.32.153:6061' 
Connected to server: 
	ver: 0.15 
	build: mysql:undef 
201 created 
Authenticated as usrvKZcUjSQ6MU 
200 ok 
tn-cli> acc --uname billiard --password 12341234 --fn 'nancy billiard' --tags nancy@business.com
422 policy violation

**Comment by or-else** [comment]
This is not a bug. Credentials is not the same as tags. See here:
https://github.com/tinode/chat/blob/master/tn-cli/sample-script.txt#L23

You must either provide required credentials or configure the server to not require credentials.

**Comment by admill1519** [comment]
Thanx a lot...
