### ISSUE TITLE
FCM: 403/404 error on notification sending 

### ISSUE THREAD

**Issue by maximbukanov** [tinode/chat#217]
### Subject of the issue
Firebase Cloud Messaging notifications do not work if the recipient is authorized in a web browser (most often this happens in Chromium browsers)

### Is this a bug report of a feature request?
- [x] Bug report

#### Server-side
- [x] Your own setup:
  * Ubuntu 
  * version of tinode server: `0.15`
  * mysql 5.7
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Version: `0.15.12`.
- [x] Tindroid: Android app
  * Android API level (22).
  * Emulator: AVD nexus6 api27(Android 8.1 Google APIs); hardware (the actual device): BlackView BW2000 Android 5.1 (api level 22); `minSdkVersion 21` `targetSdkVersion 27`

### Steps to reproduce
1. Set the "Service account credentials" on tinode.conf
2. Put the actual vapid key and project id from Firebase Console to frontend (FIREBASE_INIT const)
3. Set up a manifest.json with `"gcm_sender_id": "103953800507"` ([from official docs](https://firebase.google.com/docs/cloud-messaging/js/client#import_an_existing_key_pair))
4. Expand roles/permissions of the Firebase service account:
- Editor
- Firebase Admin
- Firebase Service Management Service Agent
- Firebase Admin SDK Administrator Service Agent
- Firebase Rules System
- Service Account Admin
- Service Account Token Creator
5. Allow notifications in browser and write outgoing message into the topic

### Expected behaviour
Clients should receive notifications after having resolved them in the browser and received firebase-token in localstorage

### Actual behaviour
Notifications work correctly if the client sends a message from the android to the browser (and vice versa).
But Firebase does not receive a notification, when client (ua TinodeWeb/0.15:Chrome/71.0) sending an outgoing message (but it's all right on Firefox browser). This issue is mainly seen in Chromium browsers. When 

### Server-side log
`fcm invalid token http error status: 404; reason: app instance has been unregistered; code: registration-token-not-registered; details: Requested entity was not found.`
`fcm push failed http error status: 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission`

**Comment by or-else** [comment]
What's the content of your `firebase-init.js`, specifically `messagingSenderId`?

**Comment by maksfreetimer** [comment]
Here comes my current firebase-init.js:
`const FIREBASE_INIT = {
  messagingSenderId: "850459016094",
  messagingVapidKey: "BIIQE-u3QHjxDRuc73xBF94qDFvvoJ6pU2axQa4uzrIjaLitVg_6W4D8tKplSgRB9vOIJOjc05qVYyukwtCTGWI"
};`

Do i need to set these values here?: apiKey, authDomain, databaseURL, projectId, storageBucket, messagingSenderId

**Comment by or-else** [comment]
> Do i need to set these values here?

No.

Let me think a bit.

**Comment by or-else** [comment]
Do I understand correctly that you are sending sending messages within the same browser? In other words, you have two tabs in the same instance of Chrome and you send messages from a user logged in in one tab to another user logged in in another tab?

**Comment by maksfreetimer** [comment]
No, I send messages in the following cases:
- Two browsers (Chrome and Chromium) open on the same machine
- Browsers are open on two different PCs
- Android device and one of the browser-clients

In any case, the sender and receiver are different users and they both have different `firebase-token` and `auth-token` in localStorage (and the `settings` key is: `{desktopAlerts: true
messageSoundsOff: false}`).

**Comment by or-else** [comment]
Is it possible that you have changed user in Chrome or Chromium, i.e. logged in as Alice, then logged out and logged in again as Bob?

**Comment by maksfreetimer** [comment]
Yes, it's possible: in case of testing, or if when the tokens (auth and/or firebase) lifetime comes to an end. 

All the localStorage data getting cleared after logout from Alice account, and new tokens (auth and firebase) are initializing for Bob. 

Should i unregister a service-worker manually after logout (like this?):
```
use strict;
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} });
```

**Comment by or-else** [comment]
I think what happens here is that the webapp does not send the token to the server after user A logout -- user B login. I'll change that in the next version.

The `HTTP 404` error is OK - it just means you have turned off notifications at some point. If it happens just once after change in notification settings.

The `HTTP 403` error means one of the clients is misconfigured. The firebase account in the server-side config in `tinode.conf` does not match the `messagingSenderId` and `messagingVapidKey` in the `firebase-init.js`.

**Comment by or-else** [comment]
I don't think you need to unregister the service-worker.

**Comment by maksfreetimer** [comment]
> I think what happens here is that the webapp does not send the token to the server after user A logout -- user B login. I'll change that in the next version.
> 
> The `HTTP 404` error is OK - it just means you have turned off notifications at some point. If it happens just once after change in notification settings then it's fine, not an error.
> 
> The `HTTP 403` error means one of the clients is misconfigured. The firebase account in the server-side config in `tinode.conf` does not match the `messagingSenderId` and `messagingVapidKey` in the `firebase-init.js`.

Does webapp should make anything like this after Alice logout?
```javascript
/* https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#deleteToken */
let firebaseToken = localStorage.getItem('firebase-token');
    if(firebaseToken){
        fbPush.deleteToken(firebaseToken).then((promise) => {
            // todo magic
    });
}
```
About `HTTP 403`. My server-side config completely matches `messagingSenderId` and `messagingVapidKey`, i got them from Firebase Console: `My project` -> `Settings` -> `Cloud Messaging` tab.

**Comment by or-else** [comment]
> Does webapp should make anything like this on Alice logout?

Not right now but I think it's a reasonable thing to do.

> My server-side config completely matches `messagingSenderId` and `messagingVapidKey`, i got them from Firebase Console: `My project` -> `Settings` -> `Cloud Messaging` tab.

This error is generated by Google. Google tells you that the server-side config does not match the client side config. Maybe there is a typo or an extra space somewhere in your config? Does your `tinode.conf` link to the fb config or does it embed it?

**Comment by or-else** [comment]
Another thing is to watch the service-worker.js. Sometimes it gets stuck in 'pending' state. If you have updated the config, reloading the page may not be enough to refresh the webapp. Sometimes you have to kill the old webworker.

**Comment by maksfreetimer** [comment]
> > Does webapp should make anything like this on Alice logout?
> 
> Not right now but I think it's a reasonable thing to do.
> 
> > My server-side config completely matches `messagingSenderId` and `messagingVapidKey`, i got them from Firebase Console: `My project` -> `Settings` -> `Cloud Messaging` tab.
> 
> This error is generated by Google. Google tells you that the server-side config does not match the client side config. Maybe there is a typo or an extra space somewhere in your config? Does your `tinode.conf` link to the fb config or does it embed it?

I use the `credentials_file` property of `tinode.conf` to locate the service account credentials, and there is no sign of error `missing credentials` (`push_fcm.go`). 

I also tried to paste the contents of `my-project-firebase-adminsdk-*****-**********.json` file to `credentials` property of tinode config, but it did not change the actual fcm-notifications behavior

**Comment by maksfreetimer** [comment]
> Another thing is to watch the service-worker.js. Sometimes it gets stuck in 'pending' state. If you have updated the config, reloading the page may not be enough to refresh the webapp. Sometimes you have to kill the old webworker.

My app removes the service-worker after each (manual) logout. 
It doesn't stuck in 'pending' state on the first (and subsequent) log in, but some clients recieve the service worker with `01.01.1970, 03:00:00` timestamp. Could this be a clue?

**Comment by or-else** [comment]
Take a look at this conversation: https://stackoverflow.com/questions/48712698/firebase-messaging-mismatched-credential
This is relevant if you have multiple projects in firebase.

**Comment by or-else** [comment]
This is what this 403 means: https://firebase.google.com/docs/cloud-messaging/admin/errors
> The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token. Make sure the credential and registration token both belong to the same Firebase project. See [Add Firebase to your app](https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app) for documentation on how to authenticate the Admin SDKs.

**Comment by maksfreetimer** [comment]
Hello, Gene!

I deleted unused projects and all Firebase accounts, and Firebase automatically created a new service account `firebase-adminsdk` with the role of `Editor`. Also, I generated a new Web Certificate Push Key.

In `tinode.conf`, I replaced the `credentials_file` with a new file received from the new firebase account. In the service-worker and webapp, I replaced `messagingVapidKey`.

I turned on stdout debugging on fcm
```
// Notificator which writes to STDOUT. Useful for debugging.
"name":"stdout",
"config": {
  // Disabled.
  "enabled": true
}
```

And I discovered that different timestamps are written in the logs (`2019/02/11 10:35:01` and `2019-02-11 07:35:01.958`):
```
2019/02/11 10:35:01 in: '{"pub":{"id":"118121","topic":"usrl8UuQMawiDA","noecho":true,"content":"hi, my friend!"}}' ip='178.251.143.5:56346' sid='sikxGtylnTI' uid='CDBVrgqFsz8'
&{[{CDBVrgqFsz8 0 []} {l8UuQMawiDA 0 []}] {usrl8UuQMawiDA usrCDBVrgqFsz8 2019-02-11 07:35:01.958 +0000 UTC 306  hi, my friend!}}
2019/02/11 10:35:02 fcm push failed http error status: 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission
```
Could this timestamp difference cause a 403 error?

_и если у Вас есть свободное время, могу ли я рассчитывать на Вашу помощь в Telegram в решении этой проблемы?)_

**Comment by or-else** [comment]
> Could this timestamp difference cause a 403 error?

I don't think so. The log timestamp is in your local time zone, the time in the message is in UTC.

> и если у Вас есть свободное время, могу ли я рассчитывать на Вашу помощь в Telegram в решении этой проблемы?)

Sure. https://t.me/joinchat/GcxClRHBKCVt6qiLqZx8tA

**Comment by or-else** [comment]
Or in Russian https://t.me/joinchat/GcxClQ9Qr5FsP6WzrI0xgg

**Comment by or-else** [comment]
I believe this has been resolved, right?

**Comment by dil-aajmera** [comment]
Getting below error on second login.
FirebaseError: Messaging: A problem occurred while unsubscribing the user from FCM: FirebaseError: Messaging: A problem occurred while unsubscribing the user from FCM: Requested entity was not found. (messaging/token-unsubscribe-failed). (messaging/token-unsubscribe-failed)

**Comment by or-else** [comment]
If you believe you found a bug, file a bug report.
