### ISSUE TITLE
how to read response generated by CLI

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#218]
### Subject of the issue
I want to read the response generated by cli file. In my case, I want to read response

200 ok (grp6B1ULeUpeOI) 

### Is this a bug report of a feature request?
- [ ] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [x] tn-cli
  * Python version 2.7
- [ ] Chatbot
  * Python version 2.7
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
excute below command in CLI
sub new --fn='sandra bullock' --tags=sandra --auth=JRWPA --anon=JR

### Client-side log
tn-cli> sub new --fn='sandra bullock' --tags=sandra --auth=JRWPA --anon=JR
200 ok (grp6B1ULeUpeOI) 
tn-cli>

**Comment by or-else** [comment]
Just follow the examples in https://github.com/tinode/chat/blob/master/tn-cli/sample-script.txt#L53
In your case it's something like this:
```
.must $ctrl sub new --fn='sandra bullock' --tags=sandra --auth=JRWPA --anon=JR
.log $ctrl.topic
```
