### ISSUE TITLE
[Ask About {pres} Packet Scenarios]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#22]
Hello, Gene

I have question regarding [{pres}](https://github.com/tinode/chat/blob/devel/API.md#pres) packet, I found that scenarios 3 & 7 doesn’t work. Are these features removed or maybe these are bugs?

Thanks

**Comment by or-else** [comment]
I'll check and get back to you.

**Comment by or-else** [comment]
Scenario 7 works incorrectly. {pres} is sent on the topic itself and arrives only if the user is live (attached) in the topic. 
Scenario 3 indeed does not work completely. 

I'll fix both tomorrow.

**Comment by or-else** [comment]
Fixed in devel: 
https://github.com/tinode/chat/commit/8e732ca6d2c9253cec6725a57687581a1ce7ad17
