### ISSUE TITLE
Malformed messages don't include the original request `id`

### ISSUE THREAD

**Issue by tiagoalves** [tinode/chat#220]
### Subject of the issue

Malformed messages don't include the original request's correlation `id` in the response.

For instance, if I login using the JS lib with `tinode.loginToken("abc")`, the response that the server sends is:

`{"ctrl":{"code":400,"text":"malformed","ts":"2019-02-15T11:31:23.479Z"}}`

Since the response does not include the `id`, it does not reject the promise of the original request and I never know whether the login was successful or failed.

Would it make sense to include the `id` in _all_ responses?

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc) Linux
  * version of tinode server: `0.15.10-rc1`
  * database backend
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.: React Native
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

**Comment by or-else** [comment]
If the id is not included it means the server failed to parse the message. I.e. it was unable to read the entire client message including the id so it does not have the id to report back.

**Comment by tiagoalves** [comment]
That makes sense, but I don't think that's the case here. My outgoing message is:

    [12:37:05:530] out: {"login":{"id":"105852","scheme":"token","secret":"abc"}}

The token however is clearly malformed. I think this is where the error is triggered: https://github.com/tinode/chat/blob/master/server/auth/token/auth_token.go#L107.

Still, even if the token is malformed, the message isn't and the `id` is readable and could be used in the response.

**Comment by or-else** [comment]
I agree that it should report the `id` if it's only the token being malformed. And it does report it back:
https://github.com/tinode/chat/blob/master/server/session.go#L627

What do you see in the server log?

**Comment by or-else** [comment]
OK, I see why it's failing to send back the `id`. It fails to parse the packet in this line:
https://github.com/tinode/chat/blob/master/server/session.go#L234

`login.secret` is expected to be decodable from json to Go's `[]byte`. That requires it to be a valid base64-encoded string. `"abc"` is not a valid base-64 encoded string.

**Comment by or-else** [comment]
So it's not a server bug. Your client is not compliant with the spec. If you want to send the `abc`, base64-encode it first.

**Comment by tiagoalves** [comment]
Fair enough! Thank you.
