### ISSUE TITLE
Save data from database

### ISSUE THREAD

**Issue by MyOnAsSalat** [tinode/chat#224]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [+ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * linux
  * latest
  * rethinkdb

When i am making new db container i lose all accounts and messages cuz after restart this container make new volume.
How to attach old volume or use just use host catalog to save database files?

**Comment by or-else** [comment]
The docker container does not do that unless instructed. 
Pease show the command line you use to restart the container. What is the container version?

**Comment by MyOnAsSalat** [comment]
> The docker container does not do that unless instructed.
> Pease show the command line you use to restart the container. What is the container version?

i am just removing container docker rm -f and start new using command from guidline

**Comment by or-else** [comment]
Pease show the command line you use to restart the container. What is the container version?

**Comment by MyOnAsSalat** [comment]
> Pease show the command line you use to restart the container. What is the container version?

docker run --name mysql --network tinode-net --env MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.7

**Comment by MyOnAsSalat** [comment]
docker rm -f mysql
but now i choose rethinkdb to use cuz this name required for another container.
But situation same, containers just make new volumes

**Comment by or-else** [comment]
You deleted your database by executing the command `docker rm -f mysql`. You deleted all your data. You should not delete all your data if you do not want to do so.

**Comment by MyOnAsSalat** [comment]
> You deleted your database by executing the command `docker rm -f mysql`. You deleted all your data. You should not delete all your data if you do not want to do so.

What i should do to save it and how i can copy tinode db data to another host?

**Comment by or-else** [comment]
https://stackoverflow.com/questions/28734086/how-to-move-docker-containers-between-different-hosts

**Comment by MyOnAsSalat** [comment]
Thx, btw how i should stop and start container to not lose data?

**Comment by or-else** [comment]
> Thx, btw how i should stop and start container to not lose data?

Just stop then start. You lost data because you explicitly deleted it.

**Comment by MyOnAsSalat** [comment]
> Just stop then start. You lost data because you explicitly deleted it.

Thx, resolved
