### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vibhi19** [tinode/chat#228]
I wanted to run one instance of Tinode. Can someone help me regarding the installation 

any guide or docs?

Thanks

**Comment by or-else** [comment]
https://github.com/tinode/chat/blob/master/INSTALL.md

**Comment by vibhi19** [comment]
it seems very complicated. is there any better guide or easiest way to install it

**Comment by or-else** [comment]
If you have questions, ask. Otherwise your comment is not something objective that can be addressed.

**Comment by vibhi19** [comment]
I followed docker guide and setup Tinode which can be accessed from here http://165.22.78.210:6060/
but How do i add domain rather than ip and install SSL cert

and i register two account and search user address couldnt find another test account

**Comment by or-else** [comment]
> How do i add domain rather than ip

This has nothing to do with Tinode. You have to register the domain then configure it. I use this registrar: https://www.namecheap.com/

> install SSL cert

Once you have the domain set up, configure TLS in Tinode and it will get the certificate for you.

> and i register two account and search user address couldnt find another test account

You probably search incorrectly. Show the client-side log.

**Comment by vibhi19** [comment]
I got the domain can you guide me a little regarding how to configure it.
hmm using cert bot that can be done

Show the client-side log. -  I never used docker before can you share cmd so i can share log

**Comment by or-else** [comment]
Your question is really not a bug report and not a feature request. It's a request to get support. Please consider using https://groups.google.com/forum/#!forum/tinode for support requests.

> I got the domain can you guide me a little regarding how to configure it.

Follow instructions at your chosen registrar. It usually involves setting up DNS and pointing it to your IP address.

> hmm using cert bot that can be done

Just follow installation instructions. Tinode has a built-in letsencrypt certbot.

> Show the client-side log. - I never used docker before can you share cmd so i can share log

Client-side logs are on the client side. They have nothing to do with docker. If you use the webapp, it's the contents of js console.
