### ISSUE TITLE
gRPC failed with StatusCode.UNKNOWN: Exception iterating requests!

### ISSUE THREAD

**Issue by jackchenY** [tinode/chat#229]
### Subject of the issue
gRPC failed with StatusCode.UNKNOWN: Exception iterating requests!
### Is this a bug report of a feature request?
- [ 1] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend

a) System
 cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
b) version & database

2019/04/07 20:23:49 Server v0.15:/home/xxx/tinode:v0.15.14-rc2; db: 'rethinkdb'; pid 3783; 1 process(es)

#### Client-side
- [ ] tn-cli
  * Python version

Python version
python --version
Python 3.7.3

### Steps to reproduce
a) run server
 ./tinode
b) run command Line client
python tn-cli.py --login-basic=alice:alice123
sub new

### Expected behaviour
 subscribe to topic

### Actual behaviour
throw the error StatusCode.UNKNOWN

### Server-side log
 ./tinode
2019/04/07 20:23:49 Server v0.15:/home/xxx/tinode:v0.15.14-rc2; db: 'rethinkdb'; pid 3783; 1 process(es)
2019/04/07 20:23:49 Using config from '/home/xxx/tinode.conf'
2019/04/07 20:23:49 Running as a standalone server.
2019/04/07 20:23:49 Restricted tags: ['email' 'tel']
2019/04/07 20:23:49 plugins: no active plugins found
2019/04/07 20:23:49 gRPC server is registered at [:6061]
2019/04/07 20:23:49 Serving static content from '/home/xxx/static' at '/'
2019/04/07 20:23:49 Large media handling enabled fs
2019/04/07 20:23:49 stats: variables exposed at '/debug/vars'
2019/04/07 20:23:49 Listening for client HTTP connections on [:6060]

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

run with sample-script:
python tn-cli.py --no-login < sample-script.txt
<_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>
gRPC failed with StatusCode.UNKNOWN: Exception iterating requests!

run with single command:
python tn-cli.py --login-basic=alice:alice123
Tinode command line client. Version 1.2.0/0.15.12; gRPC/1.19.0.
Server at 'localhost:6061'
Logging in with login:password alice:alice123
<= Connected to server: build: rethinkdb:v0.15.14-rc2; ver: 0.15
<= 201 created
<= Authenticated as usrZYSA9OoaWKE
<= 200 ok
tn> sub new
<_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>
gRPC failed with StatusCode.UNKNOWN: Exception iterating requests!
Shutting down...

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/chat/commit/950129e2bee86747d2e6ee55813e1629cd5362e5

If you don't want to wait for the next release just change
https://github.com/tinode/chat/blob/devel/tn-cli/tn-cli.py#L822
`if not cmd.no_yield:`
to
`if not hasattr(cmd, 'no_yield'):`

**Comment by jackchenY** [comment]
Thanks for your prompt reply, now the issue go away.

**Comment by or-else** [comment]
I believe this has been resolved and the fix released. Is there anything else that needs to be done here?

**Comment by jackchenY** [comment]
Now everything works well, just another minor issue when login by bob's token:

python  tn-cli.py --login-token=O/smgkiBjqQ8sMZcFAABAAEAEUNwg4vzhQcHVAenTbGK7Q0j85nGsyF/TbUivFph3Ow=
Tinode command line client. Version 1.2.1/0.15.14rc2; gRPC/1.19.0.
Server at 'localhost:6061'
Traceback (most recent call last):
  File "tn-cli.py", line 1021, in <module>
    secret = args.login_token.encode('acsii')
LookupError: unknown encoding: acsii


I believe it can be improved in later release, thanks!
