### ISSUE TITLE
Base64 decoding error for authenticating non-websocket HTTP request

### ISSUE THREAD

**Issue by alphaqiu** [tinode/chat#231]
### Subject of the issue
https://github.com/tinode/chat/blob/0a77e8e9b4bb40f09fba77b9f6e6bc3071db71a8/server/http.go#L316
```go
// Authenticate non-websocket HTTP request
func authHttpRequest(req *http.Request) (types.Uid, []byte, error) {
```

The secret: carol:carol123 after base64 encoded, the value is Y2Fyb2w6Y2Fyb2wxMjM=
carol:carol123 byte slice: [99 97 114 111 108 49 50 51]

Using code below, will get the byte slice [99 97 114 111 108 49 50 51 0]
```go
decodedSecret := make([]byte, base64.StdEncoding.DecodedLen(len(secret)))
if _, err := base64.StdEncoding.Decode(decodedSecret, []byte(secret)); err != nil {
	return uid, nil, types.ErrMalformed
}
```

Using code below, will get corrected byte slice [99 97 114 111 108 49 50 51]
```go
decodedSecret, err := base64.StdEncoding.DecodeString(secret)
if err != nil {
	return uid, nil, types.ErrMalformed
}
```
The difference between the method DecodeString and Decode in here:
```go
// DecodeString returns the bytes represented by the base64 string s.
func (enc *Encoding) DecodeString(s string) ([]byte, error) {
	dbuf := make([]byte, enc.DecodedLen(len(s)))
	n, err := enc.Decode(dbuf, []byte(s))
	return dbuf[:n], err
}
```
so using code in master repo can not verify non-websocket HTTP request.

### Is this a bug report of a feature request?
- [√] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [√] Your own setup:
  * platform Mac
  * version of tinode server, master or  v0.15.14-rc2
  * database backend mysql
  
### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
Fixed. 

Good catch. Thanks!
