### ISSUE TITLE
[Feature request] PostgreSQL support?

### ISSUE THREAD

**Issue by ghost** [tinode/chat#232]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

I don't like mysql because some reason, my other services are using PostgreSQL database. Could you add the PostgreSQL as database backend?
Thanks.

**Comment by or-else** [comment]
I definitely want to support PgSQL, but I don't have the cycles to do it right now. 

It's not a complicated task though. The MySQL adapter uses Go's sql interface so it should be rather easy to convert it a generic sql adapter supporting both MySQL & PgSQL. Maybe you can contribute the code?

I would imagine the steps to look like the following:

1. Make sure the connection string (DSN) works for PgSQL, not just MySQL
2. Make sure all SQL works on PgSQL. The SQL is rather generic with (hopefully) nothing being too MySQL-specific, but it has to be tested anyway.
3. Add handling for errors. Some of the errors are currently expected to be explicitly MySQL errors. This has to be converted to generic error checks.
4. Update installation instructions.

**Comment by Cyraus** [comment]
@or-else I certainly want to contribute the code, but I won't be golang at present, I suggest you use ORM to solve the above problems, because ORM encapsulates database operations, so it can also support SQLite.

**Comment by or-else** [comment]
I disagree about ORM. First, it's not needed: the https://golang.org/pkg/database/sql/ provides adequate abstraction. Second, ORM introduces on opaque layer which may or may not generate performant SQL queries. The hard part of mapping Tinode structures to SQL is  already done. There is no need  to replace it with something inferior.

**Comment by Cyraus** [comment]
@or-else If you think ORM can't solve the above problems, you can also use Golang database binding.
Ordinary users don't care about how the technical details are implemented, they only care about whether it works or not.

**Comment by or-else** [comment]
ORM may solve some problems by potentially introducing unnecessary complexity and other problems. It's just not needed. 

I understand that end-users don't care how software works. I don't see how that is relevant though.

**Comment by Cyraus** [comment]
@or-else I'll wait for your good news, although I can't help you solve these problem. and I'll migrate the database after Tinode supporting PostgreSQL.

**Comment by or-else** [comment]
No need to close this ticket. It's a reminder that the feature was requested. Thanks!

**Comment by sebastianmacias** [comment]
I’ll second PostgreSQL support too. The scope of this project is amazing and would like to use it in a project, however using PostgreSQL is a must in this particular project.

**Comment by or-else** [comment]
If anyone on your team knows Go then adding support for PgSQL would take a couple of days. It's really not that hard. I can help if you have questions. 

Otherwise wait a month or so until we are done with the iOS client.

**Comment by tapkain** [comment]
Hello, I'm also interested in Pg support. Do you guys still work on the iOS client?

**Comment by or-else** [comment]
Yes, it's still in active development: https://github.com/tinode/ios/commits/devel
Taking a bit longer than expected.

**Comment by sebastianmacias** [comment]
Thanks for the update

**Comment by A9u** [comment]
Hello, Is anybody working on this? I am willing to take this up

**Comment by or-else** [comment]
No one is working on it. You are welcome to lead it.

**Comment by or-else** [comment]
In progress: https://github.com/tinode/chat/pull/300

**Comment by or-else** [comment]
No longer in progress.

**Comment by mayank-mundhra-2012** [comment]
I also would like to see PgSQL support for the server. I second it.
Unfortunately I don't have experience in Go

**Comment by kuchaguangjie** [comment]
Any new on supporting for postgresql ?

**Comment by Ayuubgaajo** [comment]
> ### Subject of the issue
> 
> Describe your issue here.
> 
> 
> 
> ### Is this a bug report of a feature request?
> 
> - [ ] Bug report
> 
> - [x] Feature request
> 
> 
> 
> I don't like mysql because some reason, my other services are using PostgreSQL database. Could you add the PostgreSQL as database backend?
> 
> Thanks.

**Comment by or-else** [comment]
We are not going to do it any time soon. If you really care then please consider either contributing or paying.

**Comment by or-else** [comment]
Just to set clear expectations: the core team will not work on PostgresSQL adapter. It's going to happen only if someone contributes it or pays for it.

**Comment by Alexman94** [comment]
@or-else, my team needed a Postgresql adapter, so I wrote it.
The adapter uses libraries github.com/jackc/pgx/v4 and github.com/jmoiron/sqlx . If this satisfies your requirements, then I am ready to share the solution.

**Comment by or-else** [comment]
Sounds great. We already use github.com/jmoiron/sqlx and github.com/jackc/pgx/v4 looks mature and well supported. Please send a  pull request to devel. Thanks!

**Comment by or-else** [comment]
Released in 0.22.5, docker image: https://hub.docker.com/repository/docker/tinode/tinode-postgres/general
