### ISSUE TITLE
DeGoogling 

### ISSUE THREAD

**Issue by vibhi19** [tinode/chat#233]
There are few things that should be remove to protect privacy of user so removing Google from the scene 

Remove Google From Web app
Stop using Firebase for Push notification
and any other google service that might track user 

and would be awesome to know what you guys think about this

**Comment by or-else** [comment]
It's impossible to remove Google completely. FCM is the push mechanism for Android outside of China and will remain so for the foreseeable future. Google also owns Chrome. So it would make no difference to privacy to use something other than FCM on Android and Chrome.

What can be done is to use native push mechanisms for Firefox and Edge, as well as APNS on iOS. I don't see a problem with adding native push mechanisms for FF & Edge other than it taking time and adding complexity. Given that push already works as is with FCM, I don't see this feature as high priority. Besides, I personally don't have time to work on it too: I'm pretty busy with https://github.com/tinode/ios/compare/contacts

If you would like to contribute the feature you are requesting then you are welcome to send a pull request.

Thanks.

**Comment by pwFoo** [comment]
That demo code works with Chrome, Firefox and IE / Edge and isn't pinned to FCM. It uses vendor services (Chrome -> Google, IE / Edge -> Microsoft, Firefox -> Mozilla), but there isn't a ready to use library for that and I'm not a developer to do it...

https://webpushdemo.azurewebsites.net/

**Comment by or-else** [comment]
It feels like this conversation is going in circles. 

I agree that it's possible to send notifications to browsers without FCM. My question is "Why?". 

If you are willing to contribute the code you are welcome to do so.

**Comment by or-else** [comment]
This seems to be abandoned.
