### ISSUE TITLE
how to parse response from grpc?

### ISSUE THREAD

**Issue by hugowan** [tinode/chat#234]
Here is my code to get grpc response:

```
in, err := stream.Recv()
in.String()
```

Response like below:
```
ctrl:<id:"0001" topic:"fnd" code:200 text:"ok" params:<key:"acs" value:"{\"want\":\"JPS\",\"given\":\"JPS\",\"mode\":\"JPS\"}" > >
```

Any good idea to get params inside JSON data?

**Comment by or-else** [comment]
gRPC uses protocol buffers, not JSON. You don't need to parse anything, it's already been parsed. Take a look at the code starting here: https://github.com/tinode/chat/blob/master/server/hdl_grpc.go#L55
The `pbCliDeserialize` converts protobufs to go structures but you don't have to. You can use protobufs directly. In your example you received `ctrl`. Here is how you are supposed to access it: https://github.com/tinode/chat/blob/master/server/pbconverter.go#L14

**Comment by hugowan** [comment]
Perfect. Thanks for your help.
