### ISSUE TITLE
Failed to add cred in Tags via CLI

### ISSUE THREAD

**Issue by hugowan** [tinode/chat#235]
### Subject of the issue
Failed to add cred (tel, email) in Tags field and no records inserted in `credentials` table
via CLI. So I cannot use `fnd` to search user by tel / email.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request
  
#### Client-side
- [x] tn-cli
  * Python 2.7.15rc1
- Tinode command line client. Version 1.2.1/0.15.12; gRPC/1.19.0.

### Steps to reproduce
`acc --uname=hugo --password=hugo123 --tags=hugo,hugo_test,a:b --fn=Hugo --cred=email:hugo@example.com,tel:12345678`

### Server-side log
`2019/05/07 12:10:36 grpc in: acc:<id:"26655" user_id:"new" scheme:"basic" secret:"hugo:hugo123" tags:"hugo" tags:"hugo_test" tags:"a:b" desc:<default_acs:<> public:"{\"fn\": \"Hugo\"}" > cred:<method:"email" value:"hugo@example.com" > cred:<method:"tel" value:"12345678" > >  WQzARgc_L1o`

### Client-side log
`<= 201 created`

**Comment by or-else** [comment]
How do you know tags are not set? Please show the log of the `fnd` query.

Do you have credentials enabled in your config file? Please show what you have in the config file in the fields `acc_validation.email.add_to_tags` and `acc_validation.email.required`.

**Comment by hugowan** [comment]
@or-else Sorry my bad. I missing to enable `acc_validation.email.required`. Now is works. Thanks.
