### ISSUE TITLE
I can find users, but can not create new chat 

### ISSUE THREAD

**Issue by ZetaChow** [tinode/chat#236]
### I did steps :
1. download release for mysql
2. ran mysql
3. set the password and username of mysql in tinode.conf file
4. ran ` ./init-db -data=data.json`
5. ran `./tinode` 
6. visited http://localhost:6060/ 
7. created two users, and found each other with tag `basic:`

So far, everything is fine.

**BUT** when I click the username in the list , something wrong here.

the page show "Unnamed" and "no access to messages".

is there a problem with my installation? Thank u.

there are some logs below:
```shell
2019/05/14 16:12:18 Server v0.15:/Users/zeta/workspace/tinode-re/tinode:v0.15.14; db: 'mysql'; pid 96762; 4 process(es)
2019/05/14 16:12:18 Using config from '/Users/zeta/workspace/tinode-re/tinode.conf'
2019/05/14 16:12:18 Running as a standalone server.
2019/05/14 16:12:18 Restricted tags: ['email' 'tel']
2019/05/14 16:12:18 plugins: no active plugins found
2019/05/14 16:12:18 gRPC/1.20.0-dev server is registered at [:6061]
2019/05/14 16:12:18 Serving static content from '/Users/zeta/workspace/tinode-re/static' at '/'
2019/05/14 16:12:18 Large media handling enabled fs
2019/05/14 16:12:18 stats: variables exposed at '/debug/vars'
2019/05/14 16:12:18 Listening for client HTTP connections on [:6060]
2019/05/14 16:12:30 ws: session started phn9EMTMtW8 1
2019/05/14 16:12:30 in: '{"hi":{"id":"110329","ver":"0.15.14","ua":"TinodeWeb/0.15.14 (Chrome/74.0; MacIntel); tinodejs/0.15.14","lang":"zh-CN"}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid=''
2019/05/14 16:12:30 in: '{"login":{"id":"110330","scheme":"token","secret":"fft+fI4+lG+s4excFAABAAEAchKK8Qc+DxwMRQkKZQJeS1lGZXL7rvnProxPOOLCBKQ="}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid=''
2019/05/14 16:12:30 in: '{"sub":{"id":"110331","topic":"me","get":{"what":"sub desc"}}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:29 in: '{"sub":{"id":"110332","topic":"fnd","get":{"what":"sub tags"}}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:31 in: '{"set":{"id":"110333","topic":"fnd","desc":{"public":"ba se i"}}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:31 in: '{"get":{"id":"110334","topic":"fnd","what":"sub"}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:33 in: '{"set":{"id":"110335","topic":"fnd","desc":{"public":"basic"}}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:33 in: '{"get":{"id":"110336","topic":"fnd","what":"sub"}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:36 in: '{"set":{"id":"110337","topic":"fnd","desc":{"public":"basic:zeta"}}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
2019/05/14 16:15:36 in: '{"get":{"id":"110338","topic":"fnd","what":"sub"}}' ip='[::1]:59732' sid='phn9EMTMtW8' uid='fft-fI4-lG8'
```

**Comment by or-else** [comment]
> BUT when I click the username in the list , something wrong here.

In the list of contacts? What user name? 

Please show the javascript console log.

**Comment by ZetaChow** [comment]
yes , in the list of contacts
console log have a error :
```javascript
[09:47:40:162] in: {"meta":{"id":"112889","topic":"me","ts":"2019-05-14T09:47:39.868Z","desc":{"created":"2019-05-14T07:00:06.753Z","updated":"2019-05-14T07:12:15.2Z","touched":"2019-05-14T07:12:15.2Z","defacs":{"auth":"JRWPA","anon":"JRWPA"},"public":{"fn":"chowzeta"}}}}
index.prod.js:1 [09:47:40:163] in: {"ctrl":{"id":"112889","topic":"me","code":200,"text":"ok","ts":"2019-05-14T09:47:39.868Z"}}
:6060/#contacts/usr3AymCXAAX8I:1 Uncaught (in promise) DOMException
Promise.then (async)
(anonymous) @ main.js:1
n @ main.js:1
(anonymous) @ main.js:1
n @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
```

**Comment by ZetaChow** [comment]
Sorry, I didn't describe it clearly. Below is a video I recorded, which may be a clear indication of this problem.

https://github.com/DawnGrp/DawnCode/blob/master/asset/video/tinode.mov

**Comment by or-else** [comment]
I cannot reproduce. 

Can you reproduce the problem using https://api.tinode.co/ ?

What's the `Uncaught in promise: DOM exception` in your log?

**Comment by or-else** [comment]
The immediate problem is caused by the client not sending the {sub} request in response to the click. But I cannot reproduce it.

**Comment by or-else** [comment]
Also, please try running http://localhost:6060/index-dev.html
It shows references to original files as opposite to minified.

**Comment by ZetaChow** [comment]
using https://api.tinode.co/, no this problem

**Comment by or-else** [comment]
Please expand this exception. It's probably related to your problem:

<img width="672" alt="Screenshot 2019-05-14 at 19 09 15" src="https://user-images.githubusercontent.com/5938143/57713879-009fb680-767c-11e9-809e-b6034768d809.png">

**Comment by ZetaChow** [comment]
![image](https://user-images.githubusercontent.com/3068492/57714642-8553fa00-76a7-11e9-8172-75ea1d6154ba.png)

**Comment by ZetaChow** [comment]
I found this to use the test user "bob","eve" , everything is ok!
![image](https://user-images.githubusercontent.com/3068492/57714934-2e9af000-76a8-11e9-88c5-c7c55c56e342.png)

**Comment by or-else** [comment]
Regarding exception: please reproduce the problem using http://localhost:6060/index-dev.html

**Comment by or-else** [comment]
And you did not reproduce the problem. You showed an exception which happens on disconnect. It's benign and has no relation to your issue.

**Comment by ZetaChow** [comment]
I just test again.
I found, register new user, the new user can not chat to others
after old user sends message to the new user, the new user works well.

1. the new user can not chat to others 
![image](https://user-images.githubusercontent.com/3068492/57715440-59397880-76a9-11e9-813c-7e7e7aea973c.png)
2. change login with user "bob", sends message to the new user "chow"
![image](https://user-images.githubusercontent.com/3068492/57715475-71a99300-76a9-11e9-853f-96085e7eac29.png)
3. change login with "chow", received bob's message
![image](https://user-images.githubusercontent.com/3068492/57715512-85ed9000-76a9-11e9-9833-af2a5815a0f0.png)
4. works well, send the message back to bob, find other user and send message
![image](https://user-images.githubusercontent.com/3068492/57715528-8d149e00-76a9-11e9-88b0-5eb0cb930076.png)

**Comment by ZetaChow** [comment]
I  use http://localhost:6060/index-dev.htm, console log:

![image](https://user-images.githubusercontent.com/3068492/57716252-22fcf880-76ab-11e9-8d38-57d2b1c69ba3.png)

**Comment by ZetaChow** [comment]
I found that after another user enter chat dialog with the new user, the new user just works well

**Comment by or-else** [comment]
Yes, I can reproduce it now. Thanks!

**Comment by ZetaChow** [comment]
Is this bug completely fixed? if I build for source on the `devel` branch can solve the problem? 
👍

**Comment by or-else** [comment]
Just wait a few hours. I'll test and release it.

**Comment by ZetaChow** [comment]
Ok, wait for your good news.

**Comment by or-else** [comment]
Released: https://github.com/tinode/chat/releases/tag/v0.15.15-rc1

**Comment by ZetaChow** [comment]
I had tried the new version, this bug was solved 💯.
👍 👍 👍

**Comment by aristofanio** [comment]
I am with same problems but without solution.
This problem was reproduced in https://api.tinode.co/#/usr4NwFM3BNPGY.
Steps:
- create um user: [uname=mama, password=mama123, name=Mama, email=mama@email.net]
- validate with 123456
- in contactlist, find 'basic:alice'
- on contact, tap/click
- result: chat unamed

<img width="1249" alt="Screen Shot 2019-05-30 at 20 25 16" src="https://user-images.githubusercontent.com/250065/58671687-e0c5ef00-8319-11e9-852c-8133de377ab1.png">

**Comment by or-else** [comment]
Please open a new issue, fill out the form, and provide logs. Thanks.

**Comment by or-else** [comment]
And please do make sure you are running version 0.15.15-rc1 or -rc2.

**Comment by aristofanio** [comment]
> And please do make sure you are running version 0.15.15-rc1 or -rc2.

I'm going to make a new issue, but I anticipate that this version 0.15.15-rc2 has same results
