### ISSUE TITLE
Bug - DB error if two users sub to a p2p topic at the same time

### ISSUE THREAD

**Issue by ozobken** [tinode/chat#238]
### Subject of the issue
When two users create a P2P topic at the same time - which happens on my testing - new users connect and immediately open a topic to each other - there is a database write bug as both subscriptions try and create the topic, and TopicCreateP2P (calling a.topicCreate(tx, topic) ) gets an INSERT error on MySQL

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform: IOS
  * tinode server: 0.15 - ios-unread branch
  * database backend: MySQL
  
#### Client-side
My IOS App

### Steps to reproduce
Create a P2P sub from two peers

### Expected behaviour
They should both succeed

### Actual behaviour
One fails, as the database error stops the connection coming up and sends an "internal error".  If the user attempts to sub later, it succeeds.

### Server-side log
```
// iPhone Xr initial connection
2019/05/31 11:20:08 grpc in: hi:<id:"12345" user_agent:"ObjCTinode/0.4.1 (iOS/12.2.0)" ver:"0.15.10" lang:"EN" platform:"ios" >  1oIZm5G-OLU
2019/05/31 11:20:08 grpc in: acc:<id:"12346" user_id:"new" scheme:"basic" secret:"DELETED" login:true >  1oIZm5G-OLU
2019/05/31 11:20:08 Resetting user's tags [basic:fcfa91ef-3291-4]

// Ken's iPhone initial connection
2019/05/31 11:24:58 grpc in: hi:<id:"12345" user_agent:"ObjCTinode/0.4.1 (iOS/12.2.0)" ver:"0.15.10" device_id:"DELETED" lang:"EN" platform:"ios" >  8CULjFjTBCg
2019/05/31 11:24:58 grpc in: acc:<id:"12346" user_id:"new" scheme:"basic" secret:"DELETED" login:true >  8CULjFjTBCg
2019/05/31 11:24:58 Resetting user's tags [basic:866e0ec1-c703-4]

// Subs happen
2019/05/31 11:27:56 grpc in: sub:<id:"12348" topic:"usrwaeMnEWKfrg" get_query:<what:"data" data:<> > >  1oIZm5G-OLU
2019/05/31 11:27:56 grpc in: sub:<id:"12348" topic:"usrVgjEHOCaFlY" get_query:<what:"data" data:<> > >  8CULjFjTBCg

// Error - from TopicCreateP2P in tinode/chat/server/db/mysql/adapter.go
2019/05/31 11:27:56 hub: databse error in creating subscriptions 'p2pVgjEHOCaFlbBp4ycRYp-uA' (Error 1062: Duplicate entry 'p2pVgjEHOCaFlbBp4ycRYp-uA' for key 'topics_name')
```

**Comment by ozobken** [comment]
..and if I try and hack around it by making it ignore the error on INSERT, I also get:

```
2019/05/31 14:34:49 topic[p2pVgjEHOCaFla16aZXQLRG_w]: failed to save message: Error 1062: Duplicate entry 'p2pVgjEHOCaFla16aZXQLRG_w-1' for key 'messages_topic_seqid'
2019/05/31 14:34:49 topic[p2pVgjEHOCaFla16aZXQLRG_w]: failed to save message: Error 1062: Duplicate entry 'p2pVgjEHOCaFla16aZXQLRG_w-1' for key 'messages_topic_seqid'
```

So - it's not as simple as I'd hoped :)

**Comment by or-else** [comment]
Got it. I'll look into it ASAP. Thanks.

**Comment by or-else** [comment]
BTW, this is fixed. I'm not making a release because I'm busy with adding the option to change email/phone etc. If you want it sooner just build from sources.

**Comment by ozobken** [comment]
OK - I can build from source - will test

**Comment by ozobken** [comment]
Looks good - I built a devel branch server to test

**Comment by ozobken** [comment]
Hmm - I don't get the subscription create error now, I get a new one:
```
2019/06/11 14:09:30 topic[p2puslO3kOZK1F0tE1X4XttdQ]: failed to save message: Error 1062: Duplicate entry 'p2puslO3kOZK1F0tE1X4XttdQ-1' for key 'messages_topic_seqid'
```

**Comment by or-else** [comment]
Please post the server log

**Comment by ozobken** [comment]
```
New User signs up
2019/06/11 14:08:53 grpc in: hi:<id:"12345" user_agent:"PIAKTinode/0.4.2 (iOS/12.2.0)" ver:"0.15.10" lang:"EN" platform:"ios" >  df0LkL6YJ34
2019/06/11 14:08:53 grpc in: acc:<id:"12346" user_id:"new" scheme:"basic" secret:"..." login:true >  df0LkL6YJ34
2019/06/11 14:08:53 Resetting user's tags [basic:...]

Existing User Logs in and subs to some channels
2019/06/11 14:09:27 grpc in: hi:<id:"12345" user_agent:"PIAKTinode/0.4.2 (iOS/12.2.0)" ver:"0.15.10" lang:"EN" platform:"ios" >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: login:<id:"12346" scheme:"token" secret:"..." >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: sub:<id:"12348" topic:"usrwaeMnEWKfrg" get_query:<what:"data" data:<since_id:8 > > >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: sub:<id:"12348" topic:"usrVFoayyfYcWw" get_query:<what:"data" data:<since_id:16 > > >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: sub:<id:"12348" topic:"usrOX8uwAgXJ4s" get_query:<what:"data" data:<since_id:13 > > >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: sub:<id:"12348" topic:"grpoZYQlJBXRMg" get_query:<what:"data" data:<since_id:4 > > >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: get:<id:"19502" topic:"grpoZYQlJBXRMg" query:<what:"sub" > >  qjzW635qvXI
2019/06/11 14:09:27 grpc in: get:<id:"13329" topic:"grpoZYQlJBXRMg" query:<what:"desc" > >  qjzW635qvXI

They Sub to each other to open a P2P
2019/06/11 14:09:30 grpc in: sub:<id:"12348" topic:"usrdLRNV-F7bXU" get_query:<what:"data" data:<> > >  df0LkL6YJ34
2019/06/11 14:09:30 grpc in: sub:<id:"12348" topic:"usruslO3kOZK1E" get_query:<what:"data" data:<> > >  qjzW635qvXI

..and send an initial message
2019/06/11 14:09:30 grpc in: pub:<id:"17833" topic:"usrdLRNV-F7bXU" no_echo:true content:"\"D\"" >  df0LkL6YJ34
2019/06/11 14:09:30 grpc in: note:<topic:"usrdLRNV-F7bXU" seq_id:1 >  df0LkL6YJ34
2019/06/11 14:09:30 grpc in: pub:<id:"13100" topic:"usruslO3kOZK1E" no_echo:true content:"\"D\"" >  qjzW635qvXI
2019/06/11 14:09:30 grpc in: note:<topic:"usruslO3kOZK1E" seq_id:1 >  qjzW635qvXI
2019/06/11 14:09:30 topic[p2puslO3kOZK1F0tE1X4XttdQ]: failed to save message: Error 1062: Duplicate entry 'p2puslO3kOZK1F0tE1X4XttdQ-1' for key 'messages_topic_seqid'
```

**Comment by or-else** [comment]
Is there any chance that you are still running the server version pre- https://github.com/tinode/chat/commit/c8a418ba45bdc92442428c67a2172f5fb5c18d87 commit ?

**Comment by ozobken** [comment]
Just checked my source, and it has the changes in that commit - I am on the "devel" branch

**Comment by or-else** [comment]
Something is off with your build. I made a mistake - the `devel` is actually busted and does not compile due to incomplete separation of changes from `credentials` branch: `store` calls `CredGet` https://github.com/tinode/chat/blob/devel/server/store/store.go#L340 but it's missing from the adapter https://github.com/tinode/chat/blob/devel/server/db/adapter.go#L55

You should not be able to compile https://github.com/tinode/chat/commit/c8a418ba45bdc92442428c67a2172f5fb5c18d87

**Comment by or-else** [comment]
Maybe that's what you are seeing: the build failed and you are still running your patched binary.

**Comment by ozobken** [comment]
Ah - yeah - I did get some issues with the CredGet stuff - So now you've got me thinking about what I actually have - I certainly have the c8a418b commit in there, though.

Should I wait until there's a buildable devel branch?

**Comment by or-else** [comment]
It might be a good idea to wait for me to release. I'm almost done with the other issue.

The error you are getting just plain cannot happen with c8a418b: the `Duplicate entry ... for key 'messages_topic_seqid'` needs two instances of the same topic running at the same time and that's what you were likely getting when you ignored the first error `Duplicate entry ... for key 'topics_name'`. I'm pretty sure c8a418b fixed that. That's why I think something is off with your build.

**Comment by ozobken** [comment]
OK - I'll wait

**Comment by ozobken** [comment]
I just tried to build v0.16.0-rc1, but I get
```
hub.go:179:8: undefined: topicInit
```
Not sure how to fix this - sounding like a Git newbie here !

**Comment by or-else** [comment]
Sorry, that's my fault. Should work now: https://github.com/tinode/chat/commit/2baa7d7b00524d8385bf7f5a0ccfe57ce62aca6a

**Comment by ozobken** [comment]
OK - Looks good in v0.16.0-rc1 (I had a couple of auth issues with the db upgrade becuase I have no authenticators defined in my conf file, but that is probably not a huge issue)
