### ISSUE TITLE
[Feature Request] Preview uploaded image to confirm before send?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#241]
If I upload an image it is send immediately. Would be nice to see the image preview and first confirm it before really send to the chat.

**Comment by or-else** [comment]
Yes, that would be nice. Would like to contribute the code?

**Comment by pwFoo** [comment]
Sorry, I don't think I can do it myself. I hope it could be done / improved in the future by someone else.
Just tried to show what could be improved...

**Comment by or-else** [comment]
Done
