### ISSUE TITLE
Chrome for Android service worker update have delay?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#244]
Service worker doesn't update with Chrome for Android.
Maybe it works with some delay. Some time ago with another test it works after 1 day delay.

```
Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script. (messaging/failed-serviceworker-registration).
```

**Comment by or-else** [comment]
Please describe steps to reproduce.

**Comment by pwFoo** [comment]
I don't know how to delete a service-worker from my mobile.

I used tinode with older version and working push notifications. Some time later I installed a newer version and push notifications stop working. One day later it works fine again.

I think the only way to reproduce is to install a version with a different service worker. Then do a clean new installation (new db / users, latest version). Push notifications are disabled in settings, but can't be enabled. Some times I get the service worker error message above or no information. I'll test it tomorrow if it works with delay or still fails.

**Comment by or-else** [comment]
The error message you are getting means either `/service-worker.js` or `/firebase-init.js` is missing. Make sure you installed components correctly.

**Comment by pwFoo** [comment]
It works fine with desktop browser. But I have problems with Chrome for Android. So it shouldn't be setup dependent I think?

**Comment by or-else** [comment]
When it happens take a look at javascript console on your device: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by pwFoo** [comment]
First I tried it with the chrome app (added to homescreen tinode), but the select box just isn't clickable. Looks disabled. 
I reproduced it with a logout, login and try to change setting. FCM ID / Key ist set by docker ENV and works for desktop browser. 

```
[16:08:06:955] Connecting to: wss://<DOMAIN>/v0/channels?apikey=<APIKEY>
index.prod.js:1 [16:08:07:072] out: {"hi":{"id":"80884","ver":"0.15.14","ua":"TinodeWeb/0.15.14 (Chrome/74.0; Linux armv8l); tinodejs/0.15.14","lang":"de-DE"}}
index.prod.js:1 [16:08:07:091] in: {"ctrl":{"id":"80884","params":{"build":"mysql:v0.15.15-rc2","ver":"0.15"},"code":201,"text":"created","ts":"2019-06-08T16:08:07.451Z"}}
index.prod.js:1 [16:08:07:096] out: {"login":{"id":"80885","scheme":"basic","secret":"<SECRET>"}}
index.prod.js:1 [16:08:07:223] in: {"ctrl":{"id":"80885","params":{"authlvl":"auth","expires":"2019-06-22T16:08:07.573Z","token":"<TOKEN>","user":"usrxt5EkKLcmi8"},"code":200,"text":"ok","ts":"2019-06-08T16:08:07.475Z"}}
index.prod.js:1 [16:08:07:234] out: {"sub":{"id":"80886","topic":"me","get":{"what":"sub desc"}}}
index.prod.js:1 [16:08:07:257] in: {"ctrl":{"id":"80886","topic":"me","params":{"acs":{"given":41,"want":41,"mode":41}},"code":200,"text":"ok","ts":"2019-06-08T16:08:07.616Z"}}
index.prod.js:1 [16:08:07:264] in: {"meta":{"id":"80886","topic":"me","ts":"2019-06-08T16:08:07.617Z","desc":{"created":"2019-06-08T09:52:38.526Z","updated":"2019-06-08T11:04:58.676Z","touched":"2019-06-08T11:04:58.676Z","defacs":{"auth":"JRWPA","anon":"N"},"public":{"fn":"<USER2>","photo":{"data":"<9024, bytes: /9j/4AAQSkZJ...zU1NTU0Rf//Z>","type":"jpg"}}}}}
index.prod.js:1 [16:08:07:266] in: {"meta":{"id":"80886","topic":"me","ts":"2019-06-08T16:08:07.617Z","sub":[{"updated":"2019-06-08T11:06:23.939Z","acs":{"given":31,"want":31,"mode":31},"read":3,"recv":3,"public":{"fn":"<USER1>"},"topic":"usrK5qBiX3SysU","touched":"2019-06-08T11:07:03.566Z","seq":3,"seen":{"when":"2019-06-08T11:48:17Z","ua":"TinodeWeb/0.15.15-rc2 (Chrome/74.0; Win32); tinodejs/0.15.15-rc2"}}]}}
index.prod.js:1 [16:08:07:267] in: {"pres":{"topic":"me","src":"usrK5qBiX3SysU","what":"on"}}
index.prod.js:1 [16:08:12:172] out: {"sub":{"id":"80887","topic":"fnd","get":{"what":"tags"}}}
index.prod.js:1 [16:08:12:196] in: {"ctrl":{"id":"80887","topic":"fnd","params":{"acs":{"given":41,"want":41,"mode":41}},"code":200,"text":"ok","ts":"2019-06-08T16:08:12.555Z"}}
index.prod.js:1 [16:08:12:202] in: {"meta":{"id":"80887","topic":"fnd","ts":"2019-06-08T16:08:12.555Z","tags":["<USER2>","email:<EMAIL"]}}
A bad HTTP response code (404) was received when fetching the script.
index.prod.js:1 Failed to retrieve firebase token c {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…t. (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: A bad HTTP res…code (404) was received when fetching the script.", stack: "FirebaseError: Messaging: We are unable to registe….com/firebase@5.8.6/firebase-messaging.js:1:32160"}
```

**Comment by or-else** [comment]
Please confirm the files are accessible:
https://<your domain>/service-worker.js
https://<your domain>/firebase-init.js

Make sure it's httpS.

**Comment by pwFoo** [comment]
Inside of static directory of the docker container
```
bash-4.4# ls -l *.js
-rw-r--r--    1 501      dialout        168 Jun  8 10:55 firebase-init.js
-rw-r--r--    6 501      dialout       2769 May 29 16:28 service-worker.js
```

content of firebase-init.js looks good with id / key.

**Comment by or-else** [comment]
Try opening them in the same browser where you have problems.

**Comment by pwFoo** [comment]
Both files available from mobile (browser with problems) and desktop.

**Comment by or-else** [comment]
Can you show the content of Network tab from Developer Tools when it happens?

**Comment by pwFoo** [comment]
I opened the chrome app (added to homescreen tinode web client) today and without do anything notifications are enabled. I think the service worker is cached for 24h (?) and is updated after cache is old enough?
It works now so I think I can't debug it any more?

**Comment by pwFoo** [comment]
But cache would be strange, because service worker was old (weeks old I think, some releases back...) before do a fresh server install. So it should be updated, but seems not activated / loaded before it is 1 day old?

**Comment by or-else** [comment]
Static content is cached for 11 hours.

**Comment by or-else** [comment]
This has not been updated in a while. Is it still relevant?
