### ISSUE TITLE
delete user usingn cli and after that login in to cli with another user

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#246]
### Subject of the issue
In the previous CLI version, I can log in to CLI using root user credential and perform operations like create user, create group, delete user, delete group but, in new CLI version to delete a user I need to log in CLI with --no-login command and then have to execute delete user command. After executing delete command it is deleting the user but when I try to re-login with another user using the command '.must $user login username:password' it's not working.

I am sending you tn-cli.py file as cli.txt. I made some changes in it (gen_message function).
Kindly check and help me to fix this issue.
[cli.txt](https://github.com/tinode/chat/files/3305628/cli.txt)

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.14
  * database backend mysql
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version 2.7
- [ ] Chatbot
  * Python version 2.7
- Version of the client, e.g. `0.15.14`

### Steps to reproduce
Login Cli with --no-login command and login with the command '.must $user login username:password'
after that delete the user using a command '.await del user --hard'
after that again try to login with another user using a command '.must $user login another_username:password'

### Expected behaviour
Should be able to login with the new credentials.

### Actual behaviour
CLI getting disconnect.

### Server-side log
1); gRPC-python/0.15.11-1.18.0" ver:"0.15.11" lang:"EN" >  0-jZ2OPn-VA
2019/06/19 14:11:51 grpc in: login:<id:"32263" scheme:"basic" secret:"krishnayad
av:123" >  0-jZ2OPn-VA
2019/06/19 14:12:11 grpc: recv 0-jZ2OPn-VA rpc error: code = Canceled desc = con
text canceled
2019/06/19 14:12:47 grpc in: hi:<id:"41129" user_agent:"tn-cli/1.2.1 (Windows/8.
1); gRPC-python/0.15.11-1.18.0" ver:"0.15.11" lang:"EN" >  p8sg3b5wOfg
2019/06/19 14:14:28 grpc in: login:<id:"41132" scheme:"basic" secret:"test1:test
1123" >  p8sg3b5wOfg
2019/06/19 14:15:18 grpc in: del:<id:"41133" what:USER hard:true >  p8sg3b5wOfg
2019/06/19 14:15:18 replyDelUser: failed to delete auth record usreIs31q1I5zI re
st internal p8sg3b5wOfg
2019/06/19 14:15:18 notifying users of interest [{{ 0 2019-06-19 07:34:33.96 +00
00 UTC 2019-06-19 07:34:33.96 +0000 UTC <nil>} eIs31q1I5zI usreIs31q1I5zI 0 0 0
JPS JPS <nil> <nil> 0 <nil> {0 0 <nil>}   <nil>} {{ 0 2019-06-19 07:34:33.96 +00
00 UTC 2019-06-19 07:34:33.96 +0000 UTC <nil>} eIs31q1I5zI fndeIs31q1I5zI 0 0 0
JPS JPS <nil> <nil> 0 <nil> {0 0 <nil>}   <nil>} {{ 0 2019-06-19 08:24:03.69 +00
00 UTC 2019-06-19 08:24:03.69 +0000 UTC <nil>} eIs31q1I5zI p2peIs31q1I5zL8mMgO7v
wVXg 0 0 0 JWA JRWPA <nil> <nil> 0 <nil> {0 0 <nil>}   <nil>} {{ 0 2019-06-19 08
:37:01.089 +0000 UTC 2019-06-19 08:37:01.089 +0000 UTC <nil>} eIs31q1I5zI p2peIs
31q1I5zKfBQ3G-4Q3dw 0 0 0 JWA JRWPA <nil> <nil> 0 <nil> {0 0 <nil>}   <nil>}]
2019/06/19 14:15:18 deleting owned topics []
2019/06/19 14:16:03 grpc in: login:<id:"41134" scheme:"basic" secret:"amol:123"
>  p8sg3b5wOfg

### Client-side log
.must $user login test1:test1123
=> .must $user login test1:test1123
<= Authenticated as usreIs31q1I5zI 
<= 200 ok 
.await del user --hard
=> .await del user --hard
<= 200 ok 
<= 205 evicted 
.must $user login amol:123
=> .must $user login amol:123
.

**Comment by or-else** [comment]
Regarding your changes in tn-cli - please show the diff. I can't get a meaningful diff myself due to formatting of spaces.

You are deleting the current user, not another user. That's what you want, right?

What happens here is that once the user is deleted the session authenticated with the current user is terminated. You need to complete the whole sequence of commands again. It's possible to automatically reinitialize the `tn-cli` after disconnect it just does not look like a high-priority task. Maybe you can help out? It's a purely client feature.

**Comment by admill1519** [comment]
Check code inside 'while loop' of function  'gen_message' to see changes I made. And yes I want to delete another user and not just user but I want to perform all the operations by login with root/admin user (like an older version of CLI).

**Comment by or-else** [comment]
> Check code inside 'while loop' of function 'gen_message' to see changes I made

Please use command `diff one_file the_other_file` to generate the diff.

>  I want to perform all the operations by using the login of root/admin user (like an older version of CLI).

There were no changes in tn-cli between 0.15 and 0.16

When you execute this command you delete the current user:
```
.await del user --hard
```
Don't delete the current user if you don't want to.

**Comment by or-else** [comment]
There was no update of the issue for a while. Is it resolved?
