### ISSUE TITLE
Adding the function to delete / edit a message with a mini archive of this message.

### ISSUE THREAD

**Issue by VictorV96** [tinode/chat#247]
### Subject of the issue
Adding the function to delete / edit a message with a mini archive of this message.

### Is this a bug report of a feature request?
- [ ] Bug report
- [+] Feature request

#### Server-side
- [+] api.tinode.co
- [+] Your own setup:
  Linux
  Клиент: TinodeWeb/0.16.0-rc1 (tinodejs/0.16.0-rc1)
  Сервер: 0.16 rethinkdb:v0.16.0-rc1; (api.tinode.co)
  
#### Client-side
- [+] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [+] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Deleting a message

### Expected behaviour
Delete / edit the message from the sender (the message frame remains, only the text changes to "Message deleted" / "Edited message"). Deleted / edited message by the recipient "Message deleted" / "Edited message".

But in both cases it is possible to see the history of editing | delete.

### Actual behaviour
Deletion on the client side.
![maxresdefault](https://user-images.githubusercontent.com/23615212/59828215-f4caa280-9353-11e9-9fcf-dbffbc74b6c2.jpg)
![maxresdefault (1)](https://user-images.githubusercontent.com/23615212/59828248-03b15500-9354-11e9-9a85-01cbb04af3ef.jpg)
![5bd7c8f4708afe28f8](https://user-images.githubusercontent.com/23615212/59828279-14fa6180-9354-11e9-8dfd-87a30fc1613b.jpg)

**Comment by VictorV96** [comment]
Mini archive can be implemented by changing the message column from the text format in json. If a string arrives, then this is a normal message. If json arrives then this is edited or deleted message.

**Comment by or-else** [comment]
1. Deleting the message with an indicator.

The messages can be deleted already. What's missing is the indicator of the message having been deleted. Such an indicator is a purely client-side feature. The messages are numbered sequentially (the `seq` value). A gap in `seq` value means the message was deleted. Maybe you can help adding this feature for one of the clients?

2. Editing the message.

It's also a client-only feature.
See discussion here: https://groups.google.com/d/msg/tinode/XsqcEF-WqkI/1bO-LiP9AQAJ

**Comment by VictorV96** [comment]
`Смотрите обсуждение здесь: https://groups.google.com/d/msg/tinode/XsqcEF-WqkI/1bO-LiP9AQAJ`
У меня нет к нему доступа, или темы не существует.

**Comment by or-else** [comment]
I found another option which was not set to be open to everybody. Please check the link again. It should work now. I can see the group even in incognito window without any login or cookies.

**Comment by freetoken-Tg1483** [comment]
I have found that the message, delete and editing is the client responsible

**Comment by or-else** [comment]
Deleting messages is done long time ago.
Editing messages is added in 0.21.0-rc1

If something is missing, please add another feature request.
