### ISSUE TITLE
How to debug push notifications?

### ISSUE THREAD

**Issue by ahoeg** [tinode/chat#248]
Hi @or-else 
I use tinode inside of docker swarm service / container and it looks like each redeploy (update, changed labels for reverse proxy settings) push notifications stop working?

Tested with desktop chrome and chrome for android. Both haven't received closed browser notifications.

Any idea why and how to debug? Haven't found anything in tinode.log about FCM / notifications.

**Comment by pwFoo** [comment]
Because it's caused by a redeploy could it related to a server key which isn't inside of a persistent tinode docker container volume?

**Comment by pwFoo** [comment]
I have some push / fcm problems deployed as docker stack / swarm

**Comment by or-else** [comment]
Where do you keep your FCM parameters?

**Comment by ahoeg** [comment]
environment variables
- FCM_CRED_FILE (inside of a named volume)
- FCM_SENDER_ID
- FCM_VAPID_KEY

I have 4 registered users with my instance. Notifications work fine most of the time, but with one user some notifications are missing. Notifications with. I need to take a closer look how much notifications are missing. If closed browser / offline notifications are missing that's a problem because I don't see new messages until I open the web client to check it...

**Comment by or-else** [comment]
Notifications are hard to debug even locally. 

Is this an issue with the web client only? Do you see it on Android at all?

**Comment by ahoeg** [comment]
I only use the web client. Some times it seems to be fine and some times it looks like single notifications are missing. I have to test it with some more users. Could it be dependent on count of opened clients? For example with startet Chrome for Android und desktop Chrome web client I have two clients open with the same user.

**Comment by or-else** [comment]
I've observed that sometimes webworker gets stuck. 

The number of clients should not matter. If they get different FCM tokens they are treated as completely independent entities. 

What may happen is that one of the clients is online in the topic. If the client is in the topic the push notification is not sent. For example, if the user `alice` is online in the topic in Android Chrome, then desktop won't get notifications for messages in that topic.

**Comment by pwFoo** [comment]
Will an android user be online if the tab is open, but Chrome for android is in background on android device? But maybe the desktop browser with opened tab could prevent my device from get notifications.

I'll do some more tests. Thanks

**Comment by or-else** [comment]
> Will an android user be online if the tab is open, but Chrome for android is in background on android device?

I'm not 100% sure about mobile Chrome, but on desktop Chrome the user in the background tab is still online.

**Comment by pwFoo** [comment]
> I'm not 100% sure about mobile Chrome, but on desktop Chrome the user in the background tab is still online.

Yes, maybe that's what I'm missed during my tests with some notification problems in the past!
Android maybe freeze / stop it in background, but desktop will stay active!

**Comment by ahoeg** [comment]
I'm not sure if it was related to a second client with an open tab... So I'll close the issue for now.
