### ISSUE TITLE
I able to find user, but fail to create new chat

### ISSUE THREAD

**Issue by hugowan** [tinode/chat#251]
I able to find user, but fail to create new chat
My steps:
1. download Tinode by go get (mysql version)
2. edit mysql config in server/tindoe.conf & tinode-db/tinode.conf
3. go install -tags mysql github.com/tinode/chat/tinode-db and server
4. access mysql to create Tinode schema (without import data.json)
5. start Tinode server
6. access localhost:6060
7. create two user by Tinode webapp UI (user1 & user2)
8. login as user1 > Start New Chat > find > basic:user2
9. got below

![](http://hugow.xyz/tinode.png)

p.s. if step 4 import data.json, it will everything is fine

**Comment by or-else** [comment]
What's the client and server versions? Please show the server-side log.

**Comment by hugowan** [comment]
Updated to v0.15.15-rc2 and tested ok. Thanks.
