### ISSUE TITLE
[Feature Request] Loading indicator for clients with poor internet connection?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#252]
History problem ist fixed (#242 ), but (web) client need a loading indicator for bad internet connections! If the mobile is offline or use a really poor internet connection you get the login form on startup and will the the logged in client with some seconds delay. 
Or opened a chat with poor connection the history is just empty. That's ok until it's loaded  from the server, but maybe better with an indicator too?

**Comment by or-else** [comment]
I completely agree. Would you like to help?

**Comment by or-else** [comment]
Done
