### ISSUE TITLE
is any plan for "go-micro" combination support in the future?

### ISSUE THREAD

**Issue by efvhi** [tinode/chat#256]
### microservice
make tinode chat being a part of go-micro service to scale it.

**Comment by or-else** [comment]
This is the first time I hear about go-micro. What's the use case and how is it supposed to be integrated with tinode?

**Comment by efvhi** [comment]
> This is the first time I hear about go-micro. What's the use case and how is it supposed to be integrated with tinode?

make tinode being a service for chat ! but an application could not only chat,  suppose that you are developing an app like instagram, chat is just a part of it, the whole project can perform well as a part of the whole go-micro project you are building,

**Comment by or-else** [comment]
What does it exactly mean in context of Tinode? Do I have to import `go-micro`? Does it publish a separate API, kind of like gRPC? If yes, what's the minimal viable product?

**Comment by efvhi** [comment]
> What does it exactly mean in context of Tinode? Do I have to import `go-micro`? Does it publish a separate API, kind of like gRPC? If yes, what's the minimal viable product?

suppose that i could extract the login auth  into a separate part named `Auth`， and `Tinode`  for chat, and i also have a `Live` project and so on , that means "the app" actually has 3 server-backend service("process") running to work together . `go-micro` supports gRPC,  maybe i have misunderstanding about this topic.

**Comment by or-else** [comment]
I still don't understand the use case. Maybe you can write up a specific proposal?

**Comment by efvhi** [comment]
> I still don't understand the use case. Maybe you can write up a specific proposal?

okay, let me do more research and think it again first.

**Comment by or-else** [comment]
It looks like this request is no longer relevant. Closing.
