### ISSUE TITLE
Maximum number of contacts?

### ISSUE THREAD

**Issue by SantoshSah** [tinode/chat#257]
### Subject of the issue
What can be maximum number of contacts/friends?

### Is this a bug report of a feature request?
- [X] Question

#### Server-side
- [ ] api.tinode.co
- [X] Your own setup:
  * platform : Mac/Linux
  * version of tinode server: latest
  * database backend: Default

**Comment by or-else** [comment]
It's configurable. The default value is 1024:
https://github.com/tinode/chat/blob/master/server/tinode.conf#L147
