### ISSUE TITLE
 Database `tinode` does not exist

### ISSUE THREAD

**Issue by beanhacker** [tinode/chat#258]
\test\frontend\tinode\server\tinode-rethinkdb>tinode.exe
19/08/13 14:33:24 Server v0.16:C:\test\frontend\tinode\server\tinode-rethinkdb\tinode.exe:v0.16.0-rc5; db: 'rethinkdb'; pid 3880; 4 process(es)
19/08/13 14:33:24 Using config from 'C:\test\frontend\tinode\server\tinode-rethinkdb\tinode.conf'
19/08/13 14:33:24 Running as a standalone server.
19/08/13 14:33:24 Failed to connect to DB: rethinkdb: Database `tinode` does not exist. in:
DB("tinode").Table("kvmeta").Get("version").Field("value")

**Comment by or-else** [comment]
Have you run `init-db` first?

**Comment by beanhacker** [comment]
it's just the same, as error show below:
C:\test\frontend\tinode\server\tinode-rethinkdb>init-db.exe
2019/08/13 20:47:50 Failed to init DB adapter:rethinkdb: Database `tinode` does not exist. in:
r.DB("tinode").Table("kvmeta").Get("version").Field("value")

C:\test\frontend\tinode\server\tinode-rethinkdb>

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/8585077103eea6a9b2e1b7c91006804b82592551

**Comment by or-else** [comment]
Fix released in https://github.com/tinode/chat/releases/tag/v0.16.0
