### ISSUE TITLE
Push Notification Solution

### ISSUE THREAD

**Issue by pulsegame** [tinode/chat#262]
We have implemented our app base on tinode.
We have learned our server can call third-party notification server to send a push notification request, such as, 
`Send a POST request to https://exp.host/--/api/v2/push/send with the following HTTP headers:`
But we have a question about how to push chat type messages. As we known, we will not call https://exp.host/--/api/v2/push/ when chat messages come every time, and we should only call expo push api when the client device offline.

For example, there are two kinds of chat message we need handle,
a. The message will be handled by Tinode chat server in websocket if the client device is connecting Tinode socket server.
b. The message should be handled by notification model if the client device doesn't connect to Tinode socket server (device offline status).

So do you have any idea or solution know how to know the connections' status of devices (connected or offline)? 

Thank you so much.

**Comment by pulsegame** [comment]
We can let the third-party push service process if we can know the connection's status of devices, such as, the client device is connected with Tinode server in websocket or the device is offline.

**Comment by or-else** [comment]
> As we known, we will not call https://exp.host/--/api/v2/push/ when chat messages come every time, and we should only call expo push api when the client device offline.

It has already been done for you. All you need to do is implement this interface:
https://github.com/tinode/chat/blob/master/server/push/push.go
then add it to your config file in the `push` section:
https://github.com/tinode/chat/blob/master/server/tinode.conf#L253

See very basic example here:
https://github.com/tinode/chat/blob/master/server/push/stdout/push_stdout.go

And this is a production handler which uses Google FCM as a backend:
https://github.com/tinode/chat/blob/master/server/push/fcm/push_fcm.go

**Comment by alexinla** [comment]
@or-else 
under: https://github.com/tinode/ios. "Push" is under "Does not work yet". Does that mean we can't implement push on ios platform? 

### **Does not work yet**
Edit chat parameters.
Delivery and received/read indicators for messages (little check marks in messages).
Muting/un-muting conversations and other permission management.
Invite contacts to the app by SMS or email.
**Push notifications.**
Attachments and inline images cannot be created yet.

**Comment by pulsegame** [comment]
> > As we known, we will not call https://exp.host/--/api/v2/push/ when chat messages come every time, and we should only call expo push api when the client device offline.
> 
> It has already been done for you. All you need to do is implement this interface:
> https://github.com/tinode/chat/blob/master/server/push/push.go
> then add it to your config file in the `push` section:
> https://github.com/tinode/chat/blob/master/server/tinode.conf#L253
> 
> See very basic example here:
> https://github.com/tinode/chat/blob/master/server/push/stdout/push_stdout.go
> 
> And this is a production handler which uses Google FCM as a backend:
> https://github.com/tinode/chat/blob/master/server/push/fcm/push_fcm.go

@or-else Thanks for your answer!
But I still have a question:
Is is possible to know the connections' status of devices (connected or offline)? 
We can do many things if we can know the devices' connection status.

**Comment by or-else** [comment]
@alexinla They are actually implemented, just not tested. I'll update the doc. Thanks for reminding.

**Comment by or-else** [comment]
> Is is possible to know the connections' status of devices (connected or offline)?

No, this status is not exported from the server. What are the use cases that you require this status for?

**Comment by alexinla** [comment]
@or-else We are building a group chat style app that integrates crypto wallets and has democratic governance. 

When you mentioned above that "push for ios has been implemented but not tested", did you mean APNs (Apple Push Network Service) has been implemented? Under push/ I could not find APNs (only three folders:  /fcm, /stdout, /push.go). Or is there another method to achieve push for messages on ios? 

Please advise, thanks!

**Comment by or-else** [comment]
@alexinla We've decided not to use APNS directly. We are using a universal push backend based on Google's FCM https://firebase.google.com/docs/cloud-messaging/. FCM supports APNS pushes as well as Android and web browser pushes, all in one API.

  - `/fcm` is the main plugin which implements the actual push mechanism for all platforms. It uses the above-mentioned FCM.
  - `/stdout` is an example to use if you want to implement your own push plugin, like @pulsegame who started this conversation.
  - `/push.go` is the interface that the push plugin must implement.

Just follow instructions here:
https://github.com/tinode/chat/blob/master/docs/faq.md#q-how-to-setup-fcm-push-notifications

**Comment by pulsegame** [comment]
> > Is is possible to know the connections' status of devices (connected or offline)?
> 
> No, this status is not exported from the server. What are the use cases that you require this status for?

hi  @or-else ,
Our use cases it that we need push chat messages if user don't open app.
The reason we want to know the connection status of devices is that we need know which devices is offline/disconnected, then we can push chat messages which been sent to him to avoid them miss messages when the app is not opened.

Br,

**Comment by or-else** [comment]
> Our use cases it that we need push chat messages if user don't open app.

That's what the existing FCM push plugin does already. It sends the pushes to users who are not subscribed to topic including those who don't have the app running.

**Comment by pulsegame** [comment]
> > Our use cases it that we need push chat messages if user don't open app.
> 
> That's what the existing FCM push plugin does already. It sends the pushes to users who are not subscribed to topic including those who don't have the app running.

Thank you @or-else ,
Understood, another question is that how FCM push plugin handle the rest users who is running app? Let those chat messages send via Tinode websocket or still sent them via push notification, which will be huge amount.
Does that mean FCM push plugin can distinguishes this two status user (running app, not running app)? and parts of messages will be sent via push service if the app is not running, parts of messages will be sent via Tinode websocket if the app is running.

**Comment by or-else** [comment]
Here is what the server does when a message is sent to a topic:

1. Create a list of all user IDs subscribed to the topic.
2. Try to send a message to every user in list (1) through a websocket. 
2.1 If it was successful in sending the message, record the ID of the device the message was sent to.
3. Pass the message, user ID list (1) and successfully delivered device ID list (2.1) to push plugin.
4. Push plugin loads IDs of all devices which are registered to users in list (1).
5. Push plugin removes devices (2.1) from (4) then sends pushes to what's left.

For example, if you have two phones A and B, and only phone A is subscribed to the topic, the server will send the message to phone A through a websocket, and will send a push notification to phone B.

The push plugin does not distinguish `running the app` vs `not running the app`. It distinguishes `the app is attached to topic` or `the app is not attached to topic`.

**Comment by pulsegame** [comment]
@or-else  Thanks for your explanations, very helpful!
Our app(ios/android) is based on React Native and Tinode js. So does that mean we have to integrate Firebase iOS SDK into client side code (need migrate Firebase sdk to React Native)?

**Comment by or-else** [comment]
I've no idea how to hook up fcm to a react-native iOS app. But a quick Google search for [fcm react native iOS] returned a bunch of results. The top one look credible: https://medium.com/@paul.allies/react-native-firebase-cloud-messaging-ios-97b59e5f28ec

**Comment by pulsegame** [comment]
@or-else 
Thank you so much, will try it out.
