### ISSUE TITLE
chat input box seems sluggish when opening and closing. See video. 

### ISSUE THREAD

**Issue by alexinla** [tinode/chat#264]
iOS app. it can be downloaded here: https://testflight.apple.com/join/mC64ktbV

For the sluggish issue, Please refer to this video: https://youtu.be/hlNoyKgJC_Y

Do you experience similar thing with any demos in the past?

**Comment by or-else** [comment]
First, it seems like you are running a modified app. Second, I don't see this behavior here.

**Comment by alexinla** [comment]
Okay, so it seems its not related to Tinode. We will look at our codes again. Thanks!
