### ISSUE TITLE
Tinode login issue

### ISSUE THREAD

**Issue by alexinla** [tinode/chat#265]
occasionally, i would get 503 web socket is not connected error while my internet is fine. Our server is in tokyo and Im in California. 
Video: https://youtu.be/ydy4GB3pIlo
App: https://testflight.apple.com/join/mC64ktbV

**Comment by or-else** [comment]
Your report is not informative. 
There is no such alert in the stock Tinode app. 
At least show client- and server-side logs.

**Comment by alexinla** [comment]
We have this issue for a while. No error is found from server side logs. Would it be possible for you to take a look at our code directly? I can email you the credentials if you leave me your email. Thanks!

**Comment by or-else** [comment]
If there are no errors in the server log then the error comes from here:
https://github.com/tinode/ios/blob/master/TinodeSDK/Tinode.swift#L815

That means the connection with the server is lost for whatever reason. It's not unusual for an app to lose connection. You should not show an alert when the app loses connection. The app will automatically restore it in a second or two.

**Comment by alexinla** [comment]
we sorted it out. thanks!
