### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#276]
Seems like RethinkDB project is abandoned (or not?). 
Any plans on supporting MongoDB? Is anyone working on MongoDB adapter now? If so, I can help with development.

**Comment by or-else** [comment]
> Seems like RethinkDB project is abandoned (or not?).

Not yet, there is a community effort to keep it going:
https://github.com/rethinkdb/rethinkdb/commits/v2.4.x

> Any plans on supporting MongoDB? Is anyone working on MongoDB adapter now? If so, I can help with development.

There is a lot of interest in supporting more DB backends, like Postgres and Mongo. It's clearly something that people would want. Unfortunately we really don't have the time to work on it right now. Maybe you can start working on it and we will help you?

**Comment by Googlom** [comment]
> There is a lot of interest in supporting more DB backends, like Postgres and Mongo. It's clearly something that people would want. Unfortunately we really don't have the time to work on it right now. Maybe you can start working on it and we will help you?
Yeah, I am thinking about it because I really need Mongo in my production. But I'm new to Go, so I'll try my best :D

**Comment by or-else** [comment]
I would suggest to use RethinkDB adapter as a starting point. The main complexity is in rewriting rdb queries into equivalent Mongo queries.

**Comment by Googlom** [comment]
One question about field names inside DB:
Should field names be CamelCase inside MongoDB? or it doesn't matter?
I'm asking because mongo driver creates field names in lowercase by default if struct tags not specified. And that means that filters in query operations must look like {"fieldname": "value"}, not {"FieldName": "value"} in code.

**Comment by or-else** [comment]
It does not matter. 

The reason for names to be camel case in rethinkdb adapter is due to an old issue specific to rethinkdb. Rethink's Go driver originally required custom tag names in structures to marshal json: it ignored `json:"fieldname"` tags, wanted `gorethink:"fieldname"` tags or some such. It was easier to keep the names in camel case instead of polluting codebase with db-specific tags. They eventually fixed this problem but I just kept the code as is. 

You can use whatever names are more convenient/common for Mongo.

**Comment by Googlom** [comment]
Do find queries have to return **nil** in **error** when no result found?
Mongo driver don't have method such `cursor.IsNil()` in Rethinkdb driver: https://github.com/tinode/chat/blob/0428153dfd84323308a3de1552d922b0d6f14557/server/db/rethinkdb/adapter.go#L511-L522
Instead cursor in mongo driver returns error with string **"no documents in result"**. Should I return this error or nil as value?

**Comment by Googlom** [comment]
In some places `t.ErrNotFound` returned:
https://github.com/tinode/chat/blob/fbb7deca57bfe3bea40050ed5a62024042121852/server/db/rethinkdb/adapter.go#L1966-L1968

**Comment by or-else** [comment]
> Do find queries have to return nil in error when no result found?

Yes, this is correct. Sometimes it's OK to have no results and then the code returns `nil` error, sometimes it's an error when nothing is found and the code returns `t.ErrNotFound`.

> Instead cursor in mongo driver returns error with string "no documents in result". Should I return this error or nil as value?

You should return either an `t.ErrNotFound` or `nil` dependent on context. 
Mongo seems to be a lot like mysql in this respect. Take a look at how no results in `AuthGetUniqueRecord` is handled there:
https://github.com/tinode/chat/blob/master/server/db/mysql/adapter.go#L632

> In some places t.ErrNotFound returned:

In those places you should also return `t.ErrNotFound` when no results are found.

**Comment by or-else** [comment]
Completed: https://github.com/tinode/chat/pull/306
