### ISSUE TITLE
Cluster mode: remote sessions for ME topic aren't correctly migrated

### ISSUE THREAD

**Issue by aforge** [tinode/chat#278]
When a node hosting ME topic for a remote session goes down, the topic gets migrated via rehashing while the remote session doesn't.
This causes issues with message routing.

**Comment by aforge** [comment]
The problems appears to have another flavor:
{sub ME} calls fail after the hosting node goes on holiday fail until rehashing happens: the client receives {ctrl 502 "cluster unreachable"}.
We should perhaps modify the clients to periodically attempt to subscribe to ME in case the initial {sub ME} fails.

**Comment by or-else** [comment]
> {sub ME} calls fail after the hosting node goes on holiday fail until rehashing happens: the client receives {ctrl 502 "cluster unreachable"}

That's by design. The master node for 'me' is unknown until rehashing is complete.

> We should perhaps modify the clients to periodically attempt to subscribe to ME

Or maybe just drop the connection and reconnect.

**Comment by aforge** [comment]
This is due to topic state in the failing node's hub not being migrated to the new hosts.
We should notify the sessions subscribed to these topics and prompt the clients to resubscribe.

**Comment by or-else** [comment]
Right. 

The commits listed above are still valid though. The cluster responds with 502 to all requests while it rehashes. The clients should be able to handle those responses too.

**Comment by or-else** [comment]
I've added topic evictions handling to tinodios: https://github.com/tinode/ios/commit/0ef6f167dfff3695df20eb99d1978b4ecca95e60

**Comment by aforge** [comment]
Btw, I understand the clients currently don't handle {pres term}, do they?
https://github.com/tinode/chat/blob/master/server/topic.go#L617

**Comment by or-else** [comment]
They don't. I'll add that too.

**Comment by or-else** [comment]
added handling of `{pres what="term"}`

**Comment by or-else** [comment]
Actually scratch that. It's not all.

**Comment by aforge** [comment]
I see these changes only leave the topic. Should we also attempt to resubscribe?

**Comment by or-else** [comment]
I don't think it should resubscribe automatically. It's just not worth it because it's a rare event. The person can just leave and re-join the topic.

Maybe 'me' in case of 'me' I can force a reconnect. Anyway, it should not stop us from launching.

**Comment by aforge** [comment]
Sounds good. Let's push forward!

**Comment by aforge** [comment]
Merged https://github.com/tinode/chat/pull/282 into devel.

**Comment by or-else** [comment]
I suppose this can be closed.
