### ISSUE TITLE
Cluster mode: sys topic not migrated on failover

### ISSUE THREAD

**Issue by aforge** [tinode/chat#280]
When the node hosting "sys" topic goes down, the topic won't be re-created in the hub on its new host.

How to reproduce:
- Bring up a basic 3-node cluster.
- Take down the node hosting "sys".
- Check the other two nodes - none of these nodes' hubs contains topic "sys".

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/chat/commit/a426e956804f8fa04e1209fcdf6f2884bbc7c2c3

**Comment by aforge** [comment]
Thanks! Added a minor comment.
