### ISSUE TITLE
Cluster mode: orphaned remote sessions upon originating node failure

### ISSUE THREAD

**Issue by aforge** [tinode/chat#281]
When the node where the session originated fails, its remote sessions on other nodes stay active.

How to reproduce:
- Bring up a basic 3-node cluster.
- Connect several clients so at least one of them subscribes to ME on a remote node
- For such a session, let's denote the original node A and the node hosting its ME topic B.
- Take down A
- Check that the remote session on node B is still present.

This behavior is not critical since it doesn't break any invariants but ideally such orphaned sessions should go away.

**Comment by or-else** [comment]
It may not be sufficient to clear orphaned sessions on cluster rehash. The node may restart too quickly for rehash to happen. I suppose we need another entity, something like `node session id` which is incremented every time the node is restarted.

**Comment by or-else** [comment]
I think https://github.com/tinode/chat/commit/363876b394398c30886009500cdb863ed7b82959 fixes it. Please take a look.

**Comment by aforge** [comment]
Giving it a glance, it should work. But for some reason it isn't (I've run a quick test).
In fact, I was thinking about something much simpler: once ClusterNode.failCount (https://github.com/tinode/chat/blob/master/server/cluster.go#L55-L56; https://github.com/tinode/chat/blob/master/server/session.go#L58) goes above a certain threshold, evict the session.

**Comment by or-else** [comment]
> about something much simpler: once ClusterNode.failCount ... goes above a certain threshold, evict the session.

Only leader node keeps the fail count. All other nodes don't count it.

**Comment by aforge** [comment]
Yes, you are right. Just saw this in my live testing setup.

**Comment by or-else** [comment]
The cleanup is delayed until the first message where the cleaning node is the master.

**Comment by aforge** [comment]
Yes, just verified it. It's working. Closing the bug.
