### ISSUE TITLE
Create user validation fails with 500 error

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#286]
Server gives 500 error when registering new account (error log below). Debugging says error is coming from here: https://github.com/tinode/chat/blob/0428153dfd84323308a3de1552d922b0d6f14557/server/db/rethinkdb/adapter.go#L1863-L1870
Registration works fine in server version `0.15.15-rc2`

#### Server-side
  * Windows 10
  * version of tinode server: `0.16.0`
  * rethinkdb backend (RethinkDB server v2.3.6)
  
#### Client-side
  * Client: TinodeWeb/0.16.1 (tinodejs/0.16.1)

### Server-side log
`2019/10/14 16:49:44 create user: failed to save or validate credential Cannot perform without on a non-object non-sequence `null`. ETcRKGgoYlE`

**Comment by Googlom** [comment]
error persists in `v0.16.2-rc2`

**Comment by or-else** [comment]
I'm looking into it now.

**Comment by or-else** [comment]
Thank you. Fixed.
