### ISSUE TITLE
adapter CredIsConfirmed() method

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#288]
adapter.CredIsConfirmed() method is unused. 
Is it for "future" or just forgot to remove?
https://github.com/tinode/chat/blob/0428153dfd84323308a3de1552d922b0d6f14557/server/db/adapter.go#L67-L68

**Comment by or-else** [comment]
Done

**Comment by or-else** [comment]
https://github.com/tinode/chat/commit/fbb7deca57bfe3bea40050ed5a62024042121852
