### ISSUE TITLE
init-db Table 'tinode.kvmeta' doesn't exist

### ISSUE THREAD

**Issue by vapao** [tinode/chat#293]
### Subject of the issue
init-data -data ./data.json
```shell
Initializing mysql 108
Failed to init DB adapter:Error 1146: Table 'tinode.kvmeta' doesn't exist
```

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Mac
  * `0.16.1`
  * mysql 5.7

**Comment by or-else** [comment]
Thanks
