### ISSUE TITLE
CredConfirm method

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#295]
I'm a little confused about this lines in `CredConfirm` method:
https://github.com/tinode/chat/blob/0428153dfd84323308a3de1552d922b0d6f14557/server/db/rethinkdb/adapter.go#L1973-L1977
Both soft and hard deletion done inside `CredUpsert` method. So why those lines for?

**Comment by or-else** [comment]
`Durability: "soft"` just means "issue command to DB and don't wait for result". There is no need to wait for result because even if it fails we can't do anything about it. 

RethinkDB does not support transactions that's why something like this is used.
