### ISSUE TITLE
[Question] adapter.SubsDelForUser hard deletion

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#303]
There is no query to hard delete subscriptions. Is that how it should be or a missing query?
https://github.com/tinode/chat/blob/84d9a499cd54e8e2170421b6984a76e776eeabcc/server/db/rethinkdb/adapter.go#L1351-L1364

**Comment by or-else** [comment]
It's a bug. I'll fix it. Thanks!

**Comment by or-else** [comment]
Done
