### ISSUE TITLE
[Feature Request] Add one key to modify the permissions of all group members, such as group estoppel

### ISSUE THREAD

**Issue by KyoShio** [tinode/chat#304]
### Subject of the issue
Add one key to modify the permissions of all group members, such as group members estoppel

### Is this a bug report of a feature request?
- [x] Feature request

**Comment by KyoShio** [comment]
thanks!

**Comment by or-else** [comment]
I'm not sure how you want this to work. Do you want to make a change of permissions for all users including yourself? Or for all other users, yourself excluded? 

What is the use case you are trying to address?

**Comment by KyoShio** [comment]
group's owner can make a change of permissions  for all other group members, group's owner excluded.

**Comment by KyoShio** [comment]
For example, the group's owner  can disable all users from speaking.

**Comment by or-else** [comment]
You are probably using the chat for something that we have not thought about. For example, we expect the chat to be used like group chats in WhatsApp, Telegram, or FB Messenger. It would be highly unusual to silence all members of such group chat. What is your use case? Why do you need to silence all members at once?

**Comment by KyoShio** [comment]
Just batch modify group member permissions, not just silence all members

**Comment by or-else** [comment]
I understand what you want to do technically. I do not understand your product use case. Could you please describe your *product* case?

**Comment by KyoShio** [comment]
In China, Wechat and QQ has these functions. For example, the group's owner wants to inform all members of something and does not want the message to be replaced by others' message.so as to ensure that everyone can see the notification message at the first time.

**Comment by or-else** [comment]
Would you please attach a couple of screenshots?

**Comment by KyoShio** [comment]
Just batch modify group member permissions

**Comment by or-else** [comment]
OK, if I understand correctly, you want to be able to to send a notification to all group members and to be sure that all have seen it, right? The permissions is just a way to achieve it?

**Comment by KyoShio** [comment]
Yes, so it will be a very convenient function if the group's owner can modify the group member permissions in batch

**Comment by or-else** [comment]
OK, if the goal is to have a way for group owners or admins to make announcements then I think it's a good feature. I'm supportive.
