### ISSUE TITLE
add fullName and Msg content in me topic's pres

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/chat#307]
Assume I am in the contact list view, at the same time another one send a message to me，I get the json like this:
{"topic":"me","src":"grph81dvFpmAiw","what":"msg","seq":27}}
It is diffcult to get the fullName and msg content without modify the chat server. So I think in server, we can change the pres as below:
{"topic":"me","src":"grph81dvFpmAiw","what":"msg","seq":27,"fn":"Bob Smith","ct":"hello"}}
so if we can modify in topic.go and pres.go?
the result like below:
![1573033886(1)](https://user-images.githubusercontent.com/5022843/68287737-2b644800-00be-11ea-95ec-c62674972699.png)
//if the pic below can't show,see below:
[http://140.143.143.225/res/prev.png](url)

**Comment by or-else** [comment]
The suggestion to add some form of sender ID to the notification is quite good. I would add ID in the form 
```
{"topic":"me","src":"grph81dvFpmAiw","act":"usrRkDVe0PYDOo","what":"msg","seq":27}}
```
where `"act":"usrRkDVe0PYDOo"` in your example would be Bob's ID. The server is not aware of contents of `public`, i.e. it does not know anything about `fn` and I don't want to introduce this change because it would be excessive. Once you get `"act":"usrRkDVe0PYDOo"` you can use it to find user in the cache or you can get it from server in a separate `{get}` call.

As for message content in `{pres}` I'm not convinced it's a good idea. It would completely change the way server operates. Besides, you can always fetch the message content after receiving the notification.

**Comment by pcgpcgpcg** [comment]
search at client side is diffcult, because if someone who is not your friend(not subscibe) at a group send a message, I can't get the fn from cache.

**Comment by pcgpcgpcg** [comment]
to avoid aggressive messge communication between server and client. I think it's better to send a summary of message by pres. It's quit straitforward！ Isn't it? such as:
"hello,I am bob bobobobobobobobobbob"->"hello,i am..."
a picture->[picture]
a video ->[video]
a file ->[file]

**Comment by or-else** [comment]
> to avoid aggressive messge communication between server and client

Server does not read messages right now. It does not care about message content at all. For instance, the messages could be encrypted. In order to implement this feature the server must process messages.

**Comment by pcgpcgpcg** [comment]
I think there is key problem about "User user = Cache.getTinode().getUser("user_id_here");"
for example, carl is not eve adams's friend, when eve adams logined in and enter the contact list, At this moment, carl send a message in the “Let's talk about flowers”, unfornately in eve's contact list page, we can't get carl's fullName by Cache.getTinode().getUser("carl's id") unless eve enter into the chat page of "Let's talk about flowers".

**Comment by or-else** [comment]
In those cases request the user info from the server
```
getMeta(getMetaGetBuilder().withSub(pres.src).build());
```
It's a bad practice to send the same unchanged data every time when it should be just cached. Yes, caches are harder than getting the data multiple times but that's the way to go, particularly on mobile.

**Comment by pcgpcgpcg** [comment]
Thank you! I will try and feedback

**Comment by or-else** [comment]
@kisulken The message snippet/preview feature can be implemented in the client with no server changes. You are welcome to send a pull request.

**Comment by or-else** [comment]
This does not seem to be relevant anymore.
