### ISSUE TITLE
adapter.go:1850:16: constant 2147483648 overflows int

### ISSUE THREAD

**Issue by supaplextor** [tinode/chat#309]
### Subject of the issue
installing from [INSTALL.md](https://github.com/tinode/chat/blob/master/INSTALL.md)

As a normal user:
```
supaplex@tinode2:~$ go get -tags mysql github.com/tinode/chat/server && go install -tags mysql github.com/tinode/chat/server
# github.com/tinode/chat/server/db/mysql
go/src/github.com/tinode/chat/server/db/mysql/adapter.go:1850:16: constant 2147483648 overflows int
go/src/github.com/tinode/chat/server/db/mysql/adapter.go:1905:16: constant 2147483648 overflows int
supaplex@tinode2:~$ echo $?
2
```

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
Two instances:
i386 tinode2 (this report) Debian Linux VM Buster 10.0 with all updates.
Raspberry Pi 4 B (same results) Raspbian Buster 10 with all updates.
  
```
supaplex@tinode2:~$ dpkg -l golang-go
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=========================================================
ii  golang-go      2:1.11~1     i386         Go programming language compiler, linker, compiled stdlib
supaplex@tinode2:~$ go version
go version go1.11.6 linux/386

```

  * version of tinode server, e.g. `0.15.2-rc3`
git-master?
  * database backend
MySQL
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
No issues here. FF, Chrome, all work.
- [x] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
Emulator (works)
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

**Comment by or-else** [comment]
Interesting. I guess it's because the system is 32 bit. Thanks! The fix is coming.

**Comment by or-else** [comment]
it's unclear to me what binary you are running at `github.com/tinode/chat/server/db/mysql`. The binary to ru is supposed to be at `~/go/bin/server`

**Comment by supaplextor** [comment]
I'm not sure which binary you mean. mysql server? Here's what's present:

```
supaplex@tinode2:~/go/src$ ls -l github.com/tinode/chat/server/db/mysql
total 80
-rw-r--r-- 1 supaplex supaplex 67741 Nov 12 20:02 adapter.go
-rw-r--r-- 1 supaplex supaplex   182 Nov 12 20:02 blank.go
-rw-r--r-- 1 supaplex supaplex  5164 Nov 12 20:02 schema.sql
supaplex@tinode2:~/go/src$ ls ~/go/src/
cloud.google.com/    firebase.google.com/ github.com/          golang.org/          google.golang.org/   go.opencensus.io/
supaplex@tinode2:~/go/src$ ls ~/go/
src
```

Before the init-db step, I was going to install mariadb-server-10.3 from apt and configure root accordingly.

**Comment by or-else** [comment]
1. The bug is fixed in `devel`. 
2. The code at `github.com/tinode/chat/server/db/mysql` is not runnable. It does not have `main`. I don't know what kind of binary you ran with `github.com/tinode/chat/server/db/mysql`.

**Comment by supaplextor** [comment]
Fix is working on both platforms now.
Pi 4: Linux portable 4.19.50-v7l+ #895 SMP Thu Jun 20 16:03:42 BST 2019 armv7l GNU/Linux
VM: Linux tinode2 4.19.0-5-686-pae #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) i686 GNU/Linux

Thanks!
