### ISSUE TITLE
Add tags on user registration

### ISSUE THREAD

**Issue by lorenzoPrimi** [tinode/chat#320]
### Subject of the issue
Is there a way to automatically add tags on user registration?
I want to add "username" (not "basic:username") and "first last name"

If yes, is it possible to do with the config file or should I modify the sources?

### Is this a bug report of a feature request?
- [ ] Bug report
- [X ] Feature request

### Your environment
- Last docker image

**Comment by or-else** [comment]
This requires modifications to the client-side code.
It's not a bad idea. We just don't have time to do it right now.

**Comment by lorenzoPrimi** [comment]
If you tell me where to look I can try to do it and open a PR

**Comment by or-else** [comment]
iOS:
https://github.com/tinode/ios/blob/master/Tinodios/SignupViewController.swift#L87
Android:
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/SignUpFragment.java#L159
Web:
https://github.com/tinode/webapp/blob/master/src/views/create-account-view.jsx#L65

Actually, I wanted to implement this feature slightly differently. My idea was to detect what was entered into the search box on the client: email, phone number, plain text, then to prefix the string with an appropriate label. I.e. if someone entered `alice@example.com` automatically convert it to `email:alice@example.com`, `john` to `basic:john`, etc. 

This is more scalable than the inverse that you want to do. It would not permit searching by personal name but that is valuable only in small teams. If it's really needed, the plain text can be searched by both converted and original, i.e. `john` -> `basic:john, john`.

**Comment by or-else** [comment]
I believe this has been addressed.
