### ISSUE TITLE
MySql Docker image failed to start

### ISSUE THREAD

**Issue by mohgh** [tinode/chat#329]
### Subject of the issue
I'm using the latest tinode mysql docker image with external config file option. I'm running the mysql docker image and then set the databast hostname to 'mysql' instead of 'localhost' in config file. Now when I run the actual tinode-mysql image, I got the following error:

2019/12/08 06:02:16 Initializing mysql 109
2019/12/08 06:02:16 Database reset requested
2019/12/08 06:02:18 No data provided, stopping

Although the container is started and running there's no active connection on port 6060.
### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Linux
  * version of tinode server: latest
  * mysql

**Comment by or-else** [comment]
Is there anything else in the logs? The log you have shown is the output of init-db. There must be some more records in the log.

**Comment by mohgh** [comment]
No there is not.
Is there a configurable option in the container that it would show the logs?
I use `docker history tinode-srv` to view the log history of the container.

**Comment by aforge** [comment]
Apparently, your `tinode-srv` docker container dies right after starting.
You can check its status with `docker container ls -a`.
Can you `docker cp TINODE_CONTAINER_ID:/var/log/tinode.log .` and post the content of `tinode.log` please?

**Comment by or-else** [comment]
Hi @mohgh. Any update on this?

**Comment by or-else** [comment]
I assume it's either resolved or no longer relevant.
