### ISSUE TITLE
[Ask About Setting Private Value of P2P Subscription]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#33]
Hello, Gene

I would like to ask regarding setting private value on P2P permission. Why it is prohibited to change private value on P2P subscription? [source code](https://github.com/tinode/chat/blob/master/server/topic.go#L1256-L1260)

Maybe there is another way if I want to set private value to P2P subscription?

Thanks

**Comment by or-else** [comment]
It's a bug. It should not reject changes to `private`. I'll fix it.

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/chat/commit/723281f1b2e97b481d8eb4a713df5c20a8bb0e4f
