### ISSUE TITLE
How to get tinode for linux?

### ISSUE THREAD

**Issue by music24by7** [tinode/chat#331]
I did following:
go get -tags mysql github.com/tinode/chat/server && go install -tags mysql github.com/tinode/chat/server

go get -tags mysql github.com/tinode/chat/tinode-db && go install -tags mysql github.com/tinode/chat/tinode-db

cd ~/go/src/github.com/tinode/chat/tinode-db

--> Change tinode.conf with proper mysql user/password

cp ~/go/bin/tinode-db .

./tinode-db -data=data.json

--> with this I can see MYSQL database getting created with proper tables/users

--> After this the next step according to INSTALL file is to run ./tinode

How I can build/get this file(tinode)?

**Comment by or-else** [comment]
> I did following:
> go get -tags mysql github.com/tinode/chat/server && go install -tags mysql github.com/tinode/chat/server

That's the step where you have built the server. I suppose the file is called `server`.

**Comment by music24by7** [comment]
If I try to run ./server I get:

2019/12/13 16:09:49 Server v0.16:/home/ubuntu/go/src/github.com/tinode/chat/server/server:undef; db: 'mysql'; pid 15347; 8 process(es)
2019/12/13 16:09:49 Using config from '/home/ubuntu/go/src/github.com/tinode/chat/server/tinode.conf'
2019/12/13 16:09:49 stats: variables exposed at '/debug/vars'
2019/12/13 16:09:49 Running as a standalone server.
2019/12/13 16:09:49 Restricted tags: ['basic' 'email' 'tel']
2019/12/13 16:09:49 plugins: no active plugins found
2019/12/13 16:09:49 gRPC/1.26.0-dev server is registered at [:6061]
2019/12/13 16:09:49 Static content directory is not found/home/ubuntu/go/src/github.com/tinode/chat/server/static

Any idea where this static directory is?

**Comment by or-else** [comment]
It's where you unpacked the webapp + js-sdk:

> Unpack JS client to a directory, for instance $HOME/tinode/webapp/ by first unzipping 
> https://github.com/tinode/webapp/archive/master.zip then extract tinode.js from
>  https://github.com/tinode/tinode-js/archive/master.zip to the same directory.

**Comment by music24by7** [comment]
Okay, got it !
