### ISSUE TITLE
Message replies and forwarding

### ISSUE THREAD

**Issue by amiri267** [tinode/chat#336]
### Is this a bug report of a feature request?
- Feature request

#### Server-side
- api.tinode.co
- platform (Windows, Mac, Linux etc)
  
#### Client-side
- Browser make and version.
- Android API level (e.g. 25).

**Comment by or-else** [comment]
Channel request is a duplicate:
https://github.com/tinode/chat/issues/182

**Comment by afshindeves** [comment]
Have you any idea for how to do this? i can develop it and send pull request but i dont have any idea about way to doing that

**Comment by or-else** [comment]
Take a look at this discussion:
https://groups.google.com/forum/#!topic/tinode/7XNy0QVPUH8
and this https://groups.google.com/forum/#!topic/tinode/1L2c8Bj98Hw

**Comment by or-else** [comment]
Here is started and abandoned pull request from @Kuvonchbeky : https://github.com/tinode/tindroid/pull/73/files

**Comment by Kuvonchbeky** [comment]
Hi @or-else , I'm busy with the iOS client, I will send pull request again.

**Comment by afshindeves** [comment]
If the original message of forwarded or replied message was deleted, how server handle this?

**Comment by Kuvonchbeky** [comment]
Server does not handle it. This is not implemented yet. I think you can check quoted text by sequence id, and replace the text with "Deleted message" if `seqId` does not exists.

**Comment by or-else** [comment]
This is added in 0.18
