### ISSUE TITLE
Feature request: Guest / anonymous users?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#338]
Would be nice to have guest / anonymous users for chat / groups by link invite. It's possible for example with nextcloud talk.
Is it possible to do with tinode and could it added to planned features?

**Comment by or-else** [comment]
We already have anonymous users. Could you please describe your use case and explain why existing scheme does not serve your needs.

**Comment by pwFoo** [comment]
I would try to test guest users in group chats, but have to wait for a new docker image with bug fix (#337).

So how to invite a guest to a (group) chat without registration by link?

**Comment by pwFoo** [comment]
I have a group with 3 members, but how to invite a guest user by for example link?
The user should join the group without user registration ("guest user").

**Comment by or-else** [comment]
Why does it have to be an external link&

What is your use case?

**Comment by pwFoo** [comment]
I think we talk from different use cases?,
Ccould you explain how guests join a (private) group in tinode if implemented?

registered user a, b and c share a private chat group and would add a guest user without a registered account to that group.

**Comment by or-else** [comment]
Is this a use case of customer support?

**Comment by or-else** [comment]
Please descripe the business operations.

**Comment by pwFoo** [comment]
Business could be support, chat room with external persons or just the private use case:
Family chat room with a non family guest. A nice to have feature I think and for my personal use case a must have feature...

**Comment by or-else** [comment]
Is this resolved?

**Comment by pwFoo** [comment]
Hi, question is answered. You can close the issue. Thanks.

Gene <notifications@github.com> schrieb am Di., 3. März 2020, 08:05:

**Comment by curiousgeek123** [comment]
@pwFoo  Did you find any plugin or a way to have anonymous users join the chat topics/groups with an invite url? how to do this?

**Comment by FaizanZahid** [comment]
> We already have anonymous users. Could you please describe your use case and explain why existing scheme does not serve your needs.

Can you please explain how can i use and see the anonymous users feature in action on tinode? How can i configure the anonymous login for users in my docker yaml file? @or-else

**Comment by curiousgeek123** [comment]
> We already have anonymous users. Could you please describe your use case and explain why existing scheme does not serve your needs.

Can you please explain how can i use and see the anonymous users feature in action on tinode? How can i configure the anonymous login for users in my docker yaml file? @or-else

**Comment by or-else** [comment]
Please use https://groups.google.com/d/forum/tinode for general conversations.
