### ISSUE TITLE
[Query] Pagination of Topics

### ISSUE THREAD

**Issue by sandeepcmsm** [tinode/chat#342]
### Pagination of Topics
If the user has more than 100 or 500 topics, Currently users are receiving all the topics at one shot. It would be better to paginate topics, but there are many cases to handle on the mobile devices when topics are cached. Can you point me direction to implement it or suggest any sources or documents related this scenario.

### Is this a bug report of a feature request?
- [ ] Bug report
- [*] Feature request

#### Server-side
- [ *] api.tinode.co
- [ *] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ *] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

**Comment by or-else** [comment]
Subscription pagination is not supported right now. If you want to work on it I would suggest to start from DB adapter:
https://github.com/tinode/chat/blob/master/server/db/adapter.go

**Comment by or-else** [comment]
The ims in {get what=subs} is now respected. The clients are not updated to use it yet but the server will paginate the subscriptions by ims.

**Comment by or-else** [comment]
done.
