### ISSUE TITLE
Sync Contacts With Mobile(Android or iOS) Contacts

### ISSUE THREAD

**Issue by ahs441** [tinode/chat#343]
### Subject of the issue
Automatically add and sync contacts with phone number (tel) from device (android or ios) contacts and show join messages if new contact join to the chat server (like telegram)

### Is this a bug report of a feature request?
- [x] Feature request

#### Server-side
- [x] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  
#### Client-side
- [x] Tindroid: Android app
- [x] Tindroid: iOS app

**Comment by or-else** [comment]
https://github.com/tinode/tindroid/issues/37

**Comment by or-else** [comment]
https://github.com/tinode/ios/issues/135

**Comment by or-else** [comment]
Android done in devel:
https://github.com/tinode/tindroid/compare/48920262399d41e4e839129c90694e47e152bff7..f7542da1d416b70fcb29db26f5ee6d076c85ca9b

**Comment by or-else** [comment]
All done
