### ISSUE TITLE
[Question] Telegram like account creation and login

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#354]
Is it possible to register users like in Telegram? I mean type your phone number, enter code from SMS to finish registering and later on use that authenticated device without typing any login/password to log in.
I know that it can be achieved by using `token` auth, but what if token expires - how to refresh?

**Comment by or-else** [comment]
Yes, it just costs money. I'm not aware of any free SMS services. Doing it involves two steps:
1. Select SMS service provider.
2. Implement SMS sending for the selected provider: 
https://github.com/tinode/chat/blob/master/server/validate/tel/validate.go#L88

If we start offering a commercial service we may implement it.

**Comment by Googlom** [comment]
Main question - is it possible in Tinode don't use username:password at all and use only tokens. I want users to register by validating phone number by SMS, get token and login with that token. I don't quite understand how the `{acc}` message should look like in this case?

**Comment by or-else** [comment]
Yes, it's also possible. In that case you need to write an authenticator https://github.com/tinode/chat/blob/master/server/auth/auth.go
or use REST authenticator to integrate with your existing SMS authentication service:
https://github.com/tinode/chat/tree/master/server/auth/rest

It probably would also require some changes to login UI in the clients to make it easier to use phone + SMS for authentication.

**Comment by Googlom** [comment]
My idea is:
1) User registers entering phone number
2) After verifying his phone number by SMS **(only once every new device)** gets token and uses it to authenticate.
In case if I use existing `token` authenticator how to handle token expiry? Is it possible somehow refresh token?

**Comment by or-else** [comment]
> 1. - 

Yes, as described above

> 2. -

(a) You can set any token expiration time, say 1 year
https://github.com/tinode/chat/blob/master/server/tinode.conf#L137
(b) token is refreshed every time it's used, so to expire the token user must not use the app at all for the designated time. For instance, if you set expiration time to one year, the token will expire after 1 year of not being used.

**Comment by or-else** [comment]
Is this resolved?

**Comment by Googlom** [comment]
Resolved. Thanks!

**Comment by blasius** [comment]
> Yes, it just costs money. I'm not aware of any free SMS services. Doing it involves two steps:
> 
> 1. Select SMS service provider.
> 
> 2. Implement SMS sending for the selected provider: 
> 
> https://github.com/tinode/chat/blob/master/server/validate/tel/validate.go#L88
> 
> 
> 
> If we start offering a commercial service we may implement it.

Have you considered Firebase Phone Authentication? They have a free 10k/month authenticated phone numbers and I think it's sufficient for Tinode current user base. 

It would be great because I think Tinode is a great project and authentication with just a phone number can bring a lot of users and help promote Tinode. 

I live in a country where most people don't use email at all. I also think telegram and WhatsApp success comes from the ease of use and simplicity of phone authentication.

If you can support me I can help on the Android client.

Please consider this, it can be a game changer for Tinode. Thanks

**Comment by or-else** [comment]
We don't have the time to work on it right now. If you can help, please help.

**Comment by blasius** [comment]
> We don't have the time to work on it right now. If you can help, please help.

Can you help me by indicating which part of the documentation I should start by?

**Comment by or-else** [comment]
Start with implementing the validator: https://github.com/tinode/chat/blob/master/server/validate/validator.go
