### ISSUE TITLE
token authentication and gRPC

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#358]
I think there is a bug with `pbconverter`. Token that client receives is unsuitable when it sent back to server. I've done some research:
1) `[]byte` generated by GenSecret(): 
`[16 206 1 189 53 77 116 50 113 70 87 94 20 0 1 0 1 0 214 47 239 28 142 176 39 196 84 226 59 59 243 185 154 200 194 190 121 142 191 42 209 240 21 20 145 3 116 235 216 65]`

2) `[]byte` after `json.Marshal()` (**pbconverter.interfaceMapToByteMap()**):  
`[34 69 77 52 66 118 84 86 78 100 68 74 120 82 108 100 101 70 65 65 66 65 65 69 65 49 105 47 118 72 73 54 119 74 56 82 85 52 106 115 55 56 55 109 97 121 77 75 43 101 89 54 47 75 116 72 119 70 82 83 82 65 51 84 114 50 69 69 61 34]`

3) and **its string** representation: `"EM4BvTVNdDJxRldeFAABAAEA1i/vHI6wJ8RU4js787mayMK+eY6/KtHwFRSRA3Tr2EE="`

4) What I received in python client:
```python 
params {
    key: "token"
    value: "\"EM4BvTVNdDJxRldeFAABAAEA1i/vHI6wJ8RU4js787mayMK+eY6/KtHwFRSRA3Tr2EE=\""
}
```
5) How I send token back to server:
```python
pb.ClientMsg(
    login=pb.ClientLogin(
        scheme="token",
        secret=b'"EM4BvTVNdDJxRldeFAABAAEA1i/vHI6wJ8RU4js787mayMK+eY6/KtHwFRSRA3Tr2EE="'
    ))
```

6) `[]byte` received by `Authenticate()` (same as in step 2): 
`[34 69 77 52 66 118 84 86 78 100 68 74 120 82 108 100 101 70 65 65 66 65 65 69 65 49 105 47 118 72 73 54 119 74 56 82 85 52 106 115 55 56 55 109 97 121 77 75 43 101 89 54 47 75 116 72 119 70 82 83 82 65 51 84 114 50 69 69 61 34]`

This value used as token during auth.

7) But after `json.Unmarshal()`:
```go
	var tkn []byte
	json.Unmarshal(token, &tkn)
```
 I get the same value as in step 1:
`[16 206 1 189 53 77 116 50 113 70 87 94 20 0 1 0 1 0 214 47 239 28 142 176 39 196 84 226 59 59 243 185 154 200 194 190 121 142 191 42 209 240 21 20 145 3 116 235 216 65]`

Is it a bug or am I doing something wrong?

**Comment by or-else** [comment]
I'm pretty sure token authentication works as expected. Take a look at tn-cli. It uses token authentication and it works fine.

I think you are base64-encoding the token twice.

**Comment by Googlom** [comment]
Oh, my fault. I didn't base64 decode before sending token back.
https://github.com/tinode/chat/blob/8d77b2be39a24e85f125e09e247ab17437df7878/tn-cli/tn-cli.py#L355-L357
