### ISSUE TITLE
the build/install doc is chaos

### ISSUE THREAD

**Issue by usernameisnull** [tinode/chat#360]
### Subject of the issue
can't build from source

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
     
```Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
     Codename:	bionic
     ```
     
  * version of tinode server, e.g. `0.15.2-rc3`
  
     `0.16.3`
  
  * database backend
  
     `mysql`
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Tell us how to reproduce this issue.

1. go install no `-output` option!!

```
go get -tags mysql github.com/tinode/chat/server && go install -tags mysql -output $GOPATH/bin/tinode github.com/tinode/chat/server
```

2. build-all.sh, this can't run,problems:

   ```
   cp: cannot stat './server/static/img/*.png': No such file or directory
   cp: cannot stat './server/static/img/*.svg': No such file or directory
   cp: cannot stat './server/static/audio/*.mp3': No such file or directory
   cp: cannot stat './server/static/css/*.css': No such file or directory
   cp: cannot stat './server/static/index.html': No such file or directory
   cp: cannot stat './server/static/index-dev.html': No such file or directory
   cp: cannot stat './server/static/umd/*.js': No such file or directory
   cp: cannot stat './server/static/manifest.json': No such file or directory
   cp: cannot stat './server/static/service-worker.js': No such file or directory
   Building python code...
   ----, /root/gopath/src/github.com/tinode/chat
   build-all.sh: line 139: ./build-py-grpc.sh: No such file or directory
   
   ```

   

### Expected behaviour

Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
> go install no `-output` option!!

thanks, fixed: https://github.com/tinode/chat/commit/248575601559d5c3d8bf70625074a4e9f21cfc98

> cp: cannot stat './server/static/img/.png': No such file or directory

Fixed: https://github.com/tinode/chat/commit/f9af0695fcabf2080d203704c6dd8239bcf59621

> build-all.sh: line 139: ./build-py-grpc.sh: No such file or directory

Thanks, added https://github.com/tinode/chat/commit/8fa0217d1373b6eadf9168448c63fbd3de1d090e

**Comment by or-else** [comment]
Is this resolved? Do you still have questions?

**Comment by usernameisnull** [comment]
> Is this resolved? Do you still have questions?

in build-all.sh, ~/go/bin/gox, I think just gox is better, ~/go/bin/gox is the author's own gox path

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/chat/commit/a597f19dd1462a7db3eedbe2af5c11d0b44bafa4

Anything else?
