### ISSUE TITLE
ios push notification issue

### ISSUE THREAD

**Issue by michael-networking** [tinode/chat#361]
I have installed latest 0.16.3 binary release (vm not docker) and compiled ios client too. Everything is good except ios client can't receive any push notification. I followed the document and also sent test message from fcm console to test notification and notification did come to our ios client. It seems server side didn't send any notification at all and there's no any log about pushing in tinode.log either even I have enabled push debug. I also notice plugin mentioned for mobile push notification, but no detail can be found. Please help and let me know if I miss anything.

By the way, is there any command line we can use to send push from server side to test because we have token already in table "devices" ?  Thanks a lot.

**Comment by aforge** [comment]
We don't have command line tools to send push notifications. Sending a regular message should trigger a push.

I'm assuming you've swapped in your own `GoogleService-Info*.plist` files when building the client and your server side configuration matches your firebase project.
Are you observing it only with iOS or both iOS and Android? Also, you are running your iOS client on a physical device, correct?
Also, do you mind sharing your `tinode.log`?

**Comment by or-else** [comment]
Are you running in a simulator or on a device? Apple doesn't support pushes in the simulator.

**Comment by michael-networking** [comment]
On two real devices.(iphone 11 pro and iphone 7). One is iOS12 and another is iOS13.  We have not tested on Android yet.  Here's what I did
in tinode.conf, updated "credentials_file" to json file from fcm console and remove "credentials".
in ios client, downloaded GoogleService-Info.plist and move to Tinodios/GoogleService-Info-Development.plist.
login no problem with alice and bob and they can chat each other. However, if we put the app with alice in background. bob sent message to alice. nothing received in alice's phone until app has been opened by alice.
I sent test notification with alice's token from table "devices" in fcm console, alice's phone received notification. What am I missing ? Thanks.

**Comment by or-else** [comment]
See if there are any errors in the server log.
Check if server actually tries to send a push. Add some logging here:
https://github.com/tinode/chat/blob/master/server/push/fcm/push_fcm.go#L232

**Comment by or-else** [comment]
@michael-networking Is this resolved? Are there any followup questions?

**Comment by or-else** [comment]
No update in almost 3 weeks. Let's assume it's resolved.
