### ISSUE TITLE
go install no -output option

### ISSUE THREAD

**Issue by usernameisnull** [tinode/chat#363]
in this link: https://github.com/tinode/chat/blob/master/docs/API.md#server-api 
go install -tags mongodb -output $GOPATH/bin/tinode github.com/tinode/chat/server

**Comment by or-else** [comment]
https://github.com/tinode/chat/issues/360

**Comment by or-else** [comment]
Please use instructions from `devel`:
https://github.com/tinode/chat/blob/devel/INSTALL.md

They will be merged to master soon.
