### ISSUE TITLE
web client login timeout

### ISSUE THREAD

**Issue by abitcyanine** [tinode/chat#367]
We have two test servers.
(A) A server of our own, with tinode server (v0.15),  is mapped to public IP through router.
(B) An alicloud server with tinode server(v0.16)
Recently, the web client connected to server A and returned timeout. I checked the client console and server messages. The client received hi's response, but did not receive login's response. 

I copy the server(v0.15) to server B, the web client can access two versions of the server successfully. And I copy the server(v0.16) to server A，the web client can only access the server(v0.16) successfully. The same conf file used by two servers.

What other information do I need to provide? Please help me to analyze and locate the problem, thx.

**Comment by or-else** [comment]
Please show client-side and server-side logs.

**Comment by abitcyanine** [comment]
I compared the logs of client-side and server-side when accessing v0.15 and v0.16 servers, and the messages are the same. However, accessing the v0.15 server, the client does not receive the response message after sending login.
Today, version 0.15 can be used normally, I doubt it's a firewall problem, but I don't understand why v0.16 can be used yesterday and v0.15 can't

**Comment by or-else** [comment]
Is this resolved?

**Comment by or-else** [comment]
No followup in a week. Let's consider this resolved.
