### ISSUE TITLE
[Ask About Implementing Hard Delete Message on P2P]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#38]
Hello, Gene

So if I would like to implement hard delete for `P2P` topic. Is it good idea to just include `D` permission on `P2P` default permissions?

Thanks

**Comment by or-else** [comment]
I suppose it's a matter of policy. I was thinking about deleting the message when both users delete it. But it would not be unreasonable to do it like Skype - if the sender deletes the message then it's deleted for both users. I think it would be weird if the message is deleted for both users when just the receiver deletes it.
