### ISSUE TITLE
build source error!

### ISSUE THREAD

**Issue by Sopage** [tinode/chat#383]
### Subject of the issue
$:./build-all.sh
error message:
Stderr: cloud.google.com/go/iam
../../../cloud.google.com/go/iam/iam.go:135:58: cannot use conn (type grpc.ClientConnInterface) as type *grpc.ClientConn in argument to iam.NewIAMPolicyClient: need type assertioncloud.google.com/go/firestore/apiv1
../../../cloud.google.com/go/firestore/apiv1/firestore_client.go:226:41: cannot use connPool (type "google.golang.org/api/internal".ConnPool) as type *"google.golang.org/grpc".ClientConn in argument to firestore.NewFirestoreClient

**Comment by or-else** [comment]
Works for me:
```
Genes-MacBook-Pro:chat gene$ ./build-all.sh 
Releasing 0.16.4-27-g7905bf5
Building mysql-darwin/amd64...
Building mongodb-darwin/amd64...
Building rethinkdb-darwin/amd64...
Building alldbs-darwin/amd64...
Building mysql-windows/amd64...
Building mongodb-windows/amd64...
Building rethinkdb-windows/amd64...
Building alldbs-windows/amd64...
Building mysql-linux/amd64...
Building mongodb-linux/amd64...
Building rethinkdb-linux/amd64...
Building alldbs-linux/amd64...
Building the binary for web.tinode.co
Building python code...
Packaging python tinode-grpc...
Packaging chatbot.py...
Packaging tn-cli...
```

If you need help, please give s much information about your setup as possible.

**Comment by or-else** [comment]
Also keep in mind that the error is generated while compiling Google's code. It's highly unlikely that Google shipped code which does not compile.

**Comment by Sopage** [comment]
thanks,  get dependencies I use "go get -v. / ...", so I don't know what's error

**Comment by Sopage** [comment]
https://github.com/googleapis/google-cloud-go
select tag v0.49.0
Why not use go mod?

**Comment by Sopage** [comment]
Releasing 0.16.4-3-g4184c45
Building mysql-linux/amd64...
TinodeWeb not found, skipping
Building the binary for web.tinode.co
Building python code...
Packaging python tinode-grpc...
Packaging chatbot.py...
Packaging tn-cli...



!!!!!!!!!! TinodeWeb not found, skipping. !!!!!!!!!!??

**Comment by or-else** [comment]
> Why not use go mod?

Because it's relatively new and we have not migrated to go mod yet. Would you like to send a pull request?

> !!!!!!!!!! TinodeWeb not found, skipping. !!!!!!!!!!??

The explanation is right there in the file:
https://github.com/tinode/chat/blob/master/build-all.sh#L5
```
# If directory ./server/static exists, it's asumed to contain
# TinodeWeb and then it's also copied and archived.
```
If you know a better way of doing it, please send a pull request. Thanks.

**Comment by Sopage** [comment]
OK。I will try to change
