### ISSUE TITLE
gRPC error 14: "Socket closed"

### ISSUE THREAD

**Issue by malte-v** [tinode/chat#384]
I'm sorry if this is not related to tinode, but I haven't found much on the internet regarding this behavior. I also have very little understanding of how gRPC works, so please bear with me :)

When trying to list the services available at the tinode sandbox via `grpc_cli`, I run into this error:
```
➜  ~ grpc_cli ls sandbox.tinode.co
Received an error when querying services endpoint.
ServerReflectionInfo rpc failed. Error code: 14, message: Socket closed, debug info: {"created":"@1584562584.361506253","description":"Error received from peer ipv4:104.196.16.37:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}
```

I get a similar error when trying to do a handshake through my Dart client:
```dart
  Future<void> _connect() async {
    final channel = ClientChannel("sandbox.tinode.co");
    final client = NodeClient(channel);

    var up = StreamController<ClientMsg>();
    var down = client.messageLoop(up.stream);

    final handshakeMsg = ClientMsg()..hi = (ClientHi()..ver = "0.15");
    up.add(handshakeMsg);

    await down.first.then((value) => print(value.writeToJson()),
        onError: (err) => print(err));

    up.close();
  }
```

```
gRPC Error (14, Closed in non-idle state)
```

Does anyone have an idea what could cause this? Thanks!

**Comment by or-else** [comment]
Two problems:

1. In general Tinode exposes gRPC at port 6061:
https://github.com/tinode/chat/blob/master/server/tinode.conf#L22
So, at the very least you need to make calls to the correct port.

2. Sandbox does not expose port 6061 to the world.
