### ISSUE TITLE
I can't Build Source project

### ISSUE THREAD

**Issue by komeil-sh** [tinode/chat#390]
### **This is Error**
`GOROOT=C:\Go #gosetup
GOPATH=C:\Users\KOMEIL-PC\go #gosetup
C:\Go\bin\go.exe build -tags mongodb -o C:\Users\KOMEIL-PC\AppData\Local\Temp\___go_build_main_go.exe C:/Users/KOMEIL-PC/Downloads/Compressed/chat-master/server/main.go #gosetup
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:14:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\aws (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:15:2: cannot find package "github.com/aws/aws-sdk-go/aws/awserr" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:16:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:17:2: cannot find package "github.com/aws/aws-sdk-go/aws/request" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\aws\request (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\request (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:18:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\aws\session (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\session (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:19:2: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOPATH)
..\..\..\..\go\src\github.com\tinode\chat\server\media\s3\s3.go:20:2: cannot find package "github.com/aws/aws-sdk-go/service/s3/s3manager" in any of:
	C:\Go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\database.go:20:2: cannot find package "go.mongodb.org/mongo-driver/x/bsonx" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\bsonx (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\bsonx (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\bsonx (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\bson\bsonrw\copier.go:15:2: cannot find package "go.mongodb.org/mongo-driver/x/bsonx/bsoncore" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\bsonx\bsoncore (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\bsonx\bsoncore (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\bsonx\bsoncore (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\options\clientoptions.go:28:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\client.go:26:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/auth" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\auth (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\auth (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\auth (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\options\clientoptions.go:29:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/connstring" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\connstring (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\connstring (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\connstring (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\bulk_write.go:17:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/description" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\description (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\description (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\description (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\errors.go:16:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/mongocrypt" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\client_encryption.go:19:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/mongocrypt/options" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt\options (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt\options (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\mongocrypt\options (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\client.go:29:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/ocsp" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\ocsp (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\ocsp (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\ocsp (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\bulk_write.go:18:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/operation" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\operation (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\operation (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\operation (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\bulk_write.go:19:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/session" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\session (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\session (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\session (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\client.go:32:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/topology" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\topology (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\topology (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\topology (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\client.go:33:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/uuid" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\uuid (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\uuid (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\uuid (from $GOPATH)
..\..\..\..\go\src\go.mongodb.org\mongo-driver\mongo\options\clientoptions.go:30:2: cannot find package "go.mongodb.org/mongo-driver/x/mongo/driver/wiremessage" in any of:
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\vendor\go.mongodb.org\mongo-driver\x\mongo\driver\wiremessage (vendor tree)
	C:\Go\src\go.mongodb.org\mongo-driver\x\mongo\driver\wiremessage (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.mongodb.org\mongo-driver\x\mongo\driver\wiremessage (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\internal\trace\trace.go:21:2: cannot find package "go.opencensus.io/trace" in any of:
	C:\Go\src\go.opencensus.io\trace (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\go.opencensus.io\trace (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\internal\trace\trace.go:22:2: cannot find package "google.golang.org/api/googleapi" in any of:
	C:\Go\src\google.golang.org\api\googleapi (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\googleapi (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\firestore\apiv1\firestore_client.go:28:2: cannot find package "google.golang.org/api/iterator" in any of:
	C:\Go\src\google.golang.org\api\iterator (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\iterator (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\firestore\apiv1\firestore_client.go:29:2: cannot find package "google.golang.org/api/option" in any of:
	C:\Go\src\google.golang.org\api\option (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\option (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\storage\acl.go:24:2: cannot find package "google.golang.org/api/storage/v1" in any of:
	C:\Go\src\google.golang.org\api\storage\v1 (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\storage\v1 (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\firestore\client.go:33:2: cannot find package "google.golang.org/api/transport" in any of:
	C:\Go\src\google.golang.org\api\transport (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\transport (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\firestore\apiv1\firestore_client.go:30:2: cannot find package "google.golang.org/api/transport/grpc" in any of:
	C:\Go\src\google.golang.org\api\transport\grpc (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\transport\grpc (from $GOPATH)
..\..\..\..\go\src\cloud.google.com\go\storage\storage.go:47:2: cannot find package "google.golang.org/api/transport/http" in any of:
	C:\Go\src\google.golang.org\api\transport\http (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\api\transport\http (from $GOPATH)
..\..\..\..\go\src\google.golang.org\grpc\resolver\resolver.go:29:2: no Go files in C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\serviceconfig
..\..\..\..\go\src\google.golang.org\grpc\internal\transport\handler_server.go:44:2: cannot find package "google.golang.org/grpc/stats" in any of:
	C:\Go\src\google.golang.org\grpc\stats (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\stats (from $GOPATH)
..\..\..\..\go\src\google.golang.org\grpc\internal\binarylog\method_logger.go:32:2: cannot find package "google.golang.org/grpc/status" in any of:
	C:\Go\src\google.golang.org\grpc\status (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\status (from $GOPATH)
..\..\..\..\go\src\google.golang.org\grpc\internal\transport\http2_server.go:50:2: cannot find package "google.golang.org/grpc/tap" in any of:
	C:\Go\src\google.golang.org\grpc\tap (from $GOROOT)
	C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\tap (from $GOPATH)

Compilation finished with exit code 1
`

**Comment by or-else** [comment]
Dependencies are misding. It seems like you did not do `go get` before building.

**Comment by komeil-sh** [comment]
I when Command `go get` error this :
`package google.golang.org/grpc/status: exit status 1
package google.golang.org/grpc/stats: cannot find package "google.golang.org/grpc/stats" in any of:
        c:\go\src\google.golang.org\grpc\stats (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\stats (from $GOPATH)
package google.golang.org/grpc/tap: cannot find package "google.golang.org/grpc/tap" in any of:
        c:\go\src\google.golang.org\grpc\tap (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\tap (from $GOPATH)
# cd C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go; git pull --ff-only
fatal: not a git repository (or any of the parent directories): .git
package github.com/aws/aws-sdk-go/aws: exit status 128
package github.com/aws/aws-sdk-go/aws/awserr: cannot find package "github.com/aws/aws-sdk-go/aws/awserr" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/credentials: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/request: cannot find package "github.com/aws/aws-sdk-go/aws/request" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\aws\request (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\request (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/session: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\aws\session (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\session (from $GOPATH)
package github.com/aws/aws-sdk-go/service/s3: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOPATH)
package github.com/aws/aws-sdk-go/service/s3/s3manager: cannot find package "github.com/aws/aws-sdk-go/service/s3/s3manager" in any of:
        c:\go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOROOT)
        C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOPATH)`

**Comment by komeil-sh** [comment]
> 
> 
> Dependencies are misding. It seems like you did not do `go get` before building.
  
### After `go get` This Error

package google.golang.org/grpc/status: exit status 1
package google.golang.org/grpc/stats: cannot find package "google.golang.org/grpc/stats" in any of:
c:\go\src\google.golang.org\grpc\stats (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\stats (from $GOPATH)
package google.golang.org/grpc/tap: cannot find package "google.golang.org/grpc/tap" in any of:
c:\go\src\google.golang.org\grpc\tap (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\google.golang.org\grpc\tap (from $GOPATH)
cd C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go; git pull --ff-only

fatal: not a git repository (or any of the parent directories): .git
package github.com/aws/aws-sdk-go/aws: exit status 128
package github.com/aws/aws-sdk-go/aws/awserr: cannot find package "github.com/aws/aws-sdk-go/aws/awserr" in any of:
c:\go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\awserr (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/credentials: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
c:\go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\credentials (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/request: cannot find package "github.com/aws/aws-sdk-go/aws/request" in any of:
c:\go\src\github.com\aws\aws-sdk-go\aws\request (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\request (from $GOPATH)
package github.com/aws/aws-sdk-go/aws/session: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
c:\go\src\github.com\aws\aws-sdk-go\aws\session (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\aws\session (from $GOPATH)
package github.com/aws/aws-sdk-go/service/s3: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
c:\go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3 (from $GOPATH)
package github.com/aws/aws-sdk-go/service/s3/s3manager: cannot find package "github.com/aws/aws-sdk-go/service/s3/s3manager" in any of:
c:\go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOROOT)
C:\Users\KOMEIL-PC\go\src\github.com\aws\aws-sdk-go\service\s3\s3manager (from $GOPATH)

**Comment by Sopage** [comment]
see [https://github.com/tinode/chat/issues/383](url)

**Comment by Sopage** [comment]
see https://github.com/tinode/chat/issues/383[https://github.com/tinode/chat/issues/383](url)

**Comment by Sopage** [comment]
see https://github.com/tinode/chat/issues/383

**Comment by Sopage** [comment]
I think it would be better to use mqtt implementation as the underlying implementation

**Comment by komeil-sh** [comment]
i'm using Windows 10

**Comment by komeil-sh** [comment]
> 383

i'm using Windows 10

**Comment by or-else** [comment]
> I think it would be better to use mqtt

Why?

**Comment by komeil-sh** [comment]
> 
> 
> > I think it would be better to use mqtt
> 
> Why?

Can you Record Video To Run that ?

**Comment by Sopage** [comment]
> > I think it would be better to use mqtt
> 
> Why?

Because simple

**Comment by or-else** [comment]
> Because simple

Then do it.

**Comment by or-else** [comment]
> Can you Record Video To Run that ?

I use Mac. It works. For some reason you are not getting the dependencies.

**Comment by komeil-sh** [comment]
> 
> 
> > Can you Record Video To Run that ?
> 
> I use Mac. It works. For some reason you are not getting the dependencies.

https://github.com/aws/aws-sdk-go/aws/request
is 404!! Why ?

**Comment by or-else** [comment]
> 404 
Because something has changed on their end. I'll get back home on a couple of hours and check.

**Comment by Sopage** [comment]
> > Because simple
> 
> Then do it.

I will try.

**Comment by or-else** [comment]
I've added go mod: https://github.com/tinode/chat/pull/392
It should fix the problem.

**Comment by komeil-sh** [comment]
Solved, thank you
