### ISSUE TITLE
how to ensure msg wont miss ? 

### ISSUE THREAD

**Issue by joshua0x** [tinode/chat#398]
### Subject of the issue
how to ensure msg wont miss ? 
how to kept msg sequence ?

### Is this a bug report of a feature request?
- [ ] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
I'm not sure I understand your question. You are probably asking about matching requests to responses. If so, please read the documentation about `id`: https://github.com/tinode/chat/blob/master/docs/API.md#general-considerations

It's best to ask general question in the form https://groups.google.com/forum/#!forum/tinode and leave github issue for specific requests and bugs. If you have further questions please continue there.
