### ISSUE TITLE
Ran the project on docker but it goes in infinite reconnection loop after i add a contact

### ISSUE THREAD

**Issue by curiousgeek123** [tinode/chat#400]
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ yes ] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [ yes ] Your own setup:
 

### Steps to reproduce
Tell us how to reproduce this issue.

I follow the official docker installation at https://github.com/tinode/chat/blob/master/docker/README.md
and ran it using MySQL.

### Expected behaviour
Server was working fine on myip:6060
i created 1 account, all was good, then i created another account from my mobile, and then went to settings and click add contact, i added the username/user ID of my first account and hit enter, then tinode UI keeps showing reconnecting, connection failure msg infinitely. Nothing is wrong in docker logs , see below

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.
root@ubuntu-s-1vcpu-1gb-nyc1-01:/var# docker logs -f tinode-srv
2020/03/26 11:28:03 Initializing  -1
2020/03/26 11:28:03 Database not found. Creating.
2020/03/26 11:28:04 No data provided, stopping

]

How to make sure my tinode server setup using docker is working correctly 100% ?

Also, how can rebrand the tinode UI for my own custom branding in the react web view web version?

**Comment by or-else** [comment]
It seems like you have either reset the database or deleted and recreated it.
Which version of Dockerfile are you using?

**Comment by aforge** [comment]
Also, can you check the content of `tinode.log` please?

```
$ docker cp tinode-srv:/var/log/tinode.log .
$ cat tinode.log
```

**Comment by curiousgeek123** [comment]
Thanks for the quick reply, @or-else & @aforge ,

I tried to start all over again, and i did this : https://github.com/tinode/chat/blob/master/docker/README.md

I pruned docker containers and volumes and images first.

1. `docker network create tinode-net`
2. decided to use mysql, so did, `docker run --name mysql --network tinode-net --restart always --env MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.7`

![image](https://user-images.githubusercontent.com/61917543/77738631-02732e00-7032-11ea-8a5f-d0dd6575bda5.png)



3. `docker run -p 6060:18080 -d --name tinode-srv --network tinode-net tinode/tinode-mysql:latest`

![image](https://user-images.githubusercontent.com/61917543/77738696-1d45a280-7032-11ea-961f-8806840b6836.png)

4. i went to http://134.122.21.244:6060/ tinode seems to be loading fine, made a new account with these credentials,
user id : test
pass : Test@123
name: testing
email: test@yahoo.com

![image](https://user-images.githubusercontent.com/61917543/77739497-6a764400-7033-11ea-994b-30297602c347.png)


5. went to tinode from my mobile and made another account with thesE:

user id : test1
pass: Test@123
name: testing1
email: test1@yahoo.com

6. then i went from my first account to see list of users, i dont see test1,
http://134.122.21.244:6060/#newtpk  neither i see test from test1 account on the user search page.
Why don't i see all available users in my db on this user discovery page, also how can i see all online users by default on this page?

7.  from test i tried to add test1 as contact , went to http://134.122.21.244:6060/#edit, added the email test1@yahoo.com in add contact, and hit enter, and infinite reconnection loop appears on both devices.

![image](https://user-images.githubusercontent.com/61917543/77739954-3a7b7080-7034-11ea-89c6-3a99ec1b8170.png)

8. i did log again as mentioned by @aforge  and got following, 
![image](https://user-images.githubusercontent.com/61917543/77740144-89c1a100-7034-11ea-8e2a-a0680c5f859a.png)

9. then tinode stopped working on http://134.122.21.244:6060/ i refreshed the page but it was not working.

10. i removed the container name "/tinode-srv" and ran again `docker run -p 6060:18080 -d --name tinode-srv --network tinode-net tinode/tinode-mysql:latest`

11. i tried signing up again and it said duplicate credentials
![image](https://user-images.githubusercontent.com/61917543/77740669-7531d880-7035-11ea-953a-cd95f697842b.png)
when i tried signing with my first user account, it said authentication failed 401

12. i logged in successfuly with test1, then tried to add contact by adding test@yahoo.com, again tinode crashed.

![image](https://user-images.githubusercontent.com/61917543/77740899-dce82380-7035-11ea-8549-4203b2f35315.png)

![image](https://user-images.githubusercontent.com/61917543/77740914-e4a7c800-7035-11ea-899c-2793a828aae9.png)

Not sure how can i check which version of docker file am i using?
![image](https://user-images.githubusercontent.com/61917543/77741401-abbc2300-7036-11ea-96b0-4a95896e0415.png)


Please let me know what am i doing wrong in setting this up? Have i missed something, is there a quick setup by step guide to setup a production server on tinode using docker on ubuntu?

Also, how can i make changes internally to the tinode UI once tinode server is running inside the docker container? for e.g if i want to change the logo and hide server and client versions?

I m not running this as of now, https://github.com/tinode/webapp how can i use this and make changes to tinode UI?

Also, i would want to use anonymous login so that i can chat without making account with other online users in real time, how can i do this?

Thanks in advance guys.

**Comment by or-else** [comment]
6. That's expected. These users are not connected to each other and consequently do not see each other. When you search make sure you search for `basic:test1` and `email:test1@yahoo.com`, not `test1` and `test1@yahoo.com`

7.  The purpose of this field is to add another email to the current account. A user may have multiple emails. 

8. You also hit a bug which was supposed to be fixed a while ago. I'll double check.

**Comment by curiousgeek123** [comment]
6. Is it possible to always connect all users together each time a new user joins? if so, how?
Also, i want users to be able to search directly by their name, email or user ID, or tel without adding any prefix.

7. Okay it would really help if we can add a tooltip or some place holder explaining about each field. Point is, why is my tinode crashing when i add another email in the contact section, is shouldnt , right?

8. Okay, please guide me how can i setup my docker setup so that tinode is production ready, and if it crashes, how can i set it to auto restart the tinode server?
 
I am new to tinode and docker, your help is appreciated.

Have i setup the docker installation correctly? how can i made changes to configurations of the server as well as the UI?

**Comment by or-else** [comment]
6. Not out of the box. You need a plugin. For example the chatbot Tino has some scaffolding for it:
https://github.com/tinode/chat/blob/master/chatbot/python/chatbot.py#L92

7. It's crashing because of a bug. Apparently we incorrectly packaged a docker with a buggy binary instead of a correct one.

8. Take a loom here:
https://github.com/tinode/chat/tree/devel/docker/docker-compose
