### ISSUE TITLE
[QUESTION] How to turn off presence but be able to continue chatting?

### ISSUE THREAD

**Issue by tsmrecki** [tinode/chat#405]
### Subject of the issue

I'm trying to set incognito mode in my app by sending **leave**:
LEAVE ME `leave {topic="me", unsub="false"}`. 
This works temporarily, my status is offline to other users.

Now, when I try to fetch the list of my conversations using **get**:
GET ME `get {topic="me", query={what="sub"} }`  
I only get my own user in **sub** array.

The only way I'm able to get list of my conversations is by using **sub**:
SUB ME `sub {topic="me", query={what="sub"} }` 
which then triggers the ONLINE status again.

Am I doing something wrong? How can I get the list of my conversations, but at the same time keep the "OFFLINE" mode?

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * version of tinode server: `0.16.3-rc.2`
  
#### Client-side
- Using on Android, pbx proto files built for Java (https://github.com/tinode/chat/tree/master/pbx)

### Steps to reproduce
As described above.

### Expected behaviour
I would expect to get the list of conversations using GET ME as well, not only SUB ME.
I expect for GET message not to trigger presence updates as SUB does, which I need for my feature.

### Actual behaviour
By using GET ME, I only get one contact in sub array - me.

### Client-side log
REQUEST:
get {
      id: "me"
      topic: "me"
      query {
        what: "sub"
      }
}

RESPONSE:
meta {
      topic: "me"
      sub {
        updated_at: 1583160248476
        acs {
          want: "JPS"
          given: "JPS"
        }
        private: "{\"x-username\":\"phone_number_hidden\"}"
        user_id: "hidden"
      }
   }

**Comment by or-else** [comment]
Remove `P` permission from `me` topic.
