### ISSUE TITLE
Failed to connect to DB: store: mysql adapter is not available in this binary

### ISSUE THREAD

**Issue by suzhi921** [tinode/chat#407]
OS : windows10
db：mysql

Build  source from goland editor,but raise a error below:

2020/04/03 19:55:38 Server v0.16:C:\Users\5555\go\src\github.com\tinode\chat\server\go_build_github_com_tinode_chat_server.exe:undef; pid 17444; 8 process(es)
2020/04/03 19:55:38 Using config from 'C:\Users\5555\go\src\github.com\tinode\chat\server\tinode.conf'
2020/04/03 19:55:38 stats: variables exposed at '/debug/vars'
2020/04/03 19:55:38 Running as a standalone server.
2020/04/03 19:55:38 Failed to connect to DB: store: mysql adapter is not available in this binary

**Comment by or-else** [comment]
Please read the documentation:
https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source
> Note the required **-tags rethinkdb**, **-tags mysql** or **-tags mongodb** build option.

If you have further questions please follow up at https://groups.google.com/d/forum/tinode

**Comment by xiwang007** [comment]
go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server
go build github.com/tinode/chat/server: copying /var/folders/d4/91n27bhs12gfdmhj1bqf34vr0000gn/T/go-build468353882/b001/exe/a.out: open /bin/tinode: operation not permitted

I just learned to go for 3 days. It's hard to cry
