### ISSUE TITLE
Reset Password mail template issue.

### ISSUE THREAD

**Issue by vs9390** [tinode/chat#409]
https://github.com/tinode/chat/blob/41f95284684c1f7e6e749aa0bc815b389706c8b2/server/validate/email/validate.go#L176

I am not an expert on this, but this line is causing issue while sending reset password email. I think it is a typo and should be as below 

`v.ResetTemplFile = resolveTemplatePath(v.ResetTemplFile) `

**Comment by or-else** [comment]
Yes, it's indeed a bug. Fixed: https://github.com/tinode/chat/commit/a4369009cd606831748602663afb4a9ed59da467
Thanks!
