### ISSUE TITLE
http: TLS handshake error from 192.168.1.200:8661 EOF

### ISSUE THREAD

**Issue by irpansetiana23** [tinode/chat#411]
Can help me for this, when i starting the server always http: TLS handshake error from 192.168.1.200:8661 EOF , i am using SSL DigiCert SHA2

in windows server 2012

Please Help Thanks

### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
Try using something like https://www.ssllabs.com/ssltest/analyze.html to debug your SSL setup.

**Comment by irpansetiana23** [comment]
> Try using something like https://www.ssllabs.com/ssltest/analyze.html to debug your SSL setup.

thanks before , i was try this one, but how do I ensure that the data there is correct ? thanks a lot

**Comment by or-else** [comment]
If you are reporting a specific issue with Tinode, please describe it in details. But it seems to me you are experiencing difficulties with general SSL setup. If so, I can't debug your SSL installation for you. You have to do it yourself or hire someone who will help you with setup.

**Comment by irpansetiana23** [comment]
i was try set TCP keepalive in server, and error handshake no exist again, and i open the chat in browser, i got Timeout error 540

![WhatsApp Image 2020-04-07 at 3 49 12 PM](https://user-images.githubusercontent.com/16398308/78653174-f23e3700-78ec-11ea-87d8-9c246307d1d8.jpeg)
![WhatsApp Image 2020-04-07 at 3 48 46 PM](https://user-images.githubusercontent.com/16398308/78653184-f5d1be00-78ec-11ea-9750-3dce8f516eaf.jpeg)

**Comment by irpansetiana23** [comment]
i was try set TCP keepalive in server, and error handshake no exist again, and i open the chat in browser, i got Timeout error 540
<img width="1176" alt="Screen Shot 2020-04-07 at 16 31 01" src="https://user-images.githubusercontent.com/16398308/78653564-83ada900-78ed-11ea-9e90-4e8c302065d1.png">
<img width="1228" alt="Screen Shot 2020-04-07 at 16 31 13" src="https://user-images.githubusercontent.com/16398308/78653588-8dcfa780-78ed-11ea-96f8-b52aeeb1f032.png">

**Comment by or-else** [comment]
See that "listen tcp :6061: bind: Only one usage ...."? It seems like something is already bound to socket at port 6061. Shut down the server you started earlier. Before starting a new one. Or reboot your windows.

**Comment by irpansetiana23** [comment]
> See that "listen tcp :6061: bind: Only one usage ...."? It seems like something is already bound to socket at port 6061. Shut down the server you started earlier before starting a new one. Or reboot your windows.

Sorry before if I ask a lot of questions ... so the report should not appear like that? so it's likely that port 6061 has been used by others or what?

thanks before

**Comment by or-else** [comment]
> 6061 has been used by others or what?

Yes.

**Comment by irpansetiana23** [comment]
> > 6061 has been used by others or what?
> 
> Yes.

so all I can do is just restart or is there something else I can do?
thanks sir

**Comment by or-else** [comment]
You can restart, you can kill the process listening on this port, you can change the port number.

**Comment by irpansetiana23** [comment]
> You can restart, you can kill the process listening on this port, you can change the port number.

thanks sir before , change the port number 6061 in server or in the chat code sir, and Is this port used by this chat application?

**Comment by or-else** [comment]
Look, this is basic system administration stuff. This has nothing to do with Tinode. 

You seem to be working for a large company. Please read documentation or have your employer pay someone to help you.

**Comment by irpansetiana23** [comment]
> Look, this is basic system administration stuff. This has nothing to do with Tinode.
> 
> You seem to be working for a large company. Please read documentation or have your employer pay someone to help you.

very sorry sir, I don't really understand about servers, and the people who are troubling this to me are also very confusing, so I can only consult here ... but after talking to you, I have become much more knowledgeable about this, thanks in advance ... I will try what do you suggest ... thanks again a lot

**Comment by irpansetiana23** [comment]
> Look, this is basic system administration stuff. This has nothing to do with Tinode.
> 
> You seem to be working for a large company. Please read documentation or have your employer pay someone to help you.

Sir sorry, one question again ....for error timeot 450 in frontend chat  like i share images in top is because listening tpc 6061 or not because this issue... ?

https://user-images.githubusercontent.com/16398308/78653564-83ada900-78ed-11ea-9e90-4e8c302065d1.png

Thanks thanks thanks alot sir

**Comment by or-else** [comment]
The server never responds with error 504:
https://github.com/tinode/chat/blob/master/server/datamodel.go

**Comment by irpansetiana23** [comment]
> The server never responds with error 504:
> https://github.com/tinode/chat/blob/master/server/datamodel.go

ok sir .....thanks for help sir
