### ISSUE TITLE
Rest user update public private info

### ISSUE THREAD

**Issue by jaynakus** [tinode/chat#412]
### Rest user update public private info
Whenever user changes his profile we need to be able to update existing chat user public and private data. So the chat user will have 

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Linux
  * Latest
  * rethink 
  
#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- latest

### Steps to reproduce
Create rest server, add user. Change user info, call {acc} API.

### Expected behaviour
One must be able to change public, and private attributes

### Actual behaviour
Nothing changes, malformed error

### Server-side log
replyUpdateUser: failed to update user malformed LabN0KxPu6U

### Client-side log
```
[15:27:08:832] out: {"acc":{"id":"79542","user":"usrZQchqAO9G1z","desc":{"public":{"fn":"Someone","n":{"surname":"Someone","given":"Someone"},"tel":[{"type":"MOBILE","uri":"tel:+996707123456"}]}}}} 
tinode.prod.js:973 
[15:27:08:971] in: {"ctrl":{"id":"79542","code":400,"text":"malformed","ts":"2020-04-06T15:26:48.718Z"}} 
```

**Comment by or-else** [comment]
You cannot use `{acc}` to update user parameters. You must communicate with the 'me' topic instead.

**Comment by jaynakus** [comment]
Oh, thanks that worked, documentation is a bit confusing.
