### ISSUE TITLE
I have a mysql8.0 server  but it doesn't work with the tinode

### ISSUE THREAD

**Issue by AlanLongYu** [tinode/chat#421]
First I typed the next command on windows 10  I have changed the tinode.conf  use_adapt:"mysql"
And modify the  "dsn": "root:xxxx@tcp(172.17.5.113:3307)/  (my  mysql8.0 server)  
D:\tinode-mysql.windows-amd64>tinode.exe -config=./tinode.conf

2020/04/15 20:02:07 Running as a standalone server.
2020/04/15 20:02:07 Failed to connect to DB: Error 1045: Access denied for user 'root'@'172.17.5.112' (using password: YES)

So I want to build the tinode application but I can't get the packages because the network error.

Can you give me some advice to download the packages? I want to run the server success for learning GOLANG, Thank you very much I'm a beginer about GOLANG

D:\www\chat\server>go get firebase.google.com/go/messaging

package firebase.google.com/go/messaging: unrecognized import path "firebase.google.com/go/messaging" (https fetch: Get https://firebase.google.com/go/messaging?go-get=1: dial tcp 216.58.199.14:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by or-else** [comment]
> Failed to connect to DB: Error 1045: Access denied for user 'root'@'172.17.5.112' (using password: YES)

This has nothing to do with Tinode. You probably misconfigured the DB. I would guess `root` is configured to connect from the localhost only.

> dial tcp 216.58.199.14:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time

Can you open https://firebase.google.com/go/messaging?go-get=1 from the browser on same host where you are building the server?

**Comment by AlanLongYu** [comment]
1、Thanks for your reply.  No. The reson is the -config=./tinode.conf doesn't work .  My localhost's ip is 112  but the mysql8.0 server's ip is 113 And I can connect it to the mysql server with sqlyog (a client about mysql).

2、I can't open the https://firebase.google.com/go/messaging?go-get=1 
sometime maybe I can open it . May who can give me a zip or tar  vendor packages about  all of the packages on github.

**Comment by or-else** [comment]
1. Once again: this has nothing to do with tinode. `Access denied for user` means network connection was established, but user `root` with the password specified by you has no permission to connect to your database. Most likely because it's configured to connect from the localhost only.

2. If you are on China then probably your government blocks you. Use https://github.com/firebase/firebase-admin-go or remove it altogether.

**Comment by AlanLongYu** [comment]
1、You are right.Thank you very much. I should have checked it.
The binary tinode.exe  -config=./tinode.conf can runs smoothly now.

tinode.exe -config=D:\tinode-mysql.windows-amd64\tinode.conf
2020/04/16 16:31:04 Server v0.16:D:\tinode-mysql.windows-amd64\tinode.exe:v0.16.5-rc2; pid 38696; 8 process(es)
2020/04/16 16:31:04 Using config from 'D:\tinode-mysql.windows-amd64\tinode.conf'
2020/04/16 16:31:04 stats: variables exposed at '/debug/vars'
2020/04/16 16:31:04 Running as a standalone server.
2020/04/16 16:31:04 DB adapter mysql
2020/04/16 16:31:04 Restricted tags: ['basic' 'email' 'tel']
2020/04/16 16:31:04 plugins: no active plugins found
2020/04/16 16:31:04 gRPC/1.28.0 server is registered at [:16060]
2020/04/16 16:31:04 Serving static content from 'D:\tinode-mysql.windows-amd64\static' at '/'
2020/04/16 16:31:04 API served from root URL path '/'
2020/04/16 16:31:04 Large media handling enabled fs
2020/04/16 16:31:04 Listening for client HTTP connections on [:6060]

2、I'll take your advice when I get familiar with the code. Thank you very much!

**Comment by AlanLongYu** [comment]
I'm a novice at the Go language, Sorry to trouble you.
