### ISSUE TITLE
[Ask About `MsgDelRange`]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#45]
Hello, Gene

I have question regarding `MsgDelRange`. Why it is having exclusive end rather than inclusive one?

Maybe there is some design consideration behind this?

Thanks

**Comment by or-else** [comment]
Hi Riandy,

No particular reason. I don't feel strongly either way. Do you think it should be inclusive-inclusive?

**Comment by riandyrn** [comment]
Hoo…, I see…

> Do you think it should be inclusive-inclusive?

Yeah, I think so. The reason is because it feels more natural when reading the sequence from the response (from human perspective).

Ok, thanks a lot, Gene 😄 👍

**Comment by or-else** [comment]
BTW, fetching messages is also inclusive-exclusive. Then it should be made consistent.

**Comment by or-else** [comment]
https://github.com/tinode/chat/pull/46

**Comment by riandyrn** [comment]
Hello, Gene

Sorry for the delay, it was midnight already on my timezone.

What I meant was like this: https://github.com/tinode/chat/pull/47

The reason is because in both get messages (whether get normal or deleted messages), it is clear that we state `"before"` in command. So it was clear that the we want to get messages with range like this: `since <= message_id < before`.

But when we fetch deleted messages, for example with following command:

```js
{  
    "get":{  
        "topic":"usrABCDEF",
        "what":"del",
        "del":{  
            "since": 1,
            "before": 4
        }
    }
}
```

We will retrieve success response like this:

```js
{
    "meta": {
        "topic": "usrABCDEF",
        "ts": "2017-12-08T06:05:06.775Z",
        "del": {
            "clear": 3,
            "delseq": [
                {
                    "low": 4,
                    "hi": 7,
                },
                {
                    "low": 9
                },
                {
                    "low": 15
                }
            ]
        }
    }
}
```

In the first object of `delseq`, it is not clear what is the meaning of `low` & `hi` (unlike `since` & `before` which have explicit meanings), so people tend to interpret it like this: 4 to 7 (`4 <= SeqId <= 7`). So the deleted messages on above response would be interpret as: `{4, 5, 6, 7, 9, 15}` not `{4, 5, 6, 9, 15}`.

**Comment by or-else** [comment]
Great, thanks! Merged.
