### ISSUE TITLE
len(availableAdapter)==0, but my tinode.conf uses mysql

### ISSUE THREAD

**Issue by CoolJie2001** [tinode/chat#453]
### Subject of the issue
Using Visual Studio Code Debug tinode server, tinode server reports that mysql adapter is not available in this binary

### Is this a bug report of a feature request?
- [x] Feature request

#### Server-side
  * Windows 10 Enterprise Edition
  * tinode server, `0.16.5`
  * MySQL 8.0.18 Community Server

### Steps to reproduce
I made it at tinode. conf:
"store_config": {
...
"use_adapter": "mysql",
"adapters": {
    "mysql": {
        "dsn": "root:password@tcp(localhost)/tinode?parseTime=true&collation=utf8mb4_unicode_ci",
        "database": "tinode"
}
...
}
}

### Actual behaviour
I'm using Visual Studio Code 1.45.0
The Debug main.go
The program will fail to execute at line 45 of store.go because availableAdapters[config.UseAdapter] return "Failed to connect to DB: store: mysql adapter is not available in this binary"

### Server-side log
 "Failed to connect to DB: store: mysql adapter is not available in this binary"

**Comment by or-else** [comment]
You did not specify `-tags mysql` when building the code. Please read the instructions:

https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source

**Comment by CoolJie2001** [comment]
So visual studio code can't use breakpoint debugging execution to learn tinode?

**Comment by or-else** [comment]
I'm not familiar with Visual Studio Code.
I do not see a connection between `-tags mysql` and breakpoints.
