### ISSUE TITLE
Users last seen not updated when connection lost

### ISSUE THREAD

**Issue by Googlom** [tinode/chat#455]
When user loses connection (kills app in task manager, internet disconnected, etc.) **last seen** not updated. Db adapters `UserUpdate()` method is receieving **uid = 0**

**Comment by or-else** [comment]
See https://github.com/tinode/chat/commit/187ac13142b3d9473253d722dfdbc71b4c717491

**Comment by Googlom** [comment]
Thanks! Didn't notice that
