### ISSUE TITLE
mongodb ssl support

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#464]
Feature request?

**Problem:**
Unable to connect to mongodb using enrypted connection.

**Use case:**
I have URI generated by MongoDB Atlas in following format:
`
mongodb://main-staging-shard-00-00.***.gcp.mongodb.net:27017,main-staging-shard-00-01.***.gcp.mongodb.net:27017,main-staging-shard-00-02.***.gcp.mongodb.net:27017/?ssl=true&authSource=admin&replicaSet=main-staging-shard-0
`

**Possible solution:**
Add possibility to pass SSL flag using config:
https://github.com/tinode/chat/blob/master/server/db/mongodb/adapter.go#L47-L56

**Version:**
docker pull tinode/tinode-mongodb:0.16.5

**Comment by or-else** [comment]
@Googlom could you please take a look at this? Thanks!

**Comment by or-else** [comment]
Thanks @Googlom!

**Comment by Googlom** [comment]
@afoninsky let me know if it worked for you.

**Comment by afoninsky** [comment]
Thank you. Will test as soon as docker images appears.

**Comment by or-else** [comment]
All `-rcX` images have this fix. Were you able to test it?

**Comment by afoninsky** [comment]
Sorry for the late response. Can't provide feedback currently as switched to another task -> let's decide that everything is ok. Will switch to current one in 1 week and will write if there is any issue :)

**Comment by afoninsky** [comment]
docker tinode/tinode-mongodb:0.16.7, follwing errors:
```
   "mongodb": {
    "database": "messenger",
    "addresses": [
     "main-staging-shard-00-00.***.gcp.mongodb.net:27017",
     "main-staging-shard-00-01.***.gcp.mongodb.net:27017",
     "main-staging-shard-00-02.***.gcp.mongodb.net:27017"
    ],
    "authSource": "admin",
    "username": "messenger-app",
    "password": "***",
    "replica_set": "main-staging-shard-0",
    "tls": true
   }
```
Failed to init DB adapter: adapter mongodb failed to parse config.Addresses

```
   "mongodb": {
    "database": "messenger",
    "addresses": "main-staging-shard-00-00.***.gcp.mongodb.net:27017",
    "authSource": "admin",
    "username": "messenger-app",
    "password": "***",
    "replica_set": "main-staging-shard-0",
    "tls": true
   }
```

Failed to init DB adapter: connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-256": (BadValue) Unsupported mechanism SCRAM-SHA-256

**Comment by or-else** [comment]
Judging from this https://stackoverflow.com/a/32998117/6692196 you have an older (below 3) version of Mongo DB.

**Comment by or-else** [comment]
@afoninsky, @Googlom I've added a config option for specifying the auth mechanism. Please take a look: https://github.com/tinode/chat/pull/536

**Comment by afoninsky** [comment]
Thanks, will check versions and auth mechanisms. And what about first error -> how should array of hosts look in json config?

**Comment by or-else** [comment]
> what about the first error

What is the first error?

**Comment by afoninsky** [comment]
> Failed to init DB adapter: adapter mongodb failed to parse config.Addresses
I'm sure I've passed following array:
```
    "addresses": [
     "main-staging-shard-00-00.***.gcp.mongodb.net:27017",
     "main-staging-shard-00-01.***.gcp.mongodb.net:27017",
     "main-staging-shard-00-02.***.gcp.mongodb.net:27017"
    ],
```
Should it be another format?

**Comment by or-else** [comment]
The format is right, I found the bug. Give me 10 min.

**Comment by or-else** [comment]
Fixed
