### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by yte0130** [tinode/chat#467]
bug reporting
1. When our team used the iOS version of Tinode, some iPhones were unable to show the user's connection.
2. When looking for a password, the password was changed without any indication when pressing the reset button. I hope there is a notification when I press the reset button.
3. send typing notifications function did not work properly on all of our iPhones.

**Comment by or-else** [comment]
Unfortunately your bug report is not informative enough. We can't really do much with this information.
Please fill out the bug report form here:
https://github.com/tinode/ios/issues/new?assignees=&labels=&template=bug_report.md&title=
