### ISSUE TITLE
Make server private

### ISSUE THREAD

**Issue by saslv** [tinode/chat#471]
### Subject of the issue
Is there a possibility to restrict public registration and allow login only by REST?

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform any

#### Client-side
Any

**Comment by or-else** [comment]
Yes.

Please use forum for questions and discussions:
https://groups.google.com/d/forum/tinode
