### ISSUE TITLE
can not load more messages

### ISSUE THREAD

**Issue by lamncn** [tinode/chat#474]
# If you are not reporting a bug or requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.

### Subject of the issue
Can not load more messages

### Is this a bug report of a feature request?
- [x ] Bug report
- [ ] Feature request

#### Server-side
- [x ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend

#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ x] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
I can not load more messages from android app, only 24 latest messages. web app working fine.

**Comment by or-else** [comment]
Confirmed. Thanks!

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/tindroid/commit/8ac454d7b189fc48553827fafba1ccddbab8a26c

**Comment by mediaboxhd** [comment]
iOS has the same problem

**Comment by lamncn** [comment]
pls check iOS app, has the same problem.  thanks

**Comment by aforge** [comment]
Yes, indeed. I'm looking into the iOS issue now.

**Comment by aforge** [comment]
Done: https://github.com/tinode/ios/commit/24490d169af24d0313912d335e9000384dbdec28

**Comment by or-else** [comment]
Hi @lamncn ,

Do you have any questions regarding the fixes or should I close the issue?

**Comment by or-else** [comment]
It's been fully released. Closing.
