### ISSUE TITLE
demo for Vue？

### ISSUE THREAD

**Issue by wYuJian** [tinode/chat#481]
demo for Vue？

**Comment by or-else** [comment]
Do you want to contribute it? Or are you asking if anyone would do it for you?

**Comment by wYuJian** [comment]
const nim = state.nim
const topic = nim.getTopic(obj.sessionId);
topic.getMessagesPage(config.localMsglimit).catch((err) => {
        console.log(err.message)
});
Why can't I get the server's chat history？

**Comment by wYuJian** [comment]
Novices cannot contribute. Want to ask someone can write one.

**Comment by or-else** [comment]
Regarding Vue, we are not going to do it. If you or anyone else wants to contribute then great.

Regarding your code snippet. It does not look like our SDK code. Please ask help from the people who wrote it.

If you have further questions please post to the https://groups.google.com/d/forum/tinode
