### ISSUE TITLE
QUESTION:  why doesn't return query result directly in websocket?

### ISSUE THREAD

**Issue by mojocn** [tinode/chat#483]
websocket-msg
```json

{"set":{"id":"112418","topic":"fnd","desc":{"public":"email:some@one.com"}}} //send1
{"ctrl":{"id":"112418","topic":"fnd","code":200,"text":"ok","ts":"2020-07-01T11:51:53.234Z"}} //response
{"get":{"id":"112419","topic":"fnd","what":"sub"}} //send2
{"meta":{"id":"68563","topic":"fnd","ts":"2020-07-01T14:04:52.921Z","sub":[{"updated":"2020-06-29T03:24:10.537Z","acs":{"mode":"JRWPAS"},"public":{"fn":"asdfasdf"},"private":["email:neochau@gmail.com"],"user":"usrR_BXgHQmiz4"}]}}   //the search result
--


//return the search result
```

you need get the result in the next msg request

**Comment by or-else** [comment]
I don't understand your question. Please elaborate. Thanks

**Comment by mojocn** [comment]
1. JS sends search query by sending `{"set":{"id":"112418","topic":"fnd","desc":{"public":"email:some@one.com"}}}`
2. Server responses  a msg of  roger `{"ctrl":{"id":"112418","topic":"fnd","code":200,"text":"ok","ts":"2020-07-01T11:51:53.234Z"}}`
3. JS sends `{"get":{"id":"112419","topic":"fnd","what":"sub"}}` to notify the server sending back the query result
4. Server sends real query result `{"meta":{"id":"68563","topic":"fnd","ts":"2020-07-01T14:04:52.921Z","sub":[{"updated":"2020-06-29T03:24:10.537Z","acs":{"mode":"JRWPAS"},"public":{"fn":"asdfasdf"},"private":["email:neochau@gmail.com"],"user":"usrR_BXgHQmiz4"}]}}`

I have read the golang server code,
the 2nd and the 3rd  procedure seems be redudant and make the code hard to understand.
> Is there any deep reason making 2nd and 3rd procedures Indispensable?

**Comment by mojocn** [comment]
in the server codebase:
How does `hub`   `topic`  and `subscribe`  struct work together ? parameter pass through channels makes hard to understand

**Comment by or-else** [comment]
Regarding two requests to find contacts instead of one: this is the design decision which keeps API simple. All commands do the same thing in all topics: `set` sets, `get` gets.

Regarding _parameter pass through channels makes it hard to understand._: channels make it easy to communicate between go routines without locks. It's one of the main features of Go which makes it so popular.
