### ISSUE TITLE
Leave might not be atomic

### ISSUE THREAD

**Issue by arseniybanayev** [tinode/chat#485]
Consider two users `usrA` and `usrB` with the following sequence of events:

1. A: `{sub topic=new}` (suppose topic is `grpX`)
2. B: `{sub topic=grpX}`
3. A: `{leave topic=grpX unsub=true}  # 403 permission denied`
4. A: `{set topic=grpX sub={user=usrB mode=JRWPASDO}}`
5. B: `{set topic=grpX sub={mode=JRWPASDO}}`
6. A: `{leave topic=grpX unsub=true}  # 409 must attach first`

If you omit step 3, then step 6 succeeds, which suggests that the server processes `{leave topic=.. unsub=true}` in two steps and not atomically.

EDIT: I originally had `user=usrA` in step 4, which was a typo.

**Comment by or-else** [comment]
1. Please show the session log when you execute this sequence of commands using `tn-cli`.
2. Show the server-side log of this sequence.

**Comment by arseniybanayev** [comment]
I'm not familiar with using `tn-cli` but does non-atomicity sound plausible in `{leave topic=.. unsub=true}`?

**Comment by or-else** [comment]
It's not difficult: https://github.com/tinode/chat/tree/master/tn-cli

All commands are asynchronous. It's possible that you did not wait for completion of the previous command before issuing the next one. 

Anyway, please show the logs.

**Comment by or-else** [comment]
Any update on this?
