### ISSUE TITLE
[Ask About Incomplete Implementation of Device Functionalities]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#49]
Hello, Gene

I have question regarding device functionalities in Tinode. So I notice that both `store.Devices.Delete()` & `store.Devices.GetAll()` are currently not called anywhere on the main.

So where should we call these functions by design?

Thanks

**Comment by or-else** [comment]
Hi Riandy,

They are used by the FCM push. Take a look here: https://github.com/tinode/chat/blob/master/push_fcm/push_fcm.go
