### ISSUE TITLE
Cyber crop

### ISSUE THREAD

**Issue by Google2020update** [tinode/chat#492]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
Describe your issue here.

#### Server-side
- [x] web.tinode.co, api.tinode.co
- [x] sandbox.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of Tinode server, e.g. `0.15.2-rc3`
  * database backend
  * cluster or standalone

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [x] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [x] Tinodios: iOS app
  * iOS version
  * Simulator or hardware, if hardware describe it.
- [x] tn-cli
  * Python version
- [x] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`
- [x] Your own client. Describe it:
  * Transport (gRPC, websocket, long polling)
  * Programming language.
  * gRPC version, if applicable.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
Please do not spam
