### ISSUE TITLE
Question about User Id 

### ISSUE THREAD

**Issue by wmshek1992** [tinode/chat#500]
Hi, 

In client side, users are identified by string "usrXXXXXXX". 
And Tinode DB are not storing this string, instead it stores a bigint, e.g. 736793179575029760.

So if I have the string, how do I convert it into the bigint that refers to the exact record in table tinode.users?

**Comment by or-else** [comment]
Please use https://groups.google.com/d/forum/tinode to ask questions.

See here:
https://github.com/tinode/chat/blob/11d514b58a1b5d7a3bbc67db55fa088394c73e7c/server/store/store.go#L194
