### ISSUE TITLE
Concurrent sorting

### ISSUE THREAD

**Issue by jfcg** [tinode/chat#502]
__Proposal:__
Replacing standard library's sort with a concurrent sorting library like [sorty](https://github.com/jfcg/sorty).
Note: I am the author of sorty.

__Current behavior:__
standard sort is not concurrent and runs in a single goroutine. This is very slow.
Also `sort.Interface` is slower than sorty's `lesswap()` as a way to access generic collections.

__Desired behavior:__
As an instant messaging server, chat can benefit a lot from concurrent sorting (with sorty or one of alternative libraries.)

__Alternatives considered:__
See the benchmarks in sorty readme.

__Use case:__
I have inspected chat code: standard sort is heavily used. sorty can cover all of it except calls to Stable().

**Comment by or-else** [comment]
Would you like to send a pull request with benchmarks demonstrating the advantage of you library?

**Comment by jfcg** [comment]
Hi,
I dont have experience with chat codebase (as well as extra time to create a PR), so I dont have a clear idea on how to benchmark chat "end-to-end". But:
- `sort.Sort()` and `sort.Slice()` calls are very trivial to convert to `lesswap()`
- primitive slices have ready-to-use functions.

I have benchmarked sorty extensively as listed in the readme, so on the server side I am guessing you should see noticable improvements.
Cheers :)

**Comment by or-else** [comment]
I don't see it as a priority and given your lack of interest in implementing it I'll pass. Thanks for the suggestion.
