### ISSUE TITLE
userData.online incremented multiple times for the same session

### ISSUE THREAD

**Issue by AVVS** [tinode/chat#510]
https://github.com/tinode/chat/blob/master/server/topic.go#L1317

Subj, to reproduce:

1. create new group topic
2. subscribe to group topic with acs wanted=JRWPAS (as an example) - online equals 1
3. perform set.sub request { mode='JRPAS' } - changing wanted - online equals 2
4. perform {leave} - {pres} off wont come as userData.online equals 1

noticed when performing the said flow. to fix it you may want to return bool in terms of whether this is a new or old session from t.addSession and skip incrementing based don this

**Comment by or-else** [comment]
Is this a standalone server or a cluster?

**Comment by AVVS** [comment]
Standalone

**Comment by or-else** [comment]
Confirmed, it's a bug.

**Comment by or-else** [comment]
Fixed in devel

**Comment by or-else** [comment]
This was released in 0.16.8-beta1. Closing.
