### ISSUE TITLE
[github] Confusing usage of tags

### ISSUE THREAD

**Issue by mar-v-in** [tinode/chat#519]
In your repository's about section you added the topics "whatsapp", "telegram" and "xmpp", yet the project has nothing to do with any of those, is not compatible with them or anything, except that it's just another chat system. I came here only by accident because I was searching for XMPP related projects, which this project clearly isn't. Please refrain from advertising with unrelated topics.

Thank you.

**Comment by or-else** [comment]
Thanks for the feedback.

**Comment by licaon-kter** [comment]
But no fix?

**Comment by or-else** [comment]
No fix is needed. I understand you disagree with the way we classify our project and I disagree with your assessment.
