### ISSUE TITLE
Manually Install gorethink.v3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by bobey6** [tinode/chat#52]
Hello,

While following the install guide, I had to manually install an additional package. I'm not sure if this is specific to my install, but I figured you might want to know so you can update your instructions. 

```
root@instance-1:~# go get github.com/tinode/chat/server && go install -tags rethinkdb github.com/tinode/chat/server
go/src/github.com/tinode/chat/server/db/rethinkdb/adapter.go:16:2: cannot find package "gopkg.in/gorethink/gorethink.v3" in any of:
        /usr/local/go/src/gopkg.in/gorethink/gorethink.v3 (from $GOROOT)
        /root/go/src/gopkg.in/gorethink/gorethink.v3 (from $GOPATH)
```

`go get gopkg.in/gorethink/gorethink.v3` fixes the error

**Comment by or-else** [comment]
Thank you for pointing this out. It's a mistake in the INSTALL.md. The correct line is 
```
go get -tags rethinkdb github.com/tinode/chat/server && go install -tags rethinkdb github.com/tinode/chat/server
```
`go get` also needs the `-tags rethinkdb`. I've updated the docs. Thanks!
