### ISSUE TITLE
Install.md - Updated Firebase URL for Cloud Messaging API Key

### ISSUE THREAD

**Issue by bobey6** [tinode/chat#53]
I found my Cloud Messaging API key at the following URL:

https://console.firebase.google.com/u/0/project/*project*/settings/cloudmessaging/

The current URL in the install document loads a blank firebase console.

**Comment by or-else** [comment]
Thanks for the report. The complexity here is that the URL you provided is formatted for a case of multiple authenticated accounts. The one you gave references "user 0": `/u/0/`. If the user is authenticated with a single account the `/u/0/` part is usually missing. It could also be `/u/1/` or `/u/2/` or any other number.

I don't think there is no way to provide a URL which works for everybody.

**Comment by or-else** [comment]
I'm closing the issue. Feel free to reopen if you find a solution.
