### ISSUE TITLE
How about the performance of tinode? Will we do some benchmarking

### ISSUE THREAD

**Issue by warfrogsdf** [tinode/chat#532]

**Comment by aforge** [comment]
This is currently being worked on.

@warfrogsdf 
Out of curiosity: are you interested in anything specific?

**Comment by warfrogsdf** [comment]
@aforge Because instant message system technology selection

**Comment by hhy5861** [comment]
> @aforge Because instant message system technology selection

I found that the cluster mode uses very high memory. The Session recycling mechanism also has some problems.
![12](https://user-images.githubusercontent.com/8274977/91554401-9e96bd80-e961-11ea-9a94-4745167c3b00.png)

**Comment by or-else** [comment]
A lot of optimizations were implemented since this issue was opened. Closing.
