### ISSUE TITLE
A very strange deadlock

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#534]
tinode version: 0.16.6

1. A large number of users subscribe to me will cause a deadlock. There is no response to the ctrl event.
2. The case has not been found yet.
3. This phenomenon can be reproduced by pressure test. Stand-alone also appeared.

**Comment by aforge** [comment]
https://github.com/tinode/chat/commit/8f7a1e2bf1536be8a44cecbd1cf982663183f3cb should help this.
I subscribed 5000 sessions to a user's me within a short period of time - and saw no stalling.

@hhy5861 
Can you try it and see if it reproduces the problem for you still?

**Comment by aforge** [comment]
Ah, also make sure to patch this as well when you run your load test: https://github.com/tinode/chat/commit/a8ec935922f412f9df8ffe4524ec3041e71ab454

**Comment by hhy5861** [comment]
> [8f7a1e2](https://github.com/tinode/chat/commit/8f7a1e2bf1536be8a44cecbd1cf982663183f3cb) should help this.
> I subscribed 5000 sessions to a user's me within a short period of time - and saw no stalling.
> 
> @hhy5861
> Can you try it and see if it reproduces the problem for you still?

My preliminary judgment should be that this case is blocked, which will cause all cases to fail.
[https://github.com/tinode/chat/blob/7bed3c0bd89469cc3cdafd39775697a79383f936/server/hub.go#L210](url)

**Comment by hhy5861** [comment]
@aforge This problem is very serious and will cause all nodes in the cluster to be paralyzed.

**Comment by aforge** [comment]
I still can't repro in `devel`.

Mind sharing your loadtest params in the single-instance setup please?
1. Are you subscribing to a single user's me or multiple? If latter, is the load distributed evenly across users?
2. What is your request rate?
3. How long does your loadtest run?
4. At what what number of sessions do you start noticing a significant slowdown in the server responses?
5. At what number of sessions does it stall completely?

Also, can you dump your the stacks please?
`kill -SIGABRT <pid>` should do the trick when you server becomes non-responsive.

**Comment by aforge** [comment]
Also, when you say deadlock, do you mean a threading related issue (a thread is waiting for a resource taken by another thread that would never release it)? Or do you mean the server becomes unresponsive and unable to make progress completely?

**Comment by hhy5861** [comment]
![image](https://user-images.githubusercontent.com/8274977/92498732-91b17e00-f22d-11ea-95dd-8ecef130085c.png)

@aforge @or-else 

Found that the memory usage is still high.

**Comment by aforge** [comment]
Assuming your heap profile is for node 0, your average topic appears to account for:
10584MB / 24119 = 0.439M

Can you check the size distribution of avatars in your database please?

And your average session is:
4496.37MB / 21181 = 0.212M

Can you post the profile picture with the full allocation call stack please?

**Comment by hhy5861** [comment]
> Assuming your heap profile is for node 0, your average topic appears to account for:
> 10584MB / 24119 = 0.439M
> 
> Can you check the size distribution of avatars in your database please?
> 
> And your average session is:
> 4496.37MB / 21181 = 0.212M
> 
> Can you post the profile picture with the full allocation call stack please?

I removed the avatar of the user information

**Comment by hhy5861** [comment]
> > Assuming your heap profile is for node 0, your average topic appears to account for:
> > 10584MB / 24119 = 0.439M
> > Can you check the size distribution of avatars in your database please?
> > And your average session is:
> > 4496.37MB / 21181 = 0.212M
> > Can you post the profile picture with the full allocation call stack please?
> 
> I removed the avatar of the user information

![image](https://user-images.githubusercontent.com/8274977/92845433-8fac1280-f419-11ea-8ca1-7844cfd6163b.png)
What is the cause of unbalanced load?

**Comment by aforge** [comment]
Yes, I think I know what the problem is.
I've posted https://github.com/tinode/chat/pull/542. Will likely need an even better hash function in the future.

**Comment by hhy5861** [comment]
> Yes, I think I know what the problem is.
> I've posted #542. Will likely need an even better hash function in the future.

I updated what you modified to solve the problem, and now the load is fairly balanced.

**Comment by or-else** [comment]
I believe this can be closed now.
