### ISSUE TITLE
Hold up Session cleanup until all requests completed

### ISSUE THREAD

**Issue by aforge** [tinode/chat#535]
Currently, a session quits whenever it receives a shutdown request.
When there are requests from this session in flight when the session is shutting down, these requests will continue to execute and may modify the server state breaking a broad range of invariants leading to memory leaks and other types of unexpected behavior.
Keep track of requests in flight, and make sure they complete before the session proceeds to the cleanup phase.

**Comment by or-else** [comment]
> breaking a broad range of invariants

Can you give an example? It really should not be a problem.

**Comment by aforge** [comment]
One invariant example is:
`Topic.sessions` will contain references to all *live* sessions subscribed to it.

Here's a scenario of breakage (in chronological order):
0. A join request arrives from the client.
1. Session passes it to the hub for further routing (it's now asynchronous).
2. The client terminates the session (the read/write loops are no longer running). The session cleans up and terminates all its subscriptions (but not the topic that the client intended to subscribe to in (0) ).
3. The join request gets picked up from the queue by the hub and routed to the topic.
4. The topic subscribes the session to itself (and stores a reference to the already dead session).

There's no way now for the topic in (4) to terminate because of this dangling session (the session object cannot be GC'd either).

**Comment by or-else** [comment]
I see. Then maybe it would be useful to have a flag that a subscription is in flight. The session would not terminate the write loop until the answer is received. It's a bit of work but should solve the problem.

**Comment by or-else** [comment]
I don't think we need to track any other message but {sub}.

**Comment by or-else** [comment]
BTW, I think buffered `join` is not the cause of this problem. This scenario could have happened with unbuffered `join` just as well, except less likely. It's the early termination of the session which causes it.
