### ISSUE TITLE
Basic authentication query was misdetected as phone number when parsing search query.

### ISSUE THREAD

**Issue by aihturie** [tinode/chat#543]
https://github.com/tinode/chat/blob/master/server/utils.go#L434
To reproduce:

1. Enable "tel" validation in configuration file
2. Create a new user with basic authentication abctest10
3. Find the new user in Fnd topic with query "abctest10"

There is no result because the query was misdetected as phone number "tel:+110"

**Comment by or-else** [comment]
Confirmed.

**Comment by or-else** [comment]
The bug is in https://github.com/nyaruka/phonenumbers
I filed an issue there: https://github.com/nyaruka/phonenumbers/issues/64. 
If it's not fixed there in a couple of days, I'll switch to another library.

**Comment by or-else** [comment]
It looks like all *phonenumber libraries are broken by design: Google made a mistake and everybody copied it. I've added a workaround.

**Comment by or-else** [comment]
Released to production.
