### ISSUE TITLE
Message loss problem

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#548]
https://github.com/tinode/chat/blob/7bed3c0bd89469cc3cdafd39775697a79383f936/server/hub.go#L231-L237

1. I found a problem with discarding {data} data points. When the data is proxyed to another node, the message will be discarded if the session is offline or cannot get the subscription.

2. I think that when this happens, the message should be stored persistently and handled as an offline message.

**Comment by or-else** [comment]
Could you please show steps to reproduce. Thanks.

**Comment by hhy5861** [comment]
> Could you please show steps to reproduce. Thanks.

![image](https://user-images.githubusercontent.com/8274977/93985434-a8bca800-fdb7-11ea-9ed2-a9bce53ebd8f.png)

If isProxy is true, then the message is proxied to topicMaster. So the message is sent to hub.route. When the message arrives on the route, no case will be hit. Then just discard it.

![image](https://user-images.githubusercontent.com/8274977/93985891-3ac4b080-fdb8-11ea-823a-89e8bae91577.png)

**Comment by or-else** [comment]
> When the message arrives on the route, no case will be hit.

That is incorrect. The first case `h.topicGet` is usually satisfied. You can see it by sending messages in web.tinode.co and sandbox.tinode.co. These are cluster setups. Messaging works.

If you believe that there is a problem, please help us identify it by providing steps to reproduce. Thank you.

**Comment by hhy5861** [comment]
> > When the message arrives on the route, no case will be hit.
> 
> That is incorrect. The first case `h.topicGet` is usually satisfied. You can see it by sending messages in web.tinode.co and sandbox.tinode.co. These are cluster setups. Messaging works.
> 
> If you believe that there is a problem, please help us identify it by providing steps to reproduce. Thank you.

From the code analysis and printed logs, some {data} did not hit `h.getTopic` when the route was reached.

This is difficult to submit a case to. My current solution is to add a channel to handle this `{data} `message as an offline message.

**Comment by or-else** [comment]
OK, I think I understand now. 16.7 has a bug. If a node is quickly restarted (for example after a crash), the connections are not cleaned up. This leads to the scenario you have described. The bug was fixed in 16.8-beta1. Please check it out.

**Comment by or-else** [comment]
I believe this is fixed now.
