### ISSUE TITLE
Cluster communication is upgraded to grpc

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#550]
Have you considered upgrading cluster communication to grpc, so that network overhead and performance should be improved a lot.

**Comment by aforge** [comment]
@hhy5861 where specifically do you see overhead from `net/rpc` (I'm assuming you are talking about the intra-cluster communication)?

**Comment by hhy5861** [comment]
@aforge @or-else 

Is there any way for me to send messages to the specified topic without logging in or subscribing?

**Comment by or-else** [comment]
There are no such options. 

1. The server needs to know if you have a right to send messages. Thus it requires authentication. It's not too hard to bypass this with grpc though.
2. Sending a message to topic without subscribing can be done but only if the topic is already in memory. If it's not loaded, the subscribe is needed to load and initialize it.

**Comment by or-else** [comment]
There is no update on this in a while. Closing.
