### ISSUE TITLE
invalid apikey signature

### ISSUE THREAD

**Issue by mzch** [tinode/chat#557]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
When register a new user, Tinode reported `invalid apikey signature` and `ws: Missing, invalid or expired API key`, so registration failed.

I confired to set valid keys generated by `keygen`, HMAC salt to `tinode.conf` and API key v1 seq1 to `src/config.js` 

#### Server-side
- [ ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [x] Your own setup:
  * platform (Linux)
  * version of Tinode server `v0.16.8`
  * database backend `mongodb`
  * cluster or standalone `standalone`

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] Tinodios: iOS app
  * iOS version
  * Simulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`
- [ ] Your own client. Describe it:
  * Transport (gRPC, websocket, long polling)
  * Programming language.
  * gRPC version, if applicable.

### Steps to reproduce
Register a new user.

### Expected behaviour
Successful registration.

### Actual behaviour
Connection failed.

### Server-side log
```
Oct 20 01:17:54 de tinode[31261]: 2020/10/20 01:17:54 invalid apikey signature
Oct 20 01:17:54 de tinode[31261]: 2020/10/20 01:17:54 ws: Missing, invalid or expired API key
Oct 20 01:19:41 de tinode[31261]: 2020/10/20 01:19:41 invalid apikey signature
Oct 20 01:19:41 de tinode[31261]: 2020/10/20 01:19:41 ws: Missing, invalid or expired API key
```

### Client-side log
<img width="1490" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/96521864-330c0500-12ad-11eb-8a0e-cfebd43915fe.png">

**Comment by or-else** [comment]
I tested and it worked just fine:

```
$ keygen/keygen 
API key v1 seq1 [ordinary]: AQAAAAABAABY2OxBLo7TsUhpMIJpRuFu
Used HMAC salt: HCDECu5SLVzLuoZV8XQVFK/5QkVM1eCx6LV6Jp8A7Ko=
```

Config:
```
  "api_key_salt": "HCDECu5SLVzLuoZV8XQVFK/5QkVM1eCx6LV6Jp8A7Ko=",
```

Client logs:
```
[00:44:56.321] Connecting to:  ws://localhost:6060/v0/channels?apikey=AQAAAAABAABY2OxBLo7TsUhpMIJpRuFu
tinode.js:1204 [00:44:56.329] out: {"hi":{"id":"113695","ver":"0.16.9-beta1","ua":"TinodeWeb/0.16.9-beta1 (Chrome/85.0; MacIntel); tinodejs/0.16.9-beta1","lang":"en-US"}} 
tinode.js:1204 [00:44:56.336] in: {"ctrl":{"id":"113695","params":{"build":"rethinkdb:undef","maxFileUploadSize":8388608,"maxMessageSize":262144,"maxSubscriberCount":32,"maxTagCount":16,"maxTagLength":96,"minTagLength":2,"ver":"0.16"},"code":201,"text":"created","ts":"2020-10-20T00:44:56.333Z"}} 
```

Did you restart the server after changing the config?

**Comment by mzch** [comment]
Hi, I created another new key again, it works. Thanks!
