### ISSUE TITLE
[16.7, 16.8] Subscription, leave and subscribe again

### ISSUE THREAD

**Issue by tim4dev** [tinode/chat#563]
### Subject of the issue
When subscribing to a group, no messages are visible. The server is sending an invalid "meta" message.

#### Server-side

0.16 mysql:v0.16.8-rc2 (sandbox.tinode.co)

and this too : 0.16 mongodb:v0.16.7

#### Client-side

- TinodeWeb/tinodejs: TinodeWeb/0.16.8-beta1 (tinodejs/0.16.8-beta1)
- Chrome v.86, Opera v.72.

### Steps to reproduce

1. [Bob] Login to sandbox.tinode.co like Bob. Check “Stay logged in”.

2. [Bob] Click “Start New Chat” -> “New group”. Enter topic name, for example “test 111”, and “Create”.  A group with <topic_id> will be created here.

3. [Bob] Send a message to a new chat.

4. [Alice] Login like Alice (in another browser). Check “Stay logged in”.

5. [Alice] “Start New Chat” -> “BY ID” -> enter <topic_id>. Alice sees the group topic “test 111”, sees the counter of new messages. But does not see the conversation. Solution to the problem: press the F5 button (page reload).

6. [Alice] “Info” -> “LEAVE CONVERSATION”. And repeat Alice's steps to subscribe to the group again.

7. [Alice] still does not see messages.

### Actual behaviour

If we use an Android client, then at step 7 we will see in the logcat that the following "meta" message is received from the server:

```
"meta"... "deleted":"2020-11-02T05:32:13.523Z", "topic":"grpG9zRGEKLkj0" …
```

This is most likely why messages are not shown.

### Expected behaviour

In order for everything to work correctly from the very beginning, the server must send such a "meta" message:

```
"meta"... "touched": "2020-11-02T06:22:57.204Z", "topic": "grpG9zRGEKLkj0"...
```

**Comment by or-else** [comment]
I cannot reproduce `"meta"... "deleted"`, but I can reproduce missing messages on the first subscription: it's a bug in the webapp.

**Comment by or-else** [comment]
The reproducible issue is fixed: https://github.com/tinode/webapp/commit/5d53899f8933fa8b1a03ff56d2a1251ca5801fea
