### ISSUE TITLE
Tinode allows to delete accounts from clients even if rest authenticator is used

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#565]
**If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Is your feature request related to a problem? Please describe.**
This feature request is related to a problem. It´s possible to delete user account from Tinode´s webapp, Android, iOS app even if rest authenticator is used. Of course, I will remove the option to delete account from all clients but it will not remove this function from Tinode. User can delete the account from Tinode and when tries to login again, server returns error because the authentication server returns Tinode´s user id saved before but in Tinode this user does not exist anymore. 

**Describe the solution you'd like**
In case of rest authentication only root user should be allowed to delete user accounts. Option for users to delete their accounts from clients should be not supported.

**Comment by or-else** [comment]
This is good point. I'll fix it.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/9d0863c3780f06ba1928d2ef4105adffbdb874b4
