### ISSUE TITLE
delseq in mongodb build does not work correctly

### ISSUE THREAD

**Issue by sbabushkin** [tinode/chat#566]
Hello guys, i m using latest (mongodb:v0.16.7) docker image for my server

when i m trying to remove massage via api:

{
      del: {
        topic,
        what: 'msg',
        delseq: [
          {
            low: seqId,
          }
        ],
        hard: true,
      },
    }

It deletes all messages after seqId instaed of only seqid.

I tried mysql docker image and it works fine.

**Comment by or-else** [comment]
The latest is 0.16.8. Could you please confirm that it's reproducible in the latest. Thanks.

**Comment by sbabushkin** [comment]
Yes, same behavior in the 0.16.8
Even if i try { low: seqId, hi: seqId } and { low: seqId, hi: seqId+1 }

As far as i understood all the attempts are logged into "dellog" collection. So the are always records without "hi" by some reason

**Comment by or-else** [comment]
Yes, I can reproduce.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/3528357fc7bca8de83f4848f199047c7d0f746c1

**Comment by or-else** [comment]
Wrong commit. Here is the right one: https://github.com/tinode/chat/commit/975a510264e14362257ece9b2320f5038226b5fa

**Comment by sbabushkin** [comment]
Thank you, can you please tell when new docker image will be available here https://hub.docker.com/r/tinode/tinode-mongodb/tags?

**Comment by or-else** [comment]
Released
