### ISSUE TITLE
Ghost users with rest authenticator if there is no response to link endpoint

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#567]
I just noticed the following problem with rest authenticator.

When user logs in the first time, the authentication server returns response as described here: [Sample response when the account needs to be created by Tinode](https://github.com/tinode/chat/tree/master/server/auth/rest#sample-response-when-the-account-needs-to-be-created-by-tinode)

`{"rec":{"authlvl":"auth","lifetime":5000,"features":"1"},"newacc":{"state":"susp","auth":"JRWP","anon":"N","public":{"fn":"names","photo":{"type":"png","data":"photo_data"}}}}`

Then Tinode sends another request - `link`. If for some reason (network problem, server down etc) the authentication server does not return anything, the user created in Tinode hungs there forever. Next time when this user logs in again, Tinode will create a new account for the same user and try to send `link` request again but previous account will stay in Tinode forever.

I checked the database and user accounts that have not received any response to `link `request have status "0", it means - ok and not suspended as should be, despite the fact that the authentication server returns `"state":"susp"` to the `auth` request when user logs in the first time. Even if returning `"state":"suspended"` new users have status "0".

I don´t know if this is a typo in the documentation that says to return
`"state": "suspended",`
with GRPC it does not work. Only works
`"state": "susp",`

**Possible solutions.**

1) Tinode immediately deletes the created account if not receive response to the link request. If not, next time when user logs in , he will get an absulutely new account because the authentication server will have no idea that 1 account already exists in Tinode.
2) User account in Tinode should know that there were no response to `link` request and to send this request again after some time.

**Comment by or-else** [comment]
Yes, indeed it's a problem. I'll look into it but not immediately because it's not critical.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/f75c84ee31683a66db89c909fec4a33f524413f9
