### ISSUE TITLE
Tinode can’t send a validation mail.

### ISSUE THREAD

**Issue by mzch** [tinode/chat#570]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
Tinode can't send a validation mail or a password reset mail. Perhaps it's caused because Tinode doesn't use `Hello` func in `net/smtp` module.

#### Server-side
- [ ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [x] Your own setup:
  * Debian Linux 10.6
  * 0.16.8
  * MariaDB
  * standalone

### Steps to reproduce
1. Put mail server settings into `tinode.conf`
1. Try sign up
1. Tinode failed to send a validation mail

### Expected behaviour
Send a validation mail normally.

### Actual behaviour
Failed to send a mail.

### Server-side log
```
SMTP error mzch@example.com 450 4.7.1 <localhost>: Helo command rejected: Host not found
```

**Comment by or-else** [comment]
This is your config problem. Please do not misuse bug reporting to ask questions.
