### ISSUE TITLE
Add server name for HELO/EHLO command

### ISSUE THREAD

**Issue by mzch** [tinode/chat#572]
**If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Is your feature request related to a problem? Please describe.**
Add server name in `tinode.conf` for HELO/EHLO smtp command.

**Describe the solution you'd like**
see #573 

**Describe alternatives you've considered**
None.

**Comment by or-else** [comment]
This is done. Closing.
