### ISSUE TITLE
Please add user's IP address to the "auth" request

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#576]
**Is your feature request related to a problem? Please describe.**
All the logins are anonymous. If somebody breaks into another user's account, it will not be possible to detect it because the only available information will be user agent that is useless. The attacker will be able to read all the messages, send messages, and there will be no way to investigate the issue.  I am using rest-auth and even database's `devices` table is empty. Tinode should record not only the user agent but also user's IP address when he/she logs in.

**Describe the solution you'd like**
As I am using rest auth, I suggest to send the auth request like this:

{
"endpoint": "auth",
"secret": "Ym9iOmJvYjEyMw==",
"ip": "XXX.XXX.XXX.XXX"
}

**Comment by or-else** [comment]
Added
