### ISSUE TITLE
Tinode crashes when gets invalid json response with rest authenticator

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#577]
### Subject of the issue
Tinode crashes when sends a request to the rest authenticator and gets an invalid json response.

#### Server-side
SDK: tinodejs/0.16.8
label_server 0.16 mysql:v0.16.8

#### Client-side
Tinode command line client. Version 1.5.3/0.16.7; 
gRPC/1.33.1; 
Python 2.7.16.

### Steps to reproduce
1. Send `auth` request to the rest authenticator.
2. Instead of json response return to the request something like `Error`
3. Tinode will crash and stop.

I had a typo in the php script on the rest authentication server. 

`
$query = mysqli_query($conn,"SELECT usser, cred FROM users WHERE $selectwhat")or die('Database error2');`

Column `usser` does not exist in the database and the script stopped to excecute returning to Tinode's request `Database error2` instead of json response.

### Expected behaviour
Tinode should not crash when gets invalid json response from the rest authenticator. 

### Server-side log

```
2020/12/02 16:42:07 in: '{"hi":{"id":"121466","ver":"0.16.8","ua":"Cchat/0.16.9-beta1 (Chrome/86.0; Win32); tinodejs/0.16.8","lang":"es-ES"}}' sid='IUpYhB4t5eo' uid=''
2020/12/02 16:42:11 in: '{"login":{"id":"121467","scheme":"basic","secret":"dGVzdDp0ZXN0MTI="}}' sid='IUpYhB4t5eo' uid=''
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x922a75]

goroutine 84 [running]:
github.com/tinode/chat/server/auth/rest.(*authenticator).Authenticate(0xc0000ac5a0, 0xc000f7e000, 0x14, 0x15, 0xc000f70160, 0xe909e0, 0xc000f7a010, 0x196, 0x0, 0x0)
        /Users/gene/go/src/github.com/tinode/chat/server/auth/rest/auth_rest.go:180 +0xb5
main.(*Session).login(0xc0003486e0, 0xc000f7a000)
        /Users/gene/go/src/github.com/tinode/chat/server/session.go:811 +0xc9
main.(*Session).dispatch.func1.1(0xc000f7a000)
        /Users/gene/go/src/github.com/tinode/chat/server/session.go:427 +0x23b
main.(*Session).dispatch(0xc0003486e0, 0xc000f7a000)
        /Users/gene/go/src/github.com/tinode/chat/server/session.go:509 +0x426
main.(*Session).dispatchRaw(0xc0003486e0, 0xc000f78000, 0x52, 0x600)
        /Users/gene/go/src/github.com/tinode/chat/server/session.go:385 +0x435
main.(*Session).readLoop(0xc0003486e0)
        /Users/gene/go/src/github.com/tinode/chat/server/hdl_websock.go:62 +0x187
created by main.serveWebSocket
        /Users/gene/go/src/github.com/tinode/chat/server/hdl_websock.go:182 +0x689

```

**Comment by aforge** [comment]
I think this will do: https://github.com/tinode/chat/pull/578
I'll let @or-else take a look.

**Comment by or-else** [comment]
I merged the PR. Thanks!
