### ISSUE TITLE
Wrong subscription permissions when creating p2p topic from GRPC with on_behalf_of

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#579]
### Subject of the issue
Creating p2p topics works correctly from webapp. Users gets the following subscription permissions:

![perm1](https://user-images.githubusercontent.com/54183931/101984880-22a85300-3c7c-11eb-88fe-f469b87748f1.png)

but when creating p2p topics from GRPC, users get the following incorrect permissions:

![perm2](https://user-images.githubusercontent.com/54183931/101984890-2e941500-3c7c-11eb-88a4-56b01449d6ba.png)

Both users have the following pemissions in "users" table:

![perm3](https://user-images.githubusercontent.com/54183931/101984935-7c108200-3c7c-11eb-8031-303f357e25cd.png)

I was thinking that it's my fault because I was playing with users permissions but not it looks like a bug.

### What I want to achieve

As a root user I want to start a p2p topic between users:
`aDj1grBOVxw`
and
`HGshCFWe5aI`
on behalf of user
`aDj1grBOVxw`

I send the same requests from GRPC as the web app but always get wrong permissions in subscriptions table for both users. The only difference with GRPC is that requests are coming `on_behalf_of`

### What I have tried
* I installed the latest version of Tinode.
* Logged off both users
* Deleted accounts of both users
* Deleted previously created subscrptions with wrong permissions and p2p topic between both users.
* Restarted Tinode
* Created new accounts for both users.
* Logged in both users in the webapp (even if they are logged off, there is the same problem)

### Webapp log and server log when creating a p2p topic from the webapp

**webapp**
```
2020/12/12 12:08:24 in: '{"sub":{"id":"79779","topic":"fnd","get":{"what":"sub"}}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:31 in: '{"sub":{"id":"79780","topic":"usrHGshCFWe5aI","get":{"what":"desc"}}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:40 in: '{"note":{"topic":"usrHGshCFWe5aI","what":"kp"}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:43 in: '{"pub":{"id":"79781","topic":"usrHGshCFWe5aI","noecho":true,"content":"sasasasaa"}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
[12:08:23.246] out: {"sub":{"id":"79780","topic":"usrHGshCFWe5aI","get":{"what":"desc"}}} 
[12:08:23.492] in: {"ctrl":{"id":"79780","topic":"usrHGshCFWe5aI","code":200,"text":"ok","ts":"2020-12-12T12:08:31.513Z"}} 
[12:08:23.522] in: {"meta":{"id":"79780","topic":"usrHGshCFWe5aI","ts":"2020-12-12T12:08:31.623Z","desc":{"updated":"2020-12-12T12:08:31.513Z","touched":"2020-12-12T12:08:31.513Z","acs":{"mode":"JRWP","given":"JRWPS","want":"JRWPA"},"public":{"fn":"mgomez","org":"CAN","photo":{"data":"<2788, bytes: /9j/4AAQSkZJ...NGikJo//2Q==>","type":"jpeg"}}}}} 
[12:08:32.487] out: {"note":{"topic":"usrHGshCFWe5aI","what":"kp"}} 
[12:08:34.827] out: {"pub":{"id":"79781","topic":"usrHGshCFWe5aI","noecho":true,"content":"sasasasaa"}} 
[12:08:35.263] in: {"ctrl":{"id":"79781","topic":"usrHGshCFWe5aI","params":{"seq":1},"code":202,"text":"accepted","ts":"2020-12-12T12:08:43.084Z"}} 
```

**server**
```
2020/12/12 12:08:24 in: '{"sub":{"id":"79779","topic":"fnd","get":{"what":"sub"}}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:31 in: '{"sub":{"id":"79780","topic":"usrHGshCFWe5aI","get":{"what":"desc"}}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:40 in: '{"note":{"topic":"usrHGshCFWe5aI","what":"kp"}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw'
2020/12/12 12:08:43 in: '{"pub":{"id":"79781","topic":"usrHGshCFWe5aI","noecho":true,"content":"sasasasaa"}}' sid='uGPewkyiTpQ' uid='aDj1grBOVxw':
```

### GRPC

**Server log**

```
2020/12/12 12:18:23 grpc: session started sC44TMC3LKE 188.165.249.27:53520 3
2020/12/12 12:18:23 grpc in: hi:<id:"310238" user_agent:"php/grpc" ver:"1" lang:"es-ES" >  sC44TMC3LKE
2020/12/12 12:18:23 grpc in: login:<id:"517629" scheme:"token" secret:"\266\323\3202\336P\365\254\274Y\337_\036\000\001\000\001\000\005\262\206\205\320\207#gW\366\233PuH6\264\035\317\340\267\006\304\225\242\243\345\367@\261)\332\037" > auth_level:ROOT  sC44TMC3LKE
2020/12/12 12:18:23 grpc in: sub:<id:"236096" topic:"fnd" get_query:<what:"sub" > > on_behalf_of:"usraDj1grBOVxw"  sC44TMC3LKE
2020/12/12 12:18:23 grpc in: sub:<id:"591218" topic:"usrHGshCFWe5aI" get_query:<what:"desc" > > on_behalf_of:"usraDj1grBOVxw"  sC44TMC3LKE
2020/12/12 12:18:23 grpc in: pub:<id:"439804" topic:"usrHGshCFWe5aI" content:"\"jyodfdfddfyoyoyoyo\"" > on_behalf_of:"usraDj1grBOVxw"  sC44TMC3LKE
2020/12/12 12:18:23 s.publish: must attach first sC44TMC3LKE
2020/12/12 12:18:23 grpc: recv sC44TMC3LKE rpc error: code = Canceled desc = context canceled
2020/12/12 12:18:23 topic[p2paDj1grBOVxwcayEIVZ7log] subscription failed topic access denied; user is banned, sid=sC44TMC3LKE
```

**Response to the client**
you must attach first

#### Server-side
- [ ] Your own setup:
  * platform: Linux Debian 10 Buster
  * version of Tinode server, v0.16.9-rc1
  * database backend: MySQL
* Tinode command line client. Version 1.5.3/0.16.7; gRPC/1.33.1; Python 2.7.16.

#### Client-side
* javascript client
* php/grpc

**Comment by or-else** [comment]
Confirming, it's a bug in gRPC interface.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/1ab545c5c36e5c6b04142cad314f262383e1d881

**Comment by or-else** [comment]
BTW, you can still use the 0.16.9-rc1 build, just assign `AUTH` level when making the call:
https://github.com/tinode/chat/blob/master/pbx/model.proto#L279
