### ISSUE TITLE
after last update the registration stopped working

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#58]
Hi, after i made git pull when i am trying to sign up and i get the error:"Error: user not found or offline (404)", i didnt change any server code in go, also i reinstall database 2 times, so maybe i find a bug.
And in console i have the next msg:
2018/01/07 19:58:44 Server v0.13: pid=3596 started with processes: 4
2018/01/07 19:58:44 Using config from: '/home/bogdan/godev/src/github.com/tinode/chat/server/tinode.conf'
2018/01/07 19:58:44 Running as a standalone server.
2018/01/07 19:58:44 plugins: no active plugins found
2018/01/07 19:58:44 Serving static content from '/home/bogdan/tinode/example-react-js/' at '/x/'
2018/01/07 19:58:44 Listening for client HTTP connections on [:6060]
2018/01/07 20:04:47 Session.dispatch got '{"hi":{"id":"80026","ver":"0.13","ua":"TinodeWeb/0.13 (Linux x86_64) tinodejs/0.13"}}' from '[::1]:39220'
2018/01/07 20:04:47 Session.dispatch got '{"acc":{"id":"80027","user":"new","scheme":"basic","secret":"dGVzdDM0MjM0Mjp0ZXN0MzQyMzQy","login":true,"desc":{"public":{"fn":"test342342"}},"tags":["email:test342342"]}}' from '[::1]:39220'
2018/01/07 20:04:47 Session.dispatch got '{"sub":{"id":"80028","topic":"me","get":{"what":"sub desc"}}}' from '[::1]:39220'
2018/01/07 20:04:47 Sub to 'me' from 'usrsBPAj0q002k'
2018/01/07 20:04:47 hub: user's account unexpectedly not found (deleted?)
2018/01/07 20:05:49 sess.readLoop: websocket: close 1001 (going away)
2018/01/07 20:05:49 serveWebsocket - stop
2018/01/07 20:06:00 Session.dispatch got '{"hi":{"id":"116964","ver":"0.13","ua":"TinodeWeb/0.13 (Linux x86_64) tinodejs/0.13"}}' from '[::1]:39284'
2018/01/07 20:06:00 Session.dispatch got '{"login":{"id":"116965","scheme":"basic","secret":"dGVzdDp0ZXN0"}}' from '[::1]:39284'
2018/01/07 20:06:00 basic auth: invalid login
2018/01/07 20:06:26 sess.writeLoop: ping/websocket: close sent

**Comment by or-else** [comment]
Hi. It seems like you are entering wrong credentials - wrong login and/or password. Do you have users in your database?

**Comment by bogdantarasenkozp** [comment]
no its emty,i have this error when i am trying to create new user

**Comment by or-else** [comment]
Looking into it.

**Comment by bogdantarasenkozp** [comment]
also i found one interesting moment, it creates user but the system dont works

**Comment by bogdantarasenkozp** [comment]
![2018-01-07 20-31-13](https://user-images.githubusercontent.com/20387183/34652651-f40589b0-f3e9-11e7-8078-1fc1d53a810a.png)

**Comment by bogdantarasenkozp** [comment]
Also i fetch users from database users (using node.js)  ,they was created on sign up
![2018-01-07 20-33-36](https://user-images.githubusercontent.com/20387183/34652669-227f8a48-f3ea-11e7-9129-62f78cc9c6c1.png)

**Comment by or-else** [comment]
Yes, it's a bug I introduced yesterday. Give me a min.

**Comment by bogdantarasenkozp** [comment]
got it, i was worried that it on my side)

**Comment by or-else** [comment]
Should be fixed now. This was the bug: https://github.com/tinode/chat/commit/08b51e054fdf43db77bec1a56dcde919138f6516#diff-b49d465c8dbf2c888fe2e2bd0c18e167L55

**Comment by bogdantarasenkozp** [comment]
i made git pull origin master, on my side still issue, maybe i did smth wrong?

**Comment by bogdantarasenkozp** [comment]
the log from console:
2018/01/07 21:02:26 Server v0.13: pid=7432 started with processes: 4
2018/01/07 21:02:26 Using config from: '/home/bogdan/godev/src/github.com/tinode/chat/server/tinode.conf'
2018/01/07 21:02:26 Running as a standalone server.
2018/01/07 21:02:26 plugins: no active plugins found
2018/01/07 21:02:26 Serving static content from '/home/bogdan/tinode/example-react-js/' at '/x/'
2018/01/07 21:02:26 Listening for client HTTP connections on [:6060]
2018/01/07 21:02:35 Session.dispatch got '{"hi":{"id":"100824","ver":"0.13","ua":"TinodeWeb/0.13 (Linux x86_64) tinodejs/0.13"}}' from '[::1]:43834'
2018/01/07 21:02:35 Session.dispatch got '{"acc":{"id":"100825","user":"new","scheme":"basic","secret":"dGVzdHRlc3QxMjMyMzEyMzM0OnRlc3QxMjMyMzEyMzM0","login":true,"desc":{"public":{"fn":"test1232312334"}},"tags":["email:test1232312334"]}}' from '[::1]:43834'
2018/01/07 21:02:35 Session.dispatch got '{"sub":{"id":"100826","topic":"me","get":{"what":"sub desc"}}}' from '[::1]:43834'
2018/01/07 21:02:35 Sub to 'me' from 'usrEvTajI3QVl4'
2018/01/07 21:02:35 hub: user's account unexpectedly not found (deleted?)

**Comment by or-else** [comment]
Something is not quite right on your side. Your log shows server version as 0.13, while the master is version 0.14: https://github.com/tinode/chat/blob/master/server/main.go#L43

**Comment by or-else** [comment]
> 2018/01/07 21:02:26 Server v0.13: pid=7432 started with processes: 4

It should be `v0.14`

**Comment by or-else** [comment]
2018/01/07 11:29:01 Server v0.14: pid=3544 started with processes: 8

**Comment by bogdantarasenkozp** [comment]
yeah, you right, thanks)
