### ISSUE TITLE
Badge with count of unread messages does not appear in newly created topics

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#580]
### Subject of the issue
If you create a p2p topic or a group topic, add user to this topic and send a message, the recipient will not see the badge with unread messages count. Badge will start appearing only when user selects the new topic (attaches to it).

there are a new message in the group but badge does not appear:

![badge1](https://user-images.githubusercontent.com/54183931/102007249-407ac400-3d1f-11eb-8ec7-a72a78ccc9d1.png)

After page reload appears badge:

![badge2](https://user-images.githubusercontent.com/54183931/102007268-79b33400-3d1f-11eb-88ba-bcec505b41b7.png)

### Steps to reproduce

- Log in into webapp with 2 different usernames from 2 different devices.
- As user A search for user B and create a new p2p topic with user B. New p2p topic will appear in the contacts (conversations list) of user B but it will be not selected (user B will not be attached to the new topic).
- As user A send a message to user B. Bagde with new messages count will not appear for user B. It will start appearing only after user B first time selects the topic with user B in the contact list (attaches to it) or reloads the page or if webapp loses connection to the server and reconnects.

The same problem with group topics.

- Create a new group.
- As user A add user B to the new group.
- As user A send a message to this group.
- Message will be delivered but new message badge will not appear for user B.

### Client-side log

This is the webapp log of user B when user A sends a message to the group and badge with new messages count does not appear:

`[08:27:51.412] in: {"pres":{"topic":"me","src":"grpCjzM689nQrU","what":"msg","seq":1,"act":"usrHGshCFWe5aI"}} `

it's correct but but badge does not appear for some reason,

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tinode-js/commit/b03026e956a2c28422660554d70116ca52e82460
