### ISSUE TITLE
sanity-test.sh broken

### ISSUE THREAD

**Issue by aforge** [tinode/chat#581]
`sanity-test.sh` is failing because of `tn-cli`'s `sample-script.txt` not terminating correctly.

`del user` command now (after https://github.com/tinode/chat/commit/3ad95cf8bc68025598136a8b11e92ee855eb6848) requires an explicit specification of the `--user` param.
https://github.com/tinode/chat/blob/devel/tn-cli/sample-script.txt#L75

An attempt to specify if `--user=$user.params[user]` leads to a server error. E.g.
```
2020/12/14 00:48:31 grpc in: del:<id:"36868" what:USER user_id:"\"usrU4W2EDiYoHQ\"" hard:true >  q3uxyIHaoEY
2020/12/14 00:48:31 replyDelUser: illegal attempt to delete another user "usrU4W2EDiYoHQ" q3uxyIHaoEY
```
Note unnecessary double quotes - this most probably is the cause.

`sample-macro-script.txt` is broken (seemingly due to a similar issue).

**Comment by or-else** [comment]
I think it would be OK to allow `--user` to be specified as `me`.

**Comment by or-else** [comment]
I can make this change if you want.

**Comment by aforge** [comment]
Sent https://github.com/tinode/chat/pull/582.

`sample-macro-script.txt` is broken due to a string encoding issue. I'll take care of it.

**Comment by aforge** [comment]
https://github.com/tinode/chat/commit/e3fc16efd080cd969f45c1b487d2c26ce75ddae8 should take care of the rest of the problem. Closing.
