### ISSUE TITLE
Lua binding?

### ISSUE THREAD

**Issue by sodomon2** [tinode/chat#585]
I was wondering if you were planning to make bindings for Lua, since you could make a desktop client using Gtk something like the telegram-desktop

**Comment by or-else** [comment]
We have no plans to provide native Lua bindings. You are welcome to take a shot at it.

We do provide [gRPC](https://grpc.io) bindings which are callable from Lua:
https://github.com/jinq0123/grpc-lua

**Comment by sodomon2** [comment]
I would like to try it but it is not C/C++

**Comment by sodomon2** [comment]
@or-else With https://github.com/jinq0123/grpc-lua could you make a desktop client for tinode?

**Comment by or-else** [comment]
I'm sure you can write a desktop client using Lua and gRPC although it would seem weird to me. 

If you care just for Windows then this C# project may be of interest:
https://github.com/tinode/csharpbot

The other option for desktop would be React Native using Tinode web app.

**Comment by sodomon2** [comment]
@or-else ok,then I will close this,since the question was answered :)
