### ISSUE TITLE
Error: command out of sequence (409)

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#59]
Hi, i made a last build version 0.14 and now when i make login or signup i got next error: Error: command out of sequence (409).
Is this on my side only?Did you get this issue?

**Comment by or-else** [comment]
Please show client-side and server-side logs.

**Comment by bogdantarasenkozp** [comment]
Server side
![2018-01-08 00-18-49](https://user-images.githubusercontent.com/20387183/34654836-893a31ba-f409-11e7-8bb3-b024159e9d7e.png)

**Comment by bogdantarasenkozp** [comment]
Client side
![2018-01-08 00-19-34](https://user-images.githubusercontent.com/20387183/34654839-a06a4104-f409-11e7-9263-25ef96aa6388.png)

**Comment by or-else** [comment]
Your server is version 0.14, but the client is version 0.13. Please get the latest client

**Comment by bogdantarasenkozp** [comment]
ohh, got it, thank you)
