### ISSUE TITLE
Error: user not found or offline (404)

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#60]
Hi,gene sorry for disturbing,i download the latest react.js and tinode.js version 0.14 also has latest version on server, but i still get "Error: user not found or offline (404)".Maybe i am doing something wrong?Can you help me please?
![2018-01-08 02-00-30](https://user-images.githubusercontent.com/20387183/34655778-2d67b524-f418-11e7-984f-7323d2be01bc.png)
![2018-01-08 02-00-51](https://user-images.githubusercontent.com/20387183/34655779-2d8a8d9c-f418-11e7-96fc-6444247414b2.png)

**Comment by or-else** [comment]
I cannot reproduce. Do you actually have the user in the database?

**Comment by or-else** [comment]
If you try to login with the credentials of the newly created account, does it work?

**Comment by or-else** [comment]
Please show what you have in the database. Open http://localhost:8080/#dataexplorer then issue the following queries (one at a time):

r.db('tinode').table('auth')

r.db('tinode').table('users')

**Comment by bogdantarasenkozp** [comment]
![2018-01-08 02-30-42](https://user-images.githubusercontent.com/20387183/34656047-696d997c-f41c-11e7-8e68-c63d39acbe6d.png)
![2018-01-08 02-32-52](https://user-images.githubusercontent.com/20387183/34656048-6990e74c-f41c-11e7-92ad-2c6ac0801771.png)
![2018-01-08 02-33-51](https://user-images.githubusercontent.com/20387183/34656049-69b0c1d4-f41c-11e7-980e-6b2bc5bc2f7b.png)

**Comment by bogdantarasenkozp** [comment]
when i am trying to login it writes Error: authentication failed (401), but the user exist in table users

**Comment by or-else** [comment]
Please click on Tree View in rethink data explorer and show the full record. 

I've added a bunch of debug logging to devel. Could you please check out devel branch, run it, and try logging in with a newly created account.

**Comment by bogdantarasenkozp** [comment]
Yes sure,one second

**Comment by bogdantarasenkozp** [comment]
![2018-01-08 03-03-30](https://user-images.githubusercontent.com/20387183/34656317-8c43bbe4-f420-11e7-9066-00ec43761611.png)
![2018-01-08 03-03-31](https://user-images.githubusercontent.com/20387183/34656318-8c645098-f420-11e7-90d8-28dc119e8702.png)
![2018-01-08 03-04-43](https://user-images.githubusercontent.com/20387183/34656329-b516a6d0-f420-11e7-9780-75e8b4cc042f.png)

**Comment by bogdantarasenkozp** [comment]
![2018-01-08 03-06-14](https://user-images.githubusercontent.com/20387183/34656338-e8110814-f420-11e7-8257-dc998ef0f744.png)
![2018-01-08 03-06-37](https://user-images.githubusercontent.com/20387183/34656342-f453f37a-f420-11e7-98cd-9ad0f769ac92.png)

**Comment by or-else** [comment]
Something is wrong with the way you build it. Looks at this line: https://github.com/tinode/chat/commit/4d464674c0d2650170b688196fd826ffb4c7a071#diff-de1005bbcda32c79b013cc70f3f11bc4R93

It must print out something like `2018/01/07 16:57:16 basic auth: test2 test2 0` but such line is missing from your server log. Please double check that you are building from correct source.

**Comment by or-else** [comment]
Your server is NOT built from the `devel` branch.

**Comment by bogdantarasenkozp** [comment]
ohh got it, sorry ,stupid me)one second

**Comment by or-else** [comment]
OK, I see the specific issue why the query fails: the DB has an `Id` and `id`. I.e. it ignores the directive for a custom primary key. Here is what the records should look like: 
```
{
"authLvl": 20 ,
"expires": Mon Jan 01 0001 00:00:00 GMT+00:00 ,
"secret": <binary, 60 bytes, "24 32 61 24 31 30..."> ,
"unique":  "basic:test2" ,
"userid":  "u9TqfPvhueY"
} {
"authLvl": 20 ,
"expires": Mon Jan 01 0001 00:00:00 GMT+00:00 ,
"secret": <binary, 60 bytes, "24 32 61 24 31 30..."> ,
"unique":  "basic:carol" ,
"userid":  "IentUmLVSG0"
}
```

and 

```
{
"Access": {
"Anon": 0 ,
"Auth": 31
} ,
"CreatedAt": Mon Jan 08 2018 00:19:04 GMT+00:00 ,
"Devices": null ,
"Id":  "u9TqfPvhueY" ,
"LastSeen": Mon Jan 08 2018 00:57:08 GMT+00:00 ,
"Public": {
"fn":  "test2"
} ,
"State": 0 ,
"Tags": [
"email:test2"
] ,
"UpdatedAt": Mon Jan 08 2018 00:19:04 GMT+00:00 ,
"UserAgent":  "TinodeWeb/0.14 (MacIntel) tinodejs/0.14"
}
```

Notice that there is no lower case `id` field with a UUID.

**Comment by or-else** [comment]
Your DB records have the rethink's default lower case `id` with a UUID primary key.

**Comment by or-else** [comment]
Which version of RethinkDB do you use?

**Comment by or-else** [comment]
How did you generate the DB? Did you use the latest generator?

**Comment by bogdantarasenkozp** [comment]
RethinkDB 2.3.6Web UI Settings

**Comment by bogdantarasenkozp** [comment]
no,i didnt use the latest generator, mybe problem was in that

**Comment by bogdantarasenkozp** [comment]
done, now it works)

**Comment by or-else** [comment]
Cool!

**Comment by bogdantarasenkozp** [comment]
Thank you very much,you are awesome, you are the best open source project founder that i see
