### ISSUE TITLE
release v0.16.10 changed a lot

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#601]
Does the release of v0.16.10 mean to abandon the v0.16.8-v0.16.9 cluster communication mode?

Is v0.16.10 from v0.16.7fork?

**Comment by aforge** [comment]
It does not abandon all changes in 0.16.8-0.16.9 but rolls back a major feature/mechanism in cluster communication (https://github.com/tinode/chat/commit/0a35bdc5cfcbc32e71ba904f66ebdfc8f449f0b9). Specifically, the problem you reported in https://github.com/tinode/chat/issues/556#issuecomment-716047935 should now go away.

There are other changes in this release also. So feel free to use this release as is.
