### ISSUE TITLE
Search users not working when users have profile images

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#608]
Hi,
There are two sides to this problem:
1. [here](https://github.com/tinode/chat/blob/d1db45e86cb126b852dafef3dea43f98365de695/server/db/mysql/adapter.go#L1906), sorting by `matches` will make Mysql load results into memory and sort them. When users have profile images, the size of each row increases and an `Error "1038 Out of sort memory, consider increasing sort buffer size` is received from Mysql.
2. because `rows.Err()` is never checked, the above error is ignored and an empty search result with a nil error is returned.

#### Server-side
latest master commit d1db45e86cb126b852dafef3dea43f98365de695
Mysql 8.0.22 with default [sort_buffer_size](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sort_buffer_size)
#### Client-side
webapp

### Steps to reproduce
1. have 200 users with profile photos
2. from webapp do a search which should return those 200 users

### Expected behaviour
receive error 1038 out of sort memory, or see the 200 users
 
### Actual behaviour
a successful response with 0 search results

edit: #609  adds checks for `rows.Err()` so the errors are reported.
Still, the query in FindUsers should be reworked so it does not result in err 1038.

**Comment by or-else** [comment]
Re: `error 1038 out of sort memory,`: this is very strange. We had a bug a while ago when search under some circumstances returned all users in the system. The web.tinode.co has a lot of users, a lot more than 200. It was slow but it worked. It's MySQL 5.7 though. 

I have to guess that you are using modified clients. From MySQL docs:
* At minimum the sort_buffer_size value must be large enough to accommodate fifteen tuples in the sort buffer. 
* sort_buffer_size default value is 262144 bytes.

So, your average tuple is larger than 262144/15 = 17KB. That means your clients are stuffing more data into `public` or `private` than expected. Probably larger avatar images. The current size of the avatar 128x128 is chosen for a reason. Support for external avatar images is not done yet.

**Comment by gabriel-vasile** [comment]
Yes, I have some 20 users with 30kb png profile images.
Breaking the the query in two (first, select only user ids matching tags; second, select whole user rows by ids) would avoid loading  JSON columns when sorting results. Does this seem like a good change to you?

**Comment by or-else** [comment]
I don't think it's a good idea to make permanent performance-affecting changes in the server to accommodate custom clients. 
As a short term fix I would suggest to increase the `sort_buffer_size` by 30 or 50%. 
The long-term fix is to add support for external avatars to VCard. Such support was added to Drafty recently. It's just a matter of copying it to VCard now. It's a purely client-side feature.

**Comment by gabriel-vasile** [comment]
Using 2 queries and thus, not loading jsons into memory, is faster when users count is 1000+ and just as fast as the existing query when there are fewer users...

**Comment by or-else** [comment]
You have a problem specific to your installation. I think it's reasonable for you to fix your specific problem by making very simple and straightforward change to your installation.

You could also help with the permanent fix by implementing support for external images in VCard in one of the clients.
