### ISSUE TITLE
installation err

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#61]
while i am writing command "go get -tags rethinkdb github.com/tinode/chat/server && go install -tags rethinkdb github.com/tinode/chat/server"
i get next error: src/github.com/tinode/chat/server/ringhash/ringhash.go:79: undefined: fnv.New128a

**Comment by or-else** [comment]
I'm not sure what the problem is. `fnv.New128a` is a part of a standard package set:
https://golang.org/pkg/hash/fnv/#New128a

Try cleaning your go installation and reinstalling it.

**Comment by riandyrn** [comment]
@bogdantarasenkozp, make sure you're running the latest version of go (1.9). I also encountered this problem when I still use go 1.8.

Hope this helps

**Comment by bogdantarasenkozp** [comment]
oh,yes i also has go 1.8, thank you very much guys)
