### ISSUE TITLE
MongoDb version of v0.16.10 - server does not start

### ISSUE THREAD

**Issue by Brandon2255p** [tinode/chat#614]
### Subject of the issue
Unable to start the latest version with mongodb. Tested windows and docker versions

#### Server-side
- [x] Your own setup:
  * platform Windows and Linux (docker)
  * version of Tinode server, e.g. `0.16.10`
  * database MongoDb
  * standalone

### Steps to reproduce
Follow https://github.com/tinode/chat/blob/master/docker/README.md
Or https://github.com/tinode/chat/blob/master/INSTALL.md#installing-from-binaries

### Expected behaviour
Server should start

### Actual behaviour
Server does not start 

### Server-side log
```
./init-db failed. Quitting.
2021/02/08 12:43:56 Database mongodb 111
2021/02/08 12:43:56 Database not found. Creating.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f0a61]

goroutine 1 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc0000bb4a0, 0x14, 0x0, 0x0)
        /usr/local/go/src/log/log.go:162 +0x81
log.(*Logger).Print(0x0, 0xc0001a78c8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:193 +0x6a
github.com/tinode/chat/server/db/mongodb.(*adapter).CreateDb(0xc0000c2190, 0x1, 0xc0000bb480, 0x1e)
        /Users/gene/go/src/github.com/tinode/chat/server/db/mongodb/adapter.go:256 +0xa5
github.com/tinode/chat/server/store.InitDb(0xc00022a000, 0x18e, 0x1a0, 0x1, 0x0, 0xc000097c20)
        /Users/gene/go/src/github.com/tinode/chat/server/store/store.go:152 +0x5f
main.main()
        /Users/gene/go/src/github.com/tinode/chat/tinode-db/main.go:254 +0x926
./init-db failed. Quitting.
```

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/42e3a2be0d756270448cb7591edadc4b149fc454.
Thanks!

**Comment by reBiocoder** [comment]
> Fixed in [42e3a2b](https://github.com/tinode/chat/commit/42e3a2be0d756270448cb7591edadc4b149fc454).
> Thanks!

How can I solve this problem? Pull the source code?

**Comment by or-else** [comment]
> Pull the source code?

Yes. You need to build `init-db` from source.

**Comment by or-else** [comment]
Or wait for the next release.

**Comment by reBiocoder** [comment]
> Or wait for the next release.

thanks! I have solved the problem
