### ISSUE TITLE
install instructions fail with mongodb

### ISSUE THREAD

**Issue by SanJoseCosta** [tinode/chat#619]
### Subject of the issue
install instructions fail with mongodb

#### Server-side
amazon linux

[ec2-user@ip-10-0-0-202 ~]$ ./init-db -data=data.json

2021/03/05 15:49:09 Database mongodb 111

2021/03/05 15:49:09 Failed to init DB adapter: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 127.0.0.1:27017: connect: connection refused }, ] }

**Comment by SatoshiNakamotogmx** [comment]
Server down or has the ip changed?

**Comment by or-else** [comment]
> `dial tcp 127.0.0.1:27017: connect: connection refused`

It looks like there is no server at `127.0.0.1:27017`. You have to setup your mongo correctly. In any case, your problem has nothing to do with Tinode.

**Comment by gogoyqj** [comment]
same problem, just comment `replica_set` in tinode.conf(standalone instance)

```
// Name of replica set of mongodb instance. Remove this line to use a standalone instance.
// If replica_set is disabled, transactions will be disabled as well.
// "replica_set": "rs0",
```
