### ISSUE TITLE
Still having connection issues

### ISSUE THREAD

**Issue by SanJoseCosta** [tinode/chat#620]
### Subject of the issue
Install fails - Cannot connect to mongodb

mongodb is running:

[ec2-user@ip-10-0-0-211 tinode]$ ps aux | grep mongo

mongod    2650  0.3  1.0 1573056 88364 ?       Sl   Mar03   9:49 /usr/bin/mongod -f /etc/mongod.conf

ec2-user 20439  0.0  0.0 119416   912 pts/0    S+   16:35   0:00 grep --color=auto mongo

[ec2-user@ip-10-0-0-211 tinode]$ sudo netstat -tulnp | grep 2650

tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      2650/mongod         

[ec2-user@ip-10-0-0-211 tinode]$ ./init-db -data=data.json

2021/03/05 16:23:02 Database mongodb 111
2021/03/05 16:23:02 Failed to init DB adapter: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }

**Comment by or-else** [comment]
Could you please stop filing this issues. These are not bugs or feature requests. You are asking for assitance with installation of Mondodb. Please send your questions to the forum: https://groups.google.com/d/forum/tinode
