### ISSUE TITLE
proxy topic may never stop

### ISSUE THREAD

**Issue by haorenfsa** [tinode/chat#621]
### proxy topic may never stop
The runProxy goroutine set a timer but then stops it.
So logically, when its session are all dead, and with tcp keepalive option unset, the proxy topic may never stop.
It seems like a typo, missing `defer`
``` go
func (t *Topic) runProxy(hub *Hub) {
	killTimer := time.NewTimer(time.Hour)
	killTimer.Stop()  // seems missing defer here ?
```

**Comment by or-else** [comment]
https://github.com/tinode/chat/blob/master/server/topic_proxy.go#L143

Please do not use github issues just to ask questions. Please use the forum instead as requested.
