### ISSUE TITLE
Sequence problem when cluster proxys {sub} and {leave} msg

### ISSUE THREAD

**Issue by haorenfsa** [tinode/chat#622]
### Sequence problem when cluster proxys sub and leave msg

This may cause a phenomenon of a client not receiving msg updates of its watched topic.

Suppose a client session sends a `{leave}` to subscribed topic and then `{sub}` it back again in a short time.
When a node recevies them from its connected sessions, they are in exact sequence as it is sent by client.
Then, If the node is not the master, the proxy topic will pass it to master through rpc call, it's still in order. 
Then, the topic master send and `{leave}` to `topic.unreg` , and the `{sub}` to `hub.join` channel. They are handled in different goroutine. So things start to go wrong.
`hub.run` goroutine may process the `{sub}` first, and put it to the master topic's `reg` channel.  then the topic goroutine goes. It switches in its `reg` and `unreg` channel, and decides to do the `reg` first, as to find out it's already subscribed, returns ok. then  it does the `unreg` and also returns ok.

So here is what we got: the client session believes it has re-subed the topic, but in fact it has just leaved it.

**Comment by or-else** [comment]
Please fill out the bug report form: client/server versions, logs, etc.

**Comment by or-else** [comment]
No response in over two weeks. Closing.
