### ISSUE TITLE
Can you implement self defined RSA encrypted comunication? because maybe everyone don't believe the server.

### ISSUE THREAD

**Issue by naowang** [tinode/chat#626]
Can you implement self defined RSA encrypted comunication? because maybe everyone don't believe the server. I am the one don't believe the chat server.

**Comment by or-else** [comment]
This is a large feature. Would you like to support it in some way?

**Comment by SongShawn** [comment]
That is really a good feature.

**Comment by or-else** [comment]
Duplicate of #357
