### ISSUE TITLE
s.login: internal Uid.UnmarshalText: failed to decode

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#629]
Tinode backend refuses to authenticate users under some conditions

### Your environment
- tinode from docker image `tinode/tinode:0.16.10`
- custom REST auth proxy similar to [auth.py](https://github.com/tinode/chat/blob/master/rest-auth/auth.py)
Server config:
```
{
  "auth_config": {
    "logical_names": ["basic:rest"],
    "rest" :{"allow_new_accounts":true,"server_url":"http://tinode-auth:3000","use_separate_endpoints":true},
    "token": {
      "expire_in": 1209600,
      "serial_num": 1,
      "key": "T713/rYYgW7g4m3vG6zGRh7+FM1t0T8j13koXScOAj4="
    }
  },
}
```

### Expected behaviour
User is able to login as long as according entity exists in the database and rest proxy answers with valid `{rec}` on `POST /auth` request

### Actual behaviour
Some users receive "internal error (500)" error message in web ui. Others are fine.

### Server-side log

Auth is failed:
```
I2021/03/26 05:52:06 ws: session started kqL3vA3uQGs 213.127.72.232 4
I2021/03/26 05:52:06 in: '{"hi":{"id":"77391","ver":"0.16.10","ua":"TinodeWeb/0.16.10 (Firefox/85.0; MacIntel); tinodejs/0.16.10","lang":"ru-RU"}}' sid='kqL3vA3uQGs' uid=''
I2021/03/26 05:52:06 in: '{"login":{"id":"77392","scheme":"basic","secret":"ZnVsbGRpdmU6ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SmZhV1FpT2lJeE9HUTRYMEpFVlc1cklpd2lhV1FpT2lJeE9HUTRYMEpFVlc1cklpd2ljbTlzWlhNaU9sc2lZVzV2Ym5sdGIzVnpJaXdpZFhObGNpSmRMQ0psZUhCcGNtVnpUMjRpT2lJeU1ESXhMVEF6TFRNd1ZERXhPakV5T2pVMUxqRTNNRm9pTENKMWMyVnlibUZ0WlNJNklrWjFiR3hFYVhabElFUmxkbVZzYjNCbGNpSjkuVU9RZHphMW56RmNVelE5SmxNejZmMUVuWFoxWm8tTWpfVGZYRXp3RTJicw=="}}' sid='kqL3vA3uQGs' uid=''
W2021/03/26 05:52:06 s.login: internal Uid.UnmarshalText: failed to decode illegal base64 data at input byte 7 kqL3vA3uQGs
```

Auth successful:
```
I2021/03/26 05:51:22 ws: session started WAfBeFxZY4Q 213.127.72.232 4
I2021/03/26 05:51:22 in: '{"hi":{"id":"93927","ver":"0.16.10","ua":"TinodeWeb/0.16.10 (Firefox/85.0; MacIntel); tinodejs/0.16.10","lang":"ru-RU"}}' sid='WAfBeFxZY4Q' uid=''
I2021/03/26 05:51:22 in: '{"login":{"id":"93928","scheme":"basic","secret":"ZnVsbGRpdmU6ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SmZhV1FpT2lKTVdETndVa2x2TlhnaUxDSnBaQ0k2SWt4WU0zQlNTVzgxZUNJc0luSnZiR1Z6SWpwYkltRnViMjU1Ylc5MWN5SXNJblZ6WlhJaUxDSmhaRzFwYmlKZExDSmxlSEJwY21WelQyNGlPaUl5TURFNUxURXhMVEV6VkRFd09qUTFPakk0TGpnME4xb2lMQ0oxYzJWeWJtRnRaU0k2SWsxaGNtbHVZU0JIYjI1dmEyaHBibUVpZlEudmRUNnlmNUZSZk5vazE2TjJPcUFUZ1FVU0o5QnJ0cndHM3RiRzhHaHl4RQ=="}}' sid='WAfBeFxZY4Q' uid=''
I2021/03/26 05:51:22 in: '{"sub":{"id":"93929","topic":"me","get":{"what":"sub desc tags cred"}}}' sid='WAfBeFxZY4Q' uid='76sEIKJfW00'
```

**Comment by aforge** [comment]
Your authenticator is supposed to return an `auth.Rec` with a valid `Uid` (`rec.uid` field in the json response).
Can you verify it actually returns a valid uid please?

Also, are these failures consistent? I.e. if user X authentication fails, it'll always fail. And vice versa, if user Y's auth is successful, it'll always succeed.

**Comment by or-else** [comment]
Please look at your authenticator's response. It's clearly returning something which it is not supposed to.

> s.login: internal Uid.UnmarshalText: failed to decode illegal base64 data at input byte 7

The UID is invalid, i.e. not a UID.

**Comment by afoninsky** [comment]
Uid generator was taken from your implementation and ported to another language. I will investigate this issue (if it wasn't ported properly) and reopen the issue if something go wrong. Thanks for the feedback.
