### ISSUE TITLE
Mysql adapter optimisations

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#631]
I understand [people have different levels of experience](https://github.com/tinode/chat/pull/609#issuecomment-765684294), but could you, please, NOT optimise sections like this? https://github.com/tinode/chat/blob/e64742f3f0c1f5c3e62dfc86703d086c288588d2/server/db/mysql/adapter.go#L827-L842

**Comment by or-else** [comment]
Could you please clarity what exactly is the problem with this code?

**Comment by gabriel-vasile** [comment]
It reuses the same user var to save some allocs.
Fortunately, builtin `append` func is not so concerned about allocs and it makes a copy of the user when called so most of user data is correct.
Unfortunately, there are some pass by reference vars inside user. 

This example uses JSON, but the problem reproduces the same with any decoding func, including `sqlx`'s `StructScan`.
https://play.golang.org/p/FBndxEXzUeZ

Unless the code is in a tight loop with thousands of executions per second, there is no reason for such optimizations. Most of the times memory goes on stack which is insanely fast. Plus, it's quite hard to say there is an improvement when there are no benchmarks to prove it.

**Comment by or-else** [comment]
Good catch with slices. Thanks!
