### ISSUE TITLE
Is it possible to get topic tags if you are not chat owner?

### ISSUE THREAD

**Issue by geraldika** [tinode/chat#642]
**If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by or-else** [comment]
If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.
