### ISSUE TITLE
Docker's README needs small fix

### ISSUE THREAD

**Issue by AnthonyKot** [tinode/chat#643]
### Subject of the issue
https://github.com/tinode/chat/blob/master/docker/README.md#supported-environment-variables table is not rendered completely. Probably, small html fix is needed.

### Your environment
Documentation bug.

### Steps to reproduce
Just open https://github.com/tinode/chat/blob/master/docker/README.md#supported-environment-variables

### Expected behaviour
Environment variables is rendered

### Actual behaviour
Environment variables is not rendered as whole thing

If you need someone to fix it, just let me know :) Have a good day!

**Comment by or-else** [comment]
Thanks. It's been fixed in https://github.com/tinode/chat/blob/devel/docker/README.md a while ago.
