### ISSUE TITLE
undefined: log.Lmsgprefix

### ISSUE THREAD

**Issue by young310** [tinode/chat#644]
### Subject of the issue
When I follow the instruction to build from source, I got the following error message:

undefined: log.Lmsgprefix

#### Server-side
- [x] Your own setup:
  * platform: ubuntu 18
  * version of Tinode server: from github source v0.17.0-rc1 master
  * database backend: MySQL 5.7
  * standalone

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.

### Steps to reproduce
1. sudo apt-get install golang (will get go version go1.10.4 linux/amd64)
2. go get -tags mysql github.com/tinode/chat/server && go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server
3. error message: 
github.com/tinode/chat/server/logs
go/src/github.com/tinode/chat/server/logs/logs.go:36:13: undefined: log.Lmsgprefix

### Expected behaviour
Should generate tinode binary file

### Actual behaviour
error message:
github.com/tinode/chat/server/logs
go/src/github.com/tinode/chat/server/logs/logs.go:36:13: undefined: log.Lmsgprefix

### error message
go get -tags mysql github.com/tinode/chat/server && go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server
github.com/tinode/chat/server/logs
go/src/github.com/tinode/chat/server/logs/logs.go:36:13: undefined: log.Lmsgprefix

**Comment by young310** [comment]
When I tried go version go1.16.3 linux/amd64

will get:

go: downloading firebase.google.com/go v1.0.2
no required module provides package github.com/tinode/chat/server: go.mod file not found in current directory or any parent directory; see 'go help modules'

by running:
go get -tags mysql github.com/tinode/chat/server && go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server

**Comment by or-else** [comment]
> undefined: log.Lmsgprefix
> will get go version go1.10.4 linux/amd64

It's defined in go1.14

**Comment by or-else** [comment]
> go: downloading firebase.google.com/go v1.0.2

Not sure where this is coming from. Something is wrong with your build. Tinode's go.mod requires 3.12.0:
https://github.com/tinode/chat/blob/master/go.mod#L6

**Comment by young310** [comment]
> > undefined: log.Lmsgprefix
> > will get go version go1.10.4 linux/amd64
> 
> It's defined in go1.14

problem solved by specifying the go version to go 1.15

**Comment by or-else** [comment]
I use go 1.16:

```
$ go version
go version go1.16 darwin/amd64
```
