### ISSUE TITLE
Update to rc2 killed notifications?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#646]
I hoped update to rc2 solves the problems with index.html ui (workaround was index-dev.html). Some cache clearing and reloads again ui load fine, but notifications are broken.

Can't re-activate push notifications again. Error message
````
react-dom.production.min.js:56 Uncaught TypeError: Promise resolver undefined is not a function
    at new Promise (<anonymous>)
    at Nt.togglePushToken (index.prod.js:1)
    at et.handleCheckboxClick (index.prod.js:1)
    at z.handleChange (index.prod.js:1)
    at Object.vi (react-dom.production.min.js:202)
    at ui (react-dom.production.min.js:32)
    at xi (react-dom.production.min.js:32)
    at zg (react-dom.production.min.js:55)
    at rg (react-dom.production.min.js:56)
    at react-dom.production.min.js:66
```

**Comment by pwFoo** [comment]
Some times all contacts disappear.
```
Sie haben keine Unterhaltungen
¯∖_(ツ)_/¯
```

**Comment by or-else** [comment]
This is not a useful report. Please list steps to reproduce.

**Comment by pwFoo** [comment]
Maybe should be moved to webapp?

Steps.

1. Update rc1 to rc2
2. UI doesn't work any more, delete caches and reload (3-4 times)
3. Remove all app data / caches / saved data to fix UI
4. After login contact list disappears
5. Delete caches, reload to fix contact list
6. Try to activate push fails
7. Tried to "fix" it with some more reloads / clear data
8. Found error message in web developer tools

**Comment by or-else** [comment]
I cannot reproduce any of it. Try using incognito browser window.

**Comment by or-else** [comment]
<img width="689" alt="Screenshot 2021-04-30 at 17 30 43" src="https://user-images.githubusercontent.com/5938143/116765439-c4fb8400-aa2d-11eb-84cb-eb52689a95fd.png">

This is the cache you need to clear.

**Comment by pwFoo** [comment]
Rebootet my pc and startet browser contacts are disappearing again.
Used incognito mode login works, contacts visible, but can't activate push notifications.
![image](https://user-images.githubusercontent.com/333408/116774404-b6789100-aa5c-11eb-88b6-7251553ae2de.png)

To get contact list back I cleared all app data and the service worker, but still can't enable push notifications again (checkbox disabled).

Cache is empty here:
![image](https://user-images.githubusercontent.com/333408/116774434-d27c3280-aa5c-11eb-8b74-0dfb2c5ed298.png)

Reloaded in incognito tab, activate push notifications is clickable again, but fails with error message in console
```
react-dom.production.min.js:56 Uncaught TypeError: Promise resolver undefined is not a function
    at new Promise (<anonymous>)
    at Nt.togglePushToken (index.prod.js:1)
    at et.handleCheckboxClick (index.prod.js:1)
    at z.handleChange (index.prod.js:1)
    at Object.vi (react-dom.production.min.js:202)
    at ui (react-dom.production.min.js:32)
    at xi (react-dom.production.min.js:32)
    at zg (react-dom.production.min.js:55)
    at rg (react-dom.production.min.js:56)
    at react-dom.production.min.js:66
```

**Comment by pwFoo** [comment]
With rc1 I used index-dev.html as workaround for that problems. For me rc1 index.html had the same problems. 
My temp fix was in static directory inside of the docker container
```
cp -a index-dev.html inidex.html
```
Tested index-dev.html and moved back to index.html, webapp shown "new version available, need reload" and then contacts disappear. Contacts gone away for both files index and index-dev. 

Move between index and index-dev generated "undefined" Cache Storage entry with both (index.html, index-dev.html).
![image](https://user-images.githubusercontent.com/333408/116774641-4b2fbe80-aa5e-11eb-82a9-a7f94f94a05d.png)

get contacts back need a full clearing of caches, but still not able to activate push notifications.

**Comment by or-else** [comment]
I was able to reproduce both issues.

**Comment by or-else** [comment]
It is more convenient to use `/index-dev.html` because it produces a usable stack trace in case of crashes.

The crash is fixed: https://github.com/tinode/webapp/commit/1537016942f4b963d64ab5f448ae3a0b24ce3790

**Comment by or-else** [comment]
The issue with blank contact list is fixed in tinode/webapp@4a480d7

**Comment by pwFoo** [comment]
Great, thanks!
I'll update and test with the next docker image release 👍

**Comment by pwFoo** [comment]
Updates to rc3 fixed both problems! Thanks! Good job!
