### ISSUE TITLE
Root user can send notify to any topic

### ISSUE THREAD

**Issue by cfanboy** [tinode/chat#648]
Currently, the root user (System Administrator) cannot send the message to the p2p topic, but sometimes it has the scenario.
So it's possible to add the IM root user can send {notify} directly to any topics?

Scenario for example: 
The system checks the p2p chat has some risks, such as one of the users is a scammer and requires the money transfer,  the system administrator can send the {notify} message to this topic to warning user.

Thanks

**Comment by or-else** [comment]
1. The sysadmin can modify messages in a p2p conversation to add a disclaimer to any message sent by any one of the participants.
2. The sysadmin may send a message on behalf of any participant.
3. If the sysadmin does not want to inject the message into the conversation then he can start a separate p2p chat with any of the participants.
4. There is a feature request to enable a `staff` or `verified` or `vip` or some such badge for users. The `scammer` could be such a badge too. It can be implemented as a read-only field in `public` or `private`.

The 1-3 don't require any changes to the server or clients. The 4 requires modifications to all the clients and the server

**Comment by or-else** [comment]
Another option is to modify clients to treat certain message headers as user-visible flags. In other words, a sysadmin adds a parameter to message header like `"danger": true` and clients show an appropriate disclaimer.

**Comment by cfanboy** [comment]
According to the documents, the sysadmin must be one of the participants in the p2p topic who can send the message to another user, so for point 1, I don't understand, you mean to use the Plugin to process it?

Yup,  we do not interfere with the user chat, the last one is a good idea, thanks a lot.

**Comment by or-else** [comment]
> so for point 1, I don't understand, you mean to use the Plugin to process it

Yes.

**Comment by or-else** [comment]
Given that the `trusted` was implemented and solves the product problem, and the fact that allowing third parties to post to p2p topics is a lot of work, I'm going to close this issue. Please reopen if you feel that `trusted` does not solve the product problem.
