### ISSUE TITLE
The reason for this sleep

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#650]
https://github.com/tinode/chat/blob/01a463ead4367d99363a05bcdef2633b64517e80/tn-cli/tn-cli.py#L942-L952

Can it just be removed/lowered/moved somewhere else? If not, why?
The issue I have is .1s add up to whole seconds for longer scripts.

If sleep .1s is there to stop `while true:` from going crazy, I guess this value could be configured; e.g.: 
```bash 
python tn-cli.py --interval 0.1
```

**Comment by or-else** [comment]
Questions -> https://groups.google.com/d/forum/tinode

> If sleep .1s is there to stop while true: from going crazy

Yes

Why is it a problem?

**Comment by gabriel-vasile** [comment]
I'm using the cli non-interactive (I pipe my script into the cli).
My script logins, creates a group, and invites 8 users into the group.
```
.must $user asd:asd
.must $group sub new --fn groupName
.must set $group.topic --mode JRWPASD --user usr1
...
.must set $group.topic --mode JRWPASD --user usr8
```
```bash
time cat script | python tn-cli.py
real	0m1,298s
user	0m0,255s
sys	0m0,030s
```
For this example the cli spends 1.29s in total out of which 1s is sleeping and 0.25s is doing actual work.

**Comment by or-else** [comment]
How about this: https://github.com/tinode/chat/commit/10dbf4ad2f24803ad5f443f9423669bebcf47e67 ?

**Comment by gabriel-vasile** [comment]
I don't know... now `while true` spins over and over while the commands run. Worse, if the server goes away, that's 5 seconds of 100% CPU usage in `while true`.

Again, how about a config option to tell the cli how much to sleep before checking for a response from the server?
```bash
python tn-cli.py --interval 0.1
```
I run the cli on the same host as the server. I know 99% of the times the latency will be less than 10ms. That's how much I want the cli to sleep before checking for a response from the server. Other users can adjust for their latency or just use the default 0.1s.

**Comment by or-else** [comment]
> python tn-cli.py --interval 0.1

This is not a good idea. It's asking users to figure out a workaround for an internal issue.

> That's how much I want the cli to sleep before checking for a response from the server.

That's not what this sleep is for. This sleep is used when `tn-cli` checks for the input from the user or while reading from the `stdin`.

> Worse, if the server goes away, that's 5 seconds of 100% CPU usage

Let me check if it's indeed the case. When `tn-cli` is run non-interactively it should just exit when it cannot connect to the server.

**Comment by or-else** [comment]
How about this: https://github.com/tinode/chat/commit/1a62d947777870af2d3e10de905f476a18bedcaa ?

**Comment by gabriel-vasile** [comment]
That's a little better. Thanks!
I'll leave the issue open and you close it after release, right?

**Comment by or-else** [comment]
> That's a little better.

Why a little? Do you know another way of fixing it which is a lot better?

**Comment by gabriel-vasile** [comment]
> This is not a good idea. It's asking users to figure out a workaround for an internal issue.

I think this is a fair config option. 
> That's not what this sleep is for. This sleep is used when `tn-cli` checks for the input from the user or while reading from the `stdin`.

First line in that `while true` checks user input ONLY if there is no pending response from server. If there is a pending response, then it sleeps. I'd argue that sleep is for server responses as much as it is for user input.

> Let me check if it's indeed the case. When `tn-cli` is run non-interactively it should just exit when it cannot connect to the server.

While the scripts runs the connection might drop, the server might panic, or for whatever other reason, never send back a response.

If you're still against the config option, I think it would be better to sleep 0.01s for interactive sessions too. Running an empty loop 100 times/s is the same as 10 times/s for a computer and it will remove that noticeable 0.1s delay for users.

**Comment by or-else** [comment]
> I think this is a fair config option.

In that case, can you describe what are the use cases addressed by this option? What are the recommended values of this parameter for each of them?

> checks user input ONLY if there is no pending response from server

The `tn_globals.WaitingFor` is true-ish when the user used `.await` command. I.e. the user explicitly told `tn-cli` to wait for either server response. This loop sleeps when both input and output queues are empty and the user did not request it to sleep.

**Comment by gabriel-vasile** [comment]
> In that case, can you describe what are the use cases addressed by this option? What are the recommended values of this parameter for each of them?

Maybe I misunderstood, but do you want me to list what values a float number parameter can take? 

> The tn_globals.WaitingFor is true-ish when the user used `.await` command. I.e. the user explicitly told tn-cli to wait for the server response. This loop sleeps when both input and output queues are empty or user requested it to sleep.

If someone uses `.await` or `.must` I think they want to wait until the response is back from server, not 10 times longer than necessary. 

> Why a little? Do you know another way of fixing it which is a lot better?

What I think is the best way is to make it always sleep for 0.01s.

**Comment by or-else** [comment]
I don't think this conversation is useful.
