### ISSUE TITLE
Sensitive information in the logs

### ISSUE THREAD

**Issue by kisulken** [tinode/chat#653]
By default tinode logs everything in `/var/log/tinode.log` including secrets, messages, topic descriptions etc

1. How to disable/limit the log output? At least in production we really shouldn't log messages and secrets
2. Do we really need to log secrets? Like `'{"login":{"id":"73280","scheme":"basic","secret":"MTIzOmYxMzdhZWYzNWYwMzViMzE="}}' sid='wDTk-dWaTK4' uid=''`

**Comment by or-else** [comment]
Duplicate of https://github.com/tinode/chat/issues/215
