### ISSUE TITLE
Cant connect to Server with any Client only Webbrowser work

### ISSUE THREAD

**Issue by lunainvictum** [tinode/chat#655]
Hi,

i want to use Tinode in LAN for simple Messaging between various clients. 

I setup the Server and everything works (after disableing verfication because of no mail server). I can use the Browser on any Device to 192.168.5.63:6060.

But any "real Client" like Tindroid, or Tinode for iOS dont work. Tried different Smartphones on Android side, and a Ipad and a Iphone 6.

All Clients says "Login-Fehler:: isConnected failed: ERCONNREFUSED (Connection refused)"

On clientside  on Setting i tried as adress:

192.168.5.63
192.168.5.63:6060
http://192.168.5.63
http://192.168.5.63:6060
https://192.168.5.63
https://192.168.5.63:6060

tried default, websocket, long polling. and any other combination on all settings. Everytime the same Error. 

Then a another Problem i have, i created 5 Users, and dont know how to find other users and write them. 

Is a great program. But sadly it is badly documented how to use and setup everything right :(

**Comment by or-else** [comment]
Please use forum for questions.

**Comment by lunainvictum** [comment]
I dont have a question. 

I have a Issue. 

The Issue is: Clients (execpt Browser) cant connect to Server.

**Comment by or-else** [comment]
Fix your configuration.
