### ISSUE TITLE
Checkout Tox

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [tinode/chat#667]
Tox and Tinode are very interesting and valuable projects. I feel they both can benefit from cross collaboration, support and a potential merger. Dev bandwidth can be pooled and both projects sped up. The server can have two modes - distributed open to public and distributed private personal use server mode. If both clients are trying to solve similar problems, why not merge efforts.

Disclaimer: I am not part of Tinode or Tox. Just someone who is looking for a chat server and chat client for his app's requirement. I found tox and tinode as good options. They all solve some parts of the problem. I see tinode stretched thin. Correct me if I'm wrong. Don't know about Tox's dev resource situation. If the two merge and work together, they will solve the problem they have set out to achieve faster

**Comment by or-else** [comment]
This is not the right place for this conversation. Please post to the forum: https://groups.google.com/d/forum/tinode
