### ISSUE TITLE
Insert some newlines in README.md and docs/API.md

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#668]
80 characters per line is the sane limit.
1000 characters lines are not fun to read.

**Comment by aforge** [comment]
Doesn't the default github `md` formatting do it for you already?
What kind of reader are you viewing these .md files with?

**Comment by or-else** [comment]
Most text editors have a feature "line wrap" or "soft line breaks".
Manual hard line breaks complicate editing: when text is added or removed, the lines have to be manually reformatted which is a waste of time.

**Comment by gabriel-vasile** [comment]
@aforge I'm viewing in my daily editor which is configured with no-wrap because I use it to read and write code. no-wrap preserves the indentation exactly as the text author wanted it to be.

@or-else I see. Maybe a line break at each sentence? It would keep lines length reasonable and the formatting duties low.
Right now it's pretty hard finding a change in `diff` on one of those lines.

**Comment by or-else** [comment]
> daily editor

Can you give a link to it? I can't find a text editor with this name.

> Right now it's pretty hard finding a change in diff on one of those lines.

Can you give an example of such diff?

**Comment by gabriel-vasile** [comment]
"my daily editor" as in the editor I use daily. It's vim, yes, I can configure it to soft wrap, but as I said, I use it to read and write code so I have it configured with no-wrap.


> Can you give an example of such diff?

https://github.com/tinode/chat/commit/c7c15f416b2ed90e5d2cc4e8d9b6ecae1f761b00#diff-b57590968a12cee85a37c1b91d8cc7092cd8b68e50b242c39a178121db82a797L378-R378

This is the last change on that 1000 characters long line.

**Comment by or-else** [comment]
Have you seen this?
https://stackoverflow.com/questions/15379660/how-to-enable-line-wrap-only-for-certain-filetypes-in-vim
