### ISSUE TITLE
How to show a list of groups to logged in users?

### ISSUE THREAD

**Issue by k0fi** [tinode/chat#67]
Hello,
I'd like to show a list of all available groups to the users who have just logged in. I appreciate if you elaborate how this can be achieved? 

Thanks

**Comment by or-else** [comment]
I've been planning to add a list of online subscribers to topic's title bar. I'll expedite this feature so you will be able to see how to do it. It won't be exactly what you want but close enough.

**Comment by or-else** [comment]
At first I misunderstood your question.

Please define _available group_. If a user created a group and invited two of his friend to this group, should it be also shown to everybody else? If 'yes', how is it useful? If 'no', who decides which groups to show to everybody?

**Comment by k0fi** [comment]
Well, by 'group', I mean 'room' in a typical chatroom sense. If Alice creates a public room, obviously she wants every newcomer to the system see that. If she creates a private group (aka room), she does not want uninvited people to see that. I think that's common practice for any general purpose chatroom.

**Comment by or-else** [comment]
This is a different use case than what I have in mind. 

On the other hand it's not too hard to make groups discoverable through search, like users are discoverable. Currently `tags` must be unique. I can  allow non-unique tags and make them available for groups too. That will be a lot like Telegram.

**Comment by or-else** [comment]
No update in a week. I assume this is no longer relevant. Please reopen if you want to continue this conversation.
