### ISSUE TITLE
Image Selector gives out error

### ISSUE THREAD

**Issue by r4nmaru1234** [tinode/chat#676]
I compiled an own apk to enable push notifications for android.
Everything works fine but if i want to send an Image the app gives out this err
![IMG_20210713_231656](https://user-images.githubusercontent.com/30414706/125527594-98269a5c-6471-467a-bd3c-3a826a7703b7.jpg)

Is this a bug or did i do something wrong?

**Comment by or-else** [comment]
Please use forum for questions:
https://groups.google.com/d/forum/tinode

It seems like something is misconfigured in your setup or some permissions are missing or you are targeting API 30.
