### ISSUE TITLE
Error on installing with docker

### ISSUE THREAD

**Issue by AmirGhazaei** [tinode/chat#68]
Hi

When I install the tinode server whit docker, face with this error:
```
docker build --tag=tinode-init-db init-rethinkdb
unable to prepare context: path "init-rethinkdb" not found
```

Thanks.

**Comment by or-else** [comment]
You need to download the docker files and save them to init-rethinkdb folder. Please read Docker documentation, maybe find a basic tutorial and in general make yourself familiar with Docker. Your problems are not specific to Tinode. You are having problem with your Docker setup.
