### ISSUE TITLE
Question: Concerns about large group

### ISSUE THREAD

**Issue by kuchaguangjie** [tinode/chat#689]
Hi, got a project that need to create groups of up to `5 ~ 10k` people.

**Questions:**

**1**. Will this group size cause performance issue or missing msg?
**2**. Same question as in **1**, but in case only a few people in the large group is allowed to send msg, and only up to several  msg per day.
**3**. Which database will have better performance in general? I'm concurrently considering `rethinkdb` with clustering.

**Comment by or-else** [comment]
This is neither bug report nor feature request. Please use forum for questions: https://groups.google.com/d/forum/tinode

**Comment by kuchaguangjie** [comment]
Lol ...
