### ISSUE TITLE
Can not start server

### ISSUE THREAD

**Issue by AmirGhazaei** [tinode/chat#69]
Hi,

When I exec this command
`sudo docker run --rm --name tinode-init --link rethinkdb tinode-init-db`
face with this error
`docker: Error response from daemon: Cannot link to a non running container: /rethinkdb AS /tinode-init/rethinkdb.`

When I want to start tinode-init-db with follow command
`sudo docker run tinode-init-db`
face with this error
```
2018/02/11 12:30:21 Initializing DB...
2018/02/11 12:30:21 Failed to init DB: gorethink: dial tcp :0: getsockopt: connection refused
```

Please help me to solve this problem.
Thanks

**Comment by or-else** [comment]
You have to start rethinkdb docker container first. Please follow instructions.
