### ISSUE TITLE
On switch database, local storage won't refresh.

### ISSUE THREAD

**Issue by kuchaguangjie** [tinode/chat#690]
### Browser storage won't refresh
When I switch database from rethinkdb to mysql, the browser web client has conversations of both databases shown.
`Re-login` or `F5` or `ctrl + F5`, won't make it refresh.
I have to open chrome's develop tool, and remove the `storage` by hand, then login again to make it refreshed.

#### Server-side
- [ *] Your own setup:
  * platform (Linux)
  * version of Tinode server, `0.17.7`
  * database backend: rethinkdb -> mysql
  * standalone

#### Client-side
- [ *] TinodeWeb/tinodejs: javascript client
  * Browser make and version.

### Steps to reproduce
- First use rethinkdb.
- In browser, login and chat.
- Then switch to mysql.
- In browser, login again, then conversations from both db are listed.

### Expected behaviour
On refresh or re-login, the conversation should be refreshed.

### Actual behaviour
The local storage is not updated.

**Comment by or-else** [comment]
Please describe a use case when this would happen outside of development.

> Re-login or F5 or ctrl + F5, won't make it refresh

If you are developing software then please learn and use development tools.

**Comment by kuchaguangjie** [comment]
> Please describe a use case when this would happen outside of development.
> 
> > Re-login or F5 or ctrl + F5, won't make it refresh
> 
> If you are developing software then please learn and use development tools.

What does that to do with learning development tools ???
Don't you understand the bug I describe ?
