### ISSUE TITLE
### Browser storage won't refresh

### ISSUE THREAD

**Issue by Ayuubgaajo** [tinode/chat#691]
### Browser storage won't refresh
When I switch database from rethinkdb to mysql, the browser web client has conversations of both databases shown.
`Re-login` or `F5` or `ctrl + F5`, won't make it refresh.
I have to open chrome's develop tool, and remove the `storage` by hand, then login again to make it refreshed.

#### Server-side
- [ *] Your own setup:
  * platform (Linux)
  * version of Tinode server, `0.17.7`
  * database backend: rethinkdb -> mysql
  * standalone

#### Client-side
- [ *] TinodeWeb/tinodejs: javascript client
  * Browser make and version.

### Steps to reproduce
- First use rethinkdb.
- In browser, login and chat.
- Then switch to mysql.
- In browser, login again, then conversations from both db are listed.

### Expected behaviour
On refresh or re-login, the conversation should be refreshed.

### Actual behaviour
The local storage is not updated.

__Originally posted by @kuchaguangjie in https://github.com/tinode/chat/issues/690__

**Comment by or-else** [comment]
You described a development-only scenario. If you believe this can happen in production, please list steps using a single backend with a single database which is not being reset.

**Comment by rkgarcia** [comment]
This looks like a non production request, you don't switch databases in production environment, probably you must need to migrate the data between databases

**Comment by or-else** [comment]
https://www.google.com/search?q=reset+indexeddb
