### ISSUE TITLE
device can't accept message

### ISSUE THREAD

**Issue by hzylyq** [tinode/chat#694]
### Subject of the issue
Describe your issue here.
1. first create p2p.
2. one device offline
3. the other send message
4. device login can't receive lastest message

database backend
mysql

func (a *adapter) TopicUpdateOnMessage(topic string, msg *t.Message) error {
	ctx, cancel := a.getContext()
	if cancel != nil {
		defer cancel()
	}
	_, err := a.db.ExecContext(ctx, "UPDATE topics SET updatedat=?,seqid=?,touchedat=? WHERE name=?", t.TimeNow(), msg.SeqId, msg.CreatedAt, topic)

	return err
}

should updat updatedat

**Comment by or-else** [comment]
Please fill out the bug report form completely.

**Comment by or-else** [comment]
No update was provided in 10 days. Closing.
