### ISSUE TITLE
auth0 authentication

### ISSUE THREAD

**Issue by veeramarni** [tinode/chat#698]
**Is your feature request related to a problem? Please describe.**
Is there a way to use Auth0 as an authentication server? What needs to be done to make it work?

**Comment by MarwaKhalid** [comment]
Is this feature still needed? I can attempt to work on it.

**Comment by or-else** [comment]
I don't understand this feature. I don't understand how it's supposed to work and I don't believe it's actually needed.

**Comment by or-else** [comment]
No update in 6 months. Closing.
