### ISSUE TITLE
iOS enchancement

### ISSUE THREAD

**Issue by jinfagang** [tinode/chat#70]
Hi, wondful project , any plan for iOS client ?

**Comment by or-else** [comment]
Thanks! 

The problem is that I personally don't have experience with iOS development and so far I've failed to find a volunteer to work on the iOS client. I certainly want one but have no capacity to build it just yet. Help would be much appreciated and I would support the effort as much as I can.

**Comment by jinfagang** [comment]
@or-else Hi or, I notice that you are keeping update tinode which is great. But unluckily I still not run it success. How about we establish a telegram group to keep discuss about this project? 
For my own purpose, I want build a centeralized instant message app for my own. So that I can integrate my chatbot into it and received so many informations from my chatbot. If you have a group of telegram pls let me in. If not lets build a new  one.

My telegram username is lucasjin

**Comment by or-else** [comment]
Sure, created the group and added you. Here is the invite link https://t.me/joinchat/GcxClRHBKCVt6qiLqZx8tA

**Comment by jinfagang** [comment]
@or-else Hi, there are just only one last question, almost success run server.

```
/go/bin/templ/email-validation-body.templ: no such file or directory

```
when I call this:
```
~/go/bin/server -config server/tinode.conf  -static_data example-react-js

```
what exactly happened here?

**Comment by jinfagang** [comment]
@or-else How to create account in python cli:

```
➜  tn-cli git:(master) ✗ python tn-cli.py 
Tinode command line client. Version 0.14.
Server 'localhost:6061'
tn> Connected to server:
	build: buildstamp-undefined
	ver: 0.14
201 created
hello
Unrecognized: hello
Possible commands:
	acc	- create account
	login	- authenticate
	sub	- subscribe to topic
	leave	- detach or unsubscribe from topic
	pub	- post message to topic
	get	- query topic for metadata or messages
	set	- update topic metadata
	del	- delete message(s), topic or subscription
	note	- send notification

	Type <command> -h for help
tn> acc
tn> 403 permission denied
log
Unrecognized: log
Possible commands:
	acc	- create account
	login	- authenticate
	sub	- subscribe to topic
	leave	- detach or unsubscribe from topic
	pub	- post message to topic
	get	- query topic for metadata or messages
	set	- update topic metadata
	del	- delete message(s), topic or subscription
	note	- send notification

	Type <command> -h for help
tn> login
tn> 400 malformed

```
Just got those 403 or 400 codes.

**Comment by or-else** [comment]
https://github.com/tinode/chat/issues/154
