### ISSUE TITLE
Failed to init DB: store: attept to Open an unknown adapter 'rethinkdb'

### ISSUE THREAD

**Issue by jinfagang** [tinode/chat#72]
Hi, I just build from source and got server, when I run tinode-db tool, error says:
```
2018/03/17 20:23:13 Failed to init DB: store: attept to Open an unknown adapter 'rethinkdb'
```

rethinkdb I just installed from brew and using:
```
rethinkdb --bind all --daemon
```
to started it. I think tinode-db tool is using for init that database right?
But there was an error. I dont know why I am sure these are right:
- I installed rethinkdb success, and run it;
- I build server with both mysql and rethinkdb enable, and conf file using default rethinkdb.

Any suggestion about this?

**Comment by or-else** [comment]
You need to specify appropriate tag when building from source, specifically for rethinkdb `-tags rethinkdb`. Just follow instructions.
