### ISSUE TITLE
Root user can't edit tags

### ISSUE THREAD

**Issue by markeloff86** [tinode/chat#721]
When I try to edit user's tags using root user I get the error - "replyUpdateUser: failed to update user malformed"

grpc versions:
tinode-grpc==0.16.7
grpcio==1.43.0

Request from client:
acc {
  id: "37129"
  user_id: "usr3mc90Ta_jAQ"
  tags: "basic:+79147777890"
  tags: "test_1"
}

Response from server:
ctrl {
  id: "37129"
  code: 400
  text: "malformed"
}

Server logs:
2022/01/17 15:47:39 grpc in: acc:<id:"37129" user_id:"usr3mc90Ta_jAQ" tags:"basic:+79147777890" tags:"test_1" >  j3ctkkdXj9g
2022/01/17 15:47:39 replyUpdateUser: failed to update user malformed j3ctkkdXj9g

**Comment by or-else** [comment]
Please read the API documentation:
https://github.com/tinode/chat/blob/master/docs/API.md#acc
Use forum for questions.
