### ISSUE TITLE
mysql adapter: restored subscriptions are not updated

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#722]
chat version: master

steps:
- owner creates group
```{"sub":{"id":"121805","topic":"new121803","set":{"desc":{"public":{"fn":"fn"}}},"get":{"data":{"limit":24},"what":"data sub desc"}}}```
- user joins group with default perms (JRWPS)
```{"sub":{"id":"121807","topic":"grpiXpO-RqqoBI","get":{"what":"sub desc"}}}```
- user leaves group
```{"del":{"id":"121808","topic":"grpiXpO-RqqoBI","what":"topic","hard":true}}```
- user joins group again, with a different set of permissions (JRP)
```{"sub":{"id":"73967","topic":"grpiXpO-RqqoBI","set":{"sub":{"mode":"JRP"}}}}```

Expected user subscription with `modewant: JRP` in database.
Got user subscription with `modewant: JRWPS` in database.

Sidenote: what's the meaning of `hard: true` when leaving a group? The subscription is soft-deleted with `hard: true`.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/b991f0059a2d8aa5044e2a044412a357a54f7306 together with some related problems. Thanks.

**Comment by or-else** [comment]
Released in v0.18.0-rc3
