### ISSUE TITLE
Add recover middleware 

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#724]
a ws client triggering a panic should not bring the whole server down

**Comment by or-else** [comment]
I'm sure you understand that the issue you created is not usable in any practical way. If you want to help the project, please describe the bug or a feature request in a way that is useful.

If you want to vent your frustrations, please find a different audience.

**Comment by gabriel-vasile** [comment]
I'm not sure what to do to make this issue useful to you.
Here is an article describing panic/recover: https://go101.org/article/panic-and-recover-use-cases.html

I'm also not sure you are aware, but panic immediately kills the server. Server down = bad. Server down = users disconnected. Server unexpectedly killed = hanged up transactions in mysql which in turn means locked rows in mysql until timeout.

A single user going on a panic code path should not kill the server. There are [many intentional panics](https://github.com/tinode/chat/search?p=1&q=panic%28) and [many unintentional](https://github.com/tinode/chat/issues?q=panic). Ideally these panics would be caught and handled by posting to an external service, but I know this is too much to ask.

**Comment by gabriel-vasile** [comment]
You want to patch the panic and call it a day?

**Comment by or-else** [comment]
Tinode server is not a web server. It's a stateful server. 
Unless you have something specific, please use forum for further conversation.
