### ISSUE TITLE
build fails after v0.18 proto update 

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#727]
```bash
$ go build *.go
# github.com/tinode/chat/server/plugins/users
plugins/users/plugin.go:22:2: undefined: pbx.RegisterPluginServer
```

**Comment by or-else** [comment]
I cannot reproduce.
```
% go build -ldflags "-s -w" -tags mysql -o ./releases/tmp/tinode ./server 
% 
```

**Comment by gabriel-vasile** [comment]
Maybe instead of building the server, try building a plugin?

Maybe you noticed, maybe you didn't but the error complains about missing `RegisterPluginServer`. 
Here is the [commit](https://github.com/tinode/chat/commit/0a2f0d2fb7a6e559be7009cc42335a002a021bd2#diff-167e7f64c52632a92414f044781318b286625b5ba14892a48b9f5a4c0e771ec7L3906) where you removed it and [here](https://github.com/tinode/chat/issues/665) is a sample plugin to compile.

**Comment by or-else** [comment]
> Maybe instead of building the server, try building a plugin?

Which plugin? Are you asking me to help you or telling me what to do?

> Maybe you noticed

Maybe you should consider less confrontational approach to communication.

**Comment by gabriel-vasile** [comment]
I don't get how this problem is so elusive to you. [This function](https://pkg.go.dev/github.com/tinode/chat@v0.18.0/pbx#RegisterPluginServer) is what a program needs to call to register itself as a GRPC plugin and it was removed in v0.18.1.

> Which plugin?

Any tinode GRPC plugin implementing [this service](https://github.com/tinode/chat/blob/d0a836ee3c7892dd75e80b91d63a986dbf9bdb5f/pbx/model.proto#L11-L37).
> Are you asking me to help you or telling me what to do?

I'm telling you what to do to reproduce the problem, because noticing the absence of the function is apparently impossible. 

> Maybe you should consider less confrontational approach to communication.

[No](https://github.com/tinode/chat/issues/693), [not](https://github.com/tinode/tinode-js/pull/43) [for you](https://github.com/tinode/chat/pull/609).
