### ISSUE TITLE
error while install server manually undefined: pbx.Node_MessageLoopServer

### ISSUE THREAD

**Issue by young310** [tinode/chat#729]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
error while install server

#### Server-side
- [ ] Your own setup:
  * platform ubuntu20
  *  version of Tinode server, 0.18.1
  *  database backend, mysql
  * standalone

#### Client-side
N/A

### Steps to reproduce
I use go 1.17.6
When I run 
go install -tags mysql github.com/tinode/chat/server@latest

will get following error messages:
./hdl_grpc.go:26:2: undefined: pbx.UnimplementedNodeServer
./hdl_grpc.go:38:43: undefined: pbx.Node_MessageLoopServer
./hdl_grpc.go:180:2: undefined: pbx.RegisterNodeServer
./plugins.go:233:9: undefined: pbx.PluginClient
./plugins.go:302:35: undefined: pbx.NewPluginClient
./session.go:76:11: undefined: pbx.Node_MessageLoopServer
./sessionstore.go:64:7: undefined: pbx.Node_MessageLoopServer

### Expected behaviour
Should install everything

### Actual behaviour
Stop installation with errors

### Server-side log
N/A

### Client-side log
N/A

**Comment by or-else** [comment]
You need to update dependencies, specifically gRPC & protobufers.

**Comment by young310** [comment]
@or-else 
I tired
```
go get -u google.golang.org/grpc
go get -u google.golang.org/protobuf
sudo apt install protobuf-compiler
```
with no luck
but 
`go install -tags mysql github.com/tinode/chat/server@v0.17.10` 
do work, any comments?

**Comment by or-else** [comment]
Works for me.

**Comment by gabriel-vasile** [comment]
Same issue as #727 and it's not because of outdated dependencies.
> [RegisterPluginServer](https://pkg.go.dev/github.com/tinode/chat@v0.18.0/pbx#RegisterPluginServer) is what a program needs to call to register itself as a GRPC plugin and it was removed in v0.18.1.

**Comment by young310** [comment]
@gabriel-vasile 
problem solved with missing files [https://github.com/tinode/chat/commit/19030526f25bb53f3bb639de9c6c4d09a212d24f](url)

**Comment by or-else** [comment]
> It is better to put on the references https://github.com/tinode/chat/issues/729, https://github.com/tinode/chat/issues/727 in your description

@young310 you are welcome to send a pull request.

**Comment by gabriel-vasile** [comment]
Thanks @young310 

> @or-else It is better to put on the references #729, #727 in your description

That would mean admitting there was a problem with the code.
