### ISSUE TITLE
The best way to get previews of topics?

### ISSUE THREAD

**Issue by ppaanngggg** [tinode/chat#730]
How to show previews of messages like this?

![image](https://user-images.githubusercontent.com/6350479/156496487-dba071f7-5538-490a-a693-04e236e8d601.png)

**Describe the solution you'd like**
I just can't find how to get previews of topics, any documents for this feature? If not, please tell me the correct way.

**Comment by or-else** [comment]
This is already implemented. Please look at the code.

**Comment by ppaanngggg** [comment]
> This is already implemented. Please look at the code.

Should I look into [tindroid](https://github.com/tinode/tindroid)?

**Comment by or-else** [comment]
Sure. You can look at any one of the three clients.
