### ISSUE TITLE
arango adapter

### ISSUE THREAD

**Issue by gfxlabs** [tinode/chat#732]
hi!

i use [arango](https://github.com/arangodb/arangodb) and i wanted an adapter for arango so i wrote one

the code ive been working on is here https://github.com/gfxlabs/chat/tree/master/server/db/arango

it passes the same test suite the mongodb adapter does, but i'm sure there are many things that those tests do not test for. not 100% of the process to test everything. i was able to start up the server and message between two accounts i made which was cool at least

would be glad to help merge it in if others might want it, otherwise i'll just keep it on my fork

**Comment by or-else** [comment]
Thank you for adding to the project. 

I see the following options:
1. It would be great if could make your adapter a part of the official distro. The core team members are already stretched thin though. None of us uses arango so we would not use it much other than running the tests you provided. The only way that's going to work is if you would agree to maintain the adapter on par with other adapters. That means you would need to commit some reasonable time to the project, like ~1 day per month and you would have to work on our release schedule. 
2. We can create a separate repo like "third party" in Tinode org and give you commit access to it. We will add links to the README & documentation. You would still be responsible for maintaining the adapter but on your own schedule.
3. You can continue to maintain the adapter in your own repo, we will add a link to your repo to the README and INSTALL docs.

Please let me know what works best for you.

**Comment by gfxlabs** [comment]
i don't have enough free time rn that i can comfortably commit. i think it would be easiest for me to just maintain the adapter in a different repo.

**Comment by gfxlabs** [comment]
> Do you want me to add a link to it to the main README?

sure

> add a go.mod to the root directory of your adapter. 

and gotcha,  yeah i was confusing myself, bouncing between too many things

**Comment by or-else** [comment]
I added the link to your project:
https://github.com/tinode/chat/commit/e3454d27d21ef4ca85cc18ae9c5450abe349fa51

Thanks! Closing this issue.
