### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by magicalbanana** [tinode/chat#74]
Any plans to create a docker image that's in docker hub?

**Comment by or-else** [comment]
Is this what you had in mind?
https://hub.docker.com/r/tinode/tinode-srv/

**Comment by or-else** [comment]
I believe this is now completed. See https://hub.docker.com/u/tinode/

**Comment by magicalbanana** [comment]
Just a question, but the images are updated as each release is made, right?

**Comment by magicalbanana** [comment]
It would be good if we split the databases to their own images so that it'll be easier to deploy this to Kubernetes especially if the user decides to use their own running instance of MySQL or RethinkDB.

**Comment by TaylorChristie** [comment]
@magicalbanana it already is split up. You can use the docker hub MySQL image. The tinode image only has the server, no database.

**Comment by magicalbanana** [comment]
@TaylorChristie gotcha. By the way, is there a more readable API docs? Like, how to create a user, login a user, etc. The docs provided are a bit unclear in my opinion.

**Comment by or-else** [comment]
I've updated the API doc:
https://github.com/tinode/chat/blob/devel/docs/API.md

**Comment by magicalbanana** [comment]
@TaylorChristie from the code it seems that the DB DNS is hardcoded. We need a way to specify this on runtime because let's say you deploy this to Kubernetes, it wouldn't be prudent that the DB be in the same container.

**Comment by magicalbanana** [comment]
Sorry DSN.
