### ISSUE TITLE
mysql: too many connections when there are many users in a group

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#742]
tinode version: master

### Steps to reproduce
- have a group with 200+ members (can reproduce with 100 too, but rarely)
- send a message in that group

### Expected behaviour
everything works

### Actual behaviour
```bash
tinode        | 2022/04/13 12:13:58 users: io failed for uid[ZpJXcSyXvfw]: Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: failed to load unread count for user  bMTmB27t26Y :  Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: io failed for uid[bMTmB27t26Y]: Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: failed to load unread count for user  d76BAx-fcw8 :  Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: io failed for uid[d76BAx-fcw8]: Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: failed to load unread count for user  iC8k5ydJiXw :  Error 1040: Too many connections
tinode        | 2022/04/13 12:13:58 users: io failed for uid[iC8k5ydJiXw]: Error 1040: Too many connections
```

https://github.com/tinode/chat/blob/adfb5f39029c0aacc72bd4de134ba07e538db5a9/server/user.go#L993-L999

This goroutine is spawned for each user from the group and they all hit the database at the same time.

**Comment by idestinytechlab** [comment]
This might help - https://stackoverflow.com/a/42196994

**Comment by gabriel-vasile** [comment]
Increasing `max_connections` only hides the problem. Better solution is to have that goroutine append to a channel instead. Then, a limited number of worker goroutines could process what is coming on the channel.

**Comment by idestinytechlab** [comment]
Yes it will be a good approach. that will reduce the memory footprint and connections both.

**Comment by or-else** [comment]
This should fix it: https://github.com/tinode/chat/commit/53ff98786057d38365721c937fd4698cac09be13
Mongo adapter is not yet done.

**Comment by or-else** [comment]
Released in https://github.com/tinode/chat/releases/tag/v0.18.5-rc1
