### ISSUE TITLE
pluginSubscription is not called when a user is added as member into a group

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#743]
tinode version: master

`anotherUserSub` function is not calling `pluginSubscription(sub, plgActCreate)`
https://github.com/tinode/chat/blob/adfb5f39029c0aacc72bd4de134ba07e538db5a9/server/topic.go#L1727

**Comment by or-else** [comment]
This should fix it: https://github.com/tinode/chat/commit/bd30e581c1d3ce94bc58987e744c74a6c4d18c86

**Comment by or-else** [comment]
Released in https://github.com/tinode/chat/releases/tag/v0.18.5-rc1
