### ISSUE TITLE
CORS Error when download large files

### ISSUE THREAD

**Issue by young310** [tinode/chat#745]
### Subject of the issue
I have set the "max_size": 52428800,
"cors_origins": ["*","https://s3.ap-southeast-1.amazonaws.com"],

When download large file will get CORS error messages.
small size file (<1MB) upload/download: yes/yes,
large size file (30MB) upload/download: yes/no,

#### Server-side
- [v] My own setup:
  * uBuntu20  
  * version of Tinode server, 0.17
  * database backend, mysql 8.0
  * standalone

#### Client-side
- [v] TinodeWeb/tinodejs: 0.18.2
  * Chrome 100 / Safari 15.4

### Steps to reproduce
1. upload a file large file >30MB.
2. download the file. 

###  Expected behaviour
Should successfully download the file but will get CORS err.

### Actual behaviour
Get CORS error.

### Server-side log
media serve: completed with status 307

### Client-side log
Access to XMLHttpRequest at 'https://s3.ap-southeast-1.amazonaws.com/ooxx/vxmdomse2dxus?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA3M6_something_removed_for_security_7K%2F20220427%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220427T042140Z&X-Amz-Expires=120&X-Amz-SignedHeaders=host&response-content-type=application%2Foctet-stream&X-Amz-Signature=75d4f6e00ee_something_removed_for_security_dddf2e6bf273f665c0531a36fe5e1e8ace' (redirected from 'https://_something_removed_for_security_.com:6060/v0/file/s/rdg3MkTQ70k') from origin 'https://_something_removed_for_security_.com:6060' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### comments
I tried to download with the s3 url provided in client console will work, but not from tinode server

**Comment by or-else** [comment]
Please upgrade to 0.18.x and try again.

https://github.com/tinode/chat/releases/tag/v0.17.6

**Comment by young310** [comment]
@or-else 
I tried client 0.18.5 (tinodejs/0.18.3)
and server v0.18.5-rc1
Still get the same error message, any idea?

**Comment by or-else** [comment]
Did you update your config?
https://github.com/tinode/chat/blob/master/server/tinode.conf#L87

**Comment by young310** [comment]
@or-else 
Sure, I use the old config file by -config=/path/tinode.conf.
And again, only small size file works.
Large files will return CORS errors.

**Comment by or-else** [comment]
I'm pretty sure you have misconfigured something. Please debug your issue to narrow it down to something reproducible. Tinode sandbox & prod use S3. It works.
