### ISSUE TITLE
where  the  code   receive broadcast

### ISSUE THREAD

**Issue by suzhi921** [tinode/chat#750]
User A  send  msg  to  group  B

The  server end  code broadcast  below :
case sub.broadcast <- msg

But  , where  the  code   receive broadcast

**Comment by or-else** [comment]
Please use form for questions:
https://groups.google.com/d/forum/tinode

**Comment by suzhi921** [comment]
> Please use form for questions: https://groups.google.com/d/forum/tinode

I don't have permission to post, can you tell me where to receive the broadcast?  thanks

**Comment by or-else** [comment]
Everyone has permission to post.
