### ISSUE TITLE
Update INSTALL.MD

### ISSUE THREAD

**Issue by HeroSony** [tinode/chat#764]
### Subject of the issue
I followed the doc (https://github.com/tinode/chat/blob/master/INSTALL.md) to build from the source and got the error `go get` command and found this:
From Go version 1.18 go get command will no longer install the packages. Make use of go install instead.

Could you please update the installation guidelines?

**Comment by or-else** [comment]
Updated in https://github.com/tinode/chat/commit/8a2a293106306c3cf96882e0631086718a17437e
Thanks.
