### ISSUE TITLE
Maybe this creates a deadlock problem

### ISSUE THREAD

**Issue by sodaling** [tinode/chat#768]
https://github.com/tinode/chat/blob/605bd27e653bf99893e1bee8b7e57dd2e53fdde2/server/session.go#L389

In the cleanUp function, it will purgeChannels to clear all channels. But if it appears, before atomic.StoreInt32(&s.terminating, 1), it enters the function on line 389. But after purgeChannels, s.detach <- fromTopic is executed.
Will this cause a deadlock problem?

**Comment by sodaling** [comment]
I wrote a simple demo code, roughly as follows
```golang
func main() {
	var a int32 = 0
	aChan := make(chan struct{})
	go func() {
		for {
			if atomic.LoadInt32(&a) == 0 {
				fmt.Println("enter")
				time.Sleep(time.Second * 2)
				fmt.Println("put")
				aChan <- struct{}{}
				fmt.Println("put over")
				return
			}
		}
	}()
	time.Sleep(time.Second * 1)
	atomic.StoreInt32(&a, 1)
	fmt.Println("set a to 1")
	select {
	case <-aChan:
	default:
	}
	fmt.Println("aChan is empty")
	time.Sleep(time.Second * 10)
}

```

Of course, this is an extreme situation, so I added the sleep method.
I mean, atomic.LoadInt32(&a) == 0 and s.detach <- fromTopic are not atomic, so it is possible that after I entered the critical section, system scheduling etc. (maybe). Causes purgeChannels to advance and finish first. It will never succeed until s.detach <- fromTopic is executed.
Of course, this is a very, very extreme case, and maybe it won't happen at all? I'm not very proficient in GMP scheduling and system scheduling, so maybe this is not the case at all.
Thanks for your clarification

**Comment by or-else** [comment]
Your `aChan` is unbuffered. `s.detach` is buffered.

**Comment by or-else** [comment]
Here is your code at go playground:
https://go.dev/play/p/HoVam_072gs

Here is the output:
```
enter
set a to 1
aChan is empty
put

Program exited.
```
Seems to work as expected. What's your point?

**Comment by sodaling** [comment]
```
golang
fmt.Println("put over") // will never be printed
```
This is where I am suspicious.

**Comment by or-else** [comment]
> This is where I am suspicious.

No, it is not. This
```go
	select {
	case <-aChan:
	default:
	}
```
does not wait for your go routine to write to channel, it exits immediately.

**Comment by or-else** [comment]
I believe the code in question works correctly.  This issue is neither a bug report nor a feature request. 
Please move this conversation to google groups.

**Comment by sodaling** [comment]
Yep, that's what I just said. If purgeChannels is entered after atomic.LoadInt32(&a) == 0, but completed before aChan <- struct{}{}, it is possible that the effect of draining the channel cannot be achieved?
Of course, you were right, if there was a buffer, it would be fine

**Comment by or-else** [comment]
Sorry, this is not the right place for this conversation. I believe there is no bug. If you feel otherwise, please conclusively show the bug. Thank you.

**Comment by sodaling** [comment]
I believe the code in question works correctly too.I am also just a beginner in golang im serving. There is indeed some ambiguity about concurrency. Thanks also for your patience.

**Comment by sodaling** [comment]
I made a post in the discussion group. Maybe it's not quite in line with the specification, I hope someone who sees here can give me an answer. Many thanks!
https://groups.google.com/g/tinode/c/nU0DudzO2ko

**Comment by sodaling** [comment]
> > If purgeChannels is entered after atomic.LoadInt32(&a) == 0
> 
> @sodaling I think this never happens. `purgeChannels` is called after atomically setting `s.terminating` to 1 and there is no other goroutine setting it back to 0.
> 
> > if there was a buffer, it would be fine
> 
> Buffered channels block too if they are full so a buffer is not fixing it (if there was an issue).

I know that after s.terminating is set to 1, no other goroutine will be reset to 0. 
https://github.com/tinode/chat/blob/605bd27e653bf99893e1bee8b7e57dd2e53fdde2/server/session.go#L389-L390
What I actually want to express is:  **atomic.LoadInt32(&a) == 0**  and **s.detach <- fromTopic** these two actions It is not atomic, so will the following timeline sequence occur?: 
 1. if atomic.LoadInt32(&a) == 0(by goroutine a)(now a is 0).
 2. atomic.StoreInt32(&s.terminating, 1) (by goroutine b)(now a is 1).
 3. s.purgeChannels()(by goroutine b).
 4. s.detach <- fromTopic (by goroutine a) Then start blocking forever.


I was really confused for a while, and my question has nothing to do with whether this channel has a buffer. Unfortunately, I am not very good at expressing my thoughts, and I can't think of a good code to demonstrate or refute this extreme situation I said.

**Comment by gabriel-vasile** [comment]
Oh, I understand now, your explanation makes sense.

**Comment by sodaling** [comment]
> Oh, I understand now, your explanation makes sense.

Thank God! Someone finally figured out my ambiguous expression.
So, is this very extreme scenario I'm talking about possible?
Or is it purely because my basic knowledge is not good enough that my understanding is biased?

**Comment by sodaling** [comment]
@or-else 
I probably added my description, a guy understands what I want to express. Can you take a look at it easily? Thank you very much

**Comment by gabriel-vasile** [comment]
I'm not sure if a deadlock is what happens at the end of the situation (if we assume `s.detach` is blocking because it's full).

[sess.writeLoop](https://github.com/tinode/chat/blob/605bd27e653bf99893e1bee8b7e57dd2e53fdde2/server/hdl_websock.go#L83) is the goroutine consuming from `s.detach` channel and this goroutine is not stopped at point 4. in explanation. 

But what if point 4. happens before point 3.? Seems like a topic from `s.detach` ends up discarded by [purgeChannels](https://github.com/tinode/chat/blob/605bd27e653bf99893e1bee8b7e57dd2e53fdde2/server/session.go#L399-L409) instead of being processed [here](https://github.com/tinode/chat/blob/605bd27e653bf99893e1bee8b7e57dd2e53fdde2/server/hdl_websock.go#L131-L132). Is this an issue? I don't know.

In any case, congrats @sodaling for noticing this subtle situation.

**Comment by sodaling** [comment]
@gabriel-vasile 
I personally think the crux of the problem is: 

> **atomic.LoadInt32(&s.terminating) == 0** and **s.detach <- fromTopic** these two actions It is not atomic.


Use atomic.LoadInt32(&s.terminating) to mark this scene Bit is not necessarily a good idea, maybe it would be better to use context or close a stop channel. I'm just curious, the extreme situation I'm talking about has been considered by contributor, and it can't happen, or is it just a momentary negligence and no consideration.
Thank you very much for your patient reply, it has inspired me a lot.
