### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by imikiani** [tinode/chat#77]
Please provide OAuth2 integration.

**Comment by or-else** [comment]
There is no vanilla _OAuth2 integration_, there is _OAuth2 Google_, _OAuth2 FB_, _OAuth2 Amazon_, etc. Which one are you looking for? Or maybe I misunderstood your request?

**Comment by imikiani** [comment]
@or-else How can we use for example Google and Facebook authorization server? But also could you please provide an interface so that developers could be able to integrate tinode chat with their custom authorization server?

**Comment by or-else** [comment]
> How can we use for example Google and Facebook authorization server?

I don't see how to add OAuth2 in a generic way. I can integrate FB or G, but then every other OAuth2 provider still needs to be handled individually. It looks like a very heavy feature. Look at the number of possible OAuth2 providers: https://github.com/golang/oauth2

Maybe you can help me out here? Send a pull request?

> But also could you please provide an interface so that developers could be able to integrate tinode chat with their custom authorization server?

It already exists. For instance, see discussion here: https://github.com/tinode/chat/issues/79

**Comment by imikiani** [comment]
Thank you. Yes, of course. I'll send you a PR.

**Comment by or-else** [comment]
Thanks, closing the issue.
