### ISSUE TITLE
Reverse Proxy (IIS aplication request router)

### ISSUE THREAD

**Issue by piratov** [tinode/chat#776]
If http://localhost:6060
Logging in is possible.

If you use http://localhost without a port
Website opens but can't login 503 error
Connection failed 503

IIS 10 web.config 
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:6060/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

---------
Если http://localhost:6060
Залогиниться возможно.

Если использовать http://localhost без порта
Открывается сайт но залогиниться невозможно 503 ошибка 
Connection failed 503

**Comment by or-else** [comment]
I do not believe this is a Tinode bug.

**Comment by piratov** [comment]
Can you advise me. Is it possible to somehow specify the address in the config tinode.conf? 
`"listen": ":6060",`

In order not to specify an additional address in the connection settings http://localhost/#settings By default, the address is localhost. 
<img src="https://user-images.githubusercontent.com/17856390/182303671-bbc29fe0-ac85-4613-9197-c278dcc2b415.png" width="200" height="70">

The console is trying to connect...but without an address
<img src="https://user-images.githubusercontent.com/17856390/182306090-4fdad458-5b3b-4f9d-b43a-92968e6b9589.png" width="200" height="50">

Where it is impossible to log in 503 error
<img src="https://user-images.githubusercontent.com/17856390/182304278-b5e52b0f-32bb-469c-bc10-69bcc946845b.png" width="200" height="120">

If you edit the connection address, add port: 6060 (localhost: 6060) Then the authorization works.
<img src="https://user-images.githubusercontent.com/17856390/182304345-75eb346b-fdc2-4eb2-a660-1b0eed749a01.png" width="200" height="100">

The message will be endless until you click "Try now".
<img src="https://user-images.githubusercontent.com/17856390/182304437-2f750256-c9a4-4eed-8478-b1e90912fc7b.png" width="200" height="120">

**Comment by piratov** [comment]
Debug status 
Before trying to connect
`{"server_version":"0.19","build_id":"undef","ts":"2022-08-02T06:56:33.407Z","topics":[{"topic":"sys","xorig":"sys"}]}`

During 503 errors
`{"server_version":"0.19","build_id":"undef","ts":"2022-08-02T06:59:03.08Z","sessions":[{"remote_addr":"[::1]:54847","sid":"CUFmQwx_iwY"},{"remote_addr":"[::1]:54855","sid":"SC1MFZX3bYM"}],"topics":[{"topic":"sys","xorig":"sys"}]}`

When to add a port in connection settings
`{"server_version":"0.19","build_id":"undef","ts":"2022-08-02T07:07:22.877Z","sessions":[{"remote_addr":"192.168.1.4:7510","ua":"TinodeWeb/0.20.0-beta3 (Chrome/97.0; Win32); tinodejs/0.20.0-beta3","sid":"3rqTI8AI9r8"}],"topics":[{"topic":"sys","xorig":"sys"}]}`

**Comment by or-else** [comment]
Please use form for questions
