### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by ultrasahand** [tinode/chat#78]
Error 1071: i tried everything, changed the storage engine, run some global query as instructed on different sites, nothing worked

**Comment by or-else** [comment]
Please provide more details: server version, database backed, installation method (docker, binary, etc).
Where did you get this error message - client or server. Show the full log. What were you doing when you got the error. Describe exact steps to reproduce.

**Comment by ultrasahand** [comment]
for those with this error

```
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Downloads\tinode>init-db.exe
2018/04/23 16:00:19 Initializing DB...
2018/04/23 16:00:20 Failed to init DB: Error 1071: Specified key was too long; max key length is 1000 bytes
```

on mysql my.ini change this line: 
`default-storage-engine=MYISAM`
with this:
`default-storage-engine=InnoDB`

and restart mysql service

**Comment by or-else** [comment]
Update you MySQL to 5.7 or pull from devel branch.

**Comment by ultrasahand** [comment]
mysql is 5.7.14
i'm using latest wamp server on win10
if this thread causes any misguidance please remove it

**Comment by or-else** [comment]
> if this thread causes any misguidance please remove it

You are not giving me enough information to work on. I want to help but this is not enough to reproduce the problem.

The issue theoretically might have happened on 5.6 or below. '1000 limit' is consistent with <=5.6. In 5.7 this limit has increased to 3072 which should be plenty enough to index a utf-8 varchar(255). The fact that you are getting it on 5.7 means you likely have some non-default setting in your mysql instance. 

I shortened some indexed fields in `devel`. Have you tried it as I suggested?

Try these:
https://stackoverflow.com/questions/40109903/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

https://hungnhotblog.wordpress.com/2016/10/06/error-1071-specified-key-was-too-long-max-key-length-is-767-bytes-when-import-mysql-db/

**Comment by ultrasahand** [comment]
i'm so sorry
all i'm saying is that I fixed the issue by switching MySQL storage engine
I tried it on my Win10 64bit, I have latest Wamp server(3.0.6 64bit), MySQL version is 5.7.14(i never customized the ini file).
what fixed the issue was setting GLOBAL storage_engine='InnoDb' (it's also mentioned on the first site that you mentioned)

> MyISAM has a limit of 1000 bytes for indexes. InnoDB has an even smaller limit (767 bytes) unless you're on MySQL 5.7.7+, in which case the limit is 3072 bytes by default.

I'll try another clean install with devel tomorrow.
Chat server is working super fine
if you need specific information let me know

**Comment by or-else** [comment]
Is working now, including with MyISAM?

**Comment by or-else** [comment]
Closing.
