### ISSUE TITLE
Start chat by presenting and scanning QR code

### ISSUE THREAD

**Issue by piratov** [tinode/chat#784]
https://groups.google.com/g/tinode/c/xYcemyHlQbI

**Describe the solution you'd like**
Add additional ability to search ID by QR code Show and read ID as QR code
It is convenient to show the representing ID (user, group or channel) as a QR code, not only as text.
Sometimes just showing a QR code with an ID is easier. Than to send a text ID as a result, it is still to be searched for in the search. QRcode will save time and make ID search easier.

**Describe alternatives you've considered**
Authorization by QR code or invite user inside Tinode.
Follow links by QR code.
Share links of various information .. groups, channels, users etc.

**Additional context**
As an option, add buttons (like an icon) to get a QR code next to the ID text.
In the search by ID, add the ability to read from the camera (where you can add as an image) QR code.

**Comment by or-else** [comment]
This is in `next`.

**Comment by or-else** [comment]
Released in 0.22
