### ISSUE TITLE
A lost user without the ability to complete registration or authorization to the end - user not found (404)

### ISSUE THREAD

**Issue by piratov** [tinode/chat#785]
If you want to ask a question, please post to https://groups.google.com/d/forum/tinode instead.
https://groups.google.com/g/tinode/c/xYcemyHlQbI

**Describe the bug**
There are users in the database who do not have the opportunity to complete the registration to the end or resume registration or authorization to continue.
When I try to log in with these users, I get a message - user not found (404).

**To Reproduce**
There is still some kind of collision during registration or authorization that I have not tracked.

**Expected behavior**
When I try to log in with these users, I get a message - user not found (404). And new users cannot be registered with these logins.

**Screenshots**
![Screenshot_12](https://user-images.githubusercontent.com/17856390/186614890-f784d701-cb84-48fa-a514-82a01ab71e5f.png)
![Screenshot_14](https://user-images.githubusercontent.com/17856390/186614968-e06696f3-0886-4fa5-9c64-88f1c3d26765.png)

Found in base of coincidence of similar behavior. The "credentials", "usertags" table does not have an entry about the user ("userid"). But there is ("userid") in the "auth" table and in the "users" table.
Characteristically similar values ​​for such users in the "users" table are "state" = 20, "stateat" = "date" and "tags" = "null" (string null).

**Environment (please complete the following information):**
 - OS: [Windows]
 - Browser [ALL]
Server v0.20 - https://github.com/tinode/chat/tree/next
Client: TinodeWeb/0.20.0-rc1 (tinodejs/0.20.0-rc1) and Android 0.20 from here https://github.com/tinode/tindroid/tree/next

**Console log**
server console
I2022/08/25 10:38:13 ws: session started voIj1ed05Fs IP-ADDRESS:51275 1
I2022/08/25 10:38:13 in: '{"hi":{"id":"101865","ver":"0.20.0-rc1","ua":"TinodeWeb/0.20.0-rc1 (Chrome/97.0; Win32); tinodejs/0.20.0-rc1","lang":"en-US","platf":"web"}}' sid='voIj1ed05Fs' uid=''
I2022/08/25 10:38:13 in: '{"login":{"id":"101866","scheme":"basic","secret":"dGVzdDI6MTIzNDU2"}}' sid='voIj1ed05Fs' uid=''
W2022/08/25 10:38:13 s.login: user state check failed gOad5Xe2oPI user not found voIj1ed05Fs

console browser
[07:39:55.570] out: {"hi":{"id":"117135","ver":"0.20.0-rc1","ua":"TinodeWeb/0.20.0-rc1 (Chrome/97.0; Win32); tinodejs/0.20.0-rc1","lang":"en-US","platf":"web"}} 
tinode.js:472 
[07:39:55.572] in: {"ctrl":{"id":"117135","params":{"build":"mysql:undef","maxFileUploadSize":8388608,"maxMessageSize":262144,"maxSubscriberCount":128,"maxTagCount":16,"maxTagLength":96,"minTagLength":2,"ver":"0.20"},"code":201,"text":"created","ts":"2022-08-25T07:39:55.572Z"}} 
tinode.js:472 
[07:39:55.585] out: {"login":{"id":"117136","scheme":"basic","secret":"dGVzdDI6MTIzNDU2"}} 
tinode.js:472 
[07:39:55.665] in: {"ctrl":{"id":"117136","code":404,"text":"user not found","ts":"2022-08-25T07:39:55.587Z"}} 

**Additional context**
I'm testing the registration and authorization of users for various events. Such as restarting the browser, applications, turning off the Internet, etc. There are two users about which there are records in the database, but they cannot be authorized.

**Comment by aforge** [comment]
`users.state` 20 means `StateDeleted`.
Can you post steps to reproduce the registration part for such users please?

**Comment by piratov** [comment]
Tried to delete the user. Removal occurs by completely removing all `auth` `credentials` `users` `usertags` records about the user without users.state 20

![Screenshot_21](https://user-images.githubusercontent.com/17856390/186688471-0a9074a0-f639-4ccb-9b54-74078f6c1cb4.png)

> Can you post steps to reproduce the registration part for such users please?
Unfortunately I can not.

**Comment by piratov** [comment]
Additionally, I noticed such a feature. If you change the user's password. Then previously opened sessions on other devices and applications with this user will still continue to work with the old password that does not exist.

Maybe add some security? For example, after changing the password, users will be logged out in all sessions of this user and not just the one who changed the password.

**Comment by piratov** [comment]
Maybe I understand the reason.
Duplicate credential (409) message during new user registration. But such a user was not in the database before registration.
This user is created in the `auth` and `users` tables.

**id**	`1039400374202535936`
**createdat**	`2022-09-01 09:52:02.708`
**updatedat** `2022-09-01 09:52:02.790`	
**state** `20`
**stateat** `2022-09-01 09:52:02.790`
**access** `{"Anon": "N", "Auth": "JRWPAS"}`
**lastseen** `\N`
**useragent** `  `
**public** `{"fn": "testet65"}`
**trusted** `\N`
**tags** `null`
							
Duplicate mail causes this behavior on registration. If the user already exists with a similar mail. Then subsequent registration for the same mail resulted in a duplicate credential error (409).

Duplicate logins are not written to the database as with duplicate mail.

**Comment by or-else** [comment]
If it's indeed the case, then the simplest fix is https://github.com/tinode/chat/issues/707

**Comment by piratov** [comment]
> Duplicate logins are not written to the database as with duplicate mail.

This can lead to spammy uncontrolled creation of records in the database during registration with the same mail.

**Comment by or-else** [comment]
The current scheme is intentional: it prevents malicious entity from easily collecting registration emails.

**Comment by or-else** [comment]
> This can lead to spammy uncontrolled creation of records in the database during registration with the same mail.

You can just as easily create records using completely fake emails.
