### ISSUE TITLE
gRPC failed with StatusCode: UNKNOWN: Failed to connect to remote host: Connection refused

### ISSUE THREAD

**Issue by Saad17** [tinode/chat#788]
**server side**

- local machine setup:
- platform: Linux (Ubuntu 20.04.5 LTS)
- version of tinode server: Version 0.18
- database:  tinode/tinode-mongodb:latest 

**Steps to reproduce:**
 Run server through docker version: 20.10.17
Follow these commands:

- docker network create tinode-net
- docker run --name mongodb --network tinode-net --restart always -d mongo:6 --replSet "rs0"
- docker exec -it mongodb mongosh

then type:

- rs.initiate( {"_id": "rs0", "members": [ {"_id": 0, "host": "mongodb:27017"} ]} )
- quit()
- docker run -p 6060:6060 -d --name tinode-srv --network tinode-net tinode/tinode mongodb:latest

### Server Status: running at localhost:6060/

**Client-side**

- tinode chatbot
- python version: Python 3.8.10
**Run command Line client**
python chatbot.py --login-basic=alice:alice123

### Actual behaviour:

2022-09-07 08:58:53.047 Disconnected: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
**Exception Iterating**

**Run through docker**
run this command:

- docker run -d --name tino-chatbot --network tinode-net --volume botdata:/botdata tinode/chatbot:latest

### Response: 

Unable to find image 'tinode/chatbot:latest' locally
latest: Pulling from tinode/chatbot
b85a868b505f: Pull complete 
e2be974225ed: Pull complete 
b41d2e1d1937: Pull complete 
f6edef4f72a4: Pull complete 
3968cb080aab: Pull complete 
44decc95854f: Pull complete 
4f4fb700ef54: Pull complete 
432560fd690c: Pull complete 
f1e0215b128f: Pull complete 
3203a51086b7: Pull complete 
Digest: sha256:810f1aff57082b054529128145e5ce0a69ee0e4a870fe54fc4ca823e980fe425
Status: Downloaded newer image for tinode/chatbot:latest
073eae560fe5f6cfe7ecb9e7b07078e47183463fabb777284954a0d6f9eb3e26

### Actual behaviour:

- Happend nothing

**docker ps -a**

CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                     PORTS 
073eae560fe5   tinode/chatbot:latest          "/bin/sh -c 'python …"   2 minutes ago   Exited (0) 2 minutes ago   tino-chatbot                                       
e39ea6bcf03c   tinode/tinode-mongodb:latest   "/bin/sh -c ./entryp…"   4 minutes ago   Created  tinode-client-self-created                                                                               
e5dc08c1d33e   tinode/tinode-mongodb:latest   "/bin/sh -c ./entryp…"   3 hours ago     Up 3 hours                 12000-12003/tcp, 0.0.0.0:6060->6060/tcp, :::6060->6060/tcp, 16060/tcp   tinode-srv
11e06d28468d   mongo:6     "docker-entrypoint.s…"   3 hours ago     Up 3 hours      27017/tcp     mongodb  

Client side log:
Run this command:
- docker logs 073eae560fe5

 tinode/chatbot:latest  == > not show any log.
tinode/tinode-mongodb:latest  == > not showing any log.
**tinode/tinode-mongodb:latest (e5dc08c1d33e) :  status**

2022/09/07 06:39:22 Database adapter: 'mongodb'; version: 112
2022/09/07 06:39:22 Database not found. Creating.
2022/09/07 06:39:22 Database initialized
2022/09/07 06:39:22 Generating users...
2022/09/07 06:39:23 Generating group topics...
2022/09/07 06:39:23 Generating P2P subscriptions...
2022/09/07 06:39:23 Generating group subscriptions...
2022/09/07 06:39:23 Inserting messages...
2022/09/07 06:39:23 Inserting forms as  tino 6vROGTI5CBw
2022/09/07 06:39:24 All done.

**mongo:6 (11e06d28468d): status** 

{"t":{"$date":"2022-09-07T06:37:38.401+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}

**Comment by or-else** [comment]
> docker run -p 6060:6060 -d --name tinode-srv --network tinode-net tinode/tinode mongodb:latest
> 2022-09-07 08:58:53.047 Disconnected: <_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE

`-p 6060:6060` is the HTTP port. You did not export the gRPC port (default 16060), consequently you are unable to connect to it from outside of the docker.

> docker run -d --name tino-chatbot --network tinode-net --volume botdata:/botdata tinode/chatbot:latest
> Happend nothing

What did you expect to happen?

Regardless, I don't think this is a bug in Tinode. You just misconfigured something or it's a misunderstanding. Please use forum for further questions.

**Comment by Saad17** [comment]
It helps a lot, thank you so much.
