### ISSUE TITLE
subscription should be checked for target, not for asUid

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#789]
https://github.com/tinode/chat/blob/ebcb536d79b57fe04cfde5b239dd768c798a9c17/server/topic.go#L1812

Subscription should be checked for `target`, not for `asUid` because it needs to be created for `target`.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/3f3de82f720abd406eae22941b9e32990047100d. Thanks.
