### ISSUE TITLE
Feature request User based on a rest API

### ISSUE THREAD

**Issue by fstn** [tinode/chat#79]
### Subject of the issue
My users are stored in my remote application, I can't access and query the database. The only way that I have to authenticate a user is to call a rest API. Is it a way to Tinode to work with an empty user table and use a rest API for users?

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

**Comment by or-else** [comment]
If the question is about authentication only then yes, it's straightforward. All you need to do is implement this interface: https://github.com/tinode/chat/blob/master/server/auth/auth.go

Take a look at some authenticators here: https://github.com/tinode/chat/tree/master/server/auth
For instance, token authenticator does not use a database at all
https://github.com/tinode/chat/blob/master/server/auth/token/auth_token.go

If you want to keep data in two databases, users in one and everything else in another, that's also possible but tricky.

If you need help or have questions, please let me know.

**Comment by fstn** [comment]
Thank you ;)

Ok for the adapter, I will try ;)

Regarding the tag option, I have some security issue. I need to limit the found people with the group.  Users from different groups must not see each other. 
I can't just filter it on the client side, **do I have a way to code a middleware on the server side that filter Fnd query for topics and user ?**


Concerning the tags, this is what I imagined:
![imagine](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=VXNlci0-VGlub2RlOiBBdXRoZW50aWNhdGlvbiBSZXF1ZXN0CgAZBi0-TG9naW5BbmRUYWdzUHJvdmlkZXIAHBkAGRQAYApvay9mYWlsICsgVEFHUwBZCVVzZXI6IFJlc3BvbnNlICsgVG9rZW4K&s=napkin)
So there is no need of inviting, tags are given by the LoginAndTagsProvider during the login. So it will update (create,remove) tags at every user login... **does it make sense?**

**Comment by fstn** [comment]
> It's easy to make sure they cannot find each other using fnd. But, say, if you and I meet by the water-cooler and exchange IDs, I will be able to open a p2p chat with you regardless of group membership. Blocking such contacts would be hard.

Ok this seems to be ok ;) Where can I add the middleware to filter this? I saw something call plgTopicFnd can I add a plugin to do that?

> Yes, it makes sense and it seems to be the most straightforward solution. If something is currently missing, I can add it. The side effect of this scheme will be that tag changes (group membership changes) will require a re-login.

Thank you

**Comment by fstn** [comment]
It would be awesome 😎 

Do you know approximately  when you can supporting it?

Thank you, it’s really a pleasure to talk with you.

**Comment by or-else** [comment]
That depends on how fast you are willing to move. I need to finish the #hash navigation in the client then I can take the next feature. You are going to need to write an adapter. It will take you a couple of days at least.

**Comment by fstn** [comment]
Great ;)

**Comment by or-else** [comment]
@fstn A question for you.

Suppose user Alice belongs to two groups `group:a` and `group:b`. Suppose Alice creates a group chat `MyChat`. What groups should it be assigned to?

1. It should be assigned to both `group:a` and `group:b`, Alice cannot change that.
2. Same as above, but Alice can change it. If so, what should be the limit on the changes, if any? I.e. can Alice add `MyChat` to `group:c` too? Can she remove both `group:a` and `group:b`? Can she add/remove `group:a` and/or `group:b` but not add `group:c`?
3. `MyChat` should not be assigned to any groups by default, Alice can edit group membership for `MyChat` freely.

**Comment by fstn** [comment]
@or-else 

For us, Alice must select her group before adding MyChat. 
Same as Slack, your select your organization first (group:a), next your channel or group (group:a:channel1 or group:a:group1). You can't mix channel or group between organization.

So MyChat is assign to group:a and only group:a if Alice as select the organization a...

I don't know if I'm clear ;)

Thank you

**Comment by or-else** [comment]
Does it mean that Alice can belong to one organization (tag) at a time only, i.e. `group:a` in this example?

I don't use Slack much so I don't know the details there.

**Comment by fstn** [comment]
Ok, imagine Alice belongs to group:a and group:b

After the login, Alice select group:a, she can only see group:a channels, after she switch to group:b she can only see group:b channels.

I think that this filter will be in the view (client js side). 

If she wants to create a new channel the new channel is added to the current selected group (will be in the client js side).

**Comment by or-else** [comment]
OK, that makes sense. 

For me that means that if Alice has tags `group:a` and `group:b` she can assign `group:a` and/or `group:b` to `MyChat` (all client-side). In other words, the server will enforce that Alice assigns to MyChat only those tags, which she has herself, i.e. assignment of `group:c` will be rejected on the server. All other logic will be left to the client.

**Comment by fstn** [comment]
I's exactly that ;)

**Comment by or-else** [comment]
Here you go: https://github.com/tinode/chat/pull/90

**Comment by or-else** [comment]
I think this is pretty much covered by now. If you think there is more work to be done let me know and I'll reopen.

**Comment by tiagoalves** [comment]
> It's easy to make sure they cannot _find_ each other using `fnd`.

@or-else, can you elaborate how one can disable users finding each other using `fnd`?

**Comment by tiagoalves** [comment]
> If the question is about authentication only then yes, it's straightforward. All you need to do is implement this interface: https://github.com/tinode/chat/blob/master/server/auth/auth.go
> 
> Take a look at some authenticators here: https://github.com/tinode/chat/tree/master/server/auth
> For instance, token authenticator does not use a database at all
> https://github.com/tinode/chat/blob/master/server/auth/token/auth_token.go

@or-else, are authenticators just created by writing new `.go` files in `chat/server/auth/`  and recompiling the server or can they be created as external daemons using the gRPC Plugin interface?

**Comment by or-else** [comment]
@tiagoalves

>  can you elaborate how one can disable users finding each other using fnd?

The use case fstn was looking for was to separate users into teams. That's done by assigning mandatory tags. Then only users within a team can find each other.
If you want to completely disable the feature for all or some users just don't assign any tags. Users without the tags cannot be found.

More info here: https://github.com/tinode/chat/blob/master/docs/API.md#fnd-and-tags-finding-users-and-topics

**Comment by or-else** [comment]
@tiagoalves

> are authenticators just created by writing new .go files in chat/server/auth/ and recompiling the server or can they be created as external daemons using the gRPC Plugin interface?

I suppose it depends on what you want but most cases I can think of can be addressed without the gRPC. 

For instance, if you decide to add an LDAP authenticator you would need to write a go file to call your LDAP server. It's a network call but it does not use gRPC. If your account credentials are stored in a database then you'd need to write a go file which communicates with the database.

**Comment by or-else** [comment]
BTW, it might be easier to post here: https://groups.google.com/d/forum/tinode
