### ISSUE TITLE
'go get' is deprecated.

### ISSUE THREAD

**Issue by SMAH1** [tinode/chat#799]
I use go version 1.19.3 to compile. When use command:

```bash
go get -tags mysql github.com/tinode/chat/server && go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server
```

Mesasge show that 'go get' is deprecated. I compile by command like:

```bash
go build -tags mysql -o $GOPATH/bin/tinode github.com/tinode/chat/server
```

It's worked.
Are you want change INSTALL.md?

**Comment by or-else** [comment]
I'm not sure where you found instructions to use `go get`. INSTALL.md recommends `go install`.

**Comment by SMAH1** [comment]
https://github.com/tinode/chat/blob/4f861246426780739060ef53bb9f7b55ea738be4/INSTALL.md?plain=1#L71-L73

**Comment by or-else** [comment]
This recommendation is specifically for older versions of Go.

**Comment by SMAH1** [comment]
Please add note for current go compiler that need use `go build -tags mysql ...` only

**Comment by or-else** [comment]
What's wrong with the current recommendation `go install -tags mysql github.com/tinode/chat/server@latest`?

**Comment by SMAH1** [comment]
Show message about 'go get' is `deprecated`. This may cause confusion.

**Comment by or-else** [comment]
As I said before, the recommendation to use `go get` is specifically for older versions of Go when it was not yet deprecated. Given this conversation going in circles, I'm closing this issue.
