### ISSUE TITLE
chat server run error

### ISSUE THREAD

**Issue by DanRui** [tinode/chat#80]
### Subject of the issue
Hi, After I install the chat server and just run from the command line:

$GOPATH/bin/server -config=$GOPATH/src/github.com/tinode/chat/server/tinode.conf -static_data=$HOME/tinode/example-react-js/

the log output is:

2018/04/24 23:28:57 Server 'v0.14:undefined:'; pid 31911; started with 4 process(es)
2018/04/24 23:28:57 Using config from '/home/dr/gocode/src/github.com/tinode/chat/server/tinode.conf'
2018/04/24 23:28:57 Running as a standalone server.
2018/04/24 23:28:57 Closed database connection(s)
2018/04/24 23:28:57 All done, good bye
panic: open /home/dr/gocode/bin/templ/email-validation-body.templ: no such file or directory

goroutine 1 [running]:
main.main()
	/home/dr/gocode/src/github.com/tinode/chat/server/main.go:247 +0x1b07

what's wrong with it ? The go version is 1.10.

**Comment by or-else** [comment]
Just like the error message says `open /home/dr/gocode/bin/templ/email-validation-body.templ: no such file or directory` -- it can't find email template at the specified path. Open `tinode.conf` and update it with correct path to email template. In your case it's probably `/home/dr/gocode/src/github.com/tinode/chat/server/templ/email-validation-body.templ`.
