### ISSUE TITLE
Sign up users manually only

### ISSUE THREAD

**Issue by SMAH1** [tinode/chat#805]
We have a small office. We have shared information/file/text between us. We try to use tinode for internal communication. It is light and enough.
But some feature is missing!
1) We want initialize databse by `init-db`:

* Add picture from other path
* Add user after initialize DB by `init-db`
* Not add extra tags like __basic:*__ and  __email:*__

2) Close sign up user. (Not support in UI and Server)

**Comment by or-else** [comment]
As I mentioned earlier, `init-db` is not intended to be used for managing users in a live server. It changes the database directly. You would have to shut down the server, make changes with `init-db`, restart server. 

Have you looked at [tn-cli](https://github.com/tinode/chat/tree/master/tn-cli)? It is intended to manage users in a live server.

**Comment by SMAH1** [comment]
If _'Close sign up user'_, How do use `tn-cli` for register new user?

**Comment by or-else** [comment]
Please read the instructions. If you have further question, please direct them to the forum.
