### ISSUE TITLE
[webapp] Include in translation to title tags

### ISSUE THREAD

**Issue by piratov** [tinode/chat#808]
There is untranslated text.
example
![Screenshot_14](https://user-images.githubusercontent.com/17856390/204136585-371140cf-49ec-4010-860e-40bd2dafb998.png)

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/webapp/commit/7731c6700bd3cc2eabb09f86b421f1a23366182b

**Comment by piratov** [comment]
Thanks
