### ISSUE TITLE
How to connect my Mysql with password?

### ISSUE THREAD

**Issue by Medesol** [tinode/chat#81]
### Subject of the issue
I'm using MySQL and Mac os. I followed the instruction of "installing from binaries". The instruction said that in case of MySQL, Tinode will try to connect as root without the password. But I have assigned the root user of MySQL a password. As a result, the terminal returns this:
`2018/04/25 21:14:22 Initializing DB...
2018/04/25 21:14:22 Failed to init DB: Error 1045: Access denied for user 'root'@'localhost' (using password: NO)`
My question is that is there a method that I can make tinode to connect with mysql with a password? Otherwise, must I reset my root password?

### Your environment
platform: Mac
version of tinode server: v0.14.6-rc1
database: mysql
client: android

**Comment by or-else** [comment]
Open the config file `tinode.conf`, find the section `mysql`, in that section there is a line `dsn` which defines mysql connection parameters. Update it with your authentication credentials. A few examples can be found here https://github.com/go-sql-driver/mysql/blob/master/README.md

**Comment by Medesol** [comment]
Thank you very much. I have figured this out. But I still have a few questions.

1. Is there any method by which I can modify your backend code? I find only some html and js files in the directory. 

2. Maybe the init-db should drop the previous database and create a new one when it finds a database called tinode, instead of throwing an exception without doing anything.

**Comment by or-else** [comment]
> Is there any method by which I can modify your backend code? I find only some html and js files in the directory.

Not sure where you see the problem. All the code is hosted here on github. See instructions for building from source: https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source

> Maybe the init-db should drop the previous database and create a new one when it finds a database called tinode, instead of throwing an exception without doing anything.

It does: https://github.com/tinode/chat/blob/master/server/db/mysql/adapter.go#L174

**Comment by Medesol** [comment]
Oh, sorry. That is because I downloaded the release "tinode-mysql.darwin-amd64.tar.gz
" version. That doesn't contain those source code.
