### ISSUE TITLE
auth: failed to update secret Error 1292: Incorrect datetime value: '0000-00-00' for column 'expires' at row 1

### ISSUE THREAD

**Issue by duynguyenkhanh** [tinode/chat#82]
### Subject of the issue
Failed to update secret of user.

### Is this a bug report of a feature request?
- [ X] Bug report
- [ ] Feature request

### Your environment
* platform: Linux
* version of tinode server: 0.14.6 rc 2
* database backend: MySQL
* which client used (javascript, android, cli) and its version: javascript

### Steps to reproduce
1. Logon.
2. Edit Account.
3. Enter new password.
4. Press Enter.

### Server-side log
auth: failed to update secret Error 1292: Incorrect datetime value: '0000-00-00' for column 'expires' at row 1

### Client-side log
Error: internal error (500)

**Comment by or-else** [comment]
Thanks for the report. Fixed: https://github.com/tinode/chat/blob/devel/server/db/mysql/adapter.go#L476
