### ISSUE TITLE
Android client no longer generates notifications

### ISSUE THREAD

**Issue by don-e-johnson** [tinode/chat#837]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
After upgrading to the latest release (0.21.6 March 9th) my Android client no longer generates notifications for incoming messages.

#### Server-side
- [ ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [ ] Your own setup:
  * platform: unknown 
  * version: unknown
  * database backend
  * cluster or standalone

#### Client-side
- [ X ] Tindroid: Android app (0.21.6)
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] Tinodios: iOS app
  * iOS version
  * Simulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`
- [ ] Your own client. Describe it:
  * Transport (gRPC, websocket, long polling)
  * Programming language.
  * gRPC version, if applicable.

### Steps to reproduce
Upgrade from previous version.
Open app.
Leave app in background.
Receive incoming messages.
Note no notifications are generated to system. 
Open app and see at first no message, then indicator there is a waiting message. Open to reveal a message exists but hasn't been notified for.

### Expected behaviour
Incoming messages should generate system notifications and icon in tray.

### Actual behaviour
No notification of incoming message

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file. When posting console log from Webapp, please use `index-dev.html`, not `index.html`; `index.html` uses minified javascript which produces unusable logs).

**Comment by or-else** [comment]
I'm using 21.6, push notifications work as expected. Please provide more information to reproduce.

**Comment by or-else** [comment]
Any update?
