### ISSUE TITLE
Inconsistent behavior of browser back button in WebApp on mobile

### ISSUE THREAD

**Issue by crendy** [tinode/chat#838]
### Subject of the issue
Describe your issue here.

When viewing a topic on mobile, the back button in the app title takes user to Chat list view, while the browser back button takes user to the previously selected topic (logo screen in the example below).

在此聊天页面，使用浏览器的返回，和页面顶部（红框部分）的后退按钮不一致：
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/6448115/224535572-1cdc52a7-a9fe-4ed7-bac7-93f5772cde5d.png">
点击上图红框的后退按钮可以正常到消息列表页面，但是使用手机后退的手势（浏览器的后退事件），就会回到此页面：
<img width="401" alt="image" src="https://user-images.githubusercontent.com/6448115/224535664-82c7bf59-a185-474b-80ed-2a935f82eafd.png">

#### Server-side
- [# ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [ #] Your own setup:
  * platform (Linux  docker setup)
  * version of Tinode server, e.g. `0.22.0-rc1`
  * database backend
  * cluster or standalone

#### Client-side
- [ #] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
  * IMPORTANT! Use `index-dev.html` to reproduce the problem, not `index.html`.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/webapp/commit/52f879490e05a9ec108335e3a4c1cb3a212785f5
