### ISSUE TITLE
Transaction is required when writing/editing/deleting to the database.

### ISSUE THREAD

**Issue by nyangko** [tinode/chat#839]
During testing, the following came out:

Tinode version: 0.22.0-rc1
Database usage: MySQL

1. User registration (userid: abc)
2. An error has occurred
create user: missing credentials; have: [] want: [email] JLbX4InS05s

3. Confirm that it has been inserted into the database.
(User ID: "basic:abc")

3. User re-registration (userid: abc)
4. Error Occurred
create user: auth secret is not unique duplicate value li6qvopiPGo

I think you should use Transaction when accessing the database. Can you add features?

**Comment by or-else** [comment]
It's a bug and it's not dies to a missing transaction. Fixed in 
https://github.com/tinode/chat/commit/001a35d0db659870728f8649c295d18df0a7e708

Thanks.
