### ISSUE TITLE
File uploader preflight request (using CORS) requires auth headers

### ISSUE THREAD

**Issue by Ledzz** [tinode/chat#840]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
We have custom web app and a tinode instance on different domains. So, when uploading a large file, we are using XHR to upload a file. Since we are using a different domain, the browser is sending an OPTIONS preflight request. We have CORS enabled in tinode.conf, but the error is happening on the OPTIONS request, we get an error message:
`{"ctrl":{"code":403,"text":"valid API key required","ts":"2023-03-15T08:59:56.88Z"}}`

Of course, we cannot add any HTTP headers to a preflight request since it is generated by a browser.

If I try curl with X-Tinode-APIKey and X-Tinode-Auth headers, the preflight request works. But it's not possible to do it in browser.

#### Server-side
- [x] web.tinode.co, api.tinode.co
- [x] sandbox.tinode.co
- [x] Your own setup

#### Client-side
Doesn't matter

### Steps to reproduce
Make a curl request on web.tinode.co:
```
  curl 'https://web.tinode.co/v0/file/u/' \
  -X 'OPTIONS' \
  -H 'authority: web.tinode.co' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  -H 'access-control-request-headers: x-tinode-apikey' \
  -H 'access-control-request-method: POST' \
  -H 'pragma: no-cache' \
  --compressed
  ```

### Expected behaviour
Preflight request should not check auth

### Actual behaviour
Preflight request is checking custom headers

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/eac88f67479a5fdfaeda97109687cf343f2e999f
Please verify. Thanks.

**Comment by or-else** [comment]
Request:
```sh
% curl -I http://localhost:6060/v0/file/s/ \
  -X 'OPTIONS' \
  -H 'authority: lovahost:6060' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  -H 'access-control-request-headers: x-tinode-apikey' \
  -H 'access-control-request-method: POST' \
  -H 'pragma: no-cache' 
  -H 'origin: http://localhost:6060' 
  -H 'Access-Control-Request-Method: HEAD'\
  --compressed
```

Response:
```
HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Access-Control-Allow-Origin: http://localhost:6060
Access-Control-Max-Age: 86400
Content-Encoding: deflate
Vary: Accept-Encoding
Vary: Origin
Vary: Access-Control-Request-Method
Date: Wed, 15 Mar 2023 17:00:33 GMT
```

**Comment by Ledzz** [comment]
@or-else Thank you for the fast response!
Sorry, I'm kind of noob in it, but we are using docker image from dockerhub.
Can you please guide me how to make an image so I can push it somewhere so we can use it in docker-compose?

**Comment by or-else** [comment]
Please use forum for questions, particularly those unrelated to the issue

https://groups.google.com/d/forum/tinode
