### ISSUE TITLE
Additional Encryption Request.

### ISSUE THREAD

**Issue by nyangko** [tinode/chat#841]
When signing up for a user or changing information, the email or cell phone number is sent without encryption.

Please add encryption/decryption function to prevent leakage of user's personal information.

**Comment by or-else** [comment]
That's not true. All traffic is encrypted with TLS (HTTPS). I don't see much value in adding more crypto on top of TLS for communication with the server. There is some value in e2ee (#357), but it's complex and creates legal problems.
