### ISSUE TITLE
Uncaught ReferenceError: FIREBASE_INIT is not defined

### ISSUE THREAD

**Issue by onlineapps-cloud** [tinode/chat#842]
Hi, i tried to install on windows and linux, i had same results on different database
![image](https://user-images.githubusercontent.com/69077240/226114208-62aa277d-9a3c-48cd-9956-3fa1d4b596b9.png)
i follow on this guide: https://github.com/tinode/chat/blob/master/INSTALL.md#installing-from-binaries
web interface not loaded.

**Comment by or-else** [comment]
Please follow installation instructions.

**Comment by onlineapps-cloud** [comment]
1. i edited file tinode.conf i configured only database.2
2. ./init-db -data=data.json
3. ./tinode
4. i had error as in picture,
in instruction not i don't find information about firebase configuration, or problem is not in firebase?

**Comment by or-else** [comment]
Please find an empty `firebase-init.js` file in `static` folder and add this line to it:
```
const FIREBASE_INIT = {};
```

**Comment by onlineapps-cloud** [comment]
working, thanks.
