### ISSUE TITLE
TypeError: a.minMsgSeq is not a function

### ISSUE THREAD

**Issue by crendy** [tinode/chat#846]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
<img width="815" alt="image" src="https://user-images.githubusercontent.com/6448115/226810086-8572f3ea-6110-48a0-8b8b-c616e06a1bf5.png">

#### Server-side
- [* ] Your own setup:
  * platform ( Linux etc)
  * version of Tinode server, e.g. `0.22.0`
  * database backend
  * cluster or standalone

#### Client-side
- [ *] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
  * IMPORTANT! Use `index-dev.html` to reproduce the problem, not `index.html`.

**Comment by or-else** [comment]
Yes, the SDK was released without rebuilding. Fixed in 0.22.2

**Comment by or-else** [comment]
Fix released in https://github.com/tinode/chat/releases/tag/v0.22.2
