### ISSUE TITLE
docker 部署升级0.22.1 后，无法正常对话，无法搜索

### ISSUE THREAD

**Issue by crendy** [tinode/chat#847]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

### Subject of the issue
<img width="306" alt="image" src="https://user-images.githubusercontent.com/6448115/226811064-62b4952f-6e20-406b-b2fa-c4bf0f6ba5c0.png">

#### Server-side

- [* ] Your own setup:
  * platform (Linux )
  * version of Tinode server, e.g. `0.22.1`
  * database backend
  * cluster or standalone

#### Client-side
- [ *] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
  * IMPORTANT! Use `index-dev.html` to reproduce the problem, not `index.html`.

**Comment by crendy** [comment]
W2023/03/22 07:32:50 topic[fndlEw_iqtROVI] meta.Get.Sub failed: Error 1054 (42S22): Unknown column 'u.state' in 'where clause'

但是数据库 users表中有state字段

**Comment by sysatom** [comment]
https://github.com/tinode/chat/blob/68471c8b828fcbbcbffeb384cf3ff1a56aa400f6/server/db/mysql/adapter.go#L2442

@or-else Here u. should be modified to t.

**Comment by or-else** [comment]
Fix released in https://github.com/tinode/chat/releases/tag/v0.22.2
