### ISSUE TITLE
Editing messages is reducing the number of messages fetched in the initial call.

### ISSUE THREAD

**Issue by slingamneni** [tinode/chat#848]
### Subject of the issue
If we have edited a message or multiple messages in a chat/group chat, it is reducing the number of messages fetched in the initial call. This is causing the scroll bar to not appear in webapp frontend and we are not able to load the previous messages.

#### Server-side
- [* ] web.tinode.co, api.tinode.co
- [ *] sandbox.tinode.co
- [* ] Your own setup:
  
#### Client-side
- [ *] TinodeWeb/tinodejs: javascript client
- [ *] Tindroid: Android app

### Steps to reproduce
Create a new group/chat or join a existing group/chat. 
Post some messages. 
Now, edit a recent message multiple times( around 20-25 times) or edit multiple(around 10) recent messages 2-3 times.
Refresh the webapp or clear the data in the android app and open the group again. 

We see that the number of messages loaded initially reduces. It is much less than the limit parameter the client is  sending. In case of webapp, the number of messages received become so less that the scroll bar is not shown and loading the previous messages become impossible

### Expected behaviour
The number of messages returned by the server should be equal to 'limit' in case the number of messages in the group is greater than 'limit'

### Actual behaviour
The number of messages returned by the server is much less than  be equal to 'limit' in case the number of messages in the group is greater than 'limit'

**Comment by or-else** [comment]
Yes, that's the way it works. Increase the limit if you think it's important.
