### ISSUE TITLE
If a user does not exist,then  create it on server side

### ISSUE THREAD

**Issue by ChenZhaobin** [tinode/chat#85]
**Requirement:**
When a new user logs in to the system, I use a third-party token to authenticate the user's legitimacy. If the authentication succeeds, create the user on the server database and log in
**Issue**
In the method login(msg *ClientComMessage) ,I called method acc(msg *ClientComMessage)  ,But the client will always reconnect. Could you please tell me what's wrong in my code? Or what's the right way to write this code?

**Code**

> `// Authenticate
> func (s *Session) login(msg *ClientComMessage) {
>         
> 	if s.ver == 0 {
> 		s.queueOut(ErrCommandOutOfSequence(msg.Login.Id, "", msg.timestamp))
> 		return
> 	}
> 
> 	if !s.uid.IsZero() {
> 		s.queueOut(ErrAlreadyAuthenticated(msg.Login.Id, "", msg.timestamp))
> 		return
> 	}
> 
> 	handler := store.GetAuthHandler(msg.Login.Scheme)
> 	if handler == nil {
> 		s.queueOut(ErrAuthUnknownScheme(msg.Login.Id, "", msg.timestamp))
> 		return
> 	}  
>        if ok, err := handler.IsUnique(msg.Login.Secret); ok {
>          //if new user , first register then login
> 		var msg1 *ClientComMessage 
> 		**msg1.Acc = &MsgClientAcc{** 
> 						**User:   "new",**
> 						**Scheme:msg.Login.Scheme,**
> 						**Secret: msg.Login.Secret,** 
> 			**}  //this step will cause error**
> 		**s.acc(msg1) //this step will cause error too**
>        }  
>         rec, err := handler.Authenticate(msg.Login.Secret)
> ........
> `

**Comment by or-else** [comment]
This is not how it's supposed to work. You should not try to create users on login. It's the other way around - you can log in automatically with a newly created account. 

If you want to provide your own authenticator you need to write an adapter. See discussion here: https://github.com/tinode/chat/issues/79

Once you have your authentication provider, you create an account with {acc scheme="your-auth-scheme-here" secret="whatever-authenticates-the-user-in-your-scheme"} which will validate the user by whatever means you give.

If you want more help, please explain your use case in more details.

**Comment by ChenZhaobin** [comment]
I will try,thank you for all of these
