### ISSUE TITLE
How to run server code on local ?

### ISSUE THREAD

**Issue by alidevhere** [tinode/chat#851]
Hii !!
I found tinode very interesting project. I want to understand and contribute to it but, sad thing i can't find any clear documentation how can i run code for local development.
### I have read installation guide, but i don't want to install it, i want tinode server to run locally from code so i can play with it and learn.

Thanks 

What i have tried is like:
```
go run ./server/  -config=./tinode-db/tinode.conf -static_data=./templates/
```

But it gives me error saying:

```
I2023/04/02 05:41:49 Server v0.22:/tmp/go-build1015110455/b001/exe/server:undef; pid 34926; 8 process(es)
I2023/04/02 05:41:49 Using config from '/home/ali/Go_Projects/chat/tinode-db/tinode.conf'
I2023/04/02 05:41:49 Cluster: running as a standalone server.
E2023/04/02 05:41:49 Failed to connect to DB: store: mysql adapter is not available in this binary
exit status 1
```

**Comment by or-else** [comment]
Please use forum for questions: https://groups.google.com/d/forum/tinode
