### ISSUE TITLE
react-dom.production.min.js net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by crendy** [tinode/chat#854]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/6448115/230279178-ea70887e-9ff7-42b4-9688-8042e18509cb.png">

GET https://cdn.jsdelivr.net/npm/react-dom@18.2.0/umd/react-dom.production.min.js net::ERR_CONNECTION_RESET

**Comment by crendy** [comment]
docker部署的是否可以直接访问docker本地资源？

**Comment by or-else** [comment]
Yes
