### ISSUE TITLE
More Documentation for API 

### ISSUE THREAD

**Issue by thebist1234** [tinode/chat#867]
Hi, hope you are doing great. 
actually you have done a great job here but for API I need more examples. It's been 2 days that I want to log in using API but I couldn't, and I'm confused.
and Also your documents don't have enough information for novice people like me. you can create swagger for this API for that to make it easier to use. and also what I've done to log in using API was this:
1- I set up mysql and tinode as docker container and everything is working well on webapp.
2- I send a GET request from post man like this for login with that use I already signed up:
* URL :
```
http://IP:PORT/v0/channels?apikey=MY_API_KEY
```
* Body in json:
```
{"login": {"scheme": "basic","secret": "cmV6YTpyZXphMTIzNA==" }}
```
and everytime I got 400(Bad Request). and also I read document but, I don't know what to do. thank you

**Comment by or-else** [comment]
The calls are made over websocket connection, not GET or POST. Please direct all further questions to the forum.

**Comment by or-else** [comment]
> maybe you have to develop swagger for this app. thank you

You are welcome to send a pull request.

**Comment by thebist1234** [comment]
after testing all part of API, I will do that.
