### ISSUE TITLE
Unable to `{sub}` with `on_behalf_of`

### ISSUE THREAD

**Issue by JustonDavies** [tinode/chat#877]
### Subject of the issue
Sending a {sub} message with a `on_behalf_of` does not subscribe a user to a topic.

#### Server-side
- [ ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [X] Your own setup:
  * platform (Windows, Mac, Linux etc) - Debian Linux 11(6.1.0-0.deb11.7-amd64)
  * version of Tinode server, e.g. `0.15.2-rc3` - v0.22.8
  * database backend - MySQL 8.0.33
  * cluster or standalone - Standalone
  * other details - podman/docker 3.0.1

```
CONTAINER ID  IMAGE                                 COMMAND  CREATED      STATUS          PORTS                                             NAMES
33c7b157aadb  docker.io/library/mysql:8             mysqld   3 hours ago  Up 3 hours ago  0.0.0.0:3306->3306/tcp                            tinode_mysql
75446ee88c6a  docker.io/tinode/tinode-mysql:0.22.8           3 hours ago  Up 3 hours ago  0.0.0.0:6060->6060/tcp, 0.0.0.0:16060->16060/tcp  tinode_chat
```

#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
  * IMPORTANT! Use `index-dev.html` to reproduce the problem, not `index.html`.
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] Tinodios: iOS app
  * iOS version
  * Simulator or hardware, if hardware describe it.
- [X] tn-cli
  * Python version - 3.11.4
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`
- [ ] Your own client. Describe it:
  * Transport (gRPC, websocket, long polling)
  * Programming language.
  * gRPC version, if applicable.

### Steps to reproduce
0. Create docker network with `sudo docker network create tinode_chat_network`
1. Setup and run mysql:8 docker container with ` sudo docker run --name "tinode_mysql" --network tinode_chat_network --env MYSQL_ROOT_PASSWORD="secure_root_password" --publish 3306:3306 --detach mysql:8`
2. Create and modify a default configuration file for tinode in `./tinode.conf`
3. Modify line 272 for the MySQL DSN to read `"dsn": "root:secure_root_password@tcp(tinode_mysql)/tinode_database?parseTime=true"`
4. Run the official tinode container via `sudo docker run --name "tinode_chat" --network tinode_chat_network --env ./tinode.conf=/tinode.conf --publish 6060:6060 --publish 16060:16060 --detach --rm tinode/tinode-mysql:0.22.8`
5. Wait for the server to start
6. Now start a third container to run the `tn-cli` client by running the following
```
$ python --version
>> Python 3.11.4
$ git clone https://github.com/tinode/chat.git
$ cd chat/tn-cli/
$ python -m pip install -r requirements.txt
$ python tn-cli.py --host=tinode_chat:16060 --login-basic=xena:xena123
```
7. Now use the command line interface to create a topic as the root user, find an existing user, and add them to it with the `sub` command
```
tn> .must $group sub new --auth=RW --anon=N
tn> .must sub fnd
tn> .must set fnd --public=email:alice@example.com
tn> .must $alice get fnd --sub
tn> .log $alice.sub[0].user_id
tn> .use --user=PASTEYOURIDHERE
tn> .must sub $group.topic
```

### Expected behaviour
The user `alice` should be subscribed to the topic based on the command issued on her behalf from the root user.
A new subscription row should appear in the supporting database which links `alice` to the topic.

### Actual behaviour
The `sub` command returns a 304 "already subscribed" message.
No database rows are added bridging the designated user to the new topic.

### Server-side log
```
I2023/07/06 22:33:25 grpc: session started oyScho6zu9Q 10.88.2.148:50630 2
I2023/07/06 22:33:25 grpc in: hi:{id:"23887"  user_agent:"tn-cli/2.0.0b2 (Linux/6.1.0-0.deb11.7-amd64); gRPC-python/0.22.3+1.56.0"  ver:"0.22.3"  lang:"EN"} oyScho6zu9Q
I2023/07/06 22:33:25 grpc in: login:{id:"23888"  scheme:"basic"  secret:"xena:xena123"} oyScho6zu9Q
I2023/07/06 22:34:15 grpc in: sub:{id:"23889"  topic:"new"  set_query:{desc:{default_acs:{auth:"RW"  anon:"N"}}  sub:{}}}  extra:{} oyScho6zu9Q
I2023/07/06 22:34:22 grpc in: sub:{id:"23890"  topic:"fnd"  set_query:{desc:{default_acs:{}}  sub:{}}}  extra:{} oyScho6zu9Q
I2023/07/06 22:34:29 grpc in: set:{id:"23891"  topic:"fnd"  query:{desc:{default_acs:{}  public:"\"email:alice@example.com\""}  sub:{}}}  extra:{} oyScho6zu9Q
I2023/07/06 22:34:33 grpc in: get:{id:"23892"  topic:"fnd"  query:{what:"sub"}}  extra:{} oyScho6zu9Q
I2023/07/06 22:36:17 grpc in: sub:{id:"23898"  topic:"grpWViOC2kYmXk"  set_query:{desc:{default_acs:{}}  sub:{}}}  extra:{on_behalf_of:"usrMroba8BAr4Q"} oyScho6zu9Q
```

### Client-side log
```
root@cf1e94032ffc:/chat/tn-cli# python tn-cli.py --host=neone_tinode_chat_manager_ephemeral_tinode_chat:16060 --login-basic=xena:xena123
Tinode command line client. Version 2.0.0b2/0.22.3; gRPC/1.56.0; Python 3.11.4.
Server at 'neone_tinode_chat_manager_ephemeral_tinode_chat:16060' 
Logging in with login:password xena:xena123
<= Connected to server: maxTagCount: 16; clusterSize: 1; build: mysql:v0.22.8; servingAt: http://:6060/; maxSubscriberCount: 128; maxMessageSize: 262144; minTagLength: 2; maxFileUploadSize: 8388608; maxTagLength: 96; reqCred: None; ver: 0.22 
<= 201 created 
<= Authenticated as usrPn9j32uk3CM 
<= 200 ok 
tn> .must $group sub new --auth=RW --anon=N
<= 200 ok (grpWViOC2kYmXk) 
tn> .must sub fnd
<= 200 ok (fnd) 
tn> .must set fnd --public=email:alice@example.com
<= 200 ok (fnd) 
tn> .must $alice get fnd --sub
<= meta sub fnd 
tn> .log $alice.sub[0].user_id
<= usrMroba8BAr4Q 
tn> .use --user=usrMroba8BAr4Q
<= Default user='usrMroba8BAr4Q' 
tn> .must sub $group.topic
<= 304 already subscribed (grpWViOC2kYmXk)
```

**Comment by JustonDavies** [comment]
I can also reproduce this issue within go using the same message types, however I can side-step the issue by using a `set` message instead on the topic.

I can provide some code samples if that is helpful.

**Comment by or-else** [comment]
The core of the issue is that we do not support multiple subscriptions of a session to topic under different IDs. Your session of the root user is attached to the topic when the topic is created. Then the same session attempts to attach again under a different ID. Such behavior is not supported and we are unlikely to change that.  

You can do one of the following:

1. Create topic `on_behalf_of` ordinary user.
2. Use one root session to create topic and another session to subscribe `users on_behalf_of`.
3. Use different root users, one to create topics, one to subscribe `users on_behalf_of`.
