### ISSUE TITLE
Can't connect to external database

### ISSUE THREAD

**Issue by oburd** [tinode/chat#880]
Hello!
I have faced with a problem. I can't connect to exnternal database using POSTGRES_DSN there is an error
Failed to init DB adapter: failed to connect to `host= user= database=`: server error (FATAL: no pg_hba.conf entry for host "", user "", database "", no encryption (SQLSTATE 28000))

Can you help ?
Thank you

**Comment by or-else** [comment]
Please use forum for questions or file a real bug report.

**Comment by oburd** [comment]
Where this forume ?

**Comment by oburd** [comment]
> Please use forum for questions or file a real bug report.

Where is this forum ?

**Comment by oburd** [comment]
Before closing, can you providing forum link ?
Thank you

**Comment by or-else** [comment]
The link to the forum was provided in the bug report form which you used when you opened this issue. It's also provided prominently in the README file on the from page of this project.
