### ISSUE TITLE
[Question] External config is not working as expected 

### ISSUE THREAD

**Issue by kientv** [tinode/chat#881]
**https://groups.google.com/d/forum/tinode  can’t be reached now.**
---

#### docker-compose.yml
```  x-tinode-env-vars: &tinode-env-vars
  "STORE_USE_ADAPTER": "mongodb"
  "PPROF_URL": "/pprof"
  "EXT_CONFIG": "./tinode.conf"
...

services:
  tinode-mongodb:
    container_name: tinode_mongodb
    hostname: tinode-mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - root_dir/tinode/chat/docker/tinode/tinode.conf:/tinode.conf
    ports:
      - "6060:6060"
    environment:
      << : *tinode-env-vars
```

### Steps to reproduce
- cp config.templete tinode.conf
- using docker-compose like below
- Add mongodb config to tinode.conf
```     
 "mongodb": {
     "database": "tinode",
    "addresses": "cluster0.44bople.mongodb.net",
    "username": "usertest",
    "password": "pass@word",
    "retry_writes": true,
    "w": "majority"
}
```
- docker-compose up
### Expected behaviour
It work and connect to external mongodb
### Actual behaviour
Can't connect to ext mongodb on mongodb.com

### Server-side log
```
Starting tinode_mongodb ... done
Attaching to tinode_mongodb
tinode_mongodb    | 2023/08/16 03:43:11 Database adapter: 'mongodb'; version: 113
tinode_mongodb    | 2023/08/16 03:43:11 Failed to init DB adapter: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }
tinode_mongodb    | ./init-db failed. Quitting.
tinode_mongodb exited with code 1
```

**Comment by or-else** [comment]
Please follow instructions https://github.com/tinode/chat/blob/master/INSTALL.md#running-a-standalone-server

_MongoDB should run as single node replicaset. See https://docs.mongodb.com/manual/administration/replica-set-deployment/_

If your mongo configuration is different, then configure your connection properly for your setup.

**Comment by or-else** [comment]
Please use forum for questions.
