### ISSUE TITLE
A feature request for status values.

### ISSUE THREAD

**Issue by nyangko** [tinode/chat#885]
**Is your feature request related to a problem? Please describe.**
I think it would be beneficial to have a notification feature for all users when a user creates, joins, gets invited to, leaves, or gets kicked out of a chat.

**Describe the solution you'd like**
I propose adding status values of Create, Join, Invite, Leave, and Kicked to the Pres or Note "What" and broadcasting it.

**Comment by or-else** [comment]
`Join`, `Leave` work. `Invite`, `Kicked` work by announcement of permissions change. I'm not sure what exactly you find missing.

I don't understand how you expect `Create` to work.

**Comment by or-else** [comment]
Questions are not answered. Closing.
