### ISSUE TITLE
Proposal New logo

### ISSUE THREAD

**Issue by omamboo** [tinode/chat#89]
I wanted to contribute to Tinode Massanger Server. I designed a logo, If you like it, I'll send you files.

![tinode](https://user-images.githubusercontent.com/38097218/39685311-e42ea886-51eb-11e8-86e9-931e2520dc85.png)

**Comment by or-else** [comment]
Thank you for contributing the logo. Unfortunately I don't think I can use it because it does not comply with either Google's https://material.io/guidelines/style/icons.html#icons-product-icons or Apple's https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ guidelines for icons. Also, comparing it to other messenger icons it just does not look as nice: https://upload.bitfeed.co/590ccc0bb8283-Messengeri1-630x374

**Comment by omamboo** [comment]
Can I contribute again?

**Comment by or-else** [comment]
Sure, you are welcome to contribute.

**Comment by omamboo** [comment]
![tinode](https://user-images.githubusercontent.com/38097218/39738804-81154e04-52b7-11e8-9a4b-395f6fdbf222.png)

How about this?

**Comment by omamboo** [comment]
I will try to make a better one. What color do you prefer?

Pada tanggal Sel, 8 Mei 2018 23.20, Gene <notifications@github.com> menulis:

**Comment by or-else** [comment]
Here is the current logo https://api.tinode.co/x/example-react-js/img/logo.svg

**Comment by omamboo** [comment]
![tinode](https://user-images.githubusercontent.com/38097218/39804664-dfd4da6c-539e-11e8-910c-dd2838145edd.png)

i hope you like

**Comment by or-else** [comment]
This is much better but still not quite there yet.

The envelope is clearly associated with email: https://www.google.com/search?q=email&source=lnms&tbm=isch&sa=X
not with instant messaging: https://www.google.com/search?q=instant+messaging&source=lnms&tbm=isch&sa=X

The green is too bright, the charcoal is too blue.

**Comment by or-else** [comment]
You can use Material colors: https://material.io/design/color/#tools-for-picking-colors

**Comment by or-else** [comment]
Here is an inspirational idea for you.
<img width="282" alt="logo-563" src="https://user-images.githubusercontent.com/5938143/39846463-bce20892-53b0-11e8-8141-b2a8522fc946.png">

**Comment by omamboo** [comment]
Thanks you.

Pada tanggal Kam, 10 Mei 2018 07.45, Gene <notifications@github.com>
menulis:

**Comment by or-else** [comment]
![logo-256](https://user-images.githubusercontent.com/5938143/39951208-991782e2-553c-11e8-9315-576234fd1513.png)

**Comment by or-else** [comment]
![logo-256-2](https://user-images.githubusercontent.com/5938143/39951338-c7dfc57a-553d-11e8-947b-9c5a1bb64695.png)

**Comment by omamboo** [comment]
I need a lot of time for this time.

Pada tanggal Sab, 12 Mei 2018 07.07, Gene <notifications@github.com>
menulis:

**Comment by or-else** [comment]
![logo-512-3](https://user-images.githubusercontent.com/5938143/39960070-abe83abc-55d0-11e8-8579-aefe0b2b33b2.png)

**Comment by or-else** [comment]
Thank you for your effort and for pushing me to update the logo. Let's discontinue this thread.

**Comment by omamboo** [comment]
1, 2 or 3?

I will send you file cdr, pdf n png.

Pada tanggal Kam, 17 Mei 2018 22.50, Gene <notifications@github.com>
menulis:

**Comment by or-else** [comment]
Thank you for your effort. No need to send anything.

I understand you want to become a designer and building a portfolio. I would suggest you start with something simpler than logo and particularly icon design. Portfolio should come after you have gained some experience. Thanks again.

**Comment by omamboo** [comment]
![tinode](https://user-images.githubusercontent.com/38097218/40413339-cb1c878a-5e9f-11e8-991f-427f7eb7d582.png)

**Comment by or-else** [comment]
Thank you. I think the current logo
![image](https://user-images.githubusercontent.com/5938143/40436248-6b76067c-5e67-11e8-8396-247a2f47687d.png)
is good enough. Thank you for your effort.
