### ISSUE TITLE
Error starting gRPC call. HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:6061) SocketException: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Moghaddm** [tinode/chat#892]
I am working with gRPC client of c# for work with tinode server using :

```
var httpHandler = new HttpClientHandler();
    httpHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

using var channel = GrpcChannel.ForAddress("http://127.0.0.1:6061/", new GrpcChannelOptions { HttpHandler = httpHandler });

var client = new Lims.Chat.TinodeClient.Console.Plugin.PluginClient(channel);

client.Message(new Lims.Chat.TinodeClient.Console.MessageEvent()
{
    Msg = new Lims.Chat.TinodeClient.Console.ServerData() { },
    Action = Lims.Chat.TinodeClient.Console.Crud.Update
});
```

but when the action is done these exceptions has been occurred : 

> : 'Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:6061) SocketException: No connection could be made because the target machine actively refused it.", DebugException="System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:6061)")'

**Comment by or-else** [comment]
Apparently, the server is listening for gRPC connection on a different port, not 6061. Please direct further questions to the forum.

**Comment by Moghaddm** [comment]
i changed port into 6060 but still not working and i got new exception!

> Grpc.Core.RpcException: 'Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError) HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError)", DebugException="System.Net.Http.HttpRequestException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError)")'

**Comment by or-else** [comment]
Please direct further questions to the forum.
