### ISSUE TITLE
Support S3 Compatible Storage Providers

### ISSUE THREAD

**Issue by DezyNation** [tinode/chat#893]
**Is your feature request related to a problem? Please describe.**
Currently Tinode is only supporting AWS S3 storage services, however there are many other storage service providers like Wasabi, Vultr, Digital Ocean who support S3 APIs for their object storage.

**Describe the solution you'd like**
An environment variable named S3_BASE_URL should be used to manage files on S3 server

**Describe alternatives you've considered**
I just read the docker specific documentation and I couldn't find any possible ways to use S3 compatible storage providers.

**Comment by or-else** [comment]
We are using https://github.com/aws/aws-sdk-go/ to access S3. I never explored, but I suspect it's not *that* simple to add support for other storage options as changing the base URL. For example, search https://github.com/search?q=repo%3Aaws%2Faws-sdk-go%20S3_BASE_URL&type=code returns no results.

Otherwise I agree, it would be useful to add support for other storage options.

**Comment by or-else** [comment]
If you know how to do it with the AWS Go SDK, please let me know.

**Comment by or-else** [comment]
Is there anything that we need to do on the tinode side to support this?

**Comment by mynameisjoe666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by boshido** [comment]
> Is there anything that we need to do on the tinode side to support this?

Base from what I have tested Tinode with Minio.
Tinode work like a charm with env EXT_CONFIG for providing custom s3 config to point to minio
```
"s3":{
    "access_key_id": "xxxxx",
    "secret_access_key": "xxxxxxx",
    "region": "sa-east-1",
    "bucket": "minio_test",
    "disable_ssl": false,
    "force_path_style": true,
    "endpoint": "minio-api.x.io",
    "presign_ttl": 3600,
    "cache_control": "max-age=86400",
    "cors_origins": ["*"]
  }
```
![image](https://github.com/tinode/chat/assets/3489862/fe2979ea-a9b1-4773-aec1-d0733e7a65b0)

But for other cloud provider that provide object storage, I'm not sure.
If Tinode only focus on S3 protocol like and compatible, there's no need for Tinode to do anything for now.

**Comment by mynameisjoe666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by or-else** [comment]
I mentioned this option in the config file and documentation: https://github.com/tinode/chat/commit/1c813cd6c9eeb57bae60848e93e9c1d7b1c21594

I think this can be closed now. Thanks everybody for helping out.
