### ISSUE TITLE
Tinode not triggering password reset emails

### ISSUE THREAD

**Issue by DezyNation** [tinode/chat#895]
I have successfully setup Tinode with my SMTP related environment variables. I verified them by running `docker inspect tinode-srv`. But when I checked my SMTP provider's dashboard, Tinode was not triggering any password reset emails.

I'm using Tinode 0.22.10 on Ubuntu 22.04
Using Brevo as SMTP service provider.

If there's already any fix, please let me know.

**Comment by or-else** [comment]
Fixed in devel: https://github.com/tinode/chat/commit/2acec5ca54c35c4866770f459e8f0e89b8d8af98#diff-117c7a2c3487fc3812338cb7765245126e3908e0e742825b8c724395f8db7fe7R63

**Comment by DezyNation** [comment]
Cool!
I tried adding the SMTP_AUTH_MECHANISM in the config.template but it doesn't seem to work for me.
Is there any expected date for this to be updated in the production release?

Also, don't you think Tinode should verify if the email even exists or not? Because it's trying to send confirmation emails to any email address I write.

**Comment by or-else** [comment]
> I tried adding the SMTP_AUTH_MECHANISM in the config.template but it doesn't seem to work for me.

I'm not sure  what you are doing and why. First, `SMTP_AUTH_MECHANISM` has nothing to do with the issue at hand. Second, did you rebuild the docker image after changing the config template?

> Also, don't you think Tinode should verify if the email even exists or not? 

It validates the email syntax but does not validate if the address exists. And I don't think it should.
