### ISSUE TITLE
NOT WORKING VIDEO CALL OTHER INTERNET

### ISSUE THREAD

**Issue by baroukh404** [tinode/chat#896]
Hi, I'm interesting on tinode.
I have some issue when making audio call an video call.
I host my tinode server on aws.
If I make video/audio call on my own home wifi, it's work perfectly but if I use for example mobile data or
my devices are not in the same network, it isn't work.
Any advise or idea on this issue ?
Thanks Tinode Teams.

**Comment by mynameisjoe666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
