### ISSUE TITLE
Cluster Not Working, Error: [ cluster: call failed two gob: unknown type id or corrupted data ]

### ISSUE THREAD

**Issue by akh-iaa** [tinode/chat#897]
Hi, I am currently working on implementing cluster configuration in Golang (version 1.20) and have encountered an issue: "cluster: call failed two gob: unknown type id or corrupted data". Here is my configuration:

`

    // List of available nodes.
    "nodes": [
        // Name and TCP address of every node in the cluster. The ports 12001..12003
        // are cluster communication ports. They don't need to be exposed to end-users.
        {"name": "one", "addr":"localhost:6060"},
        {"name": "three", "addr":"localhost:6062"}
    ],

    // Failover config. No need to change unless you are doing something unusual.
    "failover": {
        // Failover is enabled.
        "enabled": true,
        // Time in milliseconds between heartbeats.
        "heartbeat": 100,
        // Initiate leader election when the leader is not available for this many heartbeats.
        "vote_after": 8,
        // Consider node failed when it missed this many heartbeats.
        "node_fail_after": 16
    }
`
The error message I am encountering is:

`I2024/01/13 09:51:16 cluster: connected to two
I2024/01/13 09:51:16 cluster: connected to three
I2024/01/13 09:51:16 cluster: leading new election for term 2
W2024/01/13 09:51:16 cluster: Cluster.Vote call failed: gob: unknown type id or corrupted data
W2024/01/13 09:51:16 cluster: call failed two gob: unknown type id or corrupted data
W2024/01/13 09:51:16 cluster: call failed three gob: unknown type id or corrupted data
...
`

It seems like there might be an issue with the data being passed during the cluster communication.

**Comment by or-else** [comment]
Please fill out the form completely or post to the forum. Your report is not actionable because cluster works just fine.
