### ISSUE TITLE
js demo doesn't work now

### ISSUE THREAD

**Issue by micwho** [tinode/chat#9]
I signed up from [this](http://api.tinode.co/x/example-react-js/), but nothing happened when I click "SIGN UP" button. The chrome development tools showed that no data had been sent.

**Comment by or-else** [comment]
Please give me more information.

**Comment by micwho** [comment]
Url: http://api.tinode.co/x/example-react-js/#
Client: 08/09/2016 06:08:02
Server: 0.7 (20160808T21:57:19Z) (api.tinode.co)

While I signed in using wrong pair username and password, got response "401 authentication failed" and found a get request log as follow:
`Request URL:ws://api.tinode.co/v0/channels?apikey=AQEAAAABAAD_rAp4DJh05a1HAwFT3A6K
Request Method:GET
Status Code:101 Switching Protocols`

But when I clicked “SIGN UP” button, none of response had got, and no logs appended to chrome dev network window. Here is the mtr results(maybe my network problem?):
|                             172.16.36.1 -    0 |   60 |   60 |   65 |   67 |   69 |   68 |
|                           27.105.94.126 -    4 |   52 |   50 |    0 |   69 |   72 |   68 |
|                           219.85.72.181 -    4 |   52 |   50 |    0 |   69 |   72 |   68 |
|                            219.85.72.77 -    0 |   60 |   60 |   68 |   72 |  108 |   69 |
|                          203.163.222.21 -   17 |   36 |   30 |    0 |   69 |   72 |   68 |
|                          108.170.244.99 -   22 |   32 |   25 |    0 |   68 |   70 |   69 |
|                             66.249.95.6 -   38 |   24 |   15 |    0 |   68 |   69 |   69 |
|                           72.14.238.136 -   56 |   18 |    8 |    0 |   72 |   82 |   71 |
|                           72.14.233.136 -   92 |   12 |    1 |    0 |  101 |  101 |  101 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   11 |    0 |    0 |    0 |    0 |    0 |

**Comment by or-else** [comment]
> Method:GET Status Code:101 Switching Protocols

That's initialization of a websocket connection. All further communication happens over a websocket so you don't see any HTTP requests in the browser log.

Please open the browser javascript console. All packets are logged there.

What's the exact sequence of your actions? Your login failed, you went to Sign Up screen, filled out the form and clicked [Sign Up]? Or you clicked [Sign Up] without filling the form?

**Comment by micwho** [comment]
My actions are went to signup screen, filled out the form and click [Sign Up].
Username, password, and full name were all filled with "hellou"

And here are logs of browser javascript console:
embedded:257 Uncaught TypeError: Cannot read property 'trim' of undefined
    at Constructor.handleSubmit (eval at transform.run (https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js:4:28099), <anonymous>:273:28)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:10707:16)
    at executeDispatch (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:2969:21)
    at Object.executeDispatchesInOrder (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:2992:5)
    at executeDispatchesAndRelease (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:2446:22)
    at executeDispatchesAndReleaseTopLevel (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:2457:10)
    at Array.forEach (native)
    at forEachAccumulated (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:16746:9)
    at Object.processEventQueue (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:2619:7)
    at runEventQueueInBatch (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:10732:18)
    at Object.handleTopLevel [as _handleTopLevel] (https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js:10743:5)

**Comment by or-else** [comment]
Yep, verified.

**Comment by or-else** [comment]
Fixed on dev. Will deploy later today.

**Comment by or-else** [comment]
Uploaded the latest version. Make sure you completely reload all the files.

**Comment by micwho** [comment]
Great, good job.
