### ISSUE TITLE
Cannot setup TLS

### ISSUE THREAD

**Issue by man-k28** [tinode/chat#910]
### Subject of the issue
I generated a self-signed SSL certificate on the machine and added it to the tinode.conf config. However, when you try to log in, autocert throws an error

#### Server-side
- [X] My setup:
  * Ubuntu 22
  * version of Tinode server `0.22.12`
  * database Postgres
  * standalone

#### Client-side
- [X] TinodeWeb/tinodejs: javascript client
- [X] Tindroid: Android app
- [X] Tinodios: iOS app

### Steps to reproduce
           "tls": {
                // Enable TLS.
                "enabled": false,

                // Listen for connections on this port and redirect them to HTTPS port.
                // Cannot be a Unix socket.
                "http_redirect": ":80",

                // Add Strict-Transport-Security to headers, the value signifies age.
                // Zero or negative value turns it off.
                "strict_max_age": 604800,
                // Letsencrypt configuration.
                "autocert": {
                        // Location of certificates.
                        //"cache": "",
                        // Contact address for this installation. LetsEncrypt will send
                        // messages to this address in case of problems. Replace with your
                        // own address or remove this line.
                        //"email": "",
                        // Domains served. Replace with your own domain name.
                        //"domains": ["X.X.X.X"]
                },

                // If "autocert" config is not defined, read static certificates from
                // these locations. Ignored if "autocert" is defined.
                "cert_file": "/root/ssl/cert.crt",
                "key_file": "/root/ssl/cert.key"
        },

### Server-side log
I2024/04/14 15:44:00 Large media handling enabled fs
I2024/04/14 15:44:00 Redirecting connections from HTTP at [:80] to HTTPS at [:6060]
I2024/04/14 15:44:00 Listening for client HTTPS connections on [:6060]
2024/04/14 15:44:13 http: TLS handshake error from X.X.X.X:3916: acme/autocert: missing server name

**Comment by or-else** [comment]
Please use forum for questions.
