### ISSUE TITLE
Provide Details on Base64 Encoding of Group Topic Names

### ISSUE THREAD

**Issue by yinebebt** [tinode/chat#914]
I am currently working on integrating Tinode with another server and need to map the topic names generated by Tinode with the other server for ease of finding existing topics. While I know that topics can be found via tags, I am looking for a more straightforward way to understand how the base64 encoding of topic names is done on the Tinode server.

According to the docs at https://github.com/tinode/chat/blob/master/docs/API.md#group-topics

> The name of a group topic is grp or chn followed by a string of characters from base64 URL-encoding set. No other assumptions can be made about internal structure or length of the group name.

**Comment by or-else** [comment]
This is all: The name of a group topic is grp or chn followed by a string of characters from base64 URL-encoding set. **No other assumptions can be made about internal structure or length of the group name**. Literally that.

Please use forum for questions.
