### ISSUE TITLE
Can't create new account

### ISSUE THREAD

**Issue by soulmayon** [tinode/chat#918]
### Subject of the issue
The code is downloaded from Github, not modified. login is OK, chat is OK, when creating new account, get error, server log:

`create user: auth secret is not unique policy sid= Or_bV1lduew` 

Chrome notice :policy violation (422)
#### Server-side
- [ ] localhost:
  * platform (Windows)
  * version of Tinode server: `0.22.13`
  * database Mysql
  * standalone

#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Chrome 127.0.6533.120.
  * Used  both `index-dev.html` and `index.html`.

### Steps to reproduce
1、Run the server.
2、Navigate to :localhost:6060 or localhost:6060/index-dev.html
3、Create new account
4、Fill the form
5、Submit

### Server-side log
`I2024/08/21 14:38:27 Server v0.22:E:\tinode0.2.3\tinode-mysql.windows-amd64\tinode.exe:v0.22.13; pid 2284; 16 process(es)
I2024/08/21 14:38:27 Using config from 'E:\tinode0.2.3\tinode-mysql.windows-amd64\tinode.conf'
I2024/08/21 14:38:27 stats: variables exposed at '/debug/vars'
I2024/08/21 14:38:27 Cluster: running as a standalone server.
I2024/08/21 14:38:27 DB adapter mysql 113
I2024/08/21 14:38:27 Restricted tags: ['email' 'tel' 'basic']
I2024/08/21 14:38:27 Stale account GC started with period 58m56s, block size 10, min account age 30 hours
I2024/08/21 14:38:27 Push handlers configured: []
I2024/08/21 14:38:27 Video calls disabled
I2024/08/21 14:38:27 plugins: no active plugins found
I2024/08/21 14:38:27 gRPC/1.59.0 server is registered at [:16060]
I2024/08/21 14:38:27 Serving static content from 'E:\tinode0.2.3\tinode-mysql.windows-amd64\static' at '/'
I2024/08/21 14:38:27 API served from root URL path '/'
I2024/08/21 14:38:27 Server status is available at '/debug/status'
I2024/08/21 14:38:27 Large media handling enabled fs
I2024/08/21 14:38:27 Listening for client HTTP connections on [:6060]
I2024/08/21 14:38:49 ws: session started Or_bV1lduew [::1]:54930 1
I2024/08/21 14:38:49 in: '{"hi":{"id":"121066","ver":"0.22.12","ua":"TinodeWeb/0.22.13 (Chrome/127.0; Win32); tinodejs/0.22.12","lang":"zh-CN","platf":"web"}}' sid='Or_bV1lduew' uid=''
I2024/08/21 14:38:55 media upload: ok 9jreHsOqGdA uploads\6y5n4hwdvim5a
I2024/08/21 14:39:14 in: '{"acc":{"id":"121068","user":"new","scheme":"basic","secret":"Z2FvOmdhbzEyMw==","login":true,"desc":{"public":{"fn":"gao","photo":{"data":"␡","ref":"/v0/file/s/9jreHsOqGdA.png","type":"jpeg"}}},"cred":[{"meth":"email","val":"gao@hotmail.com"}]},"extra":{"attachments":["/v0/file/s/9jreHsOqGdA.png"]}}' sid='Or_bV1lduew' uid=''
W2024/08/21 14:39:14 create user: auth secret is not unique policy sid= Or_bV1lduew

### Client-side log
`[07:05:27.124] in: {"ctrl":{"id":"116415","params":{"build":"mysql:v0.22.13","maxFileUploadSize":8388608,"maxMessageSize":262144,"maxSubscriberCount":128,"maxTagCount":16,"maxTagLength":96,"minTagLength":2,"reqCred":{"auth":["email"]},"ver":"0.22"},"code":201,"text":"created","ts":"2024-08-21T07:05:27.135Z"}} 
tinode.prod.js:1 [07:06:11.012] out: {"acc":{"id":"116417","user":"new","scheme":"basic","secret":"Z2FvOmdhbzEyMw==","login":true,"desc":{"public":{"fn":"gao","photo":{"data":"␡","ref":"/v0/file/s/gPRqma_JKns.png","type":"jpeg"}}},"cred":[{"meth":"email","val":"gao@hotmail.com"}]},"extra":{"attachments":["/v0/file/s/gPRqma_JKns.png"]}} `

![server](https://github.com/user-attachments/assets/af781a30-ac5c-4fb1-827d-60b766e6eeda)
![client](https://github.com/user-attachments/assets/0966dd97-8446-4304-a511-3f2a6d5e0498)
![clientdev](https://github.com/user-attachments/assets/e42b0def-35f4-45b4-bb71-68fa75adedcc)

**Comment by or-else** [comment]
So, what exactly is unclear in `auth secret is not unique`?

Please use forum for further questions.

**Comment by soulmayon** [comment]
I am confused. The code is just downloaded, only using sample data in guide , just create a new account, it threw an error. Is it not a bug? how to create a new account?  I don't know why auth secret is not unique.  Thanks for the reply, I'll try to use forum.

**Comment by or-else** [comment]
https://github.com/tinode/chat/blob/a97c49477fae478062238049e6cde2da2fe9c114/server/tinode.conf#L175

Please use forum for further questions.
