### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by jsign** [tinode/chat#92]
I followed 'Building from source' step by step (for mysql) but:
- When I should run 'init-db', wouldn't now be 'tinode-db'?
- If I run 'tinode-db', it fails with: Failed to init DB: store: database adapter is missing

I did a quick lookup and found that 'store' has a 'RegisterAdapter', but I didn't see any call to it.

Maybe I'm missing something.

Thanks!

**Comment by or-else** [comment]
> When I should run 'init-db', wouldn't now be 'tinode-db'?

Yes, you are correct.

> If I run 'tinode-db', it fails with: Failed to init DB: store: database adapter is missing

The most likely reason you did not specify the `tags`  option when building. Note the required `-tags rethinkdb` or `-tags mysql` build option. The instruction is very clear about it.

**Comment by jsign** [comment]
You're right. I basically copy pasted it from the instructions, but then did a 'go build' without the flag.

Thanks
