### ISSUE TITLE
Chat para tirar suas dúvidas 

### ISSUE THREAD

**Issue by 29112004-sa** [tinode/chat#921]
<script>
  async function perguntarChatbot(pergunta) {
    const resposta = await fetch('SUA_API_OPENAI', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer SUA_CHAVE_API'
      },
      body: JSON.stringify({
        prompt: pergunta,
        max_tokens: 100,
      })
    });
    
    const dados = await resposta.json();
    document.getElementById('resposta').innerText = dados.choices[0].text;
  }
</script>

<div>
  <input type="text" id="pergunta" placeholder="Digite sua dúvida bíblica">
  <button onclick="perguntarChatbot(document.getElementById('pergunta').value)">Perguntar</button>
  <p id="resposta"></p>
</div>

**Comment by or-else** [comment]
If you indeed found a bug, then fill out the form.
