### ISSUE TITLE
How to include forms in the chat to receive inputs from user

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#93]
Hi I am creating a chatbot  using this repository. I want to include forms in the chat to receive inputs from user on particular command and read those inputs. Anybody could help me with the example how I can achieve it.

Thanks

**Comment by or-else** [comment]
It's not supported right now but I think it's a useful feature to add. What's the minimum useful set of form elements to support? Text, selector and button? Do you know some bot form API that you think is well designed?

**Comment by or-else** [comment]
Any update on this?
