### ISSUE TITLE
add new tags to a topic without knowing about existing tags of this topic 

### ISSUE THREAD

**Issue by ChenZhaobin** [tinode/chat#96]
In tinode.js ,there is a method to update a topic's tags through posting a package just like below to   the server backend:

> {"set":{"id":"124985","topic":"grp100","tags":["oldtag1","oldtag2","newtag1","newtag2"]}}

if do so,I should first get all the  existing tags of this topic before adding new tags
Is there any form packageto just add new tags directly , just like below:

> {"add":{"id":"124985","topic":"grp100","tags":["newtag1","newtag2"]}}

**Comment by or-else** [comment]
Yes, that's the only way to do it now, but it's not too hard to allow incremental changes to tags. 
What is your use case? What are you trying to achieve?

**Comment by ChenZhaobin** [comment]
**Requirement**:I want to allow users to fake delete some group topic  in his own  history topic lists,but when new messages come ,the topic should show in the list again.
**Method have tried**：delete topic from local cach ,then call topic._gone() ,but this method can not show new message unless logout then login again ,but also when login again ,the method prepareContactList() invoked ,then the topic is  showed in the list again even no new message comes.
**Next want to try** : When user try to hide some group topic ,I add a tag named hide_curUserId to this topic,when new message recieved in this topic ,remove the tag hide_curUserId. so I need a method to add or remove tags to a topic directly

**Comment by or-else** [comment]
So, you want to archive a topic and if someone sends a message on it, un-archive? I.e. hide the topic from contact list, then when message arrives show it again?
The original intent was to use Private field to indicate topic's archived status. Private may contain structured data. Alternatively I can add some key-value store to each subscription.

**Comment by ChenZhaobin** [comment]
@or-else  thanks Gene,maybe using private field should be more reasonable and easier to implement
