### ISSUE TITLE
API key inquiries and grpc documentation 

### ISSUE THREAD

**Issue by georgeyameen** [tinode/chat#97]
Is there any documentation about API Keys that answer the following:

- Does the server require a specific key?  Can it be any key?
- How do you configure keys on the server?
 
Also, Is there any GRPC documentation? 

CC: @monirz

**Comment by or-else** [comment]
Please take a look here: 
https://github.com/tinode/chat/tree/devel/keygen
https://github.com/tinode/chat/blob/devel/docs/API.md#connecting-to-the-server

As for configuring the key, the config file takes the salt, not the key itself:
https://github.com/tinode/chat/blob/devel/server/tinode.conf#L19

**Comment by georgeyameen** [comment]
Thank you :) Is there anything on GRPC?

**Comment by monirz** [comment]
Any documentation or example for gRPC yet? I will use `Go` for the client as well.

**Comment by or-else** [comment]
gRPC is just the comments in https://github.com/tinode/chat/blob/devel/pbx/model.proto

You can see how it's used in Python here https://github.com/tinode/chat/blob/master/chatbot/chatbot.py 
and here
https://github.com/tinode/chat/blob/master/tn-cli/tn-cli.py

**Comment by monirz** [comment]
Any gRPC example with Golang as a client would have been more helpful but thanks!

**Comment by or-else** [comment]
You are welcome to contribute one :)

**Comment by monirz** [comment]
Thank you :)
