### ISSUE TITLE
Unable to create  or figure out gRPC stream with Go.

### ISSUE THREAD

**Issue by monirz** [tinode/chat#98]
### Unable to create gRPC stream with Go.
Hello I'm trying to create a client for Tinode server with Go using gRPC. And trying to follow Tinode protocol. So I have been able to send `Hi` to the server for Client Handshake and response back with `201` status. Then it closes immediately. What I understand so is far if I want send `login`, `acc` messages I need to send `hi` first to make the client handshake. Then I can send other requests. Like I tried to login without sending hi and got `ctrl:<code:409 text:"command out of sequence" >` . Now I not sure how do I create the stream, it seems to me that `nodeMessageLoopClient.Send()` returns a stream of  `grpc.ClientStream` . But it just closing immediately after the call. Bellow is part of the code 

```

	c := pbx.NewNodeClient(conn)
	response, err := c.MessageLoop(context.Background())

	if err != nil {
		log.Fatalf("Error calling : %s", err)
	}

	hi := &pbx.ClientHi{}
	hi.Id = "1"
	hi.UserAgent = "Golang_Spider_Bot/3.0"
	hi.Ver = "0.15"
	hi.Lang = "EN"

       	msgHi := &pbx.ClientMsg_Hi{hi}
	clientMessage := &pbx.ClientMsg{Message: msgHi}
	err = response.Send(clientMessage)

	if err != nil {
		log.Fatal("error sending message ", err)
	}

      
	login := &pbx.ClientLogin{}
	login.Id = "112121"
	login.Scheme = "basic"
	login.Secret = []byte("secret")
	clMsg := &pbx.ClientMsg_Login{login}
	clientMessage = &pbx.ClientMsg{Message: clMsg}
	err = response.Send(clientMessage)

	if err != nil {
		log.Fatal("error sending message ", err)
	}
       
	serverMsg, err := response.Recv()

	if err != nil {
		log.Fatal(err)
	}

	log.Println(serverMsg)
```    

What I'm missing here?  Couldn't figure out how do I send the login or other request.

**Comment by or-else** [comment]
Your sample code has a problem as you send {login} before completing {hi}. Send {hi}, wait for an answer, then send login. The server is asynchronous. 

It would be helpful to see the server-side logs. 

In general, please try to provide more structured information. Its hard for me to understand what happens when and in what sequence. 

You may find gist.github.com useful for posting code snippets. You may also post your project to github so I could take a look at it.

**Comment by or-else** [comment]
Here is a complete working code sample
https://gist.github.com/or-else/025ca48ce04faceb924b5f8d0a1460ed

It works exactly as expected:
```
2018/05/25 09:52:51 ctrl:<id:"1" code:201 text:"created" params:<key:"build" value:"\"mysql:undef\"" > params:<key:"ver" value:"\"0.15\"" > > 
2018/05/25 09:52:51 ctrl:<id:"112121" code:400 text:"malformed" > 
```

**Comment by monirz** [comment]
Thank you! I will provide more information including server side log when I ask question next time :)
