### ISSUE TITLE
Calculating Unread Messages From Others

### ISSUE THREAD

**Issue by TaylorChristie** [tinode/chat#99]
### Subject of the issue
Currently, a user can read their own message  and it will be marked read for the other user. This is difficult because I am finding it hard to determine each separate user's unread messages. 

Basically, if I send three messages to a user who doesn't read them they will also show unread for me as well (based on the read variable). There are a couple different ways to handle this (read receipts from both sides) or another variable marking number of unread messages you have (not including your own) on a topic.

Perhaps I'm reading too much into the issue, but I can't determine an accurate way to get the number of unread messages from a single user's point of view. Since if I don't mark my message as read then it'll show as another notification on my side, but if I do mark as read then the other user won't see the notification for the unread message.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

### Your environment
- [ ] api.tinode.co
- [x] Your wn setup:
  * platform Linux
  * version of tinode server 14.6
  * database backend MySQL
  * which client used custom angular application w/ websockets

### Steps to reproduce
N/A

### Expected behaviour
N/A

### Actual behaviour
N/A

### Server-side log
N/A

### Client-side log
N/A

**Comment by or-else** [comment]
> Currently, a user can read their own message and it will be marked read for the other user.

If it happens then it's a bug. Could you please describe steps to reproduce? Please test against version 0.15. Thanks!

**Comment by TaylorChristie** [comment]
I tried again and I actually seemed to be an issue with my own code, sorry for the issue!
